libpx: px::db::CKeyValueStore Class Reference
px::db::CKeyValueStore Class Reference
Read-write Key/Value Store.
#include <key_value_store.hpp>
Public Member Functions
PUBLIC CKeyValueStore (const px::string &name, bool create=false, bool compress=true)
Constructor.
PUBLIC ~CKeyValueStore ()
Destructor.
PUBLIC CIterator iterator (bool cache=true) const
Get an iterator into the database.
PUBLIC void write (CBatch &batch, bool sync=true)
Write a batch of updates to the database.
PUBLIC void make_table (const px::string &name, bool compress=true) const
Create a single SSTable from this database.
PUBLIC void compact (const CBlobHolder &begin_key=CBlobHolder(), const CBlobHolder &end_key=CBlobHolder())
Compact the database from begin_key to end_key.
Static Public Member Functions
static PUBLIC void repair (const px::string &name)
Attempt to repair a corrupted database file, given the path name.
Private Member Functions
void renew_owner ()
Useful for testing – acquire a new iterator owner (thus invalidating all outstanding iterators) without actually closing the database.
Private Attributes
std::unique_ptr< leveldb::DB > _db
Handle to the LevelDB database.
std::shared_ptr< CIteratorOwner > _iter_owner
Dummy "owner" for iterators on this table, to enforce their validity.
std::shared_ptr< CLevelDBLogger > _logger
Log-control object.
Detailed Description
Read-write Key/Value Store.
This class abstracts away the implementation of a key/value database. Keys are treated as opaque binary blobs, which are sorted lexicographically in the underlying storage, and accessed in an ordered manner.
That means that the "schema" of the database is defined solely by the details of which pieces of information (in what order) go into the binary key. This class doesn't concern itself with the schema, since it treats the key opaquely. Higher-level logic built on top of this class is therefore responsible for correctly interpreting keys according to a meaningful ordering.
Definition at line 36 of file key_value_store.hpp.
Constructor & Destructor Documentation
px::db::CKeyValueStore::CKeyValueStore (const px::string & name, bool create = false, bool compress = true)
Constructor.
Opens the named file as a LevelDB database
Parameters
name The name of the file to open. Must not be empty.
create Should we create the DB if it doesn't exist?
compress Should we compress entries that are written to the database?
Exceptions
generic_err Thrown if the file can not be opened
Definition at line 21 of file key_value_store.cpp.
References _db, _iter_owner, _logger, px::db::CIteratorOwner::create(), and px::sub::create().
px::db::CKeyValueStore::~CKeyValueStore ()
Destructor.
Definition at line 71 of file key_value_store.cpp.
Member Function Documentation
px::db::CIterator px::db::CKeyValueStore::iterator (bool cache = true) const
Get an iterator into the database.
Parameters
cache If true, data read by this iterator is cached by LevelDB to help speed up future reads
Returns
An iterator into the database, which is not initially pointing to any valid entry
Definition at line 83 of file key_value_store.cpp.
Referenced by px::db::allocate_ids(), BOOST_AUTO_TEST_CASE(), px::db::CheckIDDB(), px::db::CleanupAlarms(), px::db::DeleteAlarms(), px::db::DeleteClosedAlarms(), px::db::DeleteTrends(), px::db::DeleteTrendsInternal(), px::db::DoesKeyExist(), px::db::ExportTrendBucket(), px::db::ExportTrendStage(), px::db::FetchChannels(), px::db::FetchDevices(), px::db::FetchOOB(), px::db::FetchOOBKeys(), px::db::FetchOOBs(), px::db::GetSchemaVersion(), px::db::IsTrendStageDbTombstoned(), px::db::LevelupBucketTrends(), px::db::LevelupBucketTrendsForChannel(), px::db::LoadActiveAlarms(), px::db::MigrateAlarmDB(), px::db::MigrateChannelDB(), px::db::MigrateDeviceDB(), px::db::MoveTrendsFromStageToBucket(), px::db::query_alarm_index_db(), px::db::QueryAlarms(), px::db::QueryAlarmsLatestUpdate(), px::db::QueryTrendStage(), px::db::reserve_ids(), and px::db::SetTrendStageDbTombstoned().
void px::db::CKeyValueStore::write (CBatch & batch, bool sync = true)
Write a batch of updates to the database.
Parameters
batch The sequence of updates to be written
sync If true, the database is synchronously flushed to disk
Exceptions
generic_err Thrown if an error is encountered while writing this batch of updates
Definition at line 97 of file key_value_store.cpp.
References px::db::CBatch::_batch.
Referenced by px::db::allocate_ids(), BOOST_AUTO_TEST_CASE(), px::db::CheckIDDB(), px::db::CleanupAlarms(), px::db::DeleteAlarms(), px::db::DeleteClosedAlarms(), px::db::DeleteTrends(), px::db::DeleteTrendsInternal(), px::db::LevelupBucketTrendsForChannel(), px::db::LevelupBucketTrendsRow(), px::db::MigrateAlarmDB(), px::db::MigrateChannelDB(), px::db::MigrateDeviceDB(), px::db::MoveTrendsFromStageToBucket(), px::db::NoteAlarmsToDelete(), px::db::reserve_ids(), px::db::SaveAlarmUpdates(), px::db::SetSchemaVersion(), px::db::SetTrendStageDbTombstoned(), and px::db::StoreTrendBucketsToDb().
void px::db::CKeyValueStore::make_table (const px::string & name, bool compress = true) const
Create a single SSTable from this database.
This call provides a convenient way to create a sorted string table: you can use the key/value store interface to add as many items as you want, in no particular order, then invoke this call to iterate over the (now ordered) contents of the database, and use them to create a single sorted string table.
Parameters
name The filename to which the table will be written. Must not be empty.
compress Should we compress entries that are written to the sstable?
Exceptions
generic_err Thrown if an error is encountered while creating the table
Definition at line 123 of file key_value_store.cpp.
References unlikely.
void px::db::CKeyValueStore::compact (const CBlobHolder & begin_key = CBlobHolder(), const CBlobHolder & end_key = CBlobHolder())
Compact the database from begin_key to end_key.
If either is omitted, go to the beginning and/or end of the database. Will increase space usage if ran while an iterator is being held to the same DB.
Definition at line 181 of file key_value_store.cpp.
References px::db::CBlobHolder::get(), likely, and px::db::CBlobHolder::size().
Referenced by px::db::CleanupAlarms(), px::db::compact_trend_bucket_channel_range(), px::db::DeleteAlarms(), px::db::DeleteClosedAlarms(), px::db::DeleteTrendsInternal(), px::db::MigrateAlarmDB(), px::db::MigrateChannelDB(), and px::db::MigrateDeviceDB().
void px::db::CKeyValueStore::repair (const px::string & name) static
Attempt to repair a corrupted database file, given the path name.
Name must not be empty.
Definition at line 212 of file key_value_store.cpp.
void px::db::CKeyValueStore::renew_owner () private
Useful for testing – acquire a new iterator owner (thus invalidating all outstanding iterators) without actually closing the database.
Definition at line 207 of file key_value_store.cpp.
References px::db::CIteratorOwner::create().
Referenced by px::db::CTestHelper::renew_iterator_owner().
Member Data Documentation
std::unique_ptr<leveldb::DB> px::db::CKeyValueStore::_db private
Handle to the LevelDB database.
Definition at line 156 of file key_value_store.hpp.
Referenced by CKeyValueStore().
std::shared_ptr<CIteratorOwner> px::db::CKeyValueStore::_iter_owner private
Dummy "owner" for iterators on this table, to enforce their validity.
Definition at line 161 of file key_value_store.hpp.
Referenced by CKeyValueStore().
std::shared_ptr<CLevelDBLogger> px::db::CKeyValueStore::_logger private
Log-control object.
Definition at line 166 of file key_value_store.hpp.
Referenced by CKeyValueStore().
The documentation for this class was generated from the following files:
key_value_store.hpp
key_value_store.cpp