libpx: px::image_util Namespace Reference
px::image_util Namespace Reference
Functions
PUBLIC bool CheckImageSums (const std::string &image_path, const std::string &image_sums, const std::string &image_type, std::string &error)
Check an image file using data from the provided image.sums.
PUBLIC bool CheckSignature (const std::string &data, const std::string &sig, const std::vector< std::string > &rvk_paths, std::string &error)
Checks a signature in the manner we use for image.sums.sig.
PUBLIC bool CheckRSA2LevelSignature (const std::string &data, const std::vector< unsigned char > &sig, const std::string &rvk, const std::vector< std::string > &fvks, size_t &fvk_index, std::string &error)
Checks a signature in the manner we use for image.sums.sig.
Function Documentation
bool px::image_util::CheckImageSums (const std::string & image_path, const std::string & image_sums, const std::string & image_type, std::string & error)
Check an image file using data from the provided image.sums.
Tests size and whichever of sha1sum or sha256sum is present, or both.
Parameters
image_path Path to image file to check. Must not be empty.
image_sums String containing contents of the image.sums file Must not be empty.
image_type The Type of this image as listed in image.sums e.g. "rootfs" Must not be empty.
[out] error If false is returned, this is set to an informative message
Returns
True if the image passes all checks, False if any checks fail, the entry is not found in image_sums or has no checksums there, or there is an error.
Definition at line 45 of file image_util.cpp.
References px::bytes_2_hex(), and unlikely.
bool px::image_util::CheckSignature (const std::string & data, const std::string & sig, const std::vector< std::string > & rvk_paths, std::string & error)
Checks a signature in the manner we use for image.sums.sig.
Checks the "new" style CMS PKCS#7 multi-level signatures (N RVKs, FVK and intermediates stored in signature).
Parameters
data The data to verify (e.g. contents of image.sums). Must not be empty.
sig The signature data (e.g. the contents of image.sums.sig). Must not be empty.
rvk_paths List of paths of the Root Verification Key certificates. Must not be empty.
[out] error If false is returned, this is set to an informative message
Returns
True if all checks pass, False if any fail.
Definition at line 244 of file image_util.cpp.
References cert_verify_callback(), likely, unlikely, and px::generic_err::what().
bool px::image_util::CheckRSA2LevelSignature (const std::string & data, const std::vector< unsigned char > & sig, const std::string & rvk, const std::vector< std::string > & fvks, size_t & fvk_index, std::string & error)
Checks a signature in the manner we use for image.sums.sig.
Checks the "old" style RSA 2-level signatures (one RVK/N FVKs).
Parameters
data The data to verify (e.g. contents of image.sums). Must not be empty.
sig The signature data (e.g. the contents of image.sums.sig). Must not be empty.
rvk Contents of the Root Verification Key certificate. Must not be empty.
fvks List of contents of the Firmware Verification Key certificates Must not be empty.
[out] fvk_index If the check succeeds, this is set to the vector index of the FVK used to verify the signature
[out] error If false is returned, this is set to an informative message
Returns
True if all checks pass, False if any fail.
Definition at line 373 of file image_util.cpp.
References cert_verify_callback(), likely, px::size, and unlikely.