libpx: px::asio::CUtil Class Reference
px::asio::CUtil Class Reference
Mercury utility functions.
#include <util.hpp>
Static Public Member Functions
static PUBLIC px::string formatTime (boost::posix_time::ptime &now, const char *fm)
convert to needed time formats
static PUBLIC uint16_t read_u16 (px::asio::iobuf_const_iter_t &ibuf)
Read a 16-bit MSB unsigned integer value from an input buffer.
static PUBLIC uint16_t read_u16_lsb (px::asio::iobuf_const_iter_t &ibuf)
Read a 16-bit LSB unsigned integer value from an input buffer.
static PUBLIC void write_u16 (px::asio::iobuf_iter_t &ibuf, uint16_t val)
Write a 16-bit MSB unsigned integer value to an output buffer.
static PUBLIC void write_u16_lsb (px::asio::iobuf_iter_t &ibuf, uint16_t val)
Write a 16-bit LSB unsigned integer value to an output buffer.
static PUBLIC uint32_t read_u32 (px::asio::iobuf_const_iter_t &ibuf)
Read a 32-bit MSB unsigned integer value from an input buffer.
static PUBLIC void write_u32 (px::asio::iobuf_iter_t &ibuf, uint32_t val)
Write a 32-bit unsigned integer value to an output buffer, MSB first.
static PUBLIC uint8_t read_u8 (px::asio::iobuf_const_iter_t &ibuf)
Read a 8-bit MSB unsigned integer value from an input buffer.
static PUBLIC uint8_t read_u8_lsb (px::asio::iobuf_const_iter_t &ibuf)
Read a 8-bit LSB unsigned integer value from an input buffer.
static PUBLIC void write_u8 (px::asio::iobuf_iter_t &ibuf, uint8_t val)
Write a 8-bit MSB unsigned integer value to an output buffer.
static PUBLIC void write_u8_lsb (px::asio::iobuf_iter_t &ibuf, uint8_t val)
Write a 8-bit LSB unsigned integer value to an output buffer.
Detailed Description
Mercury utility functions.
Definition at line 15 of file asio/util.hpp.
Member Function Documentation
px::string px::asio::CUtil::formatTime (boost::posix_time::ptime & now, const char * fm) static
convert to needed time formats
Definition at line 7 of file asio_util.cpp.
uint16_t px::asio::CUtil::read_u16 (px::asio::iobuf_const_iter_t & ibuf) static
Read a 16-bit MSB unsigned integer value from an input buffer.
Parameters
ibuf The head of the input buffer
Returns
The 16-bit number parsed from the buffer head
Definition at line 26 of file asio_util.cpp.
uint16_t px::asio::CUtil::read_u16_lsb (px::asio::iobuf_const_iter_t & ibuf) static
Read a 16-bit LSB unsigned integer value from an input buffer.
Parameters
ibuf The head of the input buffer
Returns
The 16-bit number parsed from the buffer head
Definition at line 37 of file asio_util.cpp.
void px::asio::CUtil::write_u16 (px::asio::iobuf_iter_t & ibuf, uint16_t val) static
Write a 16-bit MSB unsigned integer value to an output buffer.
Parameters
ibuf The tail of the output buffer
val The 16-bit number to be written to the buffer tail
Definition at line 48 of file asio_util.cpp.
void px::asio::CUtil::write_u16_lsb (px::asio::iobuf_iter_t & ibuf, uint16_t val) static
Write a 16-bit LSB unsigned integer value to an output buffer.
Parameters
ibuf The tail of the output buffer
val The 16-bit number to be written to the buffer tail
Definition at line 59 of file asio_util.cpp.
uint32_t px::asio::CUtil::read_u32 (px::asio::iobuf_const_iter_t & ibuf) static
Read a 32-bit MSB unsigned integer value from an input buffer.
Parameters
ibuf The head of the input buffer
Returns
The 32-bit number parsed from the buffer head
Definition at line 70 of file asio_util.cpp.
Referenced by px::proto::CMercuryHeader::parse_header_only().
void px::asio::CUtil::write_u32 (px::asio::iobuf_iter_t & ibuf, uint32_t val) static
Write a 32-bit unsigned integer value to an output buffer, MSB first.
Parameters
ibuf The tail of the output buffer
val The 32-bit number to be written to the buffer tail
Definition at line 84 of file asio_util.cpp.
Referenced by px::proto::CMercuryHeader::serialize().
uint8_t px::asio::CUtil::read_u8 (px::asio::iobuf_const_iter_t & ibuf) static
Read a 8-bit MSB unsigned integer value from an input buffer.
Parameters
ibuf The head of the input buffer
Returns
The 8-bit number parsed from the buffer head
Definition at line 99 of file asio_util.cpp.
Referenced by px::proto::CMercuryHeader::parse_header_only().
uint8_t px::asio::CUtil::read_u8_lsb (px::asio::iobuf_const_iter_t & ibuf) static
Read a 8-bit LSB unsigned integer value from an input buffer.
Parameters
ibuf The head of the input buffer
Returns
The 8-bit number parsed from the buffer head
Definition at line 110 of file asio_util.cpp.
void px::asio::CUtil::write_u8 (px::asio::iobuf_iter_t & ibuf, uint8_t val) static
Write a 8-bit MSB unsigned integer value to an output buffer.
Parameters
ibuf The tail of the output buffer
val The 8-bit number to be written to the buffer tail
Definition at line 121 of file asio_util.cpp.
Referenced by px::proto::CMercuryHeader::serialize().
void px::asio::CUtil::write_u8_lsb (px::asio::iobuf_iter_t & ibuf, uint8_t val) static
Write a 8-bit LSB unsigned integer value to an output buffer.
Parameters
ibuf The tail of the output buffer
val The 8-bit number to be written to the buffer tail
Definition at line 130 of file asio_util.cpp.
The documentation for this class was generated from the following files:
asio/util.hpp
asio_util.cpp