libpx: px::CProtoOPS Class Reference
px::CProtoOPS Class Reference
CProtoOPS class.
#include <proto_ops.hpp>
Static Public Member Functions
static PUBLIC void Update (const google::protobuf::Message &from, google::protobuf::Message *to)
We need to perform partial updates between messages for vaiouse reasons.
static PUBLIC void Update (const google::protobuf::UnknownFieldSet &from, google::protobuf::UnknownFieldSet *to)
We should probably also perform partial updates between unknown field sets too.
static PUBLIC void Subtract (google::protobuf::Message *pb, const google::protobuf::Message &ref)
Remove any fields from "pb" containing the same values as "ref".
static PUBLIC std::vector
< px::string > ListUnsetFields (const google::protobuf::Message &pb, const google::protobuf::Message &ref)
List all fields set in "ref" but not in "pb".
static PUBLIC void ClearFields (google::protobuf::Message *pb, const std::vector< px::string > &fields)
Clear the specified fields in "pb".
static PUBLIC void Copy (const google::protobuf::Message &from, json_spirit::Object &to)
toJSON takes a protobuf and returns the JSON convertion of it.
static PUBLIC void Copy (const json_spirit::Object &from, google::protobuf::Message &to)
toJSON takes a protobuf and returns the JSON convertion of it.
static PUBLIC CValue GetFieldValue (const px::string &field, const googlePB::Message &msg)
GetFieldValue returns a single field value from a protobuf message.
static PUBLIC int SetFieldValue (const px::string &field, googlePB::Message &msg, const CValue &val)
SetFieldValue sets a single field value in a protobuf message.
static PUBLIC px::string GetFields (size_t remove_layers, const googlePB::Message &msg)
GetFields returns the internal text of a protobuf message, stripping away as many outer layers as requested, and removing quote marks.
Detailed Description
CProtoOPS class.
encapsulates custom operations that generically alter a protobuf
Definition at line 49 of file proto_ops.hpp.
Member Function Documentation
void px::CProtoOPS::Update (const google::protobuf::Message & from, google::protobuf::Message * to) static
We need to perform partial updates between messages for vaiouse reasons.
Update takes the data in "from" and updates it with the changes in "to"
Parameters
from proto message to serve as the base copy
to proto message containing the updated data
Definition at line 22 of file proto_ops.cpp.
Referenced by px::db::FetchChannels().
void px::CProtoOPS::Update (const google::protobuf::UnknownFieldSet & from, google::protobuf::UnknownFieldSet * to) static
We should probably also perform partial updates between unknown field sets too.
Update takes the data in "from" and updates it with the changes in "to"
Parameters
from unknown field to serve as the base copy
to unknown field containing the updated data
Definition at line 14 of file proto_ops.cpp.
void px::CProtoOPS::Subtract (google::protobuf::Message * pb, const google::protobuf::Message & ref) static
Remove any fields from "pb" containing the same values as "ref".
Leave repeated fields alone. After Subtract(&pb, ref) and Update(pb, &ref), content of "ref" should equal content of "pb" in all cases. pb must not be empty.
Definition at line 178 of file proto_ops.cpp.
References LIBPX_FERR, and unlikely.
Referenced by px::db::AddChannelToBatch().
std::vector< px::string > px::CProtoOPS::ListUnsetFields (const google::protobuf::Message & pb, const google::protobuf::Message & ref) static
List all fields set in "ref" but not in "pb".
Field name format is the same as for Get/SetFieldValue. Repeated fields are included if they have no entries in "pb" but some in "ref".
Definition at line 276 of file proto_ops.cpp.
References LIBPX_FERR, and unlikely.
Referenced by px::db::AddChannelToBatch().
void px::CProtoOPS::ClearFields (google::protobuf::Message * pb, const std::vector< px::string > & fields) static
Clear the specified fields in "pb".
pb must not be null. Fields must not be empty.
Definition at line 323 of file proto_ops.cpp.
References LIBPX_FERR, and unlikely.
Referenced by px::db::FetchChannels().
static PUBLIC void px::CProtoOPS::Copy (const google::protobuf::Message & from, json_spirit::Object & to) static
toJSON takes a protobuf and returns the JSON convertion of it.
Parameters
from proto message to convert from
to JSON message to convert to
Returns
px::string json representation of protobuf
static PUBLIC void px::CProtoOPS::Copy (const json_spirit::Object & from, google::protobuf::Message & to) static
toJSON takes a protobuf and returns the JSON convertion of it.
Parameters
from json representation of a protobuf
to proto message to convert to.
px::CValue px::CProtoOPS::GetFieldValue (const px::string & field, const googlePB::Message & msg) static
GetFieldValue returns a single field value from a protobuf message.
The value is returned as a CValue variant object. generic_err is thrown for any problems. Embedded message fields are supported by periods in the field name, e.g. "request_response.request_id".
Parameters
field String name of field to read. Must not be empty.
msg Protobuf object to read
Returns
px::CValue Value of the field (px::invalid_t if field not set)
Definition at line 406 of file proto_ops.cpp.
References remove_index(), px::CUtil::split_string(), px::string, and unlikely.
Referenced by px::CChannelSettings::get_field_by_name(), px::CChannel::get_field_by_name(), and px::CDevice::get_field_by_name().
int px::CProtoOPS::SetFieldValue (const px::string & field, googlePB::Message & msg, const CValue & val) static
SetFieldValue sets a single field value in a protobuf message.
The field name is specified as in GetFieldValue(). If an index is one greater than the number of values in a repeated field, then the value is added, otherwise the value in a repeated field is overwritten. (Non-repeated fields always get overwritten). generic_err is thrown for any problems.
Parameters
field String name of field to set. Must not be empty.
msg Protobuf object to modify
value Value to set
Returns
int 0 for success, -1 for failure
Definition at line 637 of file proto_ops.cpp.
References px::CValue::as_binary(), px::CValue::as_bool(), px::CValue::as_double(), px::CValue::as_float(), px::CValue::as_int32(), px::CValue::as_int64(), px::CValue::as_string(), px::CValue::as_uint32(), px::CValue::as_uint64(), px::CDataType::is_string(), remove_index(), px::CUtil::split_string(), px::string, px::CValue::type(), and unlikely.
px::string px::CProtoOPS::GetFields (size_t remove_layers, const googlePB::Message & msg) static
GetFields returns the internal text of a protobuf message, stripping away as many outer layers as requested, and removing quote marks.
This function will start with the protobuf DebugString() output and remove outer layers of protobuf metadata. Eg, to show just the fields of an OOB protobuf, set remove_layers to 3, so ACCESS_CTRL/HTTP of { "toolkitStruct":{ "access_ctrl":{ "restricted":false, "port":80, "trusted":[ "10.222.41.58"] , "label":"HTTP" } } } becomes just restricted:false, port:80, trusted:[ 10.222.41.58] , label:HTTP
Parameters
remove_layers The number of outer layers (ie, braces) to remove.
msg Protobuf object to be processed (dumped)
Returns
String containing the inner text of the requested protobuf
Definition at line 945 of file proto_ops.cpp.
References px::string.
The documentation for this class was generated from the following files:
proto_ops.hpp
proto_ops.cpp