libpx: perf__adapter.cpp File Reference
perf__adapter.cpp File Reference
#include <boost/test/unit_test.hpp>
#include <stdio.h>
#include "px/exception.hpp"
#include "px/db/key_value_store.hpp"
#include "px/db/batch.hpp"
#include "px/db/blob_holder.hpp"
#include "px/db/adapter.hpp"
#include "px/proto/Core.hpp"
#include "px/proto/MasterChannelList.hpp"
#include "px/data/device.hpp"
#include "px/proto/ToolkitConfiguration.hpp"
#include "pcd_perf.h"
Functions
static px::string get_dname ()
BOOST_AUTO_TEST_CASE (oob)
Suite for all libpx tests.
BOOST_AUTO_TEST_CASE (device)
Device database tests.
BOOST_AUTO_TEST_CASE (channel)
Device database tests.
BOOST_AUTO_TEST_CASE (id)
ID DB test cases.
Function Documentation
static px::string get_dname () static
Definition at line 16 of file perf__adapter.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
BOOST_AUTO_TEST_CASE (oob)
Suite for all libpx tests.
Suite for all db tests Suite for all db adapter tests OOB database tests
Definition at line 45 of file perf__adapter.cpp.
References px::db::AddClearOOBToBatch(), px::db::AddOOBToBatch(), px::db::CBatch::clear(), px::db::FetchOOB(), px::db::FetchOOBKeys(), px::db::CIterator::first(), get_dname(), px::db::CKeyValueStore::iterator(), px::db::MigrateOOBDB(), px::db::CIterator::valid(), and px::db::CKeyValueStore::write().
BOOST_AUTO_TEST_CASE (device)
Device database tests.
Definition at line 146 of file perf__adapter.cpp.
References px::db::AddDeleteDeviceToBatch(), px::db::AddDeviceToBatch(), px::db::FetchDevices(), get_dname(), px::CDevice::model, px::CDevice::vendor, and px::db::CKeyValueStore::write().
BOOST_AUTO_TEST_CASE (channel)
Device database tests.
Definition at line 252 of file perf__adapter.cpp.
References px::db::AddChannelToBatch(), px::db::AddDeleteChannelToBatch(), px::CChannel::channel_settings, px::db::FetchChannels(), get_dname(), px::db::CKeyValueStore::iterator(), and px::db::CKeyValueStore::write().
BOOST_AUTO_TEST_CASE (id)
ID DB test cases.
Definition at line 365 of file perf__adapter.cpp.
References px::db::AddChannelToBatch(), px::db::AddDeviceToBatch(), px::db::AllocateDeviceIDs(), px::db::CheckIDDB(), get_dname(), px::CDevice::id(), px::db::CKeyValueStore::iterator(), px::db::MigrateChannelDB(), px::db::MigrateDeviceDB(), px::db::MigrateIDDB(), and px::db::CKeyValueStore::write().