libpx: px::asio::CWatchdogTimer Class Reference
px::asio::CWatchdogTimer Class Reference
ASIO interface details and general IO functions. | IO_Actors
Watchdog timer actor used to periodically ping the CDS.
#include <watchdog_timer.hpp>
Public Member Functions
PUBLIC ~CWatchdogTimer ()
Destructor.
virtual void close ()
On a graceful close, unregister this app's watchdog from the CDS so we won't get an unintended watchdog reboot.
virtual PUBLIC void timeout (const CIoTimer &timer)
Callback invoked when our internal timer times out.
Public Member Functions inherited from px::asio::CIoActor
CIoActor (CIoManager &manager)
Constructor.
virtual ~CIoActor ()
Destructor.
boost::asio::io_service & get_io_service () const
Get the I/O service associated with the owner of this actor.
PUBLIC CServerCore & get_server_core () const
Get the container for CDS data management.
PUBLIC CCdsHandler & get_cds_handler () const
Get the container for CDS data management.
PUBLIC bool get_quit_status ()
Get the quit status from connection IO manager.
Static Public Member Functions
static PUBLIC std::shared_ptr
< CIoActor > create (CIoManager &manager, unsigned int timeout)
Factory function to create a new CWatchdogTimer object.
Private Member Functions
PUBLIC CWatchdogTimer (CIoManager &manager, unsigned int timeout)
Constructor.
Private Attributes
size_t _timeout
The period (in msec) at which we should ping the CDS watchdog subsystem Initialized to 1/3 the watchdog timeout used to create this instance.
std::shared_ptr< CIoTimer > _timer
The timer object we use to trigger us when the CDS watchdog needs to be pinged.
Additional Inherited Members
Protected Member Functions inherited from px::asio::CIoActor
void remove ()
This method is called when an actor wants to remove itself from the I/O management interface.
Protected Attributes inherited from px::asio::CIoActor
CIoManager & _owner
The I/O manager object that "owns" this connection.
Detailed Description
Watchdog timer actor used to periodically ping the CDS.
By periodically pinging the CDS, we assert that this application is still "alive". Otherwise, if enabled, the CDS watchdog function will be triggered and result in a system reboot.
We register with the CDS Watchdog using the given "timeout" value, but, within this process, we set a timer at 1/3 of "timeout" and use that timer to trigger our pings to the CDS Watchdog. Using 1/3 of the full timeout gives us margin and 2-3 chances to get our message through to the CDS.
Definition at line 28 of file watchdog_timer.hpp.
Constructor & Destructor Documentation
px::asio::CWatchdogTimer::~CWatchdogTimer ()
Destructor.
Definition at line 53 of file watchdog_timer.cpp.
References _timeout, close(), and LIBPX_FERR.
px::asio::CWatchdogTimer::CWatchdogTimer (CIoManager & manager, unsigned int timeout) private
Constructor.
Parameters
manager The I/O manager object to which this object is to be bound
timeout The watchdog timeout value, in seconds
Exceptions
boost::system::system_error The actor could not be initialized
Definition at line 29 of file watchdog_timer.cpp.
References _timeout, _timer, px::cds::CClient::get(), and px::cds::CClient::submit().
Referenced by create().
Member Function Documentation
std::shared_ptr< CIoActor > px::asio::CWatchdogTimer::create (CIoManager & manager, unsigned int timeout) static
Factory function to create a new CWatchdogTimer object.
Parameters
manager The I/O manager object to which this object is to be bound
timeout The watchdog timeout value, in seconds
Exceptions
boost::system::system_error The signal handler could not be initialized
Returns
Shared pointer containing the new instance of CWatchdogTimer as an CIoActor.
Definition at line 19 of file watchdog_timer.cpp.
References CWatchdogTimer().
Referenced by px::asio::CIoManager::CIoManager().
void px::asio::CWatchdogTimer::close () virtual
On a graceful close, unregister this app's watchdog from the CDS so we won't get an unintended watchdog reboot.
This will gracefully close the actor. It is called automatically by the actor's destructor, but any resulting error information will be lost in that case.
Reimplemented from px::asio::CIoActor.
Definition at line 92 of file watchdog_timer.cpp.
References _timeout, _timer, px::cds::CClient::get(), LIBPX_ERR, LIBPX_INFO, and px::cds::CClient::submit_wait().
Referenced by ~CWatchdogTimer().
void px::asio::CWatchdogTimer::timeout (const CIoTimer & timer) virtual
Callback invoked when our internal timer times out.
Use this to pace our watchdog pings, to make sure that we do ping the CDS in 1/3 the timeout interval this Watchdog actor was created with.
Inherited from CTimedObject
Parameters
timer The timer which expired and which we will rewind to the _timeout interval.
Implements px::asio::CTimedObject.
Definition at line 72 of file watchdog_timer.cpp.
References _timeout, _timer, px::cds::CClient::get(), LIBPX_INFO, and px::cds::CClient::submit().
Member Data Documentation
size_t px::asio::CWatchdogTimer::_timeout private
The period (in msec) at which we should ping the CDS watchdog subsystem Initialized to 1/3 the watchdog timeout used to create this instance.
Definition at line 114 of file watchdog_timer.hpp.
Referenced by close(), CWatchdogTimer(), timeout(), and ~CWatchdogTimer().
std::shared_ptr<CIoTimer> px::asio::CWatchdogTimer::_timer private
The timer object we use to trigger us when the CDS watchdog needs to be pinged.
Definition at line 120 of file watchdog_timer.hpp.
Referenced by close(), CWatchdogTimer(), and timeout().
The documentation for this class was generated from the following files:
watchdog_timer.hpp
watchdog_timer.cpp