libpx: px::CWallTime Class Reference
px::CWallTime Class Reference
Wall-clock time.
#include "px/type/wall_time.hpp"
Public Member Functions
CWallTime (const CMonoTime &)=delete
Constructor.
CWallTime (CMonoTime &&)=delete
CWallTime ()
CWallTime (time_t sec, long nsec)
CWallTime (timespec ts)
CWallTime (timeval tv)
template<typename T >
CWallTime (T time, __REQUIRE(std::is_arithmetic< T >::value))
CWallTime (const px::string &time)
String format is that seen with the command: date +"%F %T" Eg, "2014-01-15 14:54:34" in UTC.
CWallTime (const char *time)
CWallTime (const px::proto::Timestamp &time)
CWallTime & operator= (const CMonoTime &)=delete
Assignment operator.
CWallTime & operator= (CMonoTime &&)=delete
Public Member Functions inherited from px::CTimestamp
CTimestamp ()
Constructor.
CTimestamp (time_t time)
Constructor.
CTimestamp & operator= (const char *time)
timeval to_timeval () const
Convert to "struct timeval".
double to_float () const
Convert to a floating-point value.
PUBLIC void normalize ()
Keep signs of sec & sub-sec consistent and within standard range.
px::string gmtime_str () const
Generate a string representation of this timestamp, assuming UTC time.
px::string localtime_str () const
Generate a string representation of this timestamp, assuming local time.
PUBLIC px::string get_time_str (bool is_utc, const char *strftime_format) const
Gets string representation of this timestamp in separate date (e.g.
template<typename Archive >
void serialize (Archive &ar)
PUBLIC void to (px::proto::Timestamp &val) const
Initialize a protobuf Timestamp object from this value.
PUBLIC void from (const px::proto::Timestamp &arg)
Assign this object's value based on a protobuf Timestamp object.
PUBLIC int64_t msec () const
Get the time in milliseconds.
PUBLIC size_t hash () const
Hash function.
Static Public Member Functions
static PUBLIC CWallTime now ()
Factory function to create a new CWallTime instance set to "now".
Detailed Description
Wall-clock time.
This is a particular kind of timestamp, known to be derived from the normal (wall/realtime) clock. It is functionally the same as a CTimestamp object for the most part, but making it its own type serves both to make it clear in code what kind of timestamp we're dealing with, as well as prevent accidental comparisons between monotonic and wall-clock times.
Since our normal realtime clock timebase is UTC, the CWallTime values are normally UTC as well. (So WallTime is NOT the time you would see on a clock the Wall, except in the Greenwich timezone.)
Definition at line 26 of file wall_time.hpp.
Constructor & Destructor Documentation
px::CWallTime::CWallTime (const CMonoTime &) delete
Constructor.
We prohibit construction from a monotonic timestamp, since it's nonsensical in virtually all cases, and likely to cause bugs.
px::CWallTime::CWallTime (CMonoTime &&) delete
px::CWallTime::CWallTime ()
Definition at line 70 of file wall_time.hpp.
px::CWallTime::CWallTime (time_t sec, long nsec)
Definition at line 73 of file wall_time.hpp.
px::CWallTime::CWallTime (timespec ts)
Definition at line 76 of file wall_time.hpp.
px::CWallTime::CWallTime (timeval tv) explicit
Definition at line 79 of file wall_time.hpp.
template<typename T > px::CWallTime::CWallTime (T time, __REQUIRE(std::is_arithmetic< T >::value)) explicit
Definition at line 83 of file wall_time.hpp.
px::CWallTime::CWallTime (const px::string & time) explicit
String format is that seen with the command: date +"%F %T" Eg, "2014-01-15 14:54:34" in UTC.
Definition at line 89 of file wall_time.hpp.
px::CWallTime::CWallTime (const char * time) explicit
Definition at line 92 of file wall_time.hpp.
px::CWallTime::CWallTime (const px::proto::Timestamp & time) explicit
Definition at line 95 of file wall_time.hpp.
Member Function Documentation
px::CWallTime px::CWallTime::now () static
Factory function to create a new CWallTime instance set to "now".
This function uses the current system clock time (at the point at which it is invoked) to create a timestamp object. Normally our systems are set to keep UTC time, so then this value will be UTC.
Returns
A timestamp corresponding to the current system ("wall") clock On success - tv_sec value will be >= 0 On failure - tv_sec value will be -1
Definition at line 10 of file wall_time.cpp.
References LIBPX_ERR.
Referenced by px::asio::CCdsSyncIO::get_device_trend_row(), px::db::CLevelDBLogger::Logv(), px::db::MigrateDeviceDB(), px::asio::CCdsHandler::set_channel_value(), px::asio::CCdsSyncIO::set_channel_value_s(), px::asio::CCdsSyncIO::set_channel_values(), CScheduler::start(), and CScheduler::timer_cb().
CWallTime& px::CWallTime::operator= (const CMonoTime &) delete
Assignment operator.
We prohibit assignment from a monotonic timestamp, since it's nonsensical in virtually all cases, and likely to cause bugs.
CWallTime& px::CWallTime::operator= (CMonoTime &&) delete
The documentation for this class was generated from the following files:
wall_time.hpp
wall_time.cpp