libpx: px::asio::CTcpListener Class Reference
px::asio::CTcpListener Class Reference
ASIO interface details and general IO functions. | IO_Actors
TCP Socket Listener class, used to accept new TCP connections.
#include <tcp_listener.hpp>
Public Member Functions
PUBLIC ~CTcpListener ()
Destructor.
virtual PUBLIC void close ()
Inherited from CIoActor.
PUBLIC bool is_open ()
Access method to test if the connection is open.
Public Member Functions inherited from px::asio::CIoActor
CIoActor (CIoManager &manager)
Constructor.
virtual ~CIoActor ()
Destructor.
boost::asio::io_service & get_io_service () const
Get the I/O service associated with the owner of this actor.
PUBLIC CServerCore & get_server_core () const
Get the container for CDS data management.
PUBLIC CCdsHandler & get_cds_handler () const
Get the container for CDS data management.
PUBLIC bool get_quit_status ()
Get the quit status from connection IO manager.
Static Public Member Functions
static PUBLIC std::shared_ptr
< CTcpListener > create (CIoManager &manager, const CProtocolHandler &prot, uint16_t port, std::shared_ptr< boost::asio::ssl::context > &ctx, bool ipv6_enable=false)
Factory function to create a new CTcpListener object with SSL.
static PUBLIC std::shared_ptr
< CTcpListener > create (CIoManager &manager, const CProtocolHandler &prot, uint16_t port, bool ipv6_enable=false)
Factory function to create a new CTcpListener object.
Private Member Functions
PUBLIC CTcpListener (CIoManager &manager, const CProtocolHandler &prot, uint16_t port, bool ipv6_enable=false)
Constructor.
PUBLIC CTcpListener (CIoManager &manager, const CProtocolHandler &prot, uint16_t port, std::shared_ptr< boost::asio::ssl::context > &ctx, bool ipv6_enable=false)
Constructor.
PUBLIC void accept ()
Asynchronously accept a new connection.
PUBLIC void ssl_accept ()
Asynchronously accept a new ssl connection.
PUBLIC void handle_accept (const boost::system::error_code &err, const std::shared_ptr< CTcpConnection > &pconn)
Callback function for Boost.Asio upon accepting a new connection.
PUBLIC void handle_ssl_accept (const boost::system::error_code &err, const std::shared_ptr< CTcpSslConnection > &pconn)
Callback function for Boost.Asio upon accepting a new ssl connection.
Private Attributes
std::unique_ptr
< boost::asio::ip::tcp::acceptor > _acceptor
The underlying Boost.Asio TCP acceptor object.
std::shared_ptr< CProtocolHandler > _prot
Protocol-specific handler, used to parse and handle incoming requests and generate responses (needed to assign each accepted connection an appropriate protocol handler).
std::shared_ptr
< boost::asio::ssl::context > _ctx
Used to get at the SSL options such as verification mode, certificate files, and so on.
Additional Inherited Members
Protected Member Functions inherited from px::asio::CIoActor
void remove ()
This method is called when an actor wants to remove itself from the I/O management interface.
Protected Attributes inherited from px::asio::CIoActor
CIoManager & _owner
The I/O manager object that "owns" this connection.
Detailed Description
TCP Socket Listener class, used to accept new TCP connections.
This class implements a TCP "listener". It binds to a specific TCP port, then listens for incoming connections, spawning (and accept()ing) a new connection object if/when a new connection attempt is made.
Definition at line 27 of file tcp_listener.hpp.
Constructor & Destructor Documentation
px::asio::CTcpListener::~CTcpListener ()
Destructor.
Definition at line 205 of file tcp_listener.cpp.
References close(), LIBPX_ERR, and LIBPX_FERR.
px::asio::CTcpListener::CTcpListener (CIoManager & manager, const CProtocolHandler & prot, uint16_t port, bool ipv6_enable = false) private
Constructor.
Parameters
manager The I/O manager object to which this listener is to be bound.
prot Protocol handler object which is utilized to perform protocol-specific operations in an abstracted manner; the listener doesn't need this directly, but individual connections will.
port The TCP port to which we should bind/listen
ipv6_enable Defined TCP version - default to false, if value is 'true' then IPV6 else IPV4
Exceptions
boost::system::system_error The listener could not be initialized.
Definition at line 92 of file tcp_listener.cpp.
References _acceptor, _prot, accept(), px::asio::CIoActor::get_io_service(), LIBPX_DEBUG, LIBPX_ERR, LIBPX_FERR, px::asio::CProtocolHandler::protocol(), and px::generic_err::what().
Referenced by create().
px::asio::CTcpListener::CTcpListener (CIoManager & manager, const CProtocolHandler & prot, uint16_t port, std::shared_ptr< boost::asio::ssl::context > & ctx, bool ipv6_enable = false) private
Constructor.
Parameters
manager The I/O manager object to which this listener is to be bound.
prot Protocol handler object which is utilized to perform protocol-specific operations in an abstracted manner; the listener doesn't need this directly, but individual connections will.
port The TCP port to which we should bind/listen
ipv6_enable Defined TCP version - default to false, if value is 'true' then IPV6 else IPV4
ctx SSL options such as verification mode, certificate files, and so on.
Exceptions
boost::system::system_error The listener could not be initialized.
Definition at line 148 of file tcp_listener.cpp.
References _acceptor, _prot, px::asio::CIoActor::get_io_service(), LIBPX_DEBUG, LIBPX_ERR, LIBPX_FERR, ssl_accept(), and px::generic_err::what().
Member Function Documentation
std::shared_ptr< CTcpListener > px::asio::CTcpListener::create (CIoManager & manager, const CProtocolHandler & prot, uint16_t port, std::shared_ptr< boost::asio::ssl::context > & ctx, bool ipv6_enable = false) static
Factory function to create a new CTcpListener object with SSL.
Parameters
manager The I/O manager object to which this object is to be bound
prot Protocol handler object which is utilized to perform protocol-specific operations in an abstracted manner; the listener doesn't need this directly, but individual connections will.
port The TCP port to which we should bind/listen
ctx The ssl context if we are listening for SSL connections
ipv6_enable Defined TCP version - default to false, if value is 'true' then IPV6 else IPV4
Exceptions
boost::system::system_error The listener could not be initialized.
px::generic_err
Returns
Shared pointer containing the new instance of CTcpListener.
Definition at line 58 of file tcp_listener.cpp.
References CTcpListener(), LIBPX_ERR, and LIBPX_FERR.
std::shared_ptr< CTcpListener > px::asio::CTcpListener::create (CIoManager & manager, const CProtocolHandler & prot, uint16_t port, bool ipv6_enable = false) static
Factory function to create a new CTcpListener object.
Parameters
manager The I/O manager object to which this object is to be bound
prot Protocol handler object which is utilized to perform protocol-specific operations in an abstracted manner; the listener doesn't need this directly, but individual connections will.
port The TCP port to which we should bind/listen
ipv6_enable Defined TCP version - default to false, if value is 'true' then IPV6 else IPV4
Exceptions
boost::system::system_error The listener could not be initialized.
px::generic_err
Returns
Shared pointer containing the new instance of CTcpListener.
Definition at line 25 of file tcp_listener.cpp.
References CTcpListener(), LIBPX_ERR, and LIBPX_FERR.
void px::asio::CTcpListener::close () virtual
Inherited from CIoActor.
Reimplemented from px::asio::CIoActor.
Definition at line 226 of file tcp_listener.cpp.
References _acceptor, LIBPX_ERR, and LIBPX_FERR.
Referenced by ~CTcpListener().
bool px::asio::CTcpListener::is_open ()
Access method to test if the connection is open.
Returns
True if open.
Definition at line 443 of file tcp_listener.cpp.
References _acceptor.
void px::asio::CTcpListener::accept () private
Asynchronously accept a new connection.
This call initiates the asynchronous acceptance of a new TCP connection. When a new incoming connection is established, the handle_accept() function is called.
Exceptions
boost::system::system_error The new connection could not be created/accepted.
Definition at line 247 of file tcp_listener.cpp.
References _acceptor, px::asio::CIoActor::_owner, _prot, px::asio::CTcpConnection::create(), handle_accept(), LIBPX_ERR, and LIBPX_FERR.
Referenced by CTcpListener(), and handle_accept().
void px::asio::CTcpListener::ssl_accept () private
Asynchronously accept a new ssl connection.
This call initiates the asynchronous acceptance of a new TCP SSL connection. When a new incoming connection is established, the handle_ssl_accept() function is called.
Exceptions
boost::system::system_error The new connection could not be created/accepted.
Definition at line 351 of file tcp_listener.cpp.
References _acceptor, _ctx, px::asio::CIoActor::_owner, _prot, px::asio::CTcpSslConnection::create(), handle_ssl_accept(), LIBPX_ERR, and LIBPX_FERR.
Referenced by CTcpListener(), and handle_ssl_accept().
void px::asio::CTcpListener::handle_accept (const boost::system::error_code & err, const std::shared_ptr< CTcpConnection > & pconn) private
Callback function for Boost.Asio upon accepting a new connection.
Parameters
err The error code (if any) returned from the asynchronous accept() operation
pconn The new connection object
Definition at line 278 of file tcp_listener.cpp.
References _acceptor, px::asio::CIoActor::_owner, accept(), px::asio::CIoManager::add(), LIBPX_DEBUG, LIBPX_ERR, LIBPX_FERR, and LIBPX_WARN.
Referenced by accept().
void px::asio::CTcpListener::handle_ssl_accept (const boost::system::error_code & err, const std::shared_ptr< CTcpSslConnection > & pconn) private
Callback function for Boost.Asio upon accepting a new ssl connection.
Parameters
err The error code (if any) returned from the asynchronous accept() operation
pconn The new connection object
Definition at line 382 of file tcp_listener.cpp.
References _acceptor, px::asio::CIoActor::_owner, px::asio::CIoManager::add(), LIBPX_DEBUG, LIBPX_ERR, LIBPX_FERR, LIBPX_WARN, and ssl_accept().
Referenced by ssl_accept().
Member Data Documentation
std::unique_ptr<boost::asio::ip::tcp::acceptor> px::asio::CTcpListener::_acceptor private
The underlying Boost.Asio TCP acceptor object.
Definition at line 222 of file tcp_listener.hpp.
Referenced by accept(), close(), CTcpListener(), handle_accept(), handle_ssl_accept(), is_open(), and ssl_accept().
std::shared_ptr<CProtocolHandler> px::asio::CTcpListener::_prot private
Protocol-specific handler, used to parse and handle incoming requests and generate responses (needed to assign each accepted connection an appropriate protocol handler).
Definition at line 229 of file tcp_listener.hpp.
Referenced by accept(), CTcpListener(), and ssl_accept().
std::shared_ptr<boost::asio::ssl::context> px::asio::CTcpListener::_ctx private
Used to get at the SSL options such as verification mode, certificate files, and so on.
Definition at line 235 of file tcp_listener.hpp.
Referenced by ssl_accept().
The documentation for this class was generated from the following files:
tcp_listener.hpp
tcp_listener.cpp