libpx: px::serialize::CRawArchive Class Reference
px::serialize::CRawArchive Class Reference
High-performance "raw" data archive.
#include <raw_archive.hpp>
Public Member Functions
CRawArchive (unsigned char *pbuf, size_t len)
Constructor.
void append (const void *pbuf, size_t len)
Append data to the archive's assocated buffer.
void scan (void *pbuf, size_t len)
Scan input data from the archive's assocated buffer.
void reset ()
Reset the archive's position back to 0.
Private Member Functions
void check (size_t len)
Santiy check: ensure that there is enough space left in the archive's associated buffer.
Private Attributes
unsigned char * _buf
Base address of the buffer to which this archive is bound.
size_t _size
Size of available space within the buffer (not necessarily valid bytes, just addressable memory)
size_t _pos
Current position within the archive.
Detailed Description
High-performance "raw" data archive.
This archive is capable of saving/loading data to/from a pre-allocated, fixed-size region of memory. This is useful for performing high-performance serialization, for example to/from a shared memory segment.
Definition at line 18 of file raw_archive.hpp.
Constructor & Destructor Documentation
px::serialize::CRawArchive::CRawArchive (unsigned char * pbuf, size_t len)
Constructor.
Parameters
pbuf Location of a buffer to use for this archive
len Length of the archive's buffer, in bytes
Definition at line 32 of file raw_archive.hpp.
Member Function Documentation
void px::serialize::CRawArchive::append (const void * pbuf, size_t len)
Append data to the archive's assocated buffer.
Parameters
pbuf Address of the data to be copied into the archive
len Number of bytes to copy into the archive
Exceptions
too_much_data Thrown if the archive's buffer does not contain enough free space to store the requested number of bytes
Definition at line 50 of file raw_archive.hpp.
References _buf, _pos, and check().
void px::serialize::CRawArchive::scan (void * pbuf, size_t len)
Scan input data from the archive's assocated buffer.
Parameters
pbuf Address into which the data scanned from the archive is to be written
len Number of bytes to copy from the archive
Exceptions
too_much_data Thrown if the archive's buffer does not contain enough data to load the requested number of bytes
Definition at line 69 of file raw_archive.hpp.
References _buf, _pos, and check().
void px::serialize::CRawArchive::reset ()
Reset the archive's position back to 0.
Definition at line 80 of file raw_archive.hpp.
References _pos.
void px::serialize::CRawArchive::check (size_t len) private
Santiy check: ensure that there is enough space left in the archive's associated buffer.
Parameters
len The number of bytes needed for the next operation
Exceptions
too_much_data Thrown if the number of requested bytes extends beyond the buffer's capacity, given the current archive position
Definition at line 97 of file raw_archive.hpp.
References _pos, _size, and unlikely.
Referenced by append(), and scan().
Member Data Documentation
unsigned char* px::serialize::CRawArchive::_buf private
Base address of the buffer to which this archive is bound.
Definition at line 112 of file raw_archive.hpp.
Referenced by append(), and scan().
size_t px::serialize::CRawArchive::_size private
Size of available space within the buffer (not necessarily valid bytes, just addressable memory)
Definition at line 118 of file raw_archive.hpp.
Referenced by check().
size_t px::serialize::CRawArchive::_pos private
Current position within the archive.
Definition at line 123 of file raw_archive.hpp.
Referenced by append(), check(), reset(), and scan().
The documentation for this class was generated from the following file:
raw_archive.hpp