libpx: px::CBase64Converter Class Reference
px::CBase64Converter Class Reference
Base64 conversion routine.
#include <b64_converter.hpp>
Static Public Member Functions
static PUBLIC px::string encode (const std::vector< unsigned char > &val)
Base64-encode a binary value.
static PUBLIC std::vector
< unsigned char > decode (const px::string &val)
Decode a base64-encoded string value.
static PUBLIC px::string uri_encode (const std::vector< unsigned char > &val)
Base64-URI-encode a binary value.
static PUBLIC std::vector
< unsigned char > uri_decode (const px::string &val)
Decode a string value that is either base64 or base64-URI encoded.
Static Private Member Functions
static void encode_block (const unsigned char *in, unsigned char *out, size_t len, bool uri=false)
Black magic taken from http://base64.sourceforge.net/b64.c In and out must not be null.
static void decode_block (const unsigned char *in, unsigned char *out)
Black magic taken from http://base64.sourceforge.net/b64.c In and out must not be null.
static px::string internal_encode (const std::vector< unsigned char > &val, bool uri)
Encode, giving choice of URI or standard style Val must not be empty.
Detailed Description
Base64 conversion routine.
This class converts (bi-directionally) between base64-encoded strings and binary blobs.
Definition at line 19 of file b64_converter.hpp.
Member Function Documentation
px::string px::CBase64Converter::encode (const std::vector< unsigned char > & val) static
Base64-encode a binary value.
Parameters
val The binary value to be encoded. Must not be empty.
Returns
A base64-encoded string version of 'val'
Definition at line 60 of file b64_converter.cpp.
Referenced by px::val_impl::as_datatype::operator()(), serialize_field_value(), and serialize_one_repeated_field_value().
std::vector< unsigned char > px::CBase64Converter::decode (const px::string & val) static
Decode a base64-encoded string value.
Parameters
val The base64-encoded string value to be decoded. Must not be empty.
Returns
A binary version of 'val'
Definition at line 73 of file b64_converter.cpp.
References b64_decode_chars.
Referenced by px::val_impl::as_datatype::operator()(), and set_single_value().
px::string px::CBase64Converter::uri_encode (const std::vector< unsigned char > & val) static
Base64-URI-encode a binary value.
The encoding will use -, _ and . in place of +, / and =, so that the resulting string will never need URI-escaping.
Parameters
val The binary value to be encoded. Must not be empty.
Returns
A base64-URI-encoded string version of 'val'
Definition at line 65 of file b64_converter.cpp.
std::vector< unsigned char > px::CBase64Converter::uri_decode (const px::string & val) static
Decode a string value that is either base64 or base64-URI encoded.
Parameters
val The base64-encoded or base64-URI-encoded string value. Must not be empty.
Returns
A binary version of 'val'
Definition at line 134 of file b64_converter.cpp.
void px::CBase64Converter::encode_block (const unsigned char * in, unsigned char * out, size_t len, bool uri = false) static private
Black magic taken from http://base64.sourceforge.net/b64.c In and out must not be null.
Len must be > 0
Definition at line 163 of file b64_converter.cpp.
References b64_chars, and b64_uri_chars.
Referenced by internal_encode().
void px::CBase64Converter::decode_block (const unsigned char * in, unsigned char * out) static private
Black magic taken from http://base64.sourceforge.net/b64.c In and out must not be null.
Definition at line 190 of file b64_converter.cpp.
px::string px::CBase64Converter::internal_encode (const std::vector< unsigned char > & val, bool uri) static private
Encode, giving choice of URI or standard style Val must not be empty.
Definition at line 23 of file b64_converter.cpp.
References encode_block().
The documentation for this class was generated from the following files:
b64_converter.hpp
b64_converter.cpp