libpx: perf__type.cpp File Reference
perf__type.cpp File Reference
#include <memory>
#include <boost/test/unit_test.hpp>
#include <boost/flyweight.hpp>
#include "px/exception.hpp"
#include "px/serialization/byte_counter.hpp"
#include "px/serialization/serializer.hpp"
#include "px/serialization/deserializer.hpp"
#include "px/serialization/archive/raw_archive.hpp"
#include "px/serialization/type/all.hpp"
#include "px/type/timestamp.hpp"
#include "pcd_perf.h"
Functions
template<typename T >
static void benchmark (T &val, const char *id)
Suite for all libpx tests.
BOOST_AUTO_TEST_CASE (core)
Core type serialization.
BOOST_AUTO_TEST_CASE (array)
Array serialization.
BOOST_AUTO_TEST_CASE (deque)
Deque serialization.
BOOST_AUTO_TEST_CASE (flyweight)
Flyweight serialization.
BOOST_AUTO_TEST_CASE (list)
List serialization.
BOOST_AUTO_TEST_CASE (map)
Map serialization.
BOOST_AUTO_TEST_CASE (optional)
Pair serialization.
BOOST_AUTO_TEST_CASE (pair)
Pair serialization.
BOOST_AUTO_TEST_CASE (pxstring)
px::string serialization
BOOST_AUTO_TEST_CASE (set)
Set serialization.
BOOST_AUTO_TEST_CASE (string)
String serialization.
BOOST_AUTO_TEST_CASE (unique_ptr)
Unique ptr serialization.
BOOST_AUTO_TEST_CASE (unordered_map)
Unordered map serialization.
BOOST_AUTO_TEST_CASE (unordered_set)
Unordered set serialization.
BOOST_AUTO_TEST_CASE (variant)
Variant serialization.
BOOST_AUTO_TEST_CASE (vector)
Vector serialization.
Function Documentation
template<typename T > static void benchmark (T & val, const char * id) static
Suite for all libpx tests.
Suite for all serialization tests Suite for all performance tests
Definition at line 35 of file perf__type.cpp.
References px::serialize::CByteCounter::size().
Referenced by BOOST_AUTO_TEST_CASE().
BOOST_AUTO_TEST_CASE (core)
Core type serialization.
Definition at line 90 of file perf__type.cpp.
References benchmark().
BOOST_AUTO_TEST_CASE (array)
Array serialization.
Definition at line 111 of file perf__type.cpp.
References benchmark().
BOOST_AUTO_TEST_CASE (deque)
Deque serialization.
Definition at line 127 of file perf__type.cpp.
References benchmark().
BOOST_AUTO_TEST_CASE (flyweight)
Flyweight serialization.
Definition at line 143 of file perf__type.cpp.
References benchmark().
BOOST_AUTO_TEST_CASE (list)
List serialization.
Definition at line 154 of file perf__type.cpp.
References benchmark().
BOOST_AUTO_TEST_CASE (map)
Map serialization.
Definition at line 170 of file perf__type.cpp.
References benchmark().
BOOST_AUTO_TEST_CASE (optional)
Pair serialization.
Definition at line 186 of file perf__type.cpp.
References benchmark().
BOOST_AUTO_TEST_CASE (pair)
Pair serialization.
Definition at line 201 of file perf__type.cpp.
References benchmark().
BOOST_AUTO_TEST_CASE (pxstring)
px::string serialization
Definition at line 212 of file perf__type.cpp.
References benchmark().
BOOST_AUTO_TEST_CASE (set)
Set serialization.
Definition at line 223 of file perf__type.cpp.
References benchmark().
BOOST_AUTO_TEST_CASE (string)
String serialization.
Definition at line 239 of file perf__type.cpp.
References benchmark().
BOOST_AUTO_TEST_CASE (unique_ptr)
Unique ptr serialization.
Definition at line 250 of file perf__type.cpp.
References benchmark().
BOOST_AUTO_TEST_CASE (unordered_map)
Unordered map serialization.
Definition at line 270 of file perf__type.cpp.
References benchmark().
BOOST_AUTO_TEST_CASE (unordered_set)
Unordered set serialization.
Definition at line 286 of file perf__type.cpp.
References benchmark().
BOOST_AUTO_TEST_CASE (variant)
Variant serialization.
Definition at line 302 of file perf__type.cpp.
References benchmark().
BOOST_AUTO_TEST_CASE (vector)
Vector serialization.
Definition at line 320 of file perf__type.cpp.
References benchmark().