libpx: px::cds::CServer Class Reference
px::cds::CServer Class Reference
Singleton class to manage CDS connections, from server side.
#include <server.hpp>
Public Member Functions
PUBLIC void listen ()
Start listening for connections.
PUBLIC void shutdown ()
Terminate existing connections.
PUBLIC std::vector
< std::shared_ptr
< CRequestResponse > > get_pending_requests ()
Get a list of pending requests to process.
PUBLIC bool send_response (std::shared_ptr< CRequestResponse > response)
Send a response, to the client_id set in the RequestResponse object.
PUBLIC px::string source (ClientID) const
Simple getter to retrive client name given client id.
PUBLIC int uid (ClientID id) const
Return the Linux UID of the process connected to a particular client ID.
PUBLIC int update_uid (ClientID id)
Update the UID, in case the process has done a setuid() Returns the new UID (even if unchanged), -1 if not known.
PUBLIC int update_uid (ClientID id, int new_uid)
Set the client's uid to new_uid.
Static Public Member Functions
static PUBLIC CServer * get ()
Factory function: constructs if necessary, returns existing instance otherwise.
Public Attributes
std::unordered_map< ClientID,
std::shared_ptr
< CServerConnection > > connections
std::mutex conn_list_lock
Private Member Functions
CServer ()
Default constructor, private so one must construct using get()
void check_for_connections ()
Look for any new connections, establish them, set up the new client IDs and IPC objects.
void serve_client_conn_req (ClientID client_id, int client_socket)
Look for any new messages on the client connection socket.
Private Attributes
ClientID next_client_id
std::vector< struct pollfd > watch_files
int master_socket
int shutdown_socket
std::vector< int > pending_connections
CSignalPipe sigpipe
Detailed Description
Singleton class to manage CDS connections, from server side.
Definition at line 20 of file server.hpp.
Constructor & Destructor Documentation
px::cds::CServer::CServer () private
Default constructor, private so one must construct using get()
Definition at line 116 of file server.hpp.
Referenced by get().
Member Function Documentation
CServer * px::cds::CServer::get () static
Factory function: constructs if necessary, returns existing instance otherwise.
Definition at line 32 of file server.cpp.
References CServer(), px::cds::g_cdsServer, px::cds::g_cdsServer_mutex, LIBPX_ERR, and unlikely.
void px::cds::CServer::listen ()
Start listening for connections.
May throw: generic_err if can't open a socket for the connection.
Definition at line 268 of file server.cpp.
References CDS_SOCKET_PATH, px::cds::CSignalPipe::fd(), LIBPX_WARN, master_socket, shutdown(), shutdown_socket, sigpipe, and watch_files.
void px::cds::CServer::shutdown ()
Terminate existing connections.
Definition at line 250 of file server.cpp.
References conn_list_lock, connections, master_socket, and watch_files.
Referenced by get_pending_requests(), and listen().
std::vector< std::shared_ptr< CRequestResponse > > px::cds::CServer::get_pending_requests ()
Get a list of pending requests to process.
Side effect: Will notice any new client connections and establish them. Will block if there are no new connections or pending requests. May return an empty list (if all that happened was new connections).
The returned requests may be from any client or combination thereof. Will usually return all pending requests for all connected clients.
May throw: generic_err if can't re-open a socket for the connection.
Definition at line 457 of file server.cpp.
References check_for_connections(), px::cds::CSignalPipe::clear(), conn_list_lock, connections, LIBPX_ERR, LIBPX_NOTICE, master_socket, pending_connections, px::cds::req_unpack(), serve_client_conn_req(), shutdown(), shutdown_socket, sigpipe, unlikely, and watch_files.
bool px::cds::CServer::send_response (std::shared_ptr< CRequestResponse > response)
Send a response, to the client_id set in the RequestResponse object.
Returns true if successful, false if the queue is full. If the client connection is gone or nonexistent, returns true and silently discards the response. Safe to call on background threads.
May throw: too_much_data (if the response is too large to ever fit in the buffer), generic_err
Definition at line 324 of file server.cpp.
References CALLBACK_NONE, conn_list_lock, connections, LIBPX_ERR, LIBPX_WARN, px::cds::QUEUE_FULL, px::cds::req_pack(), px::cds::RESPONSE_TOO_BIG, px::cds::SUCCEEDED, and unlikely.
px::string px::cds::CServer::source (ClientID id) const
Simple getter to retrive client name given client id.
returns "unknown" if unable to find client ID
Definition at line 619 of file server.cpp.
References conn_list_lock, and connections.
Referenced by check_for_connections().
int px::cds::CServer::uid (ClientID id) const
Return the Linux UID of the process connected to a particular client ID.
Returns -1 if not known.
Definition at line 631 of file server.cpp.
References conn_list_lock, connections, and unlikely.
int px::cds::CServer::update_uid (ClientID id)
Update the UID, in case the process has done a setuid() Returns the new UID (even if unchanged), -1 if not known.
Definition at line 681 of file server.cpp.
References conn_list_lock, connections, px::CUtil::get_process_gids(), and unlikely.
Referenced by check_for_connections(), and serve_client_conn_req().
int px::cds::CServer::update_uid (ClientID id, int new_uid)
Set the client's uid to new_uid.
new_uid is useful when the uid is set after a CDS connection is made.
Definition at line 648 of file server.cpp.
References conn_list_lock, connections, px::CUtil::get_process_gids(), LIBPX_NOTICE, and unlikely.
void px::cds::CServer::check_for_connections () private
Look for any new connections, establish them, set up the new client IDs and IPC objects.
Can throw px::generic_err if can't open a socket for the connection.
Definition at line 57 of file server.cpp.
References connections, LIBPX_NOTICE, master_socket, next_client_id, pending_connections, source(), unlikely, update_uid(), and watch_files.
Referenced by get_pending_requests().
void px::cds::CServer::serve_client_conn_req (ClientID client_id, int client_socket) private
Look for any new messages on the client connection socket.
SCM_CREDENTIALS is an example of a client message.
Definition at line 709 of file server.cpp.
References LIBPX_ERR, LIBPX_WARN, and update_uid().
Referenced by get_pending_requests().
Member Data Documentation
std::unordered_map<ClientID, std::shared_ptr<CServerConnection> > px::cds::CServer::connections
Definition at line 103 of file server.hpp.
Referenced by check_for_connections(), get_pending_requests(), send_response(), shutdown(), source(), uid(), and update_uid().
std::mutex px::cds::CServer::conn_list_lock mutable
Definition at line 105 of file server.hpp.
Referenced by get_pending_requests(), send_response(), shutdown(), source(), uid(), and update_uid().
ClientID px::cds::CServer::next_client_id private
Definition at line 132 of file server.hpp.
Referenced by check_for_connections().
std::vector<struct pollfd> px::cds::CServer::watch_files private
Definition at line 135 of file server.hpp.
Referenced by check_for_connections(), get_pending_requests(), listen(), and shutdown().
int px::cds::CServer::master_socket private
Definition at line 137 of file server.hpp.
Referenced by check_for_connections(), get_pending_requests(), listen(), and shutdown().
int px::cds::CServer::shutdown_socket private
Definition at line 139 of file server.hpp.
Referenced by get_pending_requests(), and listen().
std::vector<int> px::cds::CServer::pending_connections private
Definition at line 142 of file server.hpp.
Referenced by check_for_connections(), and get_pending_requests().
CSignalPipe px::cds::CServer::sigpipe private
Definition at line 145 of file server.hpp.
Referenced by get_pending_requests(), and listen().
The documentation for this class was generated from the following files:
server.hpp
server.cpp