libpx: px::sub::CSubscriptionManager Class Reference
px::sub::CSubscriptionManager Class Reference
Class for managing CDS subscriptions.
#include <subscription_manager.hpp>
Public Member Functions
PUBLIC CSubscriptionManager ()
Constructor.
PUBLIC ~CSubscriptionManager ()
Destructor.
PUBLIC uint64_t new_subscriber ()
Allocate a new subscriber.
PUBLIC void remove_subscriber (uint64_t id)
Remove an existing subscriber.
PUBLIC bool add_subscription (uint64_t subscriber, const CItemId &item)
Add a new item to an existing subscription.
PUBLIC bool remove_subscription (uint64_t subscriber, const CItemId &item)
Remove a [potentially] existing subscription.
PUBLIC void get_subscribers (const CItemId &item, std::vector< uint64_t > &results) const
Get a list of subscribers for a given item.
PUBLIC void set_reflexive (const uint64_t subscriber, const bool reflexive)
Set subscriber's preference for reflexive notifications.
PUBLIC bool is_reflexive (const uint64_t subscriber) const
Determine if subscriber wants reflexive notifications.
PUBLIC const boost::optional
< CSubscriberInfo & > get_subscriber_info (uint64_t subscriber)
Get an existing subscriber's information.
PUBLIC bool get_validationhook_object (px::id_t &id, std::weak_ptr< px::sub::CValidationHook > &validation_object)
Get the validation object from subscription manager item_id map.
PUBLIC bool get_validationhook_object (std::string &tag, std::weak_ptr< px::sub::CValidationHook > &validation_object)
Get the validation object from subscription manager item_id map.
Static Public Member Functions
static PUBLIC std::vector
< px::sub::subscription_type > list_device_subscription_types ()
List all subscription types that apply to devices.
static PUBLIC std::vector
< px::sub::subscription_type > list_channel_subscription_types ()
List all subscription types that apply to channels.
static PUBLIC std::vector
< px::sub::subscription_type > list_device_recursive_subscription_types ()
List all recursive subscription types that apply to devices.
static PUBLIC std::vector
< px::sub::subscription_type > list_channel_recursive_subscription_types ()
List all recursive subscription types that apply to channels.
static PUBLIC std::vector
< px::sub::subscription_type > list_device_direct_subscription_types ()
List all non-recursive subscription types that apply to devices.
static PUBLIC std::vector
< px::sub::subscription_type > list_channel_direct_subscription_types ()
List all non-recursive subscription types that apply to channels.
Private Types
typedef std::vector< size_t > item_sublist_t
A list of subscriber indices (offsets in _subscribers)
Private Attributes
std::unordered_map< CItemId,
item_sublist_t > _item_map
Map from the subscribed item to the list of subscribers (indices)
std::unordered_map< px::id_t,
std::weak_ptr
< px::sub::CValidationHook > > _validation_id_map
Map of channel id and the weak validation pointer.
std::unordered_map
< std::string, std::weak_ptr
< px::sub::CValidationHook > > _validation_tag_map
Map of oob tag and the weak validation pointer.
std::vector< CSubscriberInfo > _subscribers
List of all known subscribers.
std::unordered_map< uint64_t,
size_t > _subscriber_map
Map from subscriber ID into the corresponding entry in the _subscribers list.
std::unordered_map< CItemId,
item_sublist_t > _partial_tag_items_map
Map from the subscribed item to the list of subscribers (indices) for the OOBs with partial tags passed.
pthread_rwlock_t _rwlock
Read/write lock to prevent these maps from changing while being iterated over or searched.
Detailed Description
Class for managing CDS subscriptions.
This class encapsulates subscription handling for use by the CDS. It doesn't actually implement subscription-based publication, or know anything about the kinds of things being subscribed or published; rather, it's a lightweight class that can be used to manage a many-to-many mapping of subscriptions between some kind of "subscribers" and some kind of "objects".
In practical terms, the "objects" are typically things like channels and devices, while a "subscriber" is an application-level concept that's exposed through the Toolkit API. This allows a single application to manage any number of separate subscribers on an individual basis, so that (for example) the Mercury server doesn't need to duplicate this functionality in order to support multiple clients that each have their own individual subscriptions.
Performance is important for subscriptions. By far the most common case, and therefore the case that these classes are optimized for, is that of a channel value update which may need to be pushed to any number of subscribers interested in real-time updates. Therefore we don't mind things like the creation and deletion of subscriptions to be somewhat slower, if it helps to optimize the case of subscriber look-up (which could happen thousands of times per second on a busy system).
Definition at line 51 of file subscription_manager.hpp.
Member Typedef Documentation
typedef std::vector<size_t> px::sub::CSubscriptionManager::item_sublist_t private
A list of subscriber indices (offsets in _subscribers)
Definition at line 225 of file subscription_manager.hpp.
Constructor & Destructor Documentation
px::sub::CSubscriptionManager::CSubscriptionManager ()
Constructor.
Definition at line 13 of file subscription_manager.cpp.
References _rwlock.
px::sub::CSubscriptionManager::~CSubscriptionManager ()
Destructor.
Definition at line 22 of file subscription_manager.cpp.
Member Function Documentation
uint64_t px::sub::CSubscriptionManager::new_subscriber ()
Allocate a new subscriber.
It is the caller's responsibility to call remove_subscriber() when it is finished with this ID.
Returns
A newly-allocated unique ID for a new subscriber
Definition at line 31 of file subscription_manager.cpp.
References px::sub::CSubscriberInfo::create(), and LIBPX_DEBUG.
void px::sub::CSubscriptionManager::remove_subscriber (uint64_t id)
Remove an existing subscriber.
If the subscriber ID doesn't exist, this call has no effect.
Parameters
id The ID of the subscriber to be removed
Definition at line 111 of file subscription_manager.cpp.
References px::sub::CSubscriberInfo::get_id(), px::sub::CSubscriberInfo::get_items(), LIBPX_DEBUG, PX_ID_UNSET, unlikely, and px::sub::validation_hook.
bool px::sub::CSubscriptionManager::add_subscription (uint64_t subscriber, const CItemId & item)
Add a new item to an existing subscription.
Parameters
subscriber The ID of the subscriber for whom this subscription should be added
item The item to be subscribed to
Returns
True if the subscription was added (i.e. did not previously exist). False if subscriber ID is invalid or subscription already existed.
Definition at line 257 of file subscription_manager.cpp.
References px::sub::CItemId::_id, px::sub::CItemId::_tag, px::sub::CItemId::_type, px::sub::CItemId::_validation_hook, px::sub::CItemId::is_tag_partial, LIBPX_DEBUG, PX_ID_UNSET, and px::sub::validation_hook.
bool px::sub::CSubscriptionManager::remove_subscription (uint64_t subscriber, const CItemId & item)
Remove a [potentially] existing subscription.
Parameters
subscriber The ID of the subscriber for whom this subscription should be removed
item The item to be un-subscribed from
Returns
True if the subscription was removed (i.e. previously existed)
Definition at line 345 of file subscription_manager.cpp.
References px::sub::CItemId::_id, px::sub::CItemId::_tag, px::sub::CItemId::_type, px::sub::CItemId::is_tag_partial, LIBPX_DEBUG, PX_ID_UNSET, unlikely, and px::sub::validation_hook.
void px::sub::CSubscriptionManager::get_subscribers (const CItemId & item, std::vector< uint64_t > & results) const
Get a list of subscribers for a given item.
This is by FAR the most common operation that is performed by the subscription manager, and the internal structures are optimized to make it very fast.
Parameters
item The item to find subscribers for
results A list of subscriber IDs; the IDs of any subscribers who are subscribed for the specified item are appended to this list upon return from this call
Definition at line 431 of file subscription_manager.cpp.
References px::sub::CItemId::_id, px::sub::CItemId::_tag, px::sub::CItemId::_type, and LIBPX_DEBUG.
void px::sub::CSubscriptionManager::set_reflexive (const uint64_t subscriber, const bool reflexive)
Set subscriber's preference for reflexive notifications.
Parameters
subscriber The ID of the subscriber
reflexive True/False subscriber wants reflexive notifications
Definition at line 484 of file subscription_manager.cpp.
References LIBPX_DEBUG, and unlikely.
bool px::sub::CSubscriptionManager::is_reflexive (const uint64_t subscriber) const
Determine if subscriber wants reflexive notifications.
Parameters
subscriber The ID of the subscriber
Returns
True if subscriber should receive reflexive notifications
Definition at line 514 of file subscription_manager.cpp.
References LIBPX_DEBUG, and unlikely.
const boost::optional< px::sub::CSubscriberInfo & > px::sub::CSubscriptionManager::get_subscriber_info (uint64_t subscriber)
Get an existing subscriber's information.
Parameters
subscriber The ID of the subscriber
Definition at line 618 of file subscription_manager.cpp.
References likely.
std::vector< px::sub::subscription_type > px::sub::CSubscriptionManager::list_device_subscription_types () static
List all subscription types that apply to devices.
Returns
Vector of subscription_type
Definition at line 597 of file subscription_manager.cpp.
std::vector< px::sub::subscription_type > px::sub::CSubscriptionManager::list_channel_subscription_types () static
List all subscription types that apply to channels.
Returns
Vector of subscription_type
Definition at line 606 of file subscription_manager.cpp.
std::vector< px::sub::subscription_type > px::sub::CSubscriptionManager::list_device_recursive_subscription_types () static
List all recursive subscription types that apply to devices.
Returns
Vector of subscription_type
Definition at line 558 of file subscription_manager.cpp.
References px::sub::alarm_recursive, px::sub::device_create_recursive, px::sub::device_delete_recursive, and px::sub::device_state_recursive.
std::vector< px::sub::subscription_type > px::sub::CSubscriptionManager::list_channel_recursive_subscription_types () static
List all recursive subscription types that apply to channels.
Returns
Vector of subscription_type
Definition at line 548 of file subscription_manager.cpp.
References px::sub::alarm_recursive, and px::sub::digital_trends_recursive.
std::vector< px::sub::subscription_type > px::sub::CSubscriptionManager::list_device_direct_subscription_types () static
List all non-recursive subscription types that apply to devices.
Returns
Vector of subscription_type
Definition at line 570 of file subscription_manager.cpp.
References px::sub::change_signature, px::sub::device_command, px::sub::device_settings, and px::sub::device_state.
std::vector< px::sub::subscription_type > px::sub::CSubscriptionManager::list_channel_direct_subscription_types () static
List all non-recursive subscription types that apply to channels.
Returns
Vector of subscription_type
Definition at line 582 of file subscription_manager.cpp.
References px::sub::alarm, px::sub::channel_settings, px::sub::channel_state, px::sub::digital_trends, px::sub::value_set, px::sub::value_state_update, and px::sub::value_update.
bool px::sub::CSubscriptionManager::get_validationhook_object (px::id_t & id, std::weak_ptr< px::sub::CValidationHook > & validation_object)
Get the validation object from subscription manager item_id map.
Parameters
id- Channel id
validation_object- stores the weak pointer of validation object
Definition at line 50 of file subscription_manager.cpp.
References LIBPX_DEBUG, likely, and unlikely.
bool px::sub::CSubscriptionManager::get_validationhook_object (std::string & tag, std::weak_ptr< px::sub::CValidationHook > & validation_object)
Get the validation object from subscription manager item_id map.
Parameters
tag- oob tag
validation_object- stores the weak pointer of validation object
Definition at line 81 of file subscription_manager.cpp.
References LIBPX_DEBUG, and unlikely.
Member Data Documentation
std::unordered_map<CItemId, item_sublist_t> px::sub::CSubscriptionManager::_item_map private
Map from the subscribed item to the list of subscribers (indices)
Definition at line 235 of file subscription_manager.hpp.
std::unordered_map<px::id_t, std::weak_ptr<px::sub::CValidationHook> > px::sub::CSubscriptionManager::_validation_id_map private
Map of channel id and the weak validation pointer.
Definition at line 240 of file subscription_manager.hpp.
std::unordered_map<std::string, std::weak_ptr<px::sub::CValidationHook> > px::sub::CSubscriptionManager::_validation_tag_map private
Map of oob tag and the weak validation pointer.
Definition at line 245 of file subscription_manager.hpp.
std::vector<CSubscriberInfo> px::sub::CSubscriptionManager::_subscribers private
List of all known subscribers.
Definition at line 250 of file subscription_manager.hpp.
std::unordered_map<uint64_t, size_t> px::sub::CSubscriptionManager::_subscriber_map private
Map from subscriber ID into the corresponding entry in the _subscribers list.
Definition at line 256 of file subscription_manager.hpp.
std::unordered_map<CItemId, item_sublist_t> px::sub::CSubscriptionManager::_partial_tag_items_map private
Map from the subscribed item to the list of subscribers (indices) for the OOBs with partial tags passed.
Definition at line 262 of file subscription_manager.hpp.
pthread_rwlock_t px::sub::CSubscriptionManager::_rwlock mutable private
Read/write lock to prevent these maps from changing while being iterated over or searched.
Definition at line 268 of file subscription_manager.hpp.
Referenced by CSubscriptionManager().
The documentation for this class was generated from the following files:
subscription_manager.hpp
subscription_manager.cpp