libpx: px::serialize::CByteCounter Class Reference
px::serialize::CByteCounter Class Reference
Byte counter class.
#include <byte_counter.hpp>
Public Member Functions
CByteCounter ()
Constructor.
template<typename T >
void operator& (const T &val)
Overloads the & operator to perform byte-counting.
void append (const void *, size_t len)
Count the number of bytes used by the serialization of the given object's data.
void reset ()
Reset the size counter back to 0.
size_t size () const
Get the number of bytes which have been accumulated.
Private Attributes
size_t _size
Number of bytes for all objects counted so far.
Detailed Description
Byte counter class.
This is used like the serializer and deserializer classes, except that it doesn't actually perform any serialization. Instead, it simply counts the number of bytes which would be required to serialize the object.
Definition at line 15 of file byte_counter.hpp.
Constructor & Destructor Documentation
px::serialize::CByteCounter::CByteCounter ()
Constructor.
Definition at line 25 of file byte_counter.hpp.
Member Function Documentation
template<typename T > void px::serialize::CByteCounter::operator& (const T & val)
Overloads the & operator to perform byte-counting.
Parameters
val The value to be counted
Definition at line 35 of file byte_counter.hpp.
References px::serialize::save().
void px::serialize::CByteCounter::append (const void * , size_t len)
Count the number of bytes used by the serialization of the given object's data.
Parameters
len Number of bytes to be copied
Definition at line 46 of file byte_counter.hpp.
References _size.
void px::serialize::CByteCounter::reset ()
Reset the size counter back to 0.
Definition at line 55 of file byte_counter.hpp.
References _size.
Referenced by BOOST_AUTO_TEST_CASE().
size_t px::serialize::CByteCounter::size () const
Get the number of bytes which have been accumulated.
Returns
The number of bytes counted (so far)
Definition at line 63 of file byte_counter.hpp.
References _size.
Referenced by benchmark(), BOOST_AUTO_TEST_CASE(), and px::cds::req_pack().
Member Data Documentation
size_t px::serialize::CByteCounter::_size private
Number of bytes for all objects counted so far.
Definition at line 73 of file byte_counter.hpp.
Referenced by append(), reset(), and size().
The documentation for this class was generated from the following file:
byte_counter.hpp