libpx: px::db::CBlobHolder Class Reference
px::db::CBlobHolder Class Reference
Binary Blob Holder class.
#include <blob_holder.hpp>
Public Member Functions
CBlobHolder ()
~CBlobHolder ()
CBlobHolder (const CBlobHolder &arg)
Copy constructor.
CBlobHolder (CBlobHolder &&arg)
Move constructor.
CBlobHolder & operator= (const CBlobHolder &arg)
Copy Assignment.
CBlobHolder & operator= (CBlobHolder &&arg)
Move Assignment.
leveldb::Slice get () const
Get a LevelDB slice referring to this blob.
const unsigned char * get_ptr () const
Get a pointer to the data in this blob.
unsigned char * get_mutable_ptr ()
Get a pointer to the data in this blob for write.
void append (const void *ptr, size_t len)
Append data to the blob.
void reset ()
Clear/reset the blob's current value.
void reset (size_t size)
Resize and reset the blob's data.
size_t size () const
Get the current size of the blob.
Private Attributes
std::vector< unsigned char > _data
Internal buffer used to store the blob.
Detailed Description
Binary Blob Holder class.
Key/value stores treat the key and value as opaque binary blobs, usually requiring a non-temporary buffer to/from which these objects can be serialized and de-serialized. This simple class is used to hold the results of serialization and de-serialization.
It also bridges the gap between the underlying Toolkit classes (which know nothing about the specific database in use) and the database classes (which know nothing about the Toolkit objects to/from which its data is converted). Currently the database layer is LevelDB, but that could be changed without much trouble, and the classes utilizing the blob holder would be oblivious.
Definition at line 27 of file blob_holder.hpp.
Constructor & Destructor Documentation
px::db::CBlobHolder::CBlobHolder ()
Definition at line 31 of file blob_holder.hpp.
px::db::CBlobHolder::~CBlobHolder ()
Definition at line 33 of file blob_holder.hpp.
px::db::CBlobHolder::CBlobHolder (const CBlobHolder & arg)
Copy constructor.
Parameters
arg Object used to initialize this channel
Definition at line 43 of file blob_holder.hpp.
References _data.
px::db::CBlobHolder::CBlobHolder (CBlobHolder && arg)
Move constructor.
Parameters
arg Object used to initialize this channel
Definition at line 50 of file blob_holder.hpp.
References _data.
Member Function Documentation
CBlobHolder& px::db::CBlobHolder::operator= (const CBlobHolder & arg)
Copy Assignment.
Definition at line 58 of file blob_holder.hpp.
References _data.
CBlobHolder& px::db::CBlobHolder::operator= (CBlobHolder && arg)
Move Assignment.
Definition at line 68 of file blob_holder.hpp.
References _data.
leveldb::Slice px::db::CBlobHolder::get () const
Get a LevelDB slice referring to this blob.
A LevelDB slice is just a thing wrapper to an existing in-memory buffer (pointer + size). As such, it can't be generated directly from a well-typed class; instead, a blob holder is instantiated to store the serialized data for a key or value class, and this call is used to extract a LevelDB slice that refers to it.
While the slice is in use, you must not modify the blob contents.
Returns
A LevelDB slice referring to this blob
Definition at line 91 of file blob_holder.hpp.
References _data.
Referenced by px::db::CKeyValueStore::compact(), and px::db::CIterator::seek().
const unsigned char* px::db::CBlobHolder::get_ptr () const
Get a pointer to the data in this blob.
Definition at line 99 of file blob_holder.hpp.
References _data.
Referenced by px::db::DoesKeyExist(), and px::db::query_alarm_index_db().
unsigned char* px::db::CBlobHolder::get_mutable_ptr ()
Get a pointer to the data in this blob for write.
Definition at line 107 of file blob_holder.hpp.
References _data.
Referenced by px::db::AddTrendBucketToBatch(), px::db::AddTrendStageToBatch(), px::db::CleanupAlarms(), px::db::compact_trend_bucket_channel_range(), px::db::DeleteAlarms(), px::db::DoesKeyExist(), px::db::ExportTrendBucket(), px::db::ExportTrendStage(), px::db::LevelupBucketTrendsRow(), px::db::LoadActiveAlarms(), px::db::NoteAlarmsToDelete(), px::db::QueryTrendStage(), and px::db::SeekTrendIterator().
void px::db::CBlobHolder::append (const void * ptr, size_t len)
Append data to the blob.
This call appends the specified data to the end of the blob's current value.
Parameters
ptr Pointer to the data to be appended
len Length (in bytes) of data to be appended
Definition at line 122 of file blob_holder.hpp.
References _data.
Referenced by px::db::AddClearOOBToBatch(), px::db::AddDeleteChannelToBatch(), px::db::AddDeleteDeviceToBatch(), px::db::allocate_ids(), px::db::CheckIDDB(), px::db::CleanupAlarms(), px::db::DeleteAlarms(), px::db::DeleteClosedAlarms(), px::db::DeleteTrends(), px::db::DeleteTrendsInternal(), px::db::FetchCCLEntry(), px::db::FetchMCLEntry(), px::db::GetSchemaVersion(), px::db::IsTrendStageDbTombstoned(), px::db::LevelupBucketTrendsForChannel(), px::db::MigrateAlarmDB(), px::db::query_alarm_index_db(), px::db::QueryAlarms(), px::db::reserve_ids(), px::db::SaveAlarmUpdates(), px::db::SetSchemaVersion(), and px::db::SetTrendStageDbTombstoned().
void px::db::CBlobHolder::reset ()
Clear/reset the blob's current value.
Definition at line 133 of file blob_holder.hpp.
References _data.
Referenced by px::db::AddTrendBucketToBatch(), px::db::AddTrendStageToBatch(), px::db::CheckIDDB(), px::db::CleanupAlarms(), px::db::compact_trend_bucket_channel_range(), px::db::DeleteAlarms(), px::db::DeleteClosedAlarms(), px::db::DeleteTrends(), px::db::DeleteTrendsInternal(), px::db::DoesKeyExist(), px::db::ExportTrendBucket(), px::db::ExportTrendStage(), px::db::LevelupBucketTrendsRow(), px::db::LoadActiveAlarms(), px::db::NoteAlarmsToDelete(), px::db::QueryTrendStage(), px::db::reserve_ids(), and px::db::SeekTrendIterator().
void px::db::CBlobHolder::reset (size_t size)
Resize and reset the blob's data.
Definition at line 141 of file blob_holder.hpp.
References _data, and size().
size_t px::db::CBlobHolder::size () const
Get the current size of the blob.
Returns
The number of bytes currently in the blob
Definition at line 167 of file blob_holder.hpp.
References _data.
Referenced by px::db::AddTrendBucketToBatch(), px::db::CKeyValueStore::compact(), px::db::DoesKeyExist(), and reset().
Member Data Documentation
std::vector<unsigned char> px::db::CBlobHolder::_data private
Internal buffer used to store the blob.
Definition at line 183 of file blob_holder.hpp.
Referenced by append(), px::db::CTestHelper::blob_raw_value(), CBlobHolder(), get(), get_mutable_ptr(), get_ptr(), operator=(), reset(), and size().
The documentation for this class was generated from the following file:
blob_holder.hpp