libpx: px::cds::CClient Class Reference
px::cds::CClient Class Reference
Singleton class to manage a connection to the CDS, from client side.
#include "px/cds/client.hpp"
Public Member Functions
~CClient ()
Default Destructor.
PUBLIC bool connect (bool wait=false, px::string source_name=px::string("unknown"), uint32_t request_queue_size=4194304, uint32_t response_queue_size=4194304)
Establish a connection to the CDS.
PUBLIC void disconnect ()
Disconnect from the CDS.
PUBLIC void disconnect_after_callback_fork ()
Disconnect from the CDS after a fork() from background thread.
PUBLIC CallbackHandle register_callback (std::shared_ptr< CCallback > callback)
Register a callback function to receive (and dequeue) responses.
PUBLIC void unregister_callback (CallbackHandle handle)
Unregister a previously registered callback structure.
PUBLIC void register_unsolicited_callback (std::shared_ptr< CCallback > callback)
Register the callback function to receive unsolicited messages from the CDS.
PUBLIC bool have_unsolicited_callback ()
Utility to test whether the callback for unsolicited (or subscribed) responses has been set.
PUBLIC void unregister_unsolicited_callback ()
Unregister the previously registered callback function for unsolicited messages from the CDS.
PUBLIC uint32_t submit (CRequestResponse &req, CallbackHandle callback=CALLBACK_NONE, bool sleep_on_full=false)
Submit a request for CDS processing.
PUBLIC std::shared_ptr
< CRequestResponse > submit_wait (CRequestResponse &req)
Submit a request for CDS processing, waiting for the response and returning it.
PUBLIC unsigned int response_queue_size () const
Get the current number of enqueued responses.
PUBLIC std::shared_ptr
< CRequestResponse > get_queued_response ()
Remove the oldest response from the response_queue and return it.
PUBLIC bool update_uid ()
Update the client's UID on the server by reading the process UID, GID, and PID, and sending via SCM_CREDENTIALS.
PUBLIC bool is_connected ()
Getter which tells if we are still connected to the CDS, or not.
PUBLIC void debug_send_raw_to_cds (const void *data, size_t length)
Debug function for stress testing.
Static Public Member Functions
static PUBLIC CClient * get ()
Static Factory function: constructs if necessary, returns existing instance of CClient otherwise.
static PUBLIC bool am_i_background_thread ()
Static function that checks whether "this" thread is the CDS Client background thread.
Private Member Functions
CClient ()
Default constructor, private so one must construct using get()
next_xid (1)
client_socket (-1)
connected (false)
bg_thread (nullptr)
bg_thread_stop_fd (-1)
bg_thread_id (0)
void bg_thread_func ()
int get_shm (uint32_t buffer_size)
Private Attributes
std::map< CallbackHandle,
std::shared_ptr< CCallback > > callbacks
std::shared_ptr< CCallback > unsol_cb
std::mutex callbacks_mutex
CallbackHandle next_handle
std::deque< std::shared_ptr
< CRequestResponse > > response_queue
std::mutex response_queue_mutex
toolkit::ipc::CIPCEventQueue * request_queue
std::mutex request_queue_mutex
toolkit::ipc::CIPCEventQueue * cds_response_queue
uint32_t request_queue_size
uint32_t cds_response_queue_size
struct pollfd request_pollfd [2]
uint32_t next_xid
int client_socket
bool connected
std::thread * bg_thread
int bg_thread_stop_fd
std::thread::id bg_thread_id
Detailed Description
Singleton class to manage a connection to the CDS, from client side.
Definition at line 92 of file client.hpp.
Constructor & Destructor Documentation
px::cds::CClient::~CClient ()
Default Destructor.
Performs a disconnect(), if connected to the CDS, and removes this global, per-application instance of the CDS Client.
Definition at line 1068 of file client.cpp.
References disconnect(), px::cds::g_cdsClient, and px::cds::g_cdsClient_mutex.
px::cds::CClient::CClient () private
Default constructor, private so one must construct using get()
Definition at line 325 of file client.hpp.
Member Function Documentation
CClient * px::cds::CClient::get () static
Static Factory function: constructs if necessary, returns existing instance of CClient otherwise.
Returns
Pointer to the CDS Client instance for this application. This is a pointer to the global, per-application instance of the CDS Client. Don't delete this pointer unless the program is exiting or for some reason will not use the CDS again.
Fast enough that you can use px::cds::CClient::get()->whatever() for all your calls instead of caching the value.
Definition at line 51 of file client.cpp.
References px::cds::g_cdsClient, px::cds::g_cdsClient_mutex, and unlikely.
Referenced by am_i_background_thread(), px::asio::CCdsConnection::CCdsConnection(), px::asio::CCdsSyncIO::cds_login(), px::asio::CCdsHandler::check_request_queue(), px::asio::CCdsSyncIO::clear_oob(), px::asio::CCdsSyncIO::clear_watchdog(), px::asio::CWatchdogTimer::close(), px::asio::CCdsHandler::closeout_device_map(), px::asio::CCdsHandler::connect_to_cds(), px::asio::CCdsSyncIO::create_channel(), px::asio::CCdsSyncIO::create_device(), px::asio::CCdsSyncIO::create_devices(), px::asio::CWatchdogTimer::CWatchdogTimer(), px::asio::CCdsSyncIO::delete_channel(), px::asio::CCdsSyncIO::delete_channels(), px::asio::CCdsSyncIO::delete_device(), px::asio::CCdsSyncIO::delete_devices(), px::asio::CCdsSyncIO::get_channel(), px::asio::CCdsSyncIO::get_channel_by_group(), px::asio::CCdsSyncIO::get_channel_settings(), px::asio::CCdsSyncIO::get_channels(), px::asio::CCdsSyncIO::get_channels_by_name(), px::asio::CCdsSyncIO::get_device_s(), px::asio::CCdsSyncIO::get_device_trend_row(), px::asio::CCdsSyncIO::get_devices(), px::asio::CCdsSyncIO::get_field(), px::asio::CCdsSyncIO::get_oob(), px::asio::CCdsSyncIO::get_oob_field(), px::asio::CCdsSyncIO::get_oob_tags(), px::asio::CCdsSyncIO::get_subscriber_ids(), px::asio::CCdsHandler::init_device_map(), px::asio::CCdsHandler::ping_watchdog(), px::asio::CCdsSyncIO::ping_watchdog_s(), px::asio::CCdsSyncIO::register_watchdog(), px::asio::CCdsSyncIO::set_channel_state(), px::asio::CCdsSyncIO::set_channel_value_s(), px::asio::CCdsSyncIO::set_channel_values(), px::asio::CCdsSyncIO::set_device_guid(), px::asio::CCdsSyncIO::set_device_state(), px::asio::CCdsSyncIO::set_field(), px::asio::CCdsSyncIO::set_oob_field(), px::asio::CCdsSyncIO::set_oob_s(), px::asio::CCdsSyncIO::set_oob_wait(), px::asio::CCdsHandler::submit(), px::asio::CCdsHandler::submit_forget(), px::asio::CCdsHandler::submit_wait(), px::asio::CCdsSyncIO::subscribe_by_id(), px::asio::CCdsHandler::subscribe_device_callbacks(), px::asio::CCdsSyncIO::subscribe_oob(), px::asio::CWatchdogTimer::timeout(), px::asio::CCdsSyncIO::unsubscribe_id(), px::asio::CCdsSyncIO::unsubscribe_oob(), px::cds::CCallback::~CCallback(), px::asio::CCdsHandler::~CCdsHandler(), and px::asio::CCdsSyncIO::~CCdsSyncIO().
bool px::cds::CClient::connect (bool wait = false, px::string source_name = px::string("unknown"), uint32_t request_queue_size = 4194304, uint32_t response_queue_size = 4194304)
Establish a connection to the CDS.
A successful connection will create a background thread for calling callbacks. If this process is already connected, does nothing and returns true.
Parameters
wait If true, then do not return until CDS is available (the connection attempt may still return false, though). If false, short waits may still occur if the CDS is available.
source_name Name associated with this connection, for logging purposes.
request_queue_size Memory allocation for buffer pending requests, in bytes. Must be at least 4096.
response_queue_size Memory allocation for queued responses, in bytes. Must be at least 4096.
Exceptions
May throw generic_err.
Returns
Returns true if the connection is successful, false otherwise (eg, if the CDS is not running). If false, no further efforts to use this Client should occur until the connection can be established.
Definition at line 65 of file client.cpp.
References bg_thread, bg_thread_func(), bg_thread_id, bg_thread_stop_fd, cds_response_queue, CDS_SOCKET_PATH, client_socket, connected, disconnect(), get_shm(), LIBPX_ERR, LIBPX_WARN, request_pollfd, request_queue, and update_uid().
Referenced by px::asio::CCdsConnection::CCdsConnection(), and px::asio::CCdsHandler::connect_to_cds().
void px::cds::CClient::disconnect ()
Disconnect from the CDS.
Unprocessed requests and responses are lost - use px::cds::CNotifyCompletion if you need to see if any requests are still unprocessed. Background thread is terminated (this may involve some waiting). All callbacks are unregistered.
Definition at line 382 of file client.cpp.
References bg_thread, bg_thread_id, bg_thread_stop_fd, callbacks, callbacks_mutex, cds_response_queue, client_socket, connected, request_queue, unregister_callback(), and unregister_unsolicited_callback().
Referenced by connect(), submit(), update_uid(), px::asio::CCdsHandler::~CCdsHandler(), px::asio::CCdsSyncIO::~CCdsSyncIO(), and ~CClient().
void px::cds::CClient::disconnect_after_callback_fork ()
Disconnect from the CDS after a fork() from background thread.
The background thread is the only one that will exist in the child. Call this and then call connect() to do further CDS operations after a fork() from a callback function.
Definition at line 319 of file client.cpp.
References bg_thread, bg_thread_id, bg_thread_stop_fd, callbacks, callbacks_mutex, cds_response_queue, client_socket, connected, request_queue, unregister_callback(), and unregister_unsolicited_callback().
CallbackHandle px::cds::CClient::register_callback (std::shared_ptr< CCallback > callback)
Register a callback function to receive (and dequeue) responses.
These will be responses to submit() requests. This function may be called more than once; this client class keeps a map of the registered callback(s) keyed by their callback handles.
If a callback is running, this will wait until it finishes.
If the callback structure already contains a handle (because this callback has been previously registered), that handle will be returned and no attempt will be made to re-register the callback. (So don't set the handle yourself.)
Parameters
callback The callback structure (derived from CCallback) containing the function to be invoked. Must not be null.
Returns
Returns the handle that identifies this callback instance. Returns CALLBACK_NONE if can't register the callback (eg, null pointer).
Definition at line 446 of file client.cpp.
References CALLBACK_FIRST_ISSUED, CALLBACK_NONE, callbacks, callbacks_mutex, next_handle, and unlikely.
Referenced by px::asio::CCdsConnection::CCdsConnection(), px::asio::CCdsHandler::init_device_map(), submit_wait(), and px::asio::CCdsHandler::subscribe_device_callbacks().
void px::cds::CClient::unregister_callback (CallbackHandle handle)
Unregister a previously registered callback structure.
If a callback is running, this will wait until it finishes.
Parameters
handle The handle that identifies this callback instance, which was returned by register_callback().
Definition at line 478 of file client.cpp.
References CALLBACK_NONE, callbacks, callbacks_mutex, and likely.
Referenced by px::asio::CCdsHandler::closeout_device_map(), disconnect(), disconnect_after_callback_fork(), submit_wait(), and px::cds::CCallback::~CCallback().
void px::cds::CClient::register_unsolicited_callback (std::shared_ptr< CCallback > callback)
Register the callback function to receive unsolicited messages from the CDS.
These will be subscription events or the unusual unexpected message from the CDS. There is only this one instance of the unsolicited callback handler per client connection, so this function should only be called once.
If a callback is running, this will wait until it finishes.
Note
If no callback has been registered, unsolicited responses will go onto the response_queue member of this Client.
There can only be one unsolicited callback per client; if you use the px::asio::CCdsConnection, it will register its handle_response() as its unsolicited callback function.
Parameters
callback The callback structure (derived from CCallback) containing the function to be invoked. Must not be null.
Definition at line 496 of file client.cpp.
References callbacks_mutex, and unsol_cb.
Referenced by px::asio::CCdsConnection::CCdsConnection(), and px::asio::CCdsHandler::subscribe_device_callbacks().
bool px::cds::CClient::have_unsolicited_callback ()
Utility to test whether the callback for unsolicited (or subscribed) responses has been set.
Returns
True if unsol_cb has been set, else False.
Definition at line 509 of file client.cpp.
References unsol_cb.
Referenced by px::asio::CCdsSyncIO::subscribe_oob().
void px::cds::CClient::unregister_unsolicited_callback ()
Unregister the previously registered callback function for unsolicited messages from the CDS.
If a callback is running, this will wait until it finishes.
Definition at line 521 of file client.cpp.
References callbacks_mutex, and unsol_cb.
Referenced by px::asio::CCdsConnection::CCdsConnection(), px::asio::CCdsHandler::closeout_device_map(), disconnect(), and disconnect_after_callback_fork().
uint32_t px::cds::CClient::submit (CRequestResponse & req, CallbackHandle callback = CALLBACK_NONE, bool sleep_on_full = false)
Submit a request for CDS processing.
Sets the transaction_id and callback_handle members. Safe to call from multiple threads.
Parameters
req The request structure, derived from CRequestResponse.
callback The handle of the callback structure to be invoked when done, derived from CCallback. If set to CALLBACK_NONE, the CDS will not send any response (and the returned transaction ID will always be 0). If set to CALLBACK_ENQUEUE, no callback will be made, and the response will be left on the response queue.
sleep_on_full If true and the request queue is full, will sleep until there is space. If false and the request queue is full, will discard the request.
Exceptions
px::no_connection if the connection has not been established or if it drops for some reason
px::too_much_data if the request is too large to ever be able to fit in the buffer
px::generic_err other causes
Returns
The transaction_id the CDS provides to identify the response to this request, or 0 if the request was discarded (could not be queued) or 0 if there is no callback provided.
Definition at line 530 of file client.cpp.
References px::cds::CRequestResponse::callback_handle, CALLBACK_NONE, connected, disconnect(), LIBPX_DEBUG, LIBPX_ERR, LIBPX_NOTICE, next_xid, px::cds::req_pack(), request_pollfd, request_queue, request_queue_mutex, px::cds::RESPONSE_TOO_BIG, px::cds::CRequestResponse::status, px::cds::CRequestResponse::transaction_id, unlikely, and px::generic_err::what().
Referenced by px::asio::CCdsHandler::check_request_queue(), px::asio::CCdsSyncIO::clear_oob(), px::asio::CWatchdogTimer::CWatchdogTimer(), px::asio::CCdsSyncIO::delete_devices(), px::cds::logout_session(), px::asio::CCdsHandler::ping_watchdog(), px::asio::CCdsSyncIO::ping_watchdog_s(), px::asio::CCdsSyncIO::register_watchdog(), px::asio::CCdsSyncIO::set_channel_state(), px::asio::CCdsSyncIO::set_channel_value_s(), px::asio::CCdsSyncIO::set_channel_values(), px::asio::CCdsSyncIO::set_device_guid(), px::asio::CCdsSyncIO::set_device_state(), px::asio::CCdsSyncIO::set_oob_s(), px::asio::CCdsHandler::submit_forget(), submit_wait(), and px::asio::CWatchdogTimer::timeout().
std::shared_ptr< CRequestResponse > px::cds::CClient::submit_wait (CRequestResponse & req)
Submit a request for CDS processing, waiting for the response and returning it.
Parameters
req The request structure, derived from CRequestResponse.
Exceptions
no_connection if the connection has not been established or if it drops for some reason
too_much_data if the request is too large to ever be able to fit in the buffer
generic_err other causes
Returns
The results of the CDS command, in a structure derived from CRequestResponse. Will return an empty shared_ptr if there is some error (that doesn't throw).
Note
Uses a wait on the callback background thread. If this is called from that background thread (e.g. from a CCallback) it will deadlock.
Definition at line 641 of file client.cpp.
References bg_thread_id, CALLBACK_NONE, LIBPX_DEBUG, LIBPX_ERR, LIBPX_WARN, px::cds::NOT_ABLE_TO_EXECUTE, register_callback(), submit(), px::cds::SUCCEEDED, px::cds::CRequestResponse::transaction_id, unlikely, unregister_callback(), and px::generic_err::what().
Referenced by px::asio::CCdsSyncIO::cds_login(), px::asio::CCdsSyncIO::clear_watchdog(), px::asio::CWatchdogTimer::close(), px::asio::CCdsSyncIO::create_channel(), px::asio::CCdsSyncIO::create_device(), px::asio::CCdsSyncIO::create_devices(), px::asio::CCdsSyncIO::delete_channel(), px::asio::CCdsSyncIO::delete_channels(), px::asio::CCdsSyncIO::delete_device(), px::asio::CCdsSyncIO::get_channel(), px::asio::CCdsSyncIO::get_channel_by_group(), px::asio::CCdsSyncIO::get_channel_settings(), px::asio::CCdsSyncIO::get_channels(), px::asio::CCdsSyncIO::get_channels_by_name(), px::asio::CCdsSyncIO::get_device_s(), px::asio::CCdsSyncIO::get_device_trend_row(), px::asio::CCdsSyncIO::get_devices(), px::asio::CCdsSyncIO::get_field(), px::asio::CCdsSyncIO::get_oob(), px::asio::CCdsSyncIO::get_oob_field(), px::asio::CCdsSyncIO::get_oob_tags(), px::asio::CCdsSyncIO::get_subscriber_ids(), px::asio::CCdsSyncIO::set_device_guid(), px::asio::CCdsSyncIO::set_field(), px::asio::CCdsSyncIO::set_oob_field(), px::asio::CCdsSyncIO::set_oob_wait(), px::asio::CCdsSyncIO::subscribe_by_id(), px::asio::CCdsSyncIO::subscribe_oob(), px::asio::CCdsSyncIO::unsubscribe_id(), and px::asio::CCdsSyncIO::unsubscribe_oob().
unsigned int px::cds::CClient::response_queue_size () const
Get the current number of enqueued responses.
There are two ways that responses are enqueued on the response_queue: 1) They are responses to requests submitted with callback handle CALLBACK_ENQUEUE 2) They are unsolicited responses (messages) when no unsolicited callback has been registered.
May be used to poll the queue (though it never sleeps) as the number of items in the queue never decreases unless you call get_queued_response().
Safe to call from multiple threads.
Returns
The current number of enqueued responses.
Definition at line 755 of file client.cpp.
References response_queue, and response_queue_mutex.
std::shared_ptr< CRequestResponse > px::cds::CClient::get_queued_response ()
Remove the oldest response from the response_queue and return it.
Returns
Pointer to a CDS response structure derived from CRequestResponse. If the queue is empty an empty shared_ptr is returned.
Safe to call from multiple threads.
Definition at line 765 of file client.cpp.
References LIBPX_WARN, response_queue, response_queue_mutex, and px::cds::SUCCEEDED.
bool px::cds::CClient::update_uid ()
Update the client's UID on the server by reading the process UID, GID, and PID, and sending via SCM_CREDENTIALS.
Definition at line 786 of file client.cpp.
References client_socket, and disconnect().
Referenced by connect().
bool px::cds::CClient::am_i_background_thread () static
Static function that checks whether "this" thread is the CDS Client background thread.
May seem like a silly question to ask, but it is actually hard to tell when inside a CdsHandler function that can be called by either the callbacks owned by the background thread or the application code.
Returns
True if "this" thread is the Client's background thread.
Definition at line 1087 of file client.cpp.
References bg_thread_id, and get().
Referenced by px::asio::CCdsHandler::set_oob(), and px::asio::CCdsHandler::submit_wait().
bool px::cds::CClient::is_connected ()
Getter which tells if we are still connected to the CDS, or not.
Returns
True if connected to the CDS.
Definition at line 422 of file client.hpp.
References connected.
void px::cds::CClient::debug_send_raw_to_cds (const void * data, size_t length)
Debug function for stress testing.
Sends the included string of bytes to the CDS, unfiltered.
Definition at line 1092 of file client.cpp.
References request_queue, and request_queue_mutex.
px::cds::CClient::next_xid (1) private
px::cds::CClient::client_socket (- 1) private
px::cds::CClient::connected (false) private
px::cds::CClient::bg_thread (nullptr) private
px::cds::CClient::bg_thread_stop_fd (- 1) private
px::cds::CClient::bg_thread_id (0) private
Definition at line 331 of file client.hpp.
void px::cds::CClient::bg_thread_func () private
Definition at line 838 of file client.cpp.
References _libpx_verb_array, _thr_local_syslog, bg_thread_stop_fd, CALLBACK_ENQUEUE, CALLBACK_NONE, callbacks, callbacks_mutex, cds_response_queue, LIBPX_DEBUG, LIBPX_ERR, LIBPX_INFO, LIBPX_LOG_CDS_THREAD, likely, px::cds::req_unpack(), response_queue, response_queue_mutex, px::CUtil::set_thread_name(), unlikely, and unsol_cb.
Referenced by connect().
int px::cds::CClient::get_shm (uint32_t buffer_size) private
Definition at line 1016 of file client.cpp.
Referenced by connect().
Member Data Documentation
std::map<CallbackHandle, std::shared_ptr<CCallback> > px::cds::CClient::callbacks private
Definition at line 369 of file client.hpp.
Referenced by bg_thread_func(), disconnect(), disconnect_after_callback_fork(), register_callback(), and unregister_callback().
std::shared_ptr<CCallback> px::cds::CClient::unsol_cb private
Definition at line 372 of file client.hpp.
Referenced by bg_thread_func(), have_unsolicited_callback(), register_unsolicited_callback(), and unregister_unsolicited_callback().
std::mutex px::cds::CClient::callbacks_mutex mutable private
Definition at line 375 of file client.hpp.
Referenced by bg_thread_func(), disconnect(), disconnect_after_callback_fork(), register_callback(), register_unsolicited_callback(), unregister_callback(), and unregister_unsolicited_callback().
CallbackHandle px::cds::CClient::next_handle private
Definition at line 378 of file client.hpp.
Referenced by register_callback().
std::deque<std::shared_ptr<CRequestResponse> > px::cds::CClient::response_queue private
Definition at line 381 of file client.hpp.
Referenced by bg_thread_func(), get_queued_response(), and response_queue_size().
std::mutex px::cds::CClient::response_queue_mutex mutable private
Definition at line 384 of file client.hpp.
Referenced by bg_thread_func(), get_queued_response(), and response_queue_size().
toolkit::ipc::CIPCEventQueue* px::cds::CClient::request_queue private
Definition at line 387 of file client.hpp.
Referenced by connect(), debug_send_raw_to_cds(), disconnect(), disconnect_after_callback_fork(), and submit().
std::mutex px::cds::CClient::request_queue_mutex mutable private
Definition at line 390 of file client.hpp.
Referenced by debug_send_raw_to_cds(), and submit().
toolkit::ipc::CIPCEventQueue* px::cds::CClient::cds_response_queue private
Definition at line 393 of file client.hpp.
Referenced by bg_thread_func(), connect(), disconnect(), and disconnect_after_callback_fork().
uint32_t px::cds::CClient::request_queue_size private
Definition at line 396 of file client.hpp.
uint32_t px::cds::CClient::cds_response_queue_size private
Definition at line 396 of file client.hpp.
struct pollfd px::cds::CClient::request_pollfd[2] private
Definition at line 401 of file client.hpp.
Referenced by connect(), and submit().
uint32_t px::cds::CClient::next_xid private
Definition at line 404 of file client.hpp.
Referenced by submit().
int px::cds::CClient::client_socket private
Definition at line 407 of file client.hpp.
Referenced by connect(), disconnect(), disconnect_after_callback_fork(), and update_uid().
bool px::cds::CClient::connected private
Definition at line 410 of file client.hpp.
Referenced by connect(), disconnect(), disconnect_after_callback_fork(), is_connected(), and submit().
std::thread* px::cds::CClient::bg_thread private
Definition at line 413 of file client.hpp.
Referenced by connect(), disconnect(), and disconnect_after_callback_fork().
int px::cds::CClient::bg_thread_stop_fd private
Definition at line 416 of file client.hpp.
Referenced by bg_thread_func(), connect(), disconnect(), and disconnect_after_callback_fork().
std::thread::id px::cds::CClient::bg_thread_id private
Definition at line 419 of file client.hpp.
Referenced by am_i_background_thread(), connect(), disconnect(), disconnect_after_callback_fork(), and submit_wait().
The documentation for this class was generated from the following files:
client.hpp
client.cpp