libpx: px::CUtil Class Reference
px::CUtil Class Reference
Encapsulating class for various utility functions.
#include <util.hpp>
Classes
struct no_such_user
Exception: specified user/UID not found.
Static Public Member Functions
static PUBLIC std::vector
< px::string > split_string (const px::string &src, char delimiter= ';')
Split a single string into multiple sub-strings.
static PUBLIC void daemonize ()
Daemonize this process.
static PUBLIC void set_gid (const px::string &user)
Set the group ID.
static PUBLIC void set_uid (const px::string &user)
Set the user ID.
static PUBLIC void set_egid (const px::string &user)
Set the effective group ID.
static PUBLIC void set_euid (const px::string &user)
Set the effective user ID.
static PUBLIC void drop_root_keep_bind (const px::string &user, const px::string &group="nobody")
Drop root privileges, but keep the ability to bind low-numbered ports (<1024).
static PUBLIC void set_file_owner (const px::string &path, const px::string &user)
Change a file's ownership to the specified user.
static PUBLIC void set_file_group (const px::string &path, const px::string &group)
Change a file's group ID to the specified group.
static PUBLIC void set_process_prio (int prio)
Set the process-wide priority level.
static PUBLIC void set_thread_prio (const px::CRealtimePriority &prio)
Set the real-time priority level.
static PUBLIC void alter_signal_mask (bool block)
Alter the signal mask for the calling thread for standard signals caught by libsyslog (SIGSEGV, SIGILL, SIGFPE).
static PUBLIC px::string read_file_to_string (const px::string &filename)
Read the entire contents of the named file into a string.
static PUBLIC void write_string_to_file (const px::string &filename, const px::string &str)
Write the given string to the named file.
static PUBLIC void append_string_to_file (const px::string &filename, const px::string &str)
Write the given string to the end of the named file.
static PUBLIC px::string tribool_to_string (boost::tribool const &b)
Convert a boost tribool to string.
static PUBLIC px::string create_uuid (const px::string &name)
This function creates a 128 bit UUID (RFC 4122) in string format from a unique string name (seed text).
static PUBLIC px::string create_random_uuid (bool dashes)
Creates a random (version 4) UUID.
static PUBLIC bool is_little_endian ()
Detect the big/little endian at run time.
static PUBLIC px::string get_user_name (uint32_t uid)
Return the user name for a given Linux user ID.
static PUBLIC px::string ChangePasswordStatus_str (enum px::proto::ChangePasswordStatus &status)
Converts password change status to string format.
static PUBLIC bool can_read_oob (const px::proto::toolkitStruct &oob, const px::CBitset< px::permissions > &perms)
Determine whether the current set of permissions is allowed to read an OOB object.
static PUBLIC bool can_write_oob (const px::proto::toolkitStruct &oob, const px::CBitset< px::permissions > &perms)
Determine whether the current set of permissions is allowed to write an OOB object.
static PUBLIC bool can_del_perm_oob (const px::proto::toolkitStruct &oob, const px::CBitset< px::permissions > &perms)
Determine whether the current set of permissions is allowed to delete an OOB object or change its permissions.
static PUBLIC void set_thread_name (const px::string &name)
Set a thread's name, visible in "ps".
static PUBLIC bool get_process_gids (int pid, std::unordered_set< int > &gids)
Get a process's group IDs.
static PUBLIC void drop_root_keep_net_admin (const px::string &user, const px::string &group="nobody")
Drop root privileges, but keep the linux capabilitiy CAP_NET_ADMIN to perform network related operations then switch to Linux user/group passed as function parameter.
Static Private Member Functions
static gid_t get_gid (const px::string &user)
Finds the user's group ID.
static uid_t get_uid (const px::string &user)
Finds the user's ID.
static bool initialize_is_little_endian ()
Static Private Attributes
static bool _is_little_endian = px::CUtil::initialize_is_little_endian()
Detailed Description
Encapsulating class for various utility functions.
This class encapsulates several functions that are mostly OS-level functionality.
Definition at line 25 of file util/util.hpp.
Member Function Documentation
std::vector< px::string > px::CUtil::split_string (const px::string & src, char delimiter = ';') static
Split a single string into multiple sub-strings.
Parameters
src The input string to be split
delimiter The delimiter character upon which to split the source string
Returns
A vector of sub-strings of the original
Definition at line 79 of file util.cpp.
Referenced by px::CChannelSettings::get_field_by_name(), px::CChannel::get_field_by_name(), px::CProtoOPS::GetFieldValue(), and px::CProtoOPS::SetFieldValue().
void px::CUtil::daemonize () static
Daemonize this process.
This call performs standard daemonization, which involves double- fork()ing the process, closing standard I/O file descriptors, etc. Upon return from this call, the process is a daemon.
Exceptions
generic_err A problem was encountered during the daemonization process (this should usually be fatal).
Definition at line 111 of file util.cpp.
void px::CUtil::set_gid (const px::string & user) static
Set the group ID.
This call sets the GID for the calling process.
Parameters
user The user name or GID in string form.
Exceptions
no_such_user The supplied user name could not be found, and conversion to a numeric GID failed.
generic_err The specified group ID could not be set.
Definition at line 260 of file util.cpp.
Referenced by drop_root_keep_bind(), and drop_root_keep_net_admin().
void px::CUtil::set_uid (const px::string & user) static
Set the user ID.
This call sets the UID for the calling process.
Parameters
user The user name or UID in string form.
Exceptions
no_such_user The supplied user name could not be found, and conversion to a numeric UID failed.
generic_err The specified user ID could not be set.
Definition at line 399 of file util.cpp.
References coverage_compensate().
Referenced by drop_root_keep_bind(), and drop_root_keep_net_admin().
void px::CUtil::set_egid (const px::string & user) static
Set the effective group ID.
This call sets the effective GID (not the real GID) for the calling process.
Parameters
user The user name or GID in string form.
Exceptions
no_such_user The supplied user name could not be found, and conversion to a numeric GID failed.
generic_err The specified group ID could not be set.
Definition at line 414 of file util.cpp.
void px::CUtil::set_euid (const px::string & user) static
Set the effective user ID.
This call sets the effective UID (not the real UID) for the calling process.
Parameters
user The user name or UID in string form.
Exceptions
no_such_user The supplied user name could not be found, and conversion to a numeric UID failed.
generic_err The specified user ID could not be set.
Definition at line 427 of file util.cpp.
References coverage_compensate().
void px::CUtil::drop_root_keep_bind (const px::string & user, const px::string & group = "nobody") static
Drop root privileges, but keep the ability to bind low-numbered ports (<1024).
Parameters
user User name or ID number to switch identity to.
group Group name or ID number to switch identity to.
Exceptions
no_such_user The supplied user or group name could not be found, and conversion to a numeric UID/GID failed.
generic_err The specified user/group ID could not be set.
Definition at line 621 of file util.cpp.
References set_gid(), and set_uid().
void px::CUtil::set_file_owner (const px::string & path, const px::string & user) static
Change a file's ownership to the specified user.
Parameters
path Path to the file.
user User name or ID number to change the file owner to.
Exceptions
no_such_user The supplied user name could not be found, and conversion to a numeric UID failed.
generic_err The specified user ID could not be set.
Definition at line 442 of file util.cpp.
void px::CUtil::set_file_group (const px::string & path, const px::string & group) static
Change a file's group ID to the specified group.
Parameters
path Path to the file.
group name or ID number to change the file owner to.
Exceptions
no_such_user The supplied group name could not be found, and conversion to a numeric GID failed.
generic_err The specified group ID could not be set.
Definition at line 455 of file util.cpp.
void px::CUtil::set_process_prio (int prio) static
Set the process-wide priority level.
This call sets the process-wide, traditional UNIX scheduling priority level to the given value. See setpriority(2).
Parameters
prio The process-wide priority level
Definition at line 486 of file util.cpp.
void px::CUtil::set_thread_prio (const px::CRealtimePriority & prio) static
Set the real-time priority level.
This call sets the scheduling priority level for the calling thread, using real-time priority. See sched_setscheduler(2).
Parameters
prio The priority level to set for this thread
Definition at line 498 of file util.cpp.
References px::CRealtimePriority::_nice, px::CRealtimePriority::_policy, and px::CRealtimePriority::_priority.
void px::CUtil::alter_signal_mask (bool block) static
Alter the signal mask for the calling thread for standard signals caught by libsyslog (SIGSEGV, SIGILL, SIGFPE).
Parameters
block True if the signals should be blocked, false if they should be unblocked
Definition at line 523 of file util.cpp.
px::string px::CUtil::read_file_to_string (const px::string & filename) static
Read the entire contents of the named file into a string.
Parameters
filename The filename (including folder path) to be read. If file name is "-" standard input is read.
Returns
Returns the contents as one string. Line endings are included, unchanged.
Throws bad_alloc if out of memory (true?) Throws generic_err on any other file access error (including file not found).
Definition at line 538 of file util.cpp.
void px::CUtil::write_string_to_file (const px::string & filename, const px::string & str) static
Write the given string to the named file.
Will create the file if it doesn't exist, else overwrite any existing contents.
Parameters
filename The filename (including folder path) to be read.
str The contents to be written.
Throws generic_err on any file access error when opening the file for writing.
Definition at line 567 of file util.cpp.
void px::CUtil::append_string_to_file (const px::string & filename, const px::string & str) static
Write the given string to the end of the named file.
Will create the file if it doesn't exist, else append it to the existing contents.
Parameters
filename The filename (including folder path) to be read.
str The contents to be written.
Throws generic_err on any file access error when opening the file for writing.
Definition at line 594 of file util.cpp.
static PUBLIC px::string px::CUtil::tribool_to_string (boost::tribool const & b) static
Convert a boost tribool to string.
Parameters
b The tribool to be converted to string.
Returns
The converted string of tribool.
Definition at line 257 of file util/util.hpp.
px::string px::CUtil::create_uuid (const px::string & name) static
This function creates a 128 bit UUID (RFC 4122) in string format from a unique string name (seed text).
NOTE: This function will return valid results only if the Toolkit is compiled with OpenSSL support enabled.
Parameters
name Unique string name to be used as the "seed" for generating the UUID.
Returns
The 16 byte (128 bits) UUID converted to string format (32 characters). If the "name" is empty, then returns an empty string.
Definition at line 721 of file util.cpp.
References _uuid_t::clock_seq_hi_and_reserved, _uuid_t::clock_seq_low, _uuid_t::node, _uuid_t::time_hi_and_version, _uuid_t::time_low, _uuid_t::time_mid, uuid_create_sha1_from_name(), and UUID_MIN_ALLOC.
Referenced by px::asio::CCdsSyncIO::set_device_guid().
px::string px::CUtil::create_random_uuid (bool dashes) static
Creates a random (version 4) UUID.
Parameters
dashes Include dashes if true, don't if false
Returns
UUID as a string of ASCII hex digits and possibly dashes
Definition at line 887 of file util.cpp.
References px::bytes_2_hex(), and rand_gen().
static PUBLIC bool px::CUtil::is_little_endian () static
Detect the big/little endian at run time.
Definition at line 286 of file util/util.hpp.
References _is_little_endian.
px::string px::CUtil::get_user_name (uint32_t uid) static
Return the user name for a given Linux user ID.
Returns string "Linux-UID-N" if not found.
Definition at line 749 of file util.cpp.
px::string px::CUtil::ChangePasswordStatus_str (enum px::proto::ChangePasswordStatus & status) static
Converts password change status to string format.
Parameters
status - Password change status
Returns
Status in string format
Definition at line 766 of file util.cpp.
References px::cds::PERMISSION_DENIED.
bool px::CUtil::can_read_oob (const px::proto::toolkitStruct & oob, const px::CBitset< px::permissions > & perms) static
Determine whether the current set of permissions is allowed to read an OOB object.
Parameters
oob The OOB object
perms The permissions being checked
Returns
True if "perms" contains permission that can read the OOB or if anyone can read it, false otherwise.
Definition at line 800 of file util.cpp.
References px::config_read, px::CBitset< T >::get(), and px::unknown.
bool px::CUtil::can_write_oob (const px::proto::toolkitStruct & oob, const px::CBitset< px::permissions > & perms) static
Determine whether the current set of permissions is allowed to write an OOB object.
Parameters
oob The OOB object
perms The permissions being checked
Returns
True if "perms" contains permission that can write the OOB, false otherwise.
Definition at line 830 of file util.cpp.
References px::config_write, px::CBitset< T >::get(), and px::unknown.
bool px::CUtil::can_del_perm_oob (const px::proto::toolkitStruct & oob, const px::CBitset< px::permissions > & perms) static
Determine whether the current set of permissions is allowed to delete an OOB object or change its permissions.
Parameters
oob The OOB object
perms The permissions being checked
Returns
True if "perms" contains permission that can change the OOB's permissions or delete it, false otherwise.
Definition at line 856 of file util.cpp.
References px::config_write, px::CBitset< T >::get(), and px::unknown.
void px::CUtil::set_thread_name (const px::string & name) static
Set a thread's name, visible in "ps".
Parameters
name Name to be set for this thread. May get truncated if too long for the implementation.
Definition at line 882 of file util.cpp.
Referenced by px::cds::CClient::bg_thread_func(), and CScheduler::start_thread().
bool px::CUtil::get_process_gids (int pid, std::unordered_set< int > & gids) static
Get a process's group IDs.
Parameters
pid Process ID of a running process
gids Unordered set of ints to be filled with GIDs
Returns
True if successful, false if error
Definition at line 925 of file util.cpp.
References LIBPX_DEBUG, px::string, and unlikely.
Referenced by px::cds::CServer::update_uid().
void px::CUtil::drop_root_keep_net_admin (const px::string & user, const px::string & group = "nobody") static
Drop root privileges, but keep the linux capabilitiy CAP_NET_ADMIN to perform network related operations then switch to Linux user/group passed as function parameter.
Parameters
user User name
group Group name
Definition at line 1009 of file util.cpp.
References set_gid(), and set_uid().
gid_t px::CUtil::get_gid (const px::string & user) static private
Finds the user's group ID.
Parameters
user - User Name
Returns
User group ID. Exception will be thrown if user not found
Definition at line 184 of file util.cpp.
uid_t px::CUtil::get_uid (const px::string & user) static private
Finds the user's ID.
Parameters
user - User Name
Returns
User ID. Exception will be thrown if user not found
Definition at line 212 of file util.cpp.
static bool px::CUtil::initialize_is_little_endian () static private
Definition at line 388 of file util/util.hpp.
Member Data Documentation
bool px::CUtil::_is_little_endian = px::CUtil::initialize_is_little_endian() static private
Definition at line 387 of file util/util.hpp.
Referenced by is_little_endian().
The documentation for this class was generated from the following files:
util/util.hpp
util.cpp