libpx: px::db::CIteratorOwner Class Reference
px::db::CIteratorOwner Class Reference
Per-database iterator "owner" class.
#include <iterator_owner.hpp>
Static Public Member Functions
static std::shared_ptr
< CIteratorOwner > create ()
Factory function to create a new iterator owner object.
Private Member Functions
CIteratorOwner ()
Constructor.
Detailed Description
Per-database iterator "owner" class.
This stub class provides no functionality, but it's very useful to have a common "owner" for iterator objects. That way we can use the semantics of weak_ptr to track the validity of outstanding iterators into a database, ensuring that they're not abused in calling code.
Definition at line 17 of file iterator_owner.hpp.
Constructor & Destructor Documentation
px::db::CIteratorOwner::CIteratorOwner () private
Constructor.
Definition at line 44 of file iterator_owner.hpp.
Member Function Documentation
static std::shared_ptr<CIteratorOwner> px::db::CIteratorOwner::create () static
Factory function to create a new iterator owner object.
Returns
A shared pointer to a new iterator owner
Definition at line 29 of file iterator_owner.hpp.
Referenced by px::db::CKeyValueStore::CKeyValueStore(), px::db::CSSTable::CSSTable(), and px::db::CKeyValueStore::renew_owner().
The documentation for this class was generated from the following file:
iterator_owner.hpp