libpx: px Namespace Reference
px Namespace Reference
Utility functions for handling permission values and sets thereof.
Namespaces
cds
px::cds is the namespace for all the classes that provide the object types and client and server functions for Power Xpert Toolkit applications to communicate with its Core Data Store (cds).
asio
proto
px::proto is the namespace for the C++ classes, generated from the Mercury Protobuf headers, that manage the data objects and request/response functions used mainly by the Mercury Server.
db
px::db is the namespace for all the classes that provide the database access for Power Xpert Toolkit applications.
dep
px::dep is the namespace for the classes that provide dependency graph support for Power Xpert Toolkit 2.0 applications.
permission
eq
px::eq is the namespace for the classes that provide equation parsing and evaluation support for Power Xpert Toolkit applications.
serialize
px::serialize is the namespace for the classes that provide serialization/deserialization support for Power Xpert Toolkit applications.
sub
px::sub is the namespace for the classes that provide CDS subscription support for Power Xpert Toolkit applications.
val_impl
conv
image_util
Classes
class CAlarmTrigger
Represents a single alarm trigger condition.
class CAlarmUpdate
Represents a single alarm update, as used in the Mercury protocol.
class CChannel
Channel as referred to by the CDS.
class CChannelSelector
Encapsulates the data of a Mercury ChannelSelector, to represent a list of channels.
class CChannelSettings
Encapsulates a channel's configuration, as seen in the Mercury message "Channel".
class CChannelTrend
Represents trend data from one interval for one channel.
class CChannelTrends
Represents a list of interval trend values from a channel.
class CDevice
Represents a device, which can be either a publisher, a device connected to the publisher, or a network connector such as INCOM port 1.
class CDeviceCommand
Contains a command/control's both meta and instance information.
class CMultistateMap
Maps variadically-typed keys into string label values.
class CParameterInfo
Contains a command/control parameter's meta information, and/or parameter values while a command is being executed.
class CTrendAccumulator
Represents an accumulator of values for one channel's data.
class CTrendBucketUpdate
Represents a bucket of trends to be stored in the trend bucket db.
class CTrendStageUpdate
Represents an interval update to be stored in the trend stage.
class CUser
Class combining what we need to know about an authenticable user.
class CUserPolicy
Represents global or per-user password-management policy, such as expiration and complexity requirements.
class CValidationData
Class to contain the parameters required for subscription to the data validation library These parameters will be passed to add or remove subscrption to create the validation hook object.
class CValueAccumulator
Represents a light weight accumulator to calculate min, min_time, max, max_time, avg, and last values for CValue.
class CAlarmTriggerType
Alarm trigger types.
class CDataType
This class enumerates all of the data types available for varidic data within the Toolkit (and exposed via Mercury).
class CDeviceRole
Device role.
class COverrideLevel
Levels of overrides for MCL entries.
struct generic_err
Exception class used to indicate a generic error.
struct too_much_data
Thrown when an operation fails due to an excess of data (context-specific).
struct no_connection
Thrown when we try to "send" something on a broken connection.
struct db_corrupt
Throw when database corruption is detected.
struct try_again
There are also a few corner cases in which we'd like to break out of an execution path and restart it, but not due to an "error" per-se.
class COob
COob class.
class CProtoOPS
CProtoOPS class.
class CBitset
Stores a bit-field of flags defined by an enumerated type.
struct invalid_t
Invalid value.
class CMonoTime
Monotonic time.
class CTimestamp
Wrapper around a "timespec" structure that provides additional useful functionality.
class CValue
Variadic value.
class CWallTime
Wall-clock time.
class CBase64Converter
Base64 conversion routine.
class CFileWatcher
File watcher/notification class.
struct minimal_signed_int
Utility class to find the smallest signed integer type that will hold up to a given value.
struct minimal_unsigned_int
Utility class to find the smallest unsigned integer type that will hold up to a given value.
class COption
This class represents an individual command-line option: the strings (flag, usage, description text, etc.) associated with it, as well as the actions to take to handle it (initialization, parsing, verification).
class COptionsBase
Configuration options base class.
class CRandom
Thin wrapper for Boost.Random.
class CRealtimePriority
Real-time scheduling policy class.
class CRecursiveFind
Find file and directories routine.
class CUtil
Encapsulating class for various utility functions.
Typedefs
typedef enum px::proto::ApiId mercury_msg_api_t
Defines the set of enums for the CMercuryHeader::_message_api field.
typedef uint64_t id_t
Unique identifier.
typedef string shared_string
Currently we use ordinary strings for shared_strings as flyweight wrappers had subtle bugs.
typedef ::__gnu_cxx::__vstring string
We're currently utilizing GCC's "versatile string" class.
Enumerations
enum channel_flag : uint8_t {
channel_flag::interval = 0, channel_flag::is_custom, channel_flag::accumulated, channel_flag::is_hidden,
channel_flag::trending_enabled, channel_flag::has_actual, channel_flag::has_min, channel_flag::has_max,
channel_flag::has_avg, channel_flag::is_writable, channel_flag::persist_value, channel_flag::size
}
Flags to govern channel behavior.
enum device_control : uint8_t { device_control::enable_controls = 0, device_control::enable_trending, device_control::enable_waveforms, device_control::size }
This is the enumerated list of standard device controls associated with a given device in the Toolkit.
enum realtime_state : uint8_t {
realtime_state::disabled = 0, realtime_state::disarmed, realtime_state::not_communicating, realtime_state::pass_through,
realtime_state::waveform_available, realtime_state::size
}
This is the enumerated list of standard states associated with a given channel or device in the Toolkit, as used in Mercury.
enum trend_trait : uint8_t {
trend_trait::avg = 0, trend_trait::min, trend_trait::max, trend_trait::actual,
trend_trait::size
}
Trend "traits", the values that may be stored on intervals in the CDS trend storage for a channel.
enum alarm_trigger_type : uint8_t {
alarm_trigger_type::upper_bound = 1, alarm_trigger_type::lower_bound = 2, alarm_trigger_type::on_value = 3, alarm_trigger_type::in_between = 4,
alarm_trigger_type::change_of_value = 5, alarm_trigger_type::invalid = 255
}
Alarm trigger types.
enum datatype : uint8_t {
datatype::boolean = 0, datatype::int32, datatype::int64, datatype::uint32,
datatype::uint64, datatype::float32, datatype::float64, datatype::timestamp,
datatype::string, datatype::binary, datatype::invalid = 255
}
This is the standard list of data types available in the Toolkit and exposed via Mercury.
enum device_command_status : uint8_t {
device_command_status::unknown = 0, device_command_status::succeeded = 1, device_command_status::failed = 2, device_command_status::in_progress = 3,
device_command_status::scheduled = 4
}
Device command's execution status From Enum.proto enum CommandStatus {}.
enum device_command_substatus : uint8_t {
device_command_substatus::none = 0, device_command_substatus::acked = 1, device_command_substatus::nacked = 2, device_command_substatus::busy = 3,
device_command_substatus::unexpected = 4
}
Device command's execution sub-status From Enum.proto enum CommandSubstatus {}.
enum device_role : uint8_t {
device_role::device = 0, device_role::publisher, device_role::port, device_role::subdevice,
device_role::invalid = 255
}
Device "role" enumeration.
enum mercury_msg_format_t {
HG_MSG_KEEPALIVE = 0, HG_MSG_PROTOBUF = 1, HG_MSG_BLOB = 2, HG_MSG_JSON_UTF8 = 3,
HG_MSG_JSON_ASCII = 4, HG_MSG_XML_UTF8 = 5, HG_MSG_XML_ASCII = 6, HG_MSG_NOT_SUPPORT = 7
}
Defines the set of enums for the CMercuryHeader::_message_type field.
enum override_level : uint8_t {
override_level::global = 0, override_level::family = 16, override_level::modelseries = 64, override_level::instance = 254,
override_level::invalid = 255
}
Level at which to apply an MCL channel-definition override.
enum permissions : uint8_t {
permissions::unknown = 0, permissions::data_read, permissions::data_write, permissions::data_admin,
permissions::config_read, permissions::config_write, permissions::config_file, permissions::internal_app,
permissions::install, permissions::troubleshoot, permissions::control_basic, permissions::control_oper,
permissions::setpoints, permissions::event_ack, permissions::security_admin, permissions::security_read,
permissions::per_user, permissions::size
}
permission enumeration
Functions
template<class Target , class Source >
Target poly_cast (Source *x)
Polymorphic casting: this utilizes dynamic_cast<> for non-release builds, thus ensuring that the cast is safe, but for release builds it becomes a more efficient static_cast<>.
template<class Target , class Source >
Target poly_cast (Source &x)
template<class Target , class Source >
std::shared_ptr< Target > poly_cast (const std::shared_ptr< Source > &x)
template<intmax_t MaxVal>
static ssize_t reverse_lookup_idx (size_t val)
This is useful for any of the classes which utilize a gperf-generated lookup table.
template<intmax_t MaxVal>
static const char * reverse_lookup (size_t val)
Find the string key associated with the given integer/enum value.
template<class T >
static size_t hash_value (const T &x)
Used by boost::hash.
PUBLIC px::string create_hmac (const px::string &key, const px::string &msg, size_t max_size)
This function creates a hmac-sha-1 hash in string format from a seed key string and message string.
PUBLIC std::vector< unsigned char > create_sha1 (const px::string &key, size_t max_size)
generate sha1 hash from key
template<>
px::string CValue::as< px::string > () const
Specialization for string type.
PUBLIC px::string PXtype2Protobuf (const px::datatype value_type)
Convert a CDS px::datatype to a Mercury value_type See Core.proto for list of Mercury value_type in string format.
PUBLIC px::datatype Protobuf2PXtype (const px::string value_type)
Convert a Mercury value_type to CDS px::datatype See Core.proto for list of Mercury value_type in string format.
PUBLIC px::string realtime_state_to_str (px::realtime_state flag, bool value)
Convert any realtime state enum to string.
PUBLIC px::string device_diff_to_str (const px::CDevice &cur_dev, const px::CDevice &new_dev)
This function will provide changes in device setting in string format.
template<typename T , typename std::enable_if<(sizeof(T)==1), int >::type = 0>
static T to_big_endian (T val)
No conversion necessary if we're only 1 byte.
template<typename T , typename std::enable_if< std::is_integral< T >::value||std::is_enum< T >::value, int >::type = 0, typename std::enable_if<(sizeof(T)==sizeof(uint16_t)), int >::type = 0>
static T to_big_endian (T val)
Integral 2-byte conversion.
template<typename T , typename std::enable_if<(sizeof(T)==1), int >::type = 0>
static T from_big_endian (T val)
No conversion necessary if we're only 1 byte.
template<typename T , typename std::enable_if< std::is_integral< T >::value||std::is_enum< T >::value, int >::type = 0, typename std::enable_if<(sizeof(T)==sizeof(uint16_t)), int >::type = 0>
static T from_big_endian (T val)
Integral 2-byte conversion.
static void float_to_big_endian (unsigned char *buf, int offset, float val)
Writes a 4-byte floating-point to a big-endian buffer with a start offset.
static float float_from_big_endian (const unsigned char *buf, int offset)
Reads a 4-byte floating-point from a big-endian buffer with a start offset.
static void double_to_big_endian (unsigned char *buf, int offset, double val)
Writes an 8-byte floating-point to a big-endian buffer with a start offset.
static double double_from_big_endian (const unsigned char *buf, int offset)
Reads an 8-byte floating-point from a big-endian buffer with a start offset.
PUBLIC px::string JSON2Protobuf (const px::string &json, std::vector< std::shared_ptr< google::protobuf::Message > > &msgs)
Conversion routines between protobuf objects and JSON strings.
PUBLIC px::string Protobuf2JSON (std::vector< std::shared_ptr< google::protobuf::Message > > &msgs, bool pretty_print=false)
Convert an array of protobuf objects into a string containing JSON formatted as above.
PUBLIC px::string QualifiedJSON2Protobuf (const px::string &json, const px::string &protobuf_type, std::vector< std::shared_ptr< google::protobuf::Message > > &msgs)
Conversion to/from a given message type.
PUBLIC px::string Protobuf2QualifiedJSON (px::string &protobuf_type, std::vector< std::shared_ptr< google::protobuf::Message > > &msgs, bool list=true, bool noextraspaces=false, bool numeric_enums=false)
Convert an array of protobuf objects - all of the same "Qualified" type - into an "unadorned" string containing JSON formatted as above.
PUBLIC bool ssl_host_check (const px::string &hostname, X509 *cert)
Check that an X.509 certificate is appropriate for a given hostname.
PUBLIC std::vector< unsigned char > hex_2_bytes (const px::string &str, bool ignore_nonhex=false)
Convert ASCII hex digits to vector of bytes.
PUBLIC px::string bytes_2_hex (const unsigned char *data, size_t size, bool uppercase=false)
Convert bytes into a string of ASCII hex digits.
PUBLIC std::vector< unsigned char > vec_bytes_2_hex (const std::vector< unsigned char > &data, bool uppercase=false)
Convert vector of bytes into a vector of of ASCII hex digits.
PUBLIC px::string bytes_2_guid (const unsigned char *data, size_t size, bool no_dashes=false)
Convert bytes into a string of ASCII hex digits in GUID format, eg 01234567-89ab-cdef-0123-456789abcdef.
PUBLIC std::vector< unsigned char > guid_2_bytes (const px::string &guid_text)
Convert a GUID's 32 or 36 ASCII hex digits to vector of 32 bytes.
PUBLIC void pxstr_tolower (px::string &str)
Convert, in place, any uppercase characters in 'str' to lowercase.
PUBLIC bool pxstr_to_printable (px::string &str, char subst_char=0)
Check for any unprintable characters in the string, and either remove or substitute for them.
PUBLIC std::string add_esc_char (const char *str)
Check for double quotes in the string and add escape characters if present.
PUBLIC uint32_t pxstr_first_utf8_codepoint (const unsigned char *&str, size_t &rem)
Given a pointer to bytes of UTF-8, return the codepoint of the first character, and a pointer to the next character.
PUBLIC std::vector< px::string > tokenize (const px::string &line)
Split an ASCII string into whitespace-separated tokens.
PUBLIC void safe_line_split (std::vector< std::string > &token_list, const std::string &text_line, const char *separators)
Function to encapuslate boost::split(), including try-catch for boost errors.
PUBLIC bool remove_trailing_slash (std::string &str)
Remove trailing slash from a string (if present) Will not work if the string is "/".
PUBLIC bool remove_trailing_slash (px::string &str)
Remove trailing slash from a string (if present) Will not work if the string is "/".
Detailed Description
Utility functions for handling permission values and sets thereof.
The overarching namespace for libpx.
Shortcut for toolkit config namespace.
All of the exported functionality for libpx is found under this px:: namespace.
This namespace is further divided by namespaces into the functional areas.
Many of the core toolkit objects, data types, and enums are defined at this namespace level because they are used across this library's functional areas.
Typedef Documentation
typedef enum px::proto::ApiId px::mercury_msg_api_t
Defines the set of enums for the CMercuryHeader::_message_api field.
Defined in Enum.proto under "enum ApiId"; this duplicates the Enums in proto/Enum.hpp Also used in the Mercury header (v3).
The entries roughly correspond to the message types in px::proto::Msg, eg px::proto::Request::kGetDevicesFieldNumber or .px.proto.GetDevicesRequest get_devices = 101 but the enum values here cannot be made to match those due to differences in the numbering of request vs response messages, and the addition of the published data "responses" here.
Definition at line 37 of file mercury_msg_enums.hpp.
typedef uint64_t px::id_t
Unique identifier.
There are numerous places in the Toolkit where we need a unique identifying number. This typedef defines the type of that identifying number, making it easy to alter the type in the future if needed (e.g. if we find that we don't actually need a full 64-bit key space, and it impacts performance).
Definition at line 23 of file id.hpp.
typedef string px::shared_string
Currently we use ordinary strings for shared_strings as flyweight wrappers had subtle bugs.
At many places in Toolkit code, strings are useful for flexibility, but many copies of the same string might exist simultaneously. We use a flyweight wrapper in these cases to save memory.
Note that using a flyweight still requires us to construct a string object, so it doesn't save any time. But it does save space, so it's a good idea to use this anywhere where you're storing non-transient copies of strings, and those strings are likely to be duplicated in multiple places.
hashed_factory: Whether this or set_factory is better depends on the particular workload, but hashed is more scalable.
simple_locking: It's unknown whether these strings will be accessed from multiple threads at once, since that's a per-application decision. Therefore to be safe, we use synchronization by default.
refcounted: When all references to a flyweight string disappear, we'd like to free up the memory associated with it. To do that, we use reference counting to detect when each string is no longer necessary.
Definition at line 40 of file shared_string.hpp.
typedef ::__gnu_cxx::__vstring px::string
We're currently utilizing GCC's "versatile string" class.
Definition at line 28 of file type/string.hpp.
Enumeration Type Documentation
enum px::channel_flag : uint8_t strong
Flags to govern channel behavior.
Enumerator
interval
Value is measured on intervals. Ignored by CDS.
is_custom
Channel does not have an entry in the Master Channel List.
accumulated
Channel measures an accumulated value (we expect it to always increase, until reset).
Ignored by CDS.
is_hidden
Channel should not be shown in the UI. Ignored by CDS.
trending_enabled
Save the channel's value on 5-minute intervals (00:00:00 - 00:05:00, etc.)
has_actual
If trending_enabled true, include the value of the channel as of the end of the interval (e.g.
just before 00:05:00)
has_min
If trending_enabled true, include the minimum value over the interval.
has_max
If trending_enabled true, include the maximum value over the interval.
has_avg
If trending_enabled true, include the average value over the interval.
is_writable
Channel's value may be updated by human users.
persist_value
Value will be saved across reboots.
Only should be enabled for "configuration"-style channels that update rarely.
size
Definition at line 12 of file channel_flag.hpp.
enum px::device_control : uint8_t strong
This is the enumerated list of standard device controls associated with a given device in the Toolkit.
Enumerator
enable_controls
enable_trending
enable_waveforms
size
Definition at line 12 of file device_flags.hpp.
enum px::realtime_state : uint8_t strong
This is the enumerated list of standard states associated with a given channel or device in the Toolkit, as used in Mercury.
Enumerator
disabled
disarmed
not_communicating
pass_through
waveform_available
size
Definition at line 12 of file realtime_state.hpp.
enum px::trend_trait : uint8_t strong
Trend "traits", the values that may be stored on intervals in the CDS trend storage for a channel.
These make their way into px::CChannelSettings via the CBitset flags of type px::channel_flag
Enumerator
avg
Average value over the interval.
min
Minimum value over the interval.
max
Maximum value over the interval.
actual
Channel's value at the end of the interval.
size
Definition at line 16 of file trend_trait.hpp.
enum px::alarm_trigger_type : uint8_t strong
Alarm trigger types.
Enumerator
upper_bound
Alarm when channel value is >= the threshold.
lower_bound
Alarm when channel value is <= the threshold.
on_value
Alarm when channel value is exactly equal to the threshold.
in_between
Alarm when channel value is <= the threshold AND >= threshold2.
change_of_value
Alarm when current_channel_value != previous_channel_value.
invalid
Definition at line 10 of file alarm_trigger_type_enums.hpp.
enum px::datatype : uint8_t strong
This is the standard list of data types available in the Toolkit and exposed via Mercury.
A px::CValue can be any of these types.
Enumerator
boolean
True or false?
int32
Signed 32-bit integer.
int64
Signed 64-bit integer.
uint32
Unsigned 32-bit integer.
uint64
Unsigned 32-bit integer.
float32
IEEE754 single-precision floating point value.
float64
IEEE754 double-precision floating point value.
timestamp
Time.
string
UTF-8 character string.
binary
Arbitrary bytes.
invalid
This is used both to indicate invalidity, and to track the end of the list of enumerations.
Definition at line 14 of file datatype_enums.hpp.
enum px::device_command_status : uint8_t strong
Device command's execution status From Enum.proto enum CommandStatus {}.
Enumerator
unknown
succeeded
Indicates that the command has succeeded.
failed
Indicates that the command has failed.
in_progress
The handler must set the command status to in progress as soon as it starts to execute it.
scheduled
Indicates that the command is scheduled in the queue, but haven't been picked up by any handler yet.
Definition at line 11 of file device_command_status_enums.hpp.
enum px::device_command_substatus : uint8_t strong
Device command's execution sub-status From Enum.proto enum CommandSubstatus {}.
Enumerator
none
acked
acked by the device. this is usually a succeeded case.
nacked
unacked by the device. this is usually a failed case.
busy
failed to execution because the device is too busy, indicating that the caller should retry it.
unexpected
The command was executed, but returned with the unexpected result.
Definition at line 11 of file device_command_substatus_enums.hpp.
enum px::device_role : uint8_t strong
Device "role" enumeration.
This is a list of various "roles" that a device may have. It is useful to allow some distinction to be made between devices that, though they are exposed using the same device structure, may have different characteristics or behavior.
Enumerator
device
Ordinary device.
publisher
The root device (at ID 1)
port
A communication port.
The CDS treats these the same but the UI treats them specially.
subdevice
A sub-device. Treated the same as any device by CDS.
invalid
This is used both to indicate invalidity, and to track the end of the list of enumerations.
Definition at line 16 of file device_role_enums.hpp.
enum px::mercury_msg_format_t
Defines the set of enums for the CMercuryHeader::_message_type field.
Enumerator
HG_MSG_KEEPALIVE
HG_MSG_PROTOBUF
HG_MSG_BLOB
HG_MSG_JSON_UTF8
HG_MSG_JSON_ASCII
HG_MSG_XML_UTF8
HG_MSG_XML_ASCII
HG_MSG_NOT_SUPPORT
Definition at line 12 of file mercury_msg_enums.hpp.
enum px::override_level : uint8_t strong
Level at which to apply an MCL channel-definition override.
Enumerator
global
family
modelseries
instance
invalid
Definition at line 10 of file override_level_enums.hpp.
enum px::permissions : uint8_t strong
permission enumeration
These are the enumerated values of the different permissions. Keep values the same as px::proto::Permissions for easy conversion, but have this separate definition for Bitset convenience, and potential additions.
Enumerator
unknown
Default value.
Used in OOB *_permission_required members to mean "nobody has this permission".
                            /* Protobuf Enum Name and value
data_read
Can read in-band data (channel values, alarms, trends, device/channel properties)
data_write
Can set channel values, device/channel properties.
data_admin
Can configure trending, alarms, device/channel states & flags.
config_read
Can read any binary-blob object, and OOB objects with default permissions.
config_write
Can create / update / delete any binary-blob object, and OOB objects with default permissions.
config_file
Can replace configuration all at once, without logging individual changes.
internal_app
Can create/delete/edit channels and edit device properties Mostly for device handlers.
install
Can update firmware, create/edit/delete devices/channels.
troubleshoot
Can do things only needed for debug, e.g. SSH login.
control_basic
Can see/run routine device commands, e.g. resets.
control_oper
Can see/run power-controlling device commands, e.g. open breaker.
setpoints
Can see/run non-routine device commands, e.g. setpoints.
event_ack
Can acknowledge alarms and other events.
security_admin
Can create / delete / update users/roles (and therefore give themselves any permission)
security_read
Can audit security settings but not change them, view logs.
per_user
All authenticated users have this permission.
size
Definition at line 16 of file permission_enums.hpp.
Function Documentation
template<class Target , class Source > Target px::poly_cast (Source * x)
Polymorphic casting: this utilizes dynamic_cast<> for non-release builds, thus ensuring that the cast is safe, but for release builds it becomes a more efficient static_cast<>.
Based off of boost::polymorphic_downcast<>.
Definition at line 20 of file cast.hpp.
Referenced by px::serialize::load(), px::cds::req_pack(), px::serialize::save(), px::cds::CGetOOBDataUnit::serialize(), and px::cds::CSetOOBDataUnit::serialize().
template<class Target , class Source > Target px::poly_cast (Source & x)
Definition at line 30 of file cast.hpp.
template<class Target , class Source > std::shared_ptr<Target> px::poly_cast (const std::shared_ptr< Source > & x)
Definition at line 41 of file cast.hpp.
template<intmax_t MaxVal> static ssize_t px::reverse_lookup_idx (size_t val) static
This is useful for any of the classes which utilize a gperf-generated lookup table.
It creates a reverse-lookup table, so that you can map directly from e.g. an enum value back into the corresponding string (or ancillary data) but without needing to replicate the strings over again.
Assumptions:
Default gperf function names are used
The structure utilized by gperf has at least 2 members: an integer named 'offset' (generated when the pic option is used), and an integer/enum value named 'num'
The template argument is the largest possible value of 'num'
Parameters
val The integer/enum/whatever value to be reverse-mapped
Returns
The index of the entry associated with this enum
Definition at line 31 of file reverse_lookup.hpp.
References unlikely, and wordlist.
template<intmax_t MaxVal> static const char* px::reverse_lookup (size_t val) static
Find the string key associated with the given integer/enum value.
Parameters
val The integer/enum/whatever value to be reverse-mapped
Returns
The string associated with this enum, or nullptr if it's invalid
Definition at line 102 of file reverse_lookup.hpp.
References stringpool, and wordlist.
template<class T > static size_t px::hash_value (const T & x) static
Used by boost::hash.
Any classes in px which already define std::hash<> don't need to re-define a hasher for boost libs – just call the std:: version instead.
Definition at line 15 of file hash.hpp.
px::string px::create_hmac (const px::string & key, const px::string & msg, size_t max_size)
This function creates a hmac-sha-1 hash in string format from a seed key string and message string.
NOTE: This function is only available if the Toolkit was compiled with OpenSSL support enabled
Parameters
key User defined context key. Must not be empty.
msg Used with the key to generate the hash. Must not be empty.
max_size Defines the length of the hash to return. Must be > 0.
Returns
returns the result string generated by hash
Exceptions
Throws generic_err if error is encountered.
Definition at line 30 of file hmac_sh1.cpp.
std::vector< unsigned char > px::create_sha1 (const px::string & key, size_t max_size)
generate sha1 hash from key
Parameters
key User defined context key. Must not be empty.
max_size Defines the length of the hash to return. Must be > 0.
Definition at line 13 of file hmac_sh1.cpp.
template<> px::string px::CValue::as< px::string > () const
Specialization for string type.
Definition at line 661 of file type/value.hpp.
px::string px::PXtype2Protobuf (const px::datatype value_type)
Convert a CDS px::datatype to a Mercury value_type See Core.proto for list of Mercury value_type in string format.
See px/enums/datatype_enums.hpp for list of px::datatype enums.
Definition at line 7 of file datatype_converter.cpp.
References binary, boolean, float32, float64, int32, int64, string, timestamp, uint32, and uint64.
Referenced by px::CDeviceCommand::to().
px::datatype px::Protobuf2PXtype (const px::string value_type)
Convert a Mercury value_type to CDS px::datatype See Core.proto for list of Mercury value_type in string format.
See px/enums/datatype_enums.hpp for list of px::datatype enums. Value_type must not be empty.
Definition at line 59 of file datatype_converter.cpp.
References binary, boolean, float32, float64, int32, int64, invalid, string, timestamp, uint32, and uint64.
Referenced by px::CParameterInfo::from().
px::string px::realtime_state_to_str (px::realtime_state flag, bool value)
Convert any realtime state enum to string.
Parameters
flag - Flag ID
value - Flag value
Returns
string format value of the flag
Definition at line 8 of file device_string.cpp.
References disabled, disarmed, not_communicating, pass_through, and waveform_available.
px::string px::device_diff_to_str (const px::CDevice & cur_dev, const px::CDevice & new_dev)
This function will provide changes in device setting in string format.
Parameters
cur_dev - Current device settings
new_dev - New device settings
Returns
Change information in string format
Definition at line 71 of file device_string.cpp.
References px::CDevice::contact, px::CDevice::guid, px::CDevice::hardware_version, px::CDevice::location, px::CDevice::name, px::CDevice::software_version, and px::CDevice::vendor.
template<typename T , typename std::enable_if<(sizeof(T)==1), int >::type = 0> static T px::to_big_endian (T val) static
No conversion necessary if we're only 1 byte.
Definition at line 38 of file endian.hpp.
Referenced by px::serialize::save().
template<typename T , typename std::enable_if< std::is_integral< T >::value||std::is_enum< T >::value, int >::type = 0, typename std::enable_if<(sizeof(T)==sizeof(uint16_t)), int >::type = 0> static T px::to_big_endian (T val) static
Integral 2-byte conversion.
Floating-point 8-byte conversion.
Floating-point 4-byte conversion.
Integral 8-byte conversion.
Integral 4-byte conversion.
Definition at line 50 of file endian.hpp.
template<typename T , typename std::enable_if<(sizeof(T)==1), int >::type = 0> static T px::from_big_endian (T val) static
No conversion necessary if we're only 1 byte.
Definition at line 114 of file endian.hpp.
Referenced by px::serialize::load().
template<typename T , typename std::enable_if< std::is_integral< T >::value||std::is_enum< T >::value, int >::type = 0, typename std::enable_if<(sizeof(T)==sizeof(uint16_t)), int >::type = 0> static T px::from_big_endian (T val) static
Integral 2-byte conversion.
Floating-point 8-byte conversion.
Floating-point 4-byte conversion.
Integral 8-byte conversion.
Integral 4-byte conversion.
Definition at line 126 of file endian.hpp.
static void px::float_to_big_endian (unsigned char * buf, int offset, float val) static
Writes a 4-byte floating-point to a big-endian buffer with a start offset.
Definition at line 188 of file endian.hpp.
Referenced by px::db::AddTrendBucketToBatch(), and px::db::AddTrendStageToBatch().
static float px::float_from_big_endian (const unsigned char * buf, int offset) static
Reads a 4-byte floating-point from a big-endian buffer with a start offset.
Definition at line 210 of file endian.hpp.
Referenced by px::db::ExportTrendStageRow(), px::db::MoveTrendsFromStageToBucket(), px::db::QueryTrendStage(), px::db::ReadTrendsFromBucketRow(), and px::db::ReadTrendsFromStageRow().
static void px::double_to_big_endian (unsigned char * buf, int offset, double val) static
Writes an 8-byte floating-point to a big-endian buffer with a start offset.
Definition at line 233 of file endian.hpp.
Referenced by px::db::AddTrendBucketToBatch(), and px::db::AddTrendStageToBatch().
static double px::double_from_big_endian (const unsigned char * buf, int offset) static
Reads an 8-byte floating-point from a big-endian buffer with a start offset.
Definition at line 262 of file endian.hpp.
Referenced by px::db::ExportTrendStageRow(), px::db::MoveTrendsFromStageToBucket(), px::db::QueryTrendStage(), px::db::ReadTrendsFromBucketRow(), and px::db::ReadTrendsFromStageRow().
px::string px::JSON2Protobuf (const px::string & json, std::vector< std::shared_ptr< google::protobuf::Message > > & msgs)
Conversion routines between protobuf objects and JSON strings.
JSON generated: one (or an array of) object(s) with the same name as the protobuf, with value of an array of objects, whose element names correspond to the names of the protobuf fields.
Examples: { "Channel":{ "canonical_name":"mACVAN", "display_order":53 } } or [ { "Channel":{ "id":123, "accumulated":false } }, { "Device":{ "id":317, "role":"publisher" } } ]
"repeated" fields become arrays, e.g.: "device_ids": [ 1, 2, 3 ] "message" fields become objects, e.g.: "minimum": { "float_val": 0.0 }
The Simplified or "Qualified" list form accepted by JSON2Protobuf(), but never generated by Protobuf2JSON(), useful when the list is all the same type of protobuf: Eg, here the protobuf_type might be "Channel" and the JSON string for 2 Channels: [ { "id":123, "accumulated":false }, { "id":456 } ]Convert a string containing JSON into an array of protobuf objects. Returns a string describing errors found, empty string if none. If any errors are found, parsing is probably incomplete. Elements whose name is not the same as an existing message field will cause a parsing error. Elements with a name corresponding to an existing message field, with a conflicting type (e.g. string value for an integer field) will return an error and not be parsed.
Parameters
json The input JSON string to be converted. Must not be empty.
[out] msgs The array of protobuf message(s) transformed from the JSON string.
Returns
Empty string on success, else an error message.
Definition at line 631 of file json_protobuf.cpp.
References json_to_protobuf_internal().
px::string px::Protobuf2JSON (std::vector< std::shared_ptr< google::protobuf::Message > > & msgs, bool pretty_print = false)
Convert an array of protobuf objects into a string containing JSON formatted as above.
Parameters
msgs The array of protobuf message(s) to transform into a string of JSON. Must not be empty.
pretty_print If true, will provide prettier formatting of the output text
Returns
The JSON text output. Will be a JSON array if there is more than one message. If there are errors in transforming the protobuf message(s), an empty string will be returned.
Definition at line 1330 of file json_protobuf.cpp.
References protobuf_to_json_internal().
px::string px::QualifiedJSON2Protobuf (const px::string & json, const px::string & protobuf_type, std::vector< std::shared_ptr< google::protobuf::Message > > & msgs)
Conversion to/from a given message type.
The input/output is unadorned JSON in an array or object, thusly: [ { "id":123, "accumulated":false } ] or { "id":123, "accumulated":false } Protobuf type is the other parameter (in the above case it would be 'Channel'). All messages in the array must be of the specified type or an error is returned.
Parameters
json The input JSON string to be converted. Must not be empty.
protobuf_type The name of the protobuf type to be converted (must be found, or error will result)
[out] msgs The array of protobuf message(s) transformed from the JSON string.
Returns
Empty string on success, else an error message.
Definition at line 667 of file json_protobuf.cpp.
References json_to_protobuf_internal().
px::string px::Protobuf2QualifiedJSON (px::string & protobuf_type, std::vector< std::shared_ptr< google::protobuf::Message > > & msgs, bool list = true, bool noextraspaces = false, bool numeric_enums = false)
Convert an array of protobuf objects - all of the same "Qualified" type - into an "unadorned" string containing JSON formatted as above.
Parameters
[out] protobuf_type On return, is set to the type of the first message in the array.
msgs The array of protobuf message(s) to transform into a string of JSON. Must not be empty.
list If true, enclose returned list in []. If false, there must be exactly one entry in 'msgs', and the [] is omitted.
noextraspaces If true, don't put whitespace outside of string constants
numeric_enums If false, translate enum values to their string representations
Returns
The unadorned JSON text output. Will always be a JSON array, even for one message. If there are errors in transforming the protobuf message(s), or if any of the messages are not the same as the protobuf_type, an empty string will be returned.
Definition at line 1338 of file json_protobuf.cpp.
References protobuf_to_json_internal().
bool px::ssl_host_check (const px::string & hostname, X509 * cert)
Check that an X.509 certificate is appropriate for a given hostname.
Checks the commonName field of the subjectName and DNS names in any subjectAltNames. One must match the given hostname (case-insensitively). Wildcards are handled, so a CN of "*.eaton.com" will match any hostname ending in ".eaton.com". No checking of signature, expiration, or any other fields is done.
Parameters
hostname Host name to check. Must not be empty.
cert OpenSSL X.509 certificate structure. Must not be null.
Returns
True if at least one name matches, false otherwise
Definition at line 53 of file ssl.cpp.
References likely, matches(), and unlikely.
std::vector< unsigned char > px::hex_2_bytes (const px::string & str, bool ignore_nonhex = false)
Convert ASCII hex digits to vector of bytes.
Parameters
str String to convert. Must not be empty.
ignore_nonhex If true, silently ignore invalid characters
Exceptions
px::generic_err if ignore_nonhex false and something outside of [0-9A-Fa-f] is in the string
Returns
Bytes represented by those hex digits, one byte per 2 input hex characters.
Definition at line 212 of file string_util.cpp.
px::string px::bytes_2_hex (const unsigned char * data, size_t size, bool uppercase = false)
Convert bytes into a string of ASCII hex digits.
The string is uninterrupted.
Parameters
data Pointer to the data. Must not be null.
size Number of bytes to convert. Must be > 0.
uppercase Use A-F instead of a-f
Returns
ASCII string of hex digits representing the data
Definition at line 62 of file string_util.cpp.
References unlikely.
Referenced by px::image_util::CheckImageSums(), and px::CUtil::create_random_uuid().
std::vector< unsigned char > px::vec_bytes_2_hex (const std::vector< unsigned char > & data, bool uppercase = false)
Convert vector of bytes into a vector of of ASCII hex digits.
Parameters
data Vector of bytes. Must not be empty.
uppercase Use A-F instead of a-f
Returns
Vector of converted bytes representing the input data bytes as ASCII hex digits
Definition at line 107 of file string_util.cpp.
px::string px::bytes_2_guid (const unsigned char * data, size_t size, bool no_dashes = false)
Convert bytes into a string of ASCII hex digits in GUID format, eg 01234567-89ab-cdef-0123-456789abcdef.
The input must be 32 bytes, or this will fail. Assumes that all bytes are hexadecimal character values. The 32 characters of hex input will be used without conversion and just have the dashes added. The international standard for GUIDs is lowercase a-f, so that is used here.
Parameters
data Pointer to the data. Must not be null.
size Number of bytes to convert. Must be 32.
no_dashes Do not include dashes in ASCII string result. Default is false.
Returns
ASCII string of hex digits representing the UUID on success, else an empty string on failure.
Definition at line 150 of file string_util.cpp.
Referenced by px::CDevice::get_device_uuid().
std::vector< unsigned char > px::guid_2_bytes (const px::string & guid_text)
Convert a GUID's 32 or 36 ASCII hex digits to vector of 32 bytes.
Parameters
guid_text GUID as a string; may be in the dashed format.
Returns
32 Bytes represented by those GUID characters on success, else an empty vector on failure (eg, invalid characters or UUID).
Definition at line 178 of file string_util.cpp.
Referenced by px::asio::CCdsSyncIO::set_device_guid(), and px::CDevice::set_device_uuid().
void px::pxstr_tolower (px::string & str)
Convert, in place, any uppercase characters in 'str' to lowercase.
Parameters
str String to convert. Must not be empty.
Definition at line 12 of file string_util.cpp.
Referenced by px::CChannelSettings::get_units_scaling(), and matches().
bool px::pxstr_to_printable (px::string & str, char subst_char = 0)
Check for any unprintable characters in the string, and either remove or substitute for them.
Uses the std::isprint() to screen for unprintable characters.
Parameters
str String to convert. Must not be empty.
subst_char If not 0, then substitute this character for any unprintable characters found. If it is 0, then remove them from the string.
Returns
True if found any unprintable characters (ie, if str was modified), else False if no changes.
Definition at line 22 of file string_util.cpp.
std::string px::add_esc_char (const char * str)
Check for double quotes in the string and add escape characters if present.
Uses the boost::replace_all api add escape characters.
Parameters
str String to check and add escape characters to. Must not be null.
Returns
Returns the modified string.
Definition at line 52 of file string_util.cpp.
uint32_t px::pxstr_first_utf8_codepoint (const unsigned char *& str, size_t & rem)
Given a pointer to bytes of UTF-8, return the codepoint of the first character, and a pointer to the next character.
For ASCII printable characters this degenerates to the first byte and a pointer to the next byte. If invalid UTF-8 is detected, return 0xFFFD (the Unicode replacement character) as the codepoint.
Parameters
str Pointer to bytes. Updated to point to the next character if size is not exhausted. Must not be null.
rem Remaining bytes in the string. Reduced by the number of bytes used to encode the returned codepoint.
Returns
uint32_t Unicode code point
Definition at line 256 of file string_util.cpp.
References likely, and unlikely.
Referenced by json_string_escape().
std::vector< px::string > px::tokenize (const px::string & line)
Split an ASCII string into whitespace-separated tokens.
Single or double quotes may enclose a token, and cause spaces to be included. Such quotes will be removed from the returned tokens. Single or double literal quotes can be escaped with a backslash. Repeated whitespace is collapsed into a single delimiter.
Parameters
line The string to tokenize. Must not be empty.
Returns
List of tokens
Definition at line 315 of file string_util.cpp.
References unlikely.
void px::safe_line_split (std::vector< std::string > & token_list, const std::string & text_line, const char * separators)
Function to encapuslate boost::split(), including try-catch for boost errors.
Nothing is directly returned from this function, but the token_list should contain the results on exit. Using std::string for this function.
Parameters
[out] token_list The array of tokens split from the input text_line. In case of bad errors, it will be empty.
text_line The input line of text to be split. Must not be empty.
separators The list of characters to be used as separators (eg, ".,-") Must not be null.
Definition at line 381 of file string_util.cpp.
Referenced by px::db::ImportTrendBucket(), and px::db::ImportTrendStage().
bool px::remove_trailing_slash (std::string & str)
Remove trailing slash from a string (if present) Will not work if the string is "/".
Parameters
str std::string input.
Returns
true if string was modified
Definition at line 398 of file string_util.cpp.
Referenced by px::CRecursiveFind::CRecursiveFind(), px::CRecursiveFind::find_files(), and remove_trailing_slash().
bool px::remove_trailing_slash (px::string & str)
Remove trailing slash from a string (if present) Will not work if the string is "/".
Parameters
str px::string input.
Returns
true if string was modified
Definition at line 413 of file string_util.cpp.
References remove_trailing_slash().