libpx: CScheduler Class Reference
CScheduler Class Reference
CScheduler maintains a pool of 1 or more threads that executes tasks on a schedule.
#include <scheduler.hpp>
Public Member Functions
PUBLIC CScheduler (const uint8_t num_threads, const bool start_now=false)
Create a scheduler.
PUBLIC ~CScheduler ()
PUBLIC void start ()
Starts the worker threads that executes tasks.
PUBLIC void shutdown (const bool wait_for_jobs_to_complete)
Halts the scheduler's execution of tasks, and cleans up all resources.
PUBLIC void run_task_async (std::shared_ptr< ITask > task)
Queue up task for asynchronous execution on one of the scheduler's worker threads.
PUBLIC void schedule_task (std::shared_ptr< ITask > task, std::unique_ptr< ITrigger > &trigger)
Queue up task to be executed in the future, based on a trigger schedule.
PUBLIC uint8_t get_num_threads ()
Private Member Functions
void start_thread ()
Initialize logger and hand thread over to io_service.run()
void execute_task_cb (std::shared_ptr< ITask > task, uint64_t id)
Function provided to boost asio post(), in order to execute task and clean up task list.
void timer_cb (const boost::system::error_code &error)
Callback for timer - helps manage scheduled task execution.
void reset_timer ()
Private Attributes
uint8_t _num_threads
Number of threads scheduler is configured to use.
std::unique_ptr
< boost::asio::io_service > _io_service
Manages threads, job execution.
std::unique_ptr
< boost::asio::io_service::work > _work
Prevents io_service from exiting when no tasks pending.
std::unique_ptr
< boost::asio::steady_timer > _timer
Helps schedule tasks.
std::vector< std::thread > _thread_pool
Worker threads.
uint64_t _next_id
Next available internal task id.
px::CWallTime _prev_time
Previous cycle time (the last time the timer was triggered to search for the scheduled tasks)
std::unordered_map< uint64_t,
std::shared_ptr< ITask > > _active_tasks
Active tasks by ID.
std::unordered_map< uint64_t,
std::shared_ptr< ITask > > _scheduled_tasks
Scheduled tasks by ID.
std::multimap< uint64_t,
std::unique_ptr< ITrigger > > _trigger_map
Map of Triggers by scheduled task ID.
std::mutex _mutex
Mutex to protect _next_id, _active_tasks, _scheduled_tasks, and _trigger_map.
boost::thread_specific_ptr
< toolkit::CSysLog > _thread_local_syslog
Needed to log in worker threads.
Detailed Description
CScheduler maintains a pool of 1 or more threads that executes tasks on a schedule.
Definition at line 36 of file scheduler.hpp.
Constructor & Destructor Documentation
CScheduler::CScheduler (const uint8_t num_threads, const bool start_now = false)
Create a scheduler.
Definition at line 21 of file scheduler.cpp.
References start().
CScheduler::~CScheduler ()
Definition at line 31 of file scheduler.cpp.
References shutdown().
Member Function Documentation
void CScheduler::start ()
Starts the worker threads that executes tasks.
Definition at line 48 of file scheduler.cpp.
References _io_service, _num_threads, _prev_time, _thread_pool, _timer, _work, LIBPX_FERR, LIBPX_NOTICE, px::CWallTime::now(), reset_timer(), and start_thread().
Referenced by CScheduler().
void CScheduler::shutdown (const bool wait_for_jobs_to_complete)
Halts the scheduler's execution of tasks, and cleans up all resources.
Parameters
wait_for_jobs_to_complete if true the scheduler will not allow this method to return until all currently executing jobs have completed.
Definition at line 81 of file scheduler.cpp.
References _io_service, _thread_pool, _timer, and _work.
Referenced by ~CScheduler().
void CScheduler::run_task_async (std::shared_ptr< ITask > task)
Queue up task for asynchronous execution on one of the scheduler's worker threads.
Execution will occur as soon as possible. Task must not be null.
Definition at line 111 of file scheduler.cpp.
References _active_tasks, _io_service, _mutex, _next_id, and execute_task_cb().
Referenced by timer_cb().
void CScheduler::schedule_task (std::shared_ptr< ITask > task, std::unique_ptr< ITrigger > & trigger)
Queue up task to be executed in the future, based on a trigger schedule.
Ptr must not be null.
Definition at line 133 of file scheduler.cpp.
References _mutex, _next_id, _scheduled_tasks, and _trigger_map.
uint8_t CScheduler::get_num_threads ()
Definition at line 234 of file scheduler.cpp.
References _num_threads.
void CScheduler::start_thread () private
Initialize logger and hand thread over to io_service.run()
Definition at line 149 of file scheduler.cpp.
References _io_service, _thread_local_syslog, LIBPX_FERR, and px::CUtil::set_thread_name().
Referenced by start().
void CScheduler::execute_task_cb (std::shared_ptr< ITask > task, uint64_t id) private
Function provided to boost asio post(), in order to execute task and clean up task list.
Definition at line 168 of file scheduler.cpp.
References _active_tasks, _mutex, LIBPX_ERR, and LIBPX_INFO.
Referenced by run_task_async().
void CScheduler::timer_cb (const boost::system::error_code & error) private
Callback for timer - helps manage scheduled task execution.
Definition at line 191 of file scheduler.cpp.
References _mutex, _prev_time, _scheduled_tasks, _trigger_map, _work, LIBPX_FERR, px::CWallTime::now(), reset_timer(), and run_task_async().
Referenced by reset_timer().
void CScheduler::reset_timer () private
Definition at line 240 of file scheduler.cpp.
References _timer, LIBPX_FERR, and timer_cb().
Referenced by start(), and timer_cb().
Member Data Documentation
uint8_t CScheduler::_num_threads private
Number of threads scheduler is configured to use.
Definition at line 85 of file scheduler.hpp.
Referenced by get_num_threads(), and start().
std::unique_ptr<boost::asio::io_service> CScheduler::_io_service private
Manages threads, job execution.
Definition at line 88 of file scheduler.hpp.
Referenced by run_task_async(), shutdown(), start(), and start_thread().
std::unique_ptr<boost::asio::io_service::work> CScheduler::_work private
Prevents io_service from exiting when no tasks pending.
Definition at line 91 of file scheduler.hpp.
Referenced by shutdown(), start(), and timer_cb().
std::unique_ptr<boost::asio::steady_timer> CScheduler::_timer private
Helps schedule tasks.
Definition at line 94 of file scheduler.hpp.
Referenced by reset_timer(), shutdown(), and start().
std::vector<std::thread> CScheduler::_thread_pool private
Worker threads.
Definition at line 97 of file scheduler.hpp.
Referenced by shutdown(), and start().
uint64_t CScheduler::_next_id private
Next available internal task id.
Definition at line 100 of file scheduler.hpp.
Referenced by run_task_async(), and schedule_task().
px::CWallTime CScheduler::_prev_time private
Previous cycle time (the last time the timer was triggered to search for the scheduled tasks)
Definition at line 103 of file scheduler.hpp.
Referenced by start(), and timer_cb().
std::unordered_map<uint64_t, std::shared_ptr<ITask> > CScheduler::_active_tasks private
Active tasks by ID.
Includes tasks from run_async and scheduled tasks that are currently running
Definition at line 107 of file scheduler.hpp.
Referenced by execute_task_cb(), and run_task_async().
std::unordered_map<uint64_t, std::shared_ptr<ITask> > CScheduler::_scheduled_tasks private
Scheduled tasks by ID.
Definition at line 110 of file scheduler.hpp.
Referenced by schedule_task(), and timer_cb().
std::multimap<uint64_t, std::unique_ptr<ITrigger> > CScheduler::_trigger_map private
Map of Triggers by scheduled task ID.
Definition at line 113 of file scheduler.hpp.
Referenced by schedule_task(), and timer_cb().
std::mutex CScheduler::_mutex private
Mutex to protect _next_id, _active_tasks, _scheduled_tasks, and _trigger_map.
Definition at line 116 of file scheduler.hpp.
Referenced by execute_task_cb(), run_task_async(), schedule_task(), and timer_cb().
boost::thread_specific_ptr<toolkit::CSysLog> CScheduler::_thread_local_syslog private
Needed to log in worker threads.
Definition at line 119 of file scheduler.hpp.
Referenced by start_thread().
The documentation for this class was generated from the following files:
scheduler.hpp
scheduler.cpp