libpx: equation.yy.hpp File Reference
equation.yy.hpp File Reference
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
#include "px/equation/internal/equation.tab.hpp"
#include <unistd.h>
Classes
struct yy_buffer_state
struct yy_trans_info
struct yyguts_t
Macros
#define YY_INT_ALIGNED short int
#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#define FLEX_BETA
#define FLEXINT_H
#define INT8_MIN (-128)
#define INT16_MIN (-32767 - 1)
#define INT32_MIN (-2147483647 - 1)
#define INT8_MAX (127)
#define INT16_MAX (32767)
#define INT32_MAX (2147483647)
#define UINT8_MAX (255U)
#define UINT16_MAX (65535U)
#define UINT32_MAX (4294967295U)
#define yyconst
#define YY_NULL 0
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
#define YY_TYPEDEF_YY_SCANNER_T
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r
#define BEGIN yyg->yy_start = 1 + 2 *
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
#define YY_NEW_FILE yyrestart(yyin, yyscanner)
#define YY_END_OF_BUFFER_CHAR 0
#define YY_BUF_SIZE 16384
#define YY_STATE_BUF_SIZE ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))
#define YY_TYPEDEF_YY_BUFFER_STATE
#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
#define YY_LESS_LINENO(n)
#define yyless(n)
#define unput(c) yyunput(c, yyg->yytext_ptr, yyscanner)
#define YY_TYPEDEF_YY_SIZE_T
#define YY_STRUCT_YY_BUFFER_STATE
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
#define YY_BUFFER_EOF_PENDING 2
#define YY_CURRENT_BUFFER
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]
#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER, yyscanner)
#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive)
#define yy_set_bol(at_bol)
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)
#define yywrap(n) 1
#define YY_SKIP_YYWRAP
#define yytext_ptr yytext_r
#define YY_DO_BEFORE_ACTION
#define YY_NUM_RULES 34
#define YY_END_OF_BUFFER 35
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#define YY_INPUT(b, r, ms) (r = my_yyinput(b, ms, yyg->yyextra_r))
#define INITIAL 0
#define YY_EXTRA_TYPE void *
#define yylval yyg->yylval_r
#define YY_READ_BUF_SIZE 8192
#define ECHO
#define yyterminate() return YY_NULL
#define YY_START_STACK_INCR 25
#define YY_FATAL_ERROR(msg) yy_fatal_error(msg, yyscanner)
#define YY_DECL_IS_OURS 1
#define YY_DECL
#define YY_USER_ACTION
#define YY_BREAK break;
#define YY_RULE_SETUP YY_USER_ACTION
#define YY_EXIT_FAILURE 2
#define yyless(n)
#define YYTABLES_NAME "yytables"
Typedefs
typedef signed char flex_int8_t
typedef short int flex_int16_t
typedef int flex_int32_t
typedef unsigned char flex_uint8_t
typedef unsigned short int flex_uint16_t
typedef unsigned int flex_uint32_t
typedef void * yyscan_t
typedef struct yy_buffer_state * YY_BUFFER_STATE
typedef size_t yy_size_t
typedef char YY_CHAR
typedef int yy_state_type
Functions
void yyrestart (FILE *input_file, yyscan_t yyscanner)
Immediately switch to a different input stream.
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
Switch to a different input buffer.
YY_BUFFER_STATE yy_create_buffer (FILE *file, int size, yyscan_t yyscanner)
Allocate and initialize an input buffer state.
void yy_delete_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
Destroy the buffer.
void yy_flush_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
Discard all buffered characters.
void yypush_buffer_state (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
Pushes the new state onto the stack.
void yypop_buffer_state (yyscan_t yyscanner)
Removes and deletes the top of the stack, if present.
static void yyensure_buffer_stack (yyscan_t yyscanner)
static void yy_load_buffer_state (yyscan_t yyscanner)
static void yy_init_buffer (YY_BUFFER_STATE b, FILE *file, yyscan_t yyscanner)
YY_BUFFER_STATE yy_scan_buffer (char *base, yy_size_t size, yyscan_t yyscanner)
Setup the input buffer state to scan directly from a user-specified character buffer.
YY_BUFFER_STATE yy_scan_string (yyconst char *yystr, yyscan_t yyscanner)
Setup the input buffer state to scan a string.
YY_BUFFER_STATE yy_scan_bytes (yyconst char *yybytes, int _yybytes_len, yyscan_t yyscanner)
Setup the input buffer state to scan the given bytes.
void * yyalloc (yy_size_t, yyscan_t yyscanner)
void * yyrealloc (void *, yy_size_t, yyscan_t yyscanner)
void yyfree (void *, yyscan_t yyscanner)
static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
static yy_state_type yy_try_NUL_trans (yy_state_type current_state, yyscan_t yyscanner)
static int yy_get_next_buffer (yyscan_t yyscanner)
static void yy_fatal_error (yyconst char msg[], yyscan_t yyscanner)
static int yy_init_globals (yyscan_t yyscanner)
int yylex_init (yyscan_t *scanner)
int yylex_init_extra (YY_EXTRA_TYPE user_defined, yyscan_t *scanner)
int yylex_destroy (yyscan_t yyscanner)
int yyget_debug (yyscan_t yyscanner)
void yyset_debug (int debug_flag, yyscan_t yyscanner)
YY_EXTRA_TYPE yyget_extra (yyscan_t yyscanner)
Get the user-defined data for this scanner.
void yyset_extra (YY_EXTRA_TYPE user_defined, yyscan_t yyscanner)
Set the user-defined data.
FILE * yyget_in (yyscan_t yyscanner)
Get the input stream.
void yyset_in (FILE *in_str, yyscan_t yyscanner)
Set the input stream.
FILE * yyget_out (yyscan_t yyscanner)
Get the output stream.
void yyset_out (FILE *out_str, yyscan_t yyscanner)
int yyget_leng (yyscan_t yyscanner)
Get the length of the current token.
char * yyget_text (yyscan_t yyscanner)
Get the current token.
int yyget_lineno (yyscan_t yyscanner)
Get the current line number.
void yyset_lineno (int line_number, yyscan_t yyscanner)
Set the current line number.
int yyget_column (yyscan_t yyscanner)
Get the current column number.
void yyset_column (int column_no, yyscan_t yyscanner)
Set the current column.
YYSTYPE * yyget_lval (yyscan_t yyscanner)
void yyset_lval (YYSTYPE *yylval_param, yyscan_t yyscanner)
static int input (yyscan_t yyscanner)
int yylex (YYSTYPE *yylval_param, yyscan_t yyscanner)
if (!yyg->yy_init)
while (1)
int isatty (int)
static void yy_fatal_error (yyconst char *msg, yyscan_t yyscanner)
Variables
static yyconst flex_int16_t yy_nxt [][128]
static yyconst flex_int16_t yy_accept [136]
static yyconst yy_state_type yy_NUL_trans [136]
YY_DECL
The main scanner function which does all the work.
register char * yy_cp
register char * yy_bp
register int yy_act
struct yyguts_t * yyg = (struct yyguts_t *)yyscanner
yylval = yylval_param
Macro Definition Documentation
#define YY_INT_ALIGNED short int
Definition at line 5 of file equation.yy.hpp.
#define FLEX_SCANNER
Definition at line 9 of file equation.yy.hpp.
#define YY_FLEX_MAJOR_VERSION 2
Definition at line 10 of file equation.yy.hpp.
#define YY_FLEX_MINOR_VERSION 5
Definition at line 11 of file equation.yy.hpp.
#define YY_FLEX_SUBMINOR_VERSION 35
Definition at line 12 of file equation.yy.hpp.
#define FLEX_BETA
Definition at line 14 of file equation.yy.hpp.
#define FLEXINT_H
Definition at line 30 of file equation.yy.hpp.
#define INT8_MIN (-128)
Definition at line 61 of file equation.yy.hpp.
#define INT16_MIN (-32767 - 1)
Definition at line 64 of file equation.yy.hpp.
#define INT32_MIN (-2147483647 - 1)
Definition at line 67 of file equation.yy.hpp.
#define INT8_MAX (127)
Definition at line 70 of file equation.yy.hpp.
#define INT16_MAX (32767)
Definition at line 73 of file equation.yy.hpp.
#define INT32_MAX (2147483647)
Definition at line 76 of file equation.yy.hpp.
Referenced by px::CValue::operator/=().
#define UINT8_MAX (255U)
Definition at line 79 of file equation.yy.hpp.
#define UINT16_MAX (65535U)
Definition at line 82 of file equation.yy.hpp.
#define UINT32_MAX (4294967295U)
Definition at line 85 of file equation.yy.hpp.
Referenced by px::CUser::from(), px::CChannelSettings::from(), px::CValue::operator/=(), px::db::QueryAlarms(), px::db::QueryAlarmsLatestUpdate(), and px::CUser::to().
#define yyconst
Definition at line 108 of file equation.yy.hpp.
#define YY_NULL 0
Definition at line 112 of file equation.yy.hpp.
#define YY_SC_TO_UI (c) ((unsigned int) (unsigned char) c)
Definition at line 119 of file equation.yy.hpp.
Referenced by while(), and yy_get_previous_state().
#define YY_TYPEDEF_YY_SCANNER_T
Definition at line 123 of file equation.yy.hpp.
#define yyin yyg->yyin_r
Definition at line 129 of file equation.yy.hpp.
Referenced by if(), input(), while(), yy_get_next_buffer(), yy_init_globals(), yy_load_buffer_state(), yyget_in(), yyrestart(), and yyset_in().
#define yyout yyg->yyout_r
Definition at line 130 of file equation.yy.hpp.
Referenced by if(), yy_init_globals(), yyget_out(), and yyset_out().
#define yyextra yyg->yyextra_r
Definition at line 131 of file equation.yy.hpp.
Referenced by yyget_extra(), and yyset_extra().
#define yyleng yyg->yyleng_r
Definition at line 132 of file equation.yy.hpp.
Referenced by yyget_leng().
#define yytext yyg->yytext_r
Definition at line 133 of file equation.yy.hpp.
Referenced by while(), and yyget_text().
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
Definition at line 134 of file equation.yy.hpp.
Referenced by yyget_lineno(), and yyset_lineno().
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
Definition at line 135 of file equation.yy.hpp.
Referenced by yyget_column(), and yyset_column().
#define yy_flex_debug yyg->yy_flex_debug_r
Definition at line 136 of file equation.yy.hpp.
Referenced by yyget_debug(), and yyset_debug().
#define BEGIN yyg->yy_start = 1 + 2 *
Definition at line 142 of file equation.yy.hpp.
#define YY_START ((yyg->yy_start - 1) / 2)
Definition at line 148 of file equation.yy.hpp.
Referenced by while().
#define YYSTATE YY_START
Definition at line 149 of file equation.yy.hpp.
#define YY_STATE_EOF (state) (YY_END_OF_BUFFER + state + 1)
Definition at line 152 of file equation.yy.hpp.
Referenced by while().
#define YY_NEW_FILE yyrestart(yyin, yyscanner)
Definition at line 155 of file equation.yy.hpp.
Referenced by input(), and while().
#define YY_END_OF_BUFFER_CHAR 0
Definition at line 157 of file equation.yy.hpp.
Referenced by input(), yy_flush_buffer(), yy_get_next_buffer(), yy_scan_buffer(), and yy_scan_bytes().
#define YY_BUF_SIZE 16384
Definition at line 161 of file equation.yy.hpp.
Referenced by if(), and yyrestart().
#define YY_STATE_BUF_SIZE ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))
Definition at line 166 of file equation.yy.hpp.
#define YY_TYPEDEF_YY_BUFFER_STATE
Definition at line 169 of file equation.yy.hpp.
#define EOB_ACT_CONTINUE_SCAN 0
Definition at line 173 of file equation.yy.hpp.
Referenced by input(), while(), and yy_get_next_buffer().
#define EOB_ACT_END_OF_FILE 1
Definition at line 174 of file equation.yy.hpp.
Referenced by input(), while(), and yy_get_next_buffer().
#define EOB_ACT_LAST_MATCH 2
Definition at line 175 of file equation.yy.hpp.
Referenced by input(), while(), and yy_get_next_buffer().
#define YY_LESS_LINENO (n)
Definition at line 177 of file equation.yy.hpp.
#define yyless (n)
Value:
do \
        { \
                /* Undo effects of setting up yytext. */ \
                int yyless_macro_arg = ( n ); \
        YY_LESS_LINENO( yyless_macro_arg ); \
                *yy_cp = yyg->yy_hold_char; \
        YY_RESTORE_YY_MORE_OFFSET \
        yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
        YY_DO_BEFORE_ACTION;/* set up yytext again */ \
        } \
    while ( 0 )
Definition at line 4152 of file equation.yy.hpp.
#define unput (c) yyunput(c, yyg->yytext_ptr, yyscanner)
Definition at line 193 of file equation.yy.hpp.
#define YY_TYPEDEF_YY_SIZE_T
Definition at line 196 of file equation.yy.hpp.
#define YY_STRUCT_YY_BUFFER_STATE
Definition at line 201 of file equation.yy.hpp.
#define YY_BUFFER_NEW 0
Definition at line 248 of file equation.yy.hpp.
Referenced by while(), yy_flush_buffer(), and yy_scan_buffer().
#define YY_BUFFER_NORMAL 1
Definition at line 249 of file equation.yy.hpp.
Referenced by while().
#define YY_BUFFER_EOF_PENDING 2
Definition at line 260 of file equation.yy.hpp.
Referenced by yy_get_next_buffer().
#define YY_CURRENT_BUFFER
Value:
(yyg->yy_buffer_stack \
                                                        ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                                                        : NULL )
Definition at line 270 of file equation.yy.hpp.
Referenced by if(), yy_delete_buffer(), yy_flush_buffer(), yy_get_next_buffer(), yy_init_buffer(), yy_switch_to_buffer(), yyget_column(), yyget_lineno(), yylex_destroy(), yypop_buffer_state(), yypush_buffer_state(), yyrestart(), yyset_column(), and yyset_lineno().
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]
Definition at line 277 of file equation.yy.hpp.
Referenced by if(), input(), while(), yy_delete_buffer(), yy_get_next_buffer(), yy_load_buffer_state(), yy_switch_to_buffer(), yylex_destroy(), yypop_buffer_state(), yypush_buffer_state(), and yyrestart().
#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER, yyscanner)
Definition at line 299 of file equation.yy.hpp.
#define yy_new_buffer yy_create_buffer
Definition at line 311 of file equation.yy.hpp.
#define yy_set_interactive (is_interactive)
Value:
{ \
        if ( !YY_CURRENT_BUFFER ){ \
            yyensure_buffer_stack( yyscanner ); \
            YY_CURRENT_BUFFER_LVALUE =    \
                yy_create_buffer( yyin, YY_BUF_SIZE, yyscanner ); \
                } \
        YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
        }
Definition at line 313 of file equation.yy.hpp.
#define yy_set_bol (at_bol)
Value:
{ \
        if ( !YY_CURRENT_BUFFER ){ \
            yyensure_buffer_stack( yyscanner ); \
            YY_CURRENT_BUFFER_LVALUE =    \
                yy_create_buffer( yyin, YY_BUF_SIZE, yyscanner ); \
                } \
        YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
        }
Definition at line 323 of file equation.yy.hpp.
#define YY_AT_BOL () (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)
Definition at line 333 of file equation.yy.hpp.
#define yywrap (n) 1
Definition at line 337 of file equation.yy.hpp.
Referenced by input(), and while().
#define YY_SKIP_YYWRAP
Definition at line 338 of file equation.yy.hpp.
#define yytext_ptr yytext_r
Definition at line 344 of file equation.yy.hpp.
#define YY_DO_BEFORE_ACTION
Value:
yyg->yytext_ptr = yy_bp; \
    yyleng = ( size_t ) ( yy_cp - yy_bp ); \
    yyg->yy_hold_char = *yy_cp; \
        *yy_cp = '\0'; \
    yyg->yy_c_buf_p = yy_cp;
Definition at line 2698 of file equation.yy.hpp.
Referenced by while().
#define YY_NUM_RULES 34
Definition at line 2705 of file equation.yy.hpp.
#define YY_END_OF_BUFFER 35
Definition at line 2706 of file equation.yy.hpp.
Referenced by while().
#define REJECT reject_used_but_not_detected
Definition at line 2755 of file equation.yy.hpp.
#define yymore () yymore_used_but_not_detected
Definition at line 2756 of file equation.yy.hpp.
#define YY_MORE_ADJ 0
Definition at line 2757 of file equation.yy.hpp.
Referenced by while(), yy_get_next_buffer(), and yy_get_previous_state().
#define YY_RESTORE_YY_MORE_OFFSET
Definition at line 2758 of file equation.yy.hpp.
Referenced by while().
#define YY_INPUT (b, r, ms) (r = my_yyinput(b, ms, yyg->yyextra_r))
Definition at line 2771 of file equation.yy.hpp.
Referenced by yy_get_next_buffer().
#define INITIAL 0
Definition at line 2777 of file equation.yy.hpp.
Referenced by while().
#define YY_EXTRA_TYPE void *
Definition at line 2788 of file equation.yy.hpp.
#define yylval yyg->yylval_r
Definition at line 2829 of file equation.yy.hpp.
Referenced by while(), yyget_lval(), and yyset_lval().
#define YY_READ_BUF_SIZE 8192
Definition at line 2910 of file equation.yy.hpp.
Referenced by yy_get_next_buffer().
#define ECHO
Value:
do { if (fwrite(yytext, yyleng, 1, yyout)){} \
} while (0)
Definition at line 2918 of file equation.yy.hpp.
#define yyterminate () return YY_NULL
Definition at line 2947 of file equation.yy.hpp.
Referenced by while().
#define YY_START_STACK_INCR 25
Definition at line 2952 of file equation.yy.hpp.
#define YY_FATAL_ERROR (msg) yy_fatal_error(msg, yyscanner)
Definition at line 2957 of file equation.yy.hpp.
Referenced by while(), yy_create_buffer(), yy_get_next_buffer(), yy_scan_buffer(), yy_scan_bytes(), and yyensure_buffer_stack().
#define YY_DECL_IS_OURS 1
Definition at line 2966 of file equation.yy.hpp.
#define YY_DECL
Value:
int yylex \
                ( YYSTYPE * yylval_param, yyscan_t yyscanner )
Definition at line 2970 of file equation.yy.hpp.
#define YY_USER_ACTION
Definition at line 2978 of file equation.yy.hpp.
#define YY_BREAK break;
Definition at line 2983 of file equation.yy.hpp.
Referenced by while().
#define YY_RULE_SETUP YY_USER_ACTION
Definition at line 2987 of file equation.yy.hpp.
Referenced by while().
#define YY_EXIT_FAILURE 2
Definition at line 4140 of file equation.yy.hpp.
Referenced by yy_fatal_error().
#define yyless (n)
Value:
do \
        { \
                /* Undo effects of setting up yytext. */ \
                int yyless_macro_arg = ( n ); \
        YY_LESS_LINENO( yyless_macro_arg ); \
        yytext[yyleng] = yyg->yy_hold_char; \
        yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
        yyg->yy_hold_char = *yyg->yy_c_buf_p; \
                *yyg->yy_c_buf_p = '\0'; \
        yyleng = yyless_macro_arg; \
        } \
    while ( 0 )
Definition at line 4152 of file equation.yy.hpp.
#define YYTABLES_NAME "yytables"
Definition at line 4527 of file equation.yy.hpp.
Typedef Documentation
typedef signed char flex_int8_t
Definition at line 51 of file equation.yy.hpp.
typedef short int flex_int16_t
Definition at line 52 of file equation.yy.hpp.
typedef int flex_int32_t
Definition at line 53 of file equation.yy.hpp.
typedef unsigned char flex_uint8_t
Definition at line 54 of file equation.yy.hpp.
typedef unsigned short int flex_uint16_t
Definition at line 55 of file equation.yy.hpp.
typedef unsigned int flex_uint32_t
Definition at line 56 of file equation.yy.hpp.
typedef void* yyscan_t
Definition at line 124 of file equation.yy.hpp.
typedef struct yy_buffer_state* YY_BUFFER_STATE
Definition at line 170 of file equation.yy.hpp.
typedef size_t yy_size_t
Definition at line 197 of file equation.yy.hpp.
typedef char YY_CHAR
Definition at line 340 of file equation.yy.hpp.
typedef int yy_state_type
Definition at line 342 of file equation.yy.hpp.
Function Documentation
void yyrestart (FILE * input_file, yyscan_t yyscanner)
Immediately switch to a different input stream.
Parameters
input_file A readable stream.
yyscanner The scanner object.
Note
This function does not reset the start condition to INITIAL .
Definition at line 3735 of file equation.yy.hpp.
References YY_BUF_SIZE, yy_create_buffer(), YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_init_buffer(), yy_load_buffer_state(), yyensure_buffer_stack(), and yyin.
Referenced by input(), and yy_get_next_buffer().
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
Switch to a different input buffer.
Parameters
new_buffer The new input buffer.
yyscanner The scanner object.
Definition at line 3754 of file equation.yy.hpp.
References yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_did_buffer_switch_on_eof, yyguts_t::yy_hold_char, yy_load_buffer_state(), yyguts_t::yy_n_chars, and yyensure_buffer_stack().
Referenced by yy_scan_buffer().
YY_BUFFER_STATE yy_create_buffer (FILE * file, int size, yyscan_t yyscanner)
Allocate and initialize an input buffer state.
Parameters
file A readable stream.
size The character buffer size in bytes. When in doubt, use YY_BUF_SIZE.
yyscanner The scanner object.
Returns
the allocated buffer state.
Definition at line 3804 of file equation.yy.hpp.
References yy_buffer_state::yy_buf_size, yy_buffer_state::yy_ch_buf, YY_FATAL_ERROR, yy_init_buffer(), yy_buffer_state::yy_is_our_buffer, and yyalloc().
Referenced by if(), and yyrestart().
void yy_delete_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
Destroy the buffer.
Parameters
b a buffer created with yy_create_buffer()
yyscanner The scanner object.
Definition at line 3836 of file equation.yy.hpp.
References yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_buffer_state::yy_is_our_buffer, and yyfree().
Referenced by yylex_destroy(), and yypop_buffer_state().
void yy_flush_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
Discard all buffered characters.
On the next scan, YY_INPUT will be called.
Parameters
b the buffer state to be flushed, usually YY_CURRENT_BUFFER.
yyscanner The scanner object.
Definition at line 3896 of file equation.yy.hpp.
References yy_buffer_state::yy_at_bol, yy_buffer_state::yy_buf_pos, YY_BUFFER_NEW, yy_buffer_state::yy_buffer_status, yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_END_OF_BUFFER_CHAR, yy_load_buffer_state(), and yy_buffer_state::yy_n_chars.
Referenced by yy_init_buffer().
void yypush_buffer_state (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
Pushes the new state onto the stack.
The new state becomes the current state. This function will allocate the stack if necessary.
Parameters
new_buffer The new state.
yyscanner The scanner object.
Definition at line 3931 of file equation.yy.hpp.
References yyguts_t::yy_buffer_stack_top, yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_did_buffer_switch_on_eof, yyguts_t::yy_hold_char, yy_load_buffer_state(), yyguts_t::yy_n_chars, and yyensure_buffer_stack().
void yypop_buffer_state (yyscan_t yyscanner)
Removes and deletes the top of the stack, if present.
The next element becomes the new top.
Parameters
yyscanner The scanner object.
Definition at line 3967 of file equation.yy.hpp.
References yyguts_t::yy_buffer_stack_top, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_delete_buffer(), yyguts_t::yy_did_buffer_switch_on_eof, and yy_load_buffer_state().
Referenced by yylex_destroy().
static void yyensure_buffer_stack (yyscan_t yyscanner) static
Definition at line 3993 of file equation.yy.hpp.
References yyguts_t::yy_buffer_stack, yyguts_t::yy_buffer_stack_max, yyguts_t::yy_buffer_stack_top, YY_FATAL_ERROR, yyalloc(), and yyrealloc().
Referenced by if(), yy_switch_to_buffer(), yypush_buffer_state(), and yyrestart().
static void yy_load_buffer_state (yyscan_t yyscanner) static
Definition at line 3788 of file equation.yy.hpp.
References yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_hold_char, yyguts_t::yy_n_chars, and yyin.
Referenced by if(), yy_flush_buffer(), yy_switch_to_buffer(), yypop_buffer_state(), yypush_buffer_state(), and yyrestart().
static void yy_init_buffer (YY_BUFFER_STATE b, FILE * file, yyscan_t yyscanner) static
Definition at line 3867 of file equation.yy.hpp.
References isatty(), yy_buffer_state::yy_bs_column, yy_buffer_state::yy_bs_lineno, YY_CURRENT_BUFFER, yy_buffer_state::yy_fill_buffer, yy_flush_buffer(), yy_buffer_state::yy_input_file, and yy_buffer_state::yy_is_interactive.
Referenced by yy_create_buffer(), and yyrestart().
YY_BUFFER_STATE yy_scan_buffer (char * base, yy_size_t size, yyscan_t yyscanner)
Setup the input buffer state to scan directly from a user-specified character buffer.
Parameters
base the character buffer
size the size in bytes of the character buffer
yyscanner The scanner object.
Returns
the newly allocated buffer state object.
Definition at line 4050 of file equation.yy.hpp.
References yy_buffer_state::yy_at_bol, yy_buffer_state::yy_buf_pos, yy_buffer_state::yy_buf_size, YY_BUFFER_NEW, yy_buffer_state::yy_buffer_status, yy_buffer_state::yy_ch_buf, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, yy_buffer_state::yy_fill_buffer, yy_buffer_state::yy_input_file, yy_buffer_state::yy_is_interactive, yy_buffer_state::yy_is_our_buffer, yy_buffer_state::yy_n_chars, yy_switch_to_buffer(), and yyalloc().
Referenced by yy_scan_bytes().
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr, yyscan_t yyscanner)
Setup the input buffer state to scan a string.
The next call to yylex() will scan from a copy of str.
Parameters
yystr a NUL-terminated string to scan
yyscanner The scanner object.
Returns
the newly allocated buffer state object.
Note
If you want to scan bytes that may contain NUL values, then use yy_scan_bytes() instead.
Definition at line 4091 of file equation.yy.hpp.
References yy_scan_bytes().
YY_BUFFER_STATE yy_scan_bytes (yyconst char * yybytes, int _yybytes_len, yyscan_t yyscanner)
Setup the input buffer state to scan the given bytes.
The next call to yylex() will scan from a copy of bytes.
Parameters
bytes the byte buffer to scan
len the number of bytes in the buffer pointed to by bytes.
yyscanner The scanner object.
Returns
the newly allocated buffer state object.
Definition at line 4103 of file equation.yy.hpp.
References YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, yy_buffer_state::yy_is_our_buffer, yy_scan_buffer(), and yyalloc().
Referenced by yy_scan_string().
void * yyalloc (yy_size_t size, yyscan_t yyscanner)
Definition at line 4505 of file equation.yy.hpp.
Referenced by yy_create_buffer(), yy_scan_buffer(), yy_scan_bytes(), yyensure_buffer_stack(), yylex_init(), and yylex_init_extra().
void * yyrealloc (void * ptr, yy_size_t size, yyscan_t yyscanner)
Definition at line 4510 of file equation.yy.hpp.
Referenced by yy_get_next_buffer(), and yyensure_buffer_stack().
void yyfree (void * ptr, yyscan_t yyscanner)
Definition at line 4522 of file equation.yy.hpp.
Referenced by yy_delete_buffer(), and yylex_destroy().
static yy_state_type yy_get_previous_state (yyscan_t yyscanner) static
Definition at line 3594 of file equation.yy.hpp.
References yy_accept, yyguts_t::yy_c_buf_p, yy_cp, yyguts_t::yy_last_accepting_cpos, yyguts_t::yy_last_accepting_state, YY_MORE_ADJ, yy_NUL_trans, yy_nxt, YY_SC_TO_UI, and yyguts_t::yy_start.
Referenced by while().
static yy_state_type yy_try_NUL_trans (yy_state_type current_state, yyscan_t yyscanner) static
Definition at line 3627 of file equation.yy.hpp.
References yy_accept, yyguts_t::yy_c_buf_p, yy_cp, yyguts_t::yy_last_accepting_cpos, yyguts_t::yy_last_accepting_state, and yy_NUL_trans.
Referenced by while().
static int yy_get_next_buffer (yyscan_t yyscanner) static
Definition at line 3444 of file equation.yy.hpp.
References EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, yy_buffer_state::yy_buf_size, YY_BUFFER_EOF_PENDING, yyguts_t::yy_c_buf_p, yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, YY_INPUT, yy_buffer_state::yy_is_our_buffer, YY_MORE_ADJ, yyguts_t::yy_n_chars, YY_READ_BUF_SIZE, yyin, yyrealloc(), and yyrestart().
Referenced by input(), and while().
static void yy_fatal_error (yyconst char msg[], yyscan_t yyscanner) static
Referenced by yyset_column(), and yyset_lineno().
static int yy_init_globals (yyscan_t yyscanner) static
Definition at line 4410 of file equation.yy.hpp.
References yyguts_t::yy_buffer_stack, yyguts_t::yy_buffer_stack_max, yyguts_t::yy_buffer_stack_top, yyguts_t::yy_c_buf_p, yyguts_t::yy_init, yyguts_t::yy_start, yyguts_t::yy_start_stack, yyguts_t::yy_start_stack_depth, yyguts_t::yy_start_stack_ptr, yyin, and yyout.
Referenced by yylex_destroy(), yylex_init(), and yylex_init_extra().
int yylex_init (yyscan_t * scanner)
Definition at line 4351 of file equation.yy.hpp.
References yy_init_globals(), and yyalloc().
Referenced by px::eq::CEquation::parse().
int yylex_init_extra (YY_EXTRA_TYPE user_defined, yyscan_t * scanner)
Definition at line 4381 of file equation.yy.hpp.
References yy_init_globals(), yyalloc(), and yyset_extra().
int yylex_destroy (yyscan_t yyscanner)
Definition at line 4445 of file equation.yy.hpp.
References yyguts_t::yy_buffer_stack, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_delete_buffer(), yy_init_globals(), yyguts_t::yy_start_stack, yyfree(), and yypop_buffer_state().
Referenced by px::eq::CEquation::parse().
int yyget_debug (yyscan_t yyscanner)
Definition at line 4314 of file equation.yy.hpp.
References yy_flex_debug.
void yyset_debug (int debug_flag, yyscan_t yyscanner)
Definition at line 4321 of file equation.yy.hpp.
References yy_flex_debug.
YY_EXTRA_TYPE yyget_extra (yyscan_t yyscanner)
Get the user-defined data for this scanner.
Parameters
yyscanner The scanner object.
Definition at line 4171 of file equation.yy.hpp.
References yyextra.
void yyset_extra (YY_EXTRA_TYPE user_defined, yyscan_t yyscanner)
Set the user-defined data.
This data is never touched by the scanner.
Parameters
user_defined The data to be associated with this scanner.
yyscanner The scanner object.
Definition at line 4253 of file equation.yy.hpp.
References yyextra.
Referenced by yylex_init_extra().
FILE * yyget_in (yyscan_t yyscanner)
Get the input stream.
Parameters
yyscanner The scanner object.
Definition at line 4211 of file equation.yy.hpp.
References yyin.
void yyset_in (FILE * in_str, yyscan_t yyscanner)
Set the input stream.
This does not discard the current input buffer.
Parameters
in_str A readable stream.
yyscanner The scanner object.
See Also
yy_switch_to_buffer
Definition at line 4300 of file equation.yy.hpp.
References yyin.
FILE * yyget_out (yyscan_t yyscanner)
Get the output stream.
Parameters
yyscanner The scanner object.
Definition at line 4221 of file equation.yy.hpp.
References yyout.
void yyset_out (FILE * out_str, yyscan_t yyscanner)
Definition at line 4307 of file equation.yy.hpp.
References yyout.
int yyget_leng (yyscan_t yyscanner)
Get the length of the current token.
Parameters
yyscanner The scanner object.
Definition at line 4231 of file equation.yy.hpp.
References yyleng.
char * yyget_text (yyscan_t yyscanner)
Get the current token.
Parameters
yyscanner The scanner object.
Definition at line 4242 of file equation.yy.hpp.
References yytext.
int yyget_lineno (yyscan_t yyscanner)
Get the current line number.
Parameters
yyscanner The scanner object.
Definition at line 4181 of file equation.yy.hpp.
References YY_CURRENT_BUFFER, and yylineno.
void yyset_lineno (int line_number, yyscan_t yyscanner)
Set the current line number.
Parameters
line_number
yyscanner The scanner object.
Definition at line 4264 of file equation.yy.hpp.
References YY_CURRENT_BUFFER, yy_fatal_error(), and yylineno.
int yyget_column (yyscan_t yyscanner)
Get the current column number.
Parameters
yyscanner The scanner object.
Definition at line 4196 of file equation.yy.hpp.
References YY_CURRENT_BUFFER, and yycolumn.
void yyset_column (int column_no, yyscan_t yyscanner)
Set the current column.
Parameters
line_number
yyscanner The scanner object.
Definition at line 4281 of file equation.yy.hpp.
References YY_CURRENT_BUFFER, yy_fatal_error(), and yycolumn.
YYSTYPE * yyget_lval (yyscan_t yyscanner)
Definition at line 4330 of file equation.yy.hpp.
References yylval.
void yyset_lval (YYSTYPE * yylval_param, yyscan_t yyscanner)
Definition at line 4337 of file equation.yy.hpp.
References yylval.
static int input (yyscan_t yyscanner) static
Definition at line 3652 of file equation.yy.hpp.
References EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, px::eq::detail::return(), yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_did_buffer_switch_on_eof, YY_END_OF_BUFFER_CHAR, yy_get_next_buffer(), yyguts_t::yy_hold_char, yyguts_t::yy_n_chars, YY_NEW_FILE, yyin, yyrestart(), and yywrap.
int yylex (YYSTYPE * yylval_param, yyscan_t yyscanner)
if (!yyg-> yy_init)
Definition at line 3007 of file equation.yy.hpp.
References YY_BUF_SIZE, yy_create_buffer(), YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_init, yy_load_buffer_state(), yyguts_t::yy_start, yyensure_buffer_stack(), yyin, and yyout.
while (1)
Definition at line 3039 of file equation.yy.hpp.
References EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, INITIAL, T_ABS, T_AND, T_AVG, T_CEIL, T_ELSE, T_EQ, T_EXP, T_FLOAT, T_FLOOR, T_GE, T_IDENTIFIER, T_IF, T_ISINF, T_ISNAN, T_LE, T_LSHIFT, T_MAX, T_MIN, T_NE, T_OR, T_ROUND, T_RSHIFT, T_SQRT, T_STRING_CONSTANT, T_SUM, T_TRUNC, T_WHILE, yy_accept, YY_BREAK, YY_BUFFER_NEW, YY_BUFFER_NORMAL, yyguts_t::yy_c_buf_p, yy_cp, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_did_buffer_switch_on_eof, YY_DO_BEFORE_ACTION, YY_END_OF_BUFFER, YY_FATAL_ERROR, yy_get_next_buffer(), yy_get_previous_state(), yyguts_t::yy_hold_char, yyguts_t::yy_last_accepting_cpos, yyguts_t::yy_last_accepting_state, YY_MORE_ADJ, yyguts_t::yy_n_chars, YY_NEW_FILE, yy_nxt, YY_RESTORE_YY_MORE_OFFSET, YY_RULE_SETUP, YY_SC_TO_UI, YY_START, yyguts_t::yy_start, YY_STATE_EOF, yy_try_NUL_trans(), yyin, yylval, yyterminate, yytext, and yywrap.
int isatty (int)
Referenced by yy_init_buffer().
static void yy_fatal_error (yyconst char * msg, yyscan_t yyscanner) static
Definition at line 4143 of file equation.yy.hpp.
References YY_EXIT_FAILURE.
Variable Documentation
yyconst flex_int16_t yy_nxt[][128] static
Definition at line 345 of file equation.yy.hpp.
Referenced by while(), and yy_get_previous_state().
yyconst flex_int16_t yy_accept[136] static
Initial value:
=
{   0,
        0,    0,   35,   33,    1,   33,   32,    1,    1,    1,
        29,   29,    1,    1,    1,   32,   32,   32,   32,   32,
        32,   32,   32,   32,   32,   32,   32,   32,    1,    9,
        0,   30,    0,   32,    4,    0,   29,    0,    3,    7,
        8,    6,    2,   32,   32,   32,   32,   32,   32,   32,
        11,   32,   32,    0,   32,   32,   32,   32,   32,   32,
        32,   32,   32,    0,    0,   32,    0,    5,    0,   28,
        18,   16,   32,   32,   23,   32,   32,   29,   32,   32,
        15,   32,   14,   32,   32,   17,   32,   32,    0,    0,
        0,    0,   29,   28,   21,   12,   32,   32,   32,   32,
        32,   13,   26,   32,   32,    0,   31,   28,   27,   22,
        25,   24,   19,   20,   10,    0,    0,   28,    0,    0,
        0,   28,    0,    0,    0,    0,   31,   28,    0,   31,
        0,   28,    0,    0,   28
}
Definition at line 2714 of file equation.yy.hpp.
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
yyconst yy_state_type yy_NUL_trans[136] static
Initial value:
=
{   0,
        4,    4,    0,    0,    0,   31,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        31,    0,   31,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   31,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0
}
Definition at line 2733 of file equation.yy.hpp.
Referenced by yy_get_previous_state(), and yy_try_NUL_trans().
YY_DECL
Initial value:
{
        register yy_state_type yy_current_state
The main scanner function which does all the work.
Definition at line 2993 of file equation.yy.hpp.
register char* yy_cp
Definition at line 2995 of file equation.yy.hpp.
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
register char * yy_bp
Definition at line 2995 of file equation.yy.hpp.
register int yy_act
Definition at line 2996 of file equation.yy.hpp.
struct yyguts_t* yyg = (struct yyguts_t *)yyscanner
Definition at line 2997 of file equation.yy.hpp.
yylval = yylval_param
Definition at line 3005 of file equation.yy.hpp.