libpx: px::asio::CIoManager Class Reference
px::asio::CIoManager Class Reference
ASIO interface details and general IO functions.
The main I/O manager to host the Power Xpert Toolkit's ASIO framework.
#include <io_manager.hpp>
Public Member Functions
PUBLIC CIoManager (CServerCore &core, CCdsHandler &cds, uint32_t watchdog_timeout=0)
Constructor for the IO Manager.
PUBLIC ~CIoManager ()
Destructor.
PUBLIC void run ()
Run the main I/O service.
PUBLIC void add (const std::shared_ptr< CIoActor > &actor)
Add an I/O actor to be tracked and managed.
PUBLIC void quit ()
Close all actors and exit the main loop.
PUBLIC px::string app_name () const
Get the application's name that was given to us.
PUBLIC CServerCore & get_Server () const
Get a reference to the "core" actor that we were created with.
PUBLIC void install_temporary_signal_handlers ()
Register "temporary" signal handlers to catch signals in the startup phase before the run() function is called.
PUBLIC bool is_stopped ()
Determine whether this manager has been stopped.
PUBLIC bool is_quit_signal_received ()
Determine whether this manager has received quit signal.
Public Attributes
bool quit_signal
A flag to indicate not quit/exit - stop processing read requests.
Private Types
typedef std::unordered_set
< std::shared_ptr< CIoActor > > actor_set_t
A collection of actors.
Private Member Functions
void close (const std::shared_ptr< CIoActor > &actor)
Close a single actor and remove it from management.
Private Attributes
std::unique_ptr
< boost::asio::io_service > _service
The underlying Boost.Asio I/O service object.
actor_set_t _actors
The set of all I/O actors "owned" by this manager.
std::shared_ptr< CIoSighandler > sig_handler
The ASIO Actor which handles signals.
CServerCore & _core
Handle to the server core.
CCdsHandler & _cds
Handle to the cds handler.
px::string _app_name
Name of the application.
Detailed Description
The main I/O manager to host the Power Xpert Toolkit's ASIO framework.
This class manages all server events from one central location, performing asynchronous I/O operations to multiplex data transfers. It handles each of the following (and potentially more in the future) in a central, consistent manner:
New connections (FastCGI)
New connections (WebSocket)
New connections (TCP)
Incoming connection data (TCP)
Connection errors / closure (TCP)
Incoming FastCGI
FastCGI errors
Incoming serial data
Serial port errors
Signals
Timer expiration
Definition at line 42 of file io_manager.hpp.
Member Typedef Documentation
typedef std::unordered_set<std::shared_ptr<CIoActor> > px::asio::CIoManager::actor_set_t private
A collection of actors.
The I/O manager doesn't truly "own" the actors, per-se, but it holds a shared ptr to each of them which guarantees that they'll continue to exist until it no longer cares about them.
Definition at line 174 of file io_manager.hpp.
Constructor & Destructor Documentation
px::asio::CIoManager::CIoManager (CServerCore & core, CCdsHandler & cds, uint32_t watchdog_timeout = 0)
Constructor for the IO Manager.
This constructor also instantiates these framework Actors:
CIoSighandler
CWatchdogTimer
CCdsConnection Note that these ASIO actors will not operate until this manager class is "running".
Parameters
core The server core object that owns this I/O manager. This will be a class derived from CServerCore.
cds The Actor which manages the CDS activity. This will be a class derived from CCdsHandler.
watchdog_timeout If provided, the timeout (in msec) this framework will use to ping the CDS periodically (at half the given time period).
app_name The text name of the application (for debugging messages).
Exceptions
generic_err The manager could not be initialized
Definition at line 17 of file io_manager.cpp.
References _service, add(), px::asio::CWatchdogTimer::create(), px::asio::CCdsConnection::create(), px::asio::CIoSighandler::create(), px::asio::CCdsHandler::is_mock(), LIBPX_ERR, LIBPX_FERR, LIBPX_INFO, quit_signal, and sig_handler.
px::asio::CIoManager::~CIoManager ()
Destructor.
Definition at line 82 of file io_manager.cpp.
References sig_handler.
Member Function Documentation
void px::asio::CIoManager::run ()
Run the main I/O service.
This call blocks while there is any remaining work to be done, i.e. until a bad error occurs or a signal is received which instructs the server to exit.
Exceptions
boost::system::system_error An error has occurred
Definition at line 91 of file io_manager.cpp.
References _actors, _service, LIBPX_ERR, LIBPX_FERR, sig_handler, and px::generic_err::what().
void px::asio::CIoManager::add (const std::shared_ptr< CIoActor > & actor)
Add an I/O actor to be tracked and managed.
Parameters
actor The new actor to be managed / owned by this manager
Definition at line 134 of file io_manager.cpp.
References _actors.
Referenced by CIoManager(), px::asio::CUdsListener::handle_accept(), px::asio::CTcpListener::handle_accept(), and px::asio::CTcpListener::handle_ssl_accept().
void px::asio::CIoManager::quit ()
Close all actors and exit the main loop.
This call is invoked (in the common case) in response to an incoming signal to shut down the server. Since the original caller is blocked in run(), it will stop the I/O service and cause run() to return to the caller.
Definition at line 150 of file io_manager.cpp.
References _actors, _service, LIBPX_ERR, LIBPX_FDEBUG, LIBPX_FERR, LIBPX_INFO, LIBPX_NOTICE, and quit_signal.
Referenced by px::asio::CIoSighandler::handle_signal().
px::string px::asio::CIoManager::app_name () const
Get the application's name that was given to us.
Returns
String with the application name (empty if none was provided).
Definition at line 240 of file io_manager.cpp.
References _app_name.
CServerCore & px::asio::CIoManager::get_Server () const
Get a reference to the "core" actor that we were created with.
Returns
A reference to the CServerCore instance that we are managing.
Definition at line 245 of file io_manager.cpp.
References _core.
void px::asio::CIoManager::install_temporary_signal_handlers ()
Register "temporary" signal handlers to catch signals in the startup phase before the run() function is called.
These are in addition to the main signal handlers registered by CIoSighandler. This is optional, but useful if the startup takes a long time to complete, eg because it is discovering devices and channels. If used, these temporary handlers will be removed automatically when run() is called.
Definition at line 259 of file io_manager.cpp.
References sig_handler.
bool px::asio::CIoManager::is_stopped ()
Determine whether this manager has been stopped.
Ie, has it received a signal that caused it to quit().
Returns
True if the manager has been stopped; False if still operating normally.
Definition at line 250 of file io_manager.cpp.
References _actors.
PUBLIC bool px::asio::CIoManager::is_quit_signal_received ()
Determine whether this manager has received quit signal.
Ie, has it received a signal that caused it to quit().
Returns
True if the manager has been stopped; False if still operating normally.
Definition at line 146 of file io_manager.hpp.
Referenced by px::asio::CIoActor::get_quit_status(), px::asio::CIoSighandler::handle_signal(), px::asio::CTcpConnection::read_more(), px::asio::CTcpSslConnection::read_more(), px::asio::CTcpConnection::write_more(), and px::asio::CTcpSslConnection::write_more().
void px::asio::CIoManager::close (const std::shared_ptr< CIoActor > & actor) private
Close a single actor and remove it from management.
This call is invoked by an actor if/when it needs to be removed from the manager's internal list. A common example of this is when a TCP client disconnects.
Parameters
actor The I/O actor which is to be closed/removed
Definition at line 211 of file io_manager.cpp.
References _actors, LIBPX_ERR, and LIBPX_FERR.
Referenced by px::asio::CIoActor::remove().
Member Data Documentation
bool px::asio::CIoManager::quit_signal
A flag to indicate not quit/exit - stop processing read requests.
Definition at line 158 of file io_manager.hpp.
Referenced by CIoManager(), and quit().
std::unique_ptr<boost::asio::io_service> px::asio::CIoManager::_service private
The underlying Boost.Asio I/O service object.
Definition at line 200 of file io_manager.hpp.
Referenced by CIoManager(), px::asio::CIoActor::get_io_service(), quit(), and run().
actor_set_t px::asio::CIoManager::_actors private
The set of all I/O actors "owned" by this manager.
Definition at line 205 of file io_manager.hpp.
Referenced by add(), close(), is_stopped(), quit(), and run().
std::shared_ptr<CIoSighandler> px::asio::CIoManager::sig_handler private
The ASIO Actor which handles signals.
Definition at line 210 of file io_manager.hpp.
Referenced by CIoManager(), install_temporary_signal_handlers(), run(), and ~CIoManager().
CServerCore& px::asio::CIoManager::_core private
Handle to the server core.
Definition at line 215 of file io_manager.hpp.
Referenced by get_Server(), and px::asio::CIoActor::get_server_core().
CCdsHandler& px::asio::CIoManager::_cds private
Handle to the cds handler.
Definition at line 220 of file io_manager.hpp.
Referenced by px::asio::CIoActor::get_cds_handler().
px::string px::asio::CIoManager::_app_name private
Name of the application.
Definition at line 225 of file io_manager.hpp.
Referenced by app_name().
The documentation for this class was generated from the following files:
io_manager.hpp
io_manager.cpp