libpx: px::asio::CCdsDevice Class Reference
px::asio::CCdsDevice Class Reference
This class define a container for Device data from the CDS.
#include <cds_device.hpp>
Public Member Functions
PUBLIC CCdsDevice (const px::CDevice &px_device)
Ctor starting with the px::CDevice data for this instance.
PUBLIC CCdsDevice ()
Default, empty constructor.
virtual PUBLIC ~CCdsDevice ()
Default xtor.
PUBLIC bool is_valid_device () const
Is the Device held by this container valid - enabled and communicating?
Public Attributes
px::CDevice _px_device
A local copy of the latest px::CDevice data.
bool _channel_values_received
Flag that indicates when all of channel values for this device have been added to the CdsHandler's map of Channel values.
bool _channel_values_subscribed
Flag to note when we have subscribed to the Channel Values for this Device.
size_t _channel_settings_count
If the Channel Settings data is requested, then this keeps track of how many Channels were included in the response.
Detailed Description
This class define a container for Device data from the CDS.
It goes beyond the px::CDevice to include state and channel information. It can also be checked during device subscription updates to see if it (or its children) have been changed and must be refreshed.
This container will be used in the CDS Device Map provided and maintained by CCdsHandler.
Definition at line 24 of file cds_device.hpp.
Constructor & Destructor Documentation
px::asio::CCdsDevice::CCdsDevice (const px::CDevice & px_device)
Ctor starting with the px::CDevice data for this instance.
Parameters
px_device The px::CDevice data for this instance, which will be copied into the local storage.
Definition at line 13 of file cds_device.cpp.
px::asio::CCdsDevice::CCdsDevice ()
Default, empty constructor.
Definition at line 21 of file cds_device.cpp.
px::asio::CCdsDevice::~CCdsDevice () virtual
Default xtor.
Definition at line 27 of file cds_device.cpp.
Member Function Documentation
bool px::asio::CCdsDevice::is_valid_device () const
Is the Device held by this container valid - enabled and communicating?
Returns
True if valid (enabled and communicating), else False
Definition at line 33 of file cds_device.cpp.
References _px_device, px::disabled, px::CBitset< T >::get(), px::CDevice::get_state(), px::CDevice::id(), px::not_communicating, and PX_ID_UNSET.
Referenced by px::asio::CCdsHandler::process_device_data().
Member Data Documentation
px::CDevice px::asio::CCdsDevice::_px_device
A local copy of the latest px::CDevice data.
This is one of the more important members of this class to be maintained. Note that it is not const; ie, it can be updated.
Definition at line 54 of file cds_device.hpp.
Referenced by is_valid_device(), px::asio::CCdsHandler::process_device_data(), and px::asio::CCdsHandler::process_subscription_update().
bool px::asio::CCdsDevice::_channel_values_received
Flag that indicates when all of channel values for this device have been added to the CdsHandler's map of Channel values.
If this flag is later cleared, they will be re-requested as a refresh maneuver.
Definition at line 60 of file cds_device.hpp.
Referenced by px::asio::CCdsHandler::process_device_data().
bool px::asio::CCdsDevice::_channel_values_subscribed
Flag to note when we have subscribed to the Channel Values for this Device.
There may be an initial delay but we want to be sure to do this later.
Definition at line 65 of file cds_device.hpp.
Referenced by px::asio::CCdsHandler::process_device_data(), and px::asio::CCdsHandler::process_subscription_update().
size_t px::asio::CCdsDevice::_channel_settings_count
If the Channel Settings data is requested, then this keeps track of how many Channels were included in the response.
So if this disagrees later with the device's channel count, because one or more channels were added later, they can be re-requested.
Definition at line 72 of file cds_device.hpp.
Referenced by px::asio::CCdsHandler::process_device_data().
The documentation for this class was generated from the following files:
cds_device.hpp
cds_device.cpp