libpx: px::asio::CCdsHandler Class Reference
px::asio::CCdsHandler Class Reference abstract
ABC for CDS Handler, provides a common synchronous/asynchronous interface to the CDS API.
#include <cds_handler.hpp>
Classes
struct ch_val_s
Define the structure to store each channel's Value, timestamp, etc (Currently there is no "etc" but maybe will add "is_subscribed" flag, etc)
struct queued_req_s
Define the structure for the queued and waiting-for-response requests Used in the _reqst_queue deque and _awaiting_resps map.
Public Types
enum queued_req_type {
RQST_GET_DEVICE = 0, RQST_GET_CHANNEL_VALUES, RQST_GET_CHANNEL_SETTINGS, RQST_SUBSCRIBE_CHANNEL_VALUES,
RQST_MAX
}
A set of Enums for the types of queued requests handled internally by this class.
typedef std::function< void(const
CCdsDevice &)> cds_device_callback_t
Define the function object type to handle CCdsDevice additions or updates from the CDS.
typedef std::function< void(px::id_t)> device_delete_callback_t
Define the function object type to handle CCdsDevice deletions from the CDS.
typedef std::function< void(const
px::CAlarmUpdate &)> cds_alarm_callback_t
Define the function object type to handle px::CAlarmUpdate updates from the CDS.
typedef std::function< void(const
CCdsDevice &, const
std::vector
< px::CChannelSettings > &)> cds_ch_settings_callback_t
Define the function object type to handle px::CGetChannelSettings responses from the CDS.
typedef std::function< void(const
std::map< px::id_t, px::CValue >
&, const px::CWallTime &)> cds_ch_values_callback_t
Define the function object type to handle channel value change notifications from the CDS.
typedef struct
px::asio::CCdsHandler::ch_val_s channel_value_t
Define the structure to store each channel's Value, timestamp, etc (Currently there is no "etc" but maybe will add "is_subscribed" flag, etc)
typedef std::map< px::id_t,
channel_value_t > channel_value_map_t
Define the map for Channel Values, keyed by CDS ID.
typedef struct queued_req_s queued_req_t
Public Member Functions
PUBLIC CCdsHandler (const px::string &app_name, uint32_t wait_secs=60, uint32_t request_queue_size=4194304, uint32_t response_queue_size=4194304, const bool enable_data_validation=true)
Constructor.
virtual PUBLIC ~CCdsHandler ()
Default destructor, a virtual.
PUBLIC void connect_to_cds (const px::string &app_name, uint32_t wait_secs=60, uint32_t request_queue_size=4194304, uint32_t response_queue_size=4194304)
Open the connection to the CDS (if not already open).
virtual PUBLIC void handle_response (std::shared_ptr< px::cds::CRequestResponse > resp)=0
Called by the ASIO io_service when one or more (normally expected) responses or subscription updates are sent from the CDS.
virtual PUBLIC std::shared_ptr
< px::cds::CRequestResponse > submit_wait (px::cds::CRequestResponse &req) const
Submit a request for CDS processing, waiting for the response and returning it.
virtual PUBLIC void submit_forget (px::cds::CRequestResponse &req, bool sleep_on_full=false)
Submit a request for CDS processing fire and forget style.
virtual PUBLIC uint32_t submit (px::cds::CRequestResponse &req, bool sleep_on_full=false)
Submit a request for CDS processing.
PUBLIC void ping_watchdog ()
Watchdog Related Asynchronous Member Functions.
PUBLIC void set_oob (const px::string &tag, const px::proto::toolkitStruct &data, bool persist=false)
OOB Related Member Functions.
PUBLIC bool get_channel_value (px::id_t channel_id, px::CValue &value)
Channel Related Asynchronous Member Functions.
PUBLIC bool get_channel_value (px::id_t channel_id, px::CValue &value, CWallTime &timestamp)
Get the current Value of a Channel based based on a specified timestamp.
PUBLIC std::map< px::string,
px::CChannelSettings > list_channel_settings (px::id_t dev_id)
Retrieve a map of MCL Channel canonical names to their Channel settings.
PUBLIC void set_channel_value (px::id_t channel_id, const px::CValue &value)
Utility function to set the current Value of a Channel into the CDS.
PUBLIC px::CDevice get_device (px::id_t dev_id)
Device Related Asynchronous Member Functions.
PUBLIC bool is_mock ()
Subscription Related Asynchronous Member Functions.
PUBLIC void set_to_reflexive ()
Simple setter to force all subscriptions entered by the CDS Handler to be reflexive.
PUBLIC void init_device_map (const cds_device_callback_t &add_device_callback, const cds_device_callback_t &update_device_callback, const device_delete_callback_t &delete_device_callback, const cds_device_callback_t &device_state_callback, bool want_channels, const cds_ch_settings_callback_t &channel_settings_callback=cds_ch_settings_callback_t())
Member Functions that manage the maps of Devices and Channels, and Alarm handling.
PUBLIC void closeout_device_map ()
Undo the features that we enabled to populate the device map: unsubscribe callbacks, clear the map.
PUBLIC void do_static_discovery (px::id_t starting_dev_id=PX_ID_ROOT)
Perform a static discovery of all device data starting at the given ID.
bool check_request_queue ()
See if there is an entry available in our queue of message requests, and, if so, send the request for its CDS data.
PUBLIC void set_override_pacing (unsigned long int override)
This overrides static discovery pacing.
PUBLIC void subscribe_device_callbacks ()
Enter CDS subscriptions for Device CrUD events to maintain the device map.
PUBLIC bool init_channel_values_callback (const cds_ch_values_callback_t &update_channel_values_callback)
Function to initialize the optional callback for channel value updates.
PUBLIC bool get_map_device (px::id_t dev_id, cds_device_map_citer_t &map_pos) const
Getter for a CCdsDevice instance in our map, looked up by its Device ID.
PUBLIC bool is_communicating_device (px::id_t dev_id) const
Checks if we have the requested Device instance in our map, and if its state is enabled and communicating, so that its Channel data will be valid.
PUBLIC void init_alarm_callback (const cds_alarm_callback_t &update_alarm_callback)
Function to initialize Alarm update callbacks.
PUBLIC void do_alarm_discovery (uint64_t starting_global_count=0)
Perform a static discovery of all alarm updates starting at the given sequence ID.
PUBLIC void subscribe_alarm_callback ()
Enter CDS subscriptions for Alarm events.
PUBLIC void internal_handle_response (std::shared_ptr< px::cds::CRequestResponse > resp)
Called by the CDS when one or more unsolicited, subscription update, or solicited responses are ready for the internal handling by this class, eg, for maintaining the device map.
PUBLIC void cds_login ()
Do a CDS Client Login (no username or password) to get a session token and permissions.
PUBLIC const px::string & get_session_token ()
Getter for our session token.
PUBLIC bool check_permission (px::permissions test_perm)
Test to see if we have a given permission (privilege), checking against the privileges for this CDS client.
PUBLIC unsigned int get_submit_wait_count ()
Getter for the up-counter for each call to submit_wait().
Public Member Functions inherited from px::asio::CCdsSyncIO
PUBLIC CCdsSyncIO (const bool enable_data_validation=true)
Constructor.
virtual PUBLIC ~CCdsSyncIO ()
Default destructor.
PUBLIC void check_cds_result (const std::shared_ptr< px::cds::CRequestResponse > cds_resp, const char *req_name) const
Utility function to check if we got a response, and that the returned CDS Results status is Success.
PUBLIC int cds_login (const px::string &service, px::string &session_token, px::CBitset< px::permissions > &perms)
Do a CDS Client Login (no username or password) to get a session token and permissions.
PUBLIC void ping_watchdog_s ()
Watchdog Related Member Functions.
PUBLIC void register_watchdog (uint32_t timeout, bool auto_clear_on_close=true)
Utility function to register the CDS watchdog timer.
PUBLIC void clear_watchdog ()
Utility function to clear the CDS watchdog timer.
PUBLIC bool get_oob (const px::string &tag, px::proto::toolkitStruct &data)
OOB Related Member Functions.
PUBLIC std::pair< px::CValue,
bool > get_oob_field (const px::string &tag_name, const px::string &field_name) const
Convenience method for synchronous CDS request to get one OOB field value.
PUBLIC std::vector< px::string > get_oob_tags (const px::string &tag_hint)
Get the list of OOB tags, given a starting hint (which can be empty to get all).
PUBLIC void set_oob_s (const px::string &tag, const px::proto::toolkitStruct &data, bool persist=false)
Synchronous non-ASIO version of CDS Set OOB, with fire-and-forget submission to the CDS.
PUBLIC bool set_oob_wait (const px::string &tag, const px::proto::toolkitStruct &data, bool persist=false)
Synchronous non-ASIO version of CDS Set OOB, which waits for the CDS response to the set.
PUBLIC int set_oob_field (::cds::field_t &field)
Convenience method for synchronous CDS request to set one OOB field value.
PUBLIC void clear_oob (const px::string &tag)
Utility function to delete an OOB object from the CDS.
PUBLIC px::id_t create_channel (const px::id_t dev_id, const px::string &canonical_name, const bool is_custom=false)
Channel Related Member Functions.
PUBLIC int delete_channel (const px::id_t ch_id)
Utility function to delete a channel in the CDS.
PUBLIC int delete_channels (const std::vector< px::id_t > ch_ids)
Utility function to delete one or more channels in the CDS.
PUBLIC px::CChannel get_channel (const px::id_t chan_id)
Retrieve a single channel by its channel id.
PUBLIC std::vector
< px::cds::CGetSingleChannel > get_channels (const px::id_t dev_id)
Get a list of Channel(s) for a given device.
PUBLIC std::vector
< px::cds::CGetSingleChannel > get_channels_by_name (px::id_t dev_id, const std::vector< px::string > &canonical_names)
Get a list of Channel(s) for a given device, looked up by their MCL canonical name(s).
PUBLIC std::shared_ptr
< px::cds::CGetChannelSettings > get_channel_settings (const px::id_t dev_id)
Utility function to get all Channel Settings for a device in the CDS.
PUBLIC bool get_data_validation ()
Utility function to check if CDS data validation is enabled or disabled.
PUBLIC void set_data_validation (const bool validate)
Utility function to enable/disable CDS data validation in member functions that set channel values.
PUBLIC void set_channel_value_s (const px::id_t channel_id, const px::CValue &value)
Synchronous non-ASIO version of CDS Set Channel Value.
PUBLIC void set_channel_values (const std::vector< px::cds::CUpdateSingleChannelValue > &values)
Utility function to set the current Values of multiple Channels into the CDS.
PUBLIC px::CDevice create_device (const bool use_given_id, const px::CDevice &device)
Device Related Member Functions.
PUBLIC std::vector< px::CDevice > create_devices (const bool use_given_ids, const std::vector< px::CDevice > &devices)
Utility function to create single or multiple devices in the CDS.
PUBLIC void delete_device (const px::id_t delete_id)
Delete the provided device ID from the CDS.
PUBLIC void delete_devices (const std::vector< px::id_t > &delete_ids)
Delete the provided device IDs from the CDS.
PUBLIC px::CDevice get_device_s (const px::id_t dev_id)
Synchronous non-ASIO version of CDS Get Device.
PUBLIC std::map< px::id_t,
px::CDevice > get_devices (const px::id_t starting_dev_id=PX_ID_ROOT)
Utility function to retrieve a map of a device and child devices.
PUBLIC std::vector
< px::CChannelTrends > get_device_trend_row (px::id_t dev_id, unsigned int interval_minutes=5, px::CWallTime start_time=px::CWallTime(), bool recursive=false)
ToDo: setup means to always have the latest trend data at hand.
PUBLIC int set_device_guid (const px::string &name_str, px::CDevice &px_device, bool is_direct=false, bool do_forget=false)
Set Device GUID in the given CDevice instance and in the CDS.
PUBLIC int set_device_guid (const px::string &name_str, px::id_t dev_id)
Set Device GUID in the given CDevice instance and in the CDS, generating the UUID from the given seed text.
PUBLIC void set_device_state (const std::vector< px::cds::CSetSingleDeviceState > &dev_states)
State Related Member Functions.
PUBLIC void set_channel_state (const std::vector< px::cds::CSetSingleChannelState > &chan_states)
Utility function to set the channel state for one or more channels.
PUBLIC void enable_device (const px::id_t dev_id, const bool is_enabled)
Utility function to enable/disable a device.
PUBLIC void enable_device (px::CDevice &device, const bool is_enabled)
Utility function to enable/disable a device, and update the realtime state of the passed in px::CDevice object.
PUBLIC void set_device_communicating (const px::id_t dev_id, const bool is_communicating)
Utility function to set the communicating state of a device.
PUBLIC void set_device_communicating (px::CDevice &device, const bool is_communicating)
Utility function to set the communicating state of a device, and update the realtime state of the passed in px::CDevice object.
PUBLIC void set_channel_communicating (const px::id_t chan_id, const bool is_communicating)
Utility function to set the communicating state of a channel.
PUBLIC::cds::field_t get_field (const ::cds::field_t &field) const
Field Related Member Functions.
PUBLIC int set_field (::cds::field_t &field)
Convenience method for synchronous CDS request to set one field value.
PUBLIC uint64_t subscribe_by_id (uint64_t sub_id, px::sub::subscription_type sub_type, px::id_t item_id, bool is_recursive_device=false, bool is_reflexive=false, std::string library_name="")
Subscription Related Member Functions.
PUBLIC bool unsubscribe_id (uint64_t sub_id, px::sub::subscription_type sub_type, px::id_t item_id, std::string library_name="")
Unsubscribe the given Device or Channel from the given subscription (by ID and type).
PUBLIC uint64_t subscribe_oob (uint64_t sub_id, px::string oob_tag, bool is_reflexive=false, bool is_tag_partial=false)
Create or update a subscription for the OOB with the given tag (name).
PUBLIC bool unsubscribe_oob (uint64_t sub_id, px::string oob_tag, bool is_tag_partial=false)
Unsubscribe the given OOB from the given subscription (by ID).
PUBLIC std::vector< uint64_t > get_subscriber_ids (size_t count, bool reflexive=false)
Use CManageSubscriberIDs to request new subscriber ID(s) for our use.
Public Attributes
px::cds::CallbackHandle handle
Callback handle for solicited responses to cds requests.
std::shared_ptr
< CCdsHandlerCallback > _internal_callback
A callback handler for our internal_handle_response().
Protected Member Functions
PUBLIC CCdsHandler (bool is_mock=true)
Non-normal Constructor, only useful for non-CDS test.
bool process_device_data (const px::CDevice &px_device)
The recursive function to check this device's data and see if we need to add or update the Device data, or its channels, or (recursively) its child devices.
bool process_channel_value (px::id_t ch_id, const px::CValue &value, const CWallTime &timestamp)
Given the Value for a Channel (from GetValue request or subscription update), save it to our map of channel values.
bool process_response_type (queued_req_type exp_req_type, std::shared_ptr< px::cds::CRequestResponse > resp)
(Attempt to) Process a CDS response of the given request type.
void process_subscription_update (std::shared_ptr< px::cds::CSubscriberNotify > update)
Given a subscribed update event, process its contents.
bool add_msg_to_rqst_queue (queued_req_type msg_type, px::id_t dev_id)
Add the given message type and Device ID to our queue of messages to be processed, unless it is already in that queue.
bool check_awaiting_timeouts ()
Check the expected responses to see if we are past the time when an async response can be expected to arrive for any; in that case, clear that entry but move it back to the end of the request queue.
bool lookup_map_device (px::id_t dev_id, cds_device_map_iter_t &map_pos)
Getter for a mutable CCdsDevice instance in our map, looked up by its Device ID.
virtual bool ok_to_proceed ()
Function for the implementation to signal to internal processing of this class' members that they should stop.
Protected Member Functions inherited from px::asio::CCdsSyncIO
std::vector< px::CChannelSettings > get_channel_by_group (const std::vector< px::id_t > &get_ids, unsigned int offset, const unsigned int &limit)
The function is used to get the channel settings for a subset of the provided ids It groups the required channels and sends request to CDS.
Protected Attributes
bool _is_mock
Flags that this is a test instance of this handler.
bool _want_reflexive
Flags that all subscriptions entered by this CDS Handler should be reflexive.
cds_device_map_t _cds_device_map
A map of the CDS' Device and Channel data, in a px::asio::CCdsDevice container, keyed by each device's CDS ID.
std::recursive_mutex _device_map_mutex
A mutex to protect iterative access or updating of the map of Device and Channel data.
cds_device_callback_t _add_device_callback
The callback function to the application to let it handle the addition of a new CCdsDevice container to the map, after this handler has filled out its data.
cds_device_callback_t _update_device_callback
The callback function to the application to let it handle the updating of an existing CCdsDevice container, after this handler has updated its data.
device_delete_callback_t _delete_device_callback
The callback function to the application to let it handle the removal of an existing CCdsDevice container and its device and channel data.
cds_device_callback_t _device_state_callback
The callback function to the application to let it handle the changing Device state for an existing CCdsDevice container, after this handler has updated its data.
cds_ch_settings_callback_t _channel_settings_callback
The callback function to the application to let it handle the response to a CGetChannelSettings request for one Device.
cds_ch_values_callback_t _channel_values_callback
The optional callback function for the application to received changed channel values.
px::id_t _change_signature_sub_id
The subscription id for our CDS subscriptions for device Change Signatures.
px::id_t _add_dev_sub_id
The subscription id for our CDS subscriptions for "add device" and "delete device" recursively.
px::id_t _dev_state_sub_id
The subscription id for our CDS subscriptions for device state changes..
px::id_t _ch_values_sub_id
The subscription id for all Channel Value updates.
px::id_t _alarm_sub_id
The subscription id for our CDS subscriptions for alarm updates.
std::deque< queued_req_t > _reqst_queue
A FIFO list of message types and device IDs that we want to process for discovery or maintenance.
std::recursive_mutex _reqst_queue_mutex
A mutex to protect access or updating of the deque _reqst_queue.
std::map< uint32_t, queued_req_t > _awaiting_resps
A map of the message types and device IDs that are awaiting a response, keyed by the their transaction IDs.
std::recursive_mutex _awaiting_resps_mutex
A recursive mutex to protect access or updating of the map _awaiting_resps.
bool _doing_initial_discovery
A flag that indicates when we are still in the initial static discovery phase, using synchronous CDS calls and with no subscriptions yet enabled.
px::cds::CallbackHandle _internal_callback_handle
If set, this is the handle we got from the CDS when we registered our internal callback for submit() calls for our own internal use.
bool _in_callback_guard
Set when we enter a callback from the CDS; cleared when we exit it.
uint32_t _last_transaction_id
Notes the last TransID processed in the internal callback handler Useful so we don't queue "waiting" TransID if it has already immediately been responded to.
bool _want_channels
Flag that tells us whether to discover and update Channel data along with device data.
long int _override_pacing
px::string _session_token
Holds the session token that we are logged into the CDS with.
px::CBitset< px::permissions > _my_perms
This client's set of permissions.
cds_alarm_callback_t _update_alarm_callback
uniquely maps an alarm ID to a px::CAlarmUpdate object
channel_value_map_t _channel_values
Our internal map of all Channel Values (if desired)
std::recursive_mutex _channel_map_mutex
A mutex to protect iterative access or updating of the map of Channel Values.
unsigned int _submit_wait_count
A simple up-counter for each call to submit_wait().
Protected Attributes inherited from px::asio::CCdsSyncIO
bool _bypass_validation
If true, bypass CDS data validation when setting channel values.
Detailed Description
ABC for CDS Handler, provides a common synchronous/asynchronous interface to the CDS API.
Synchronous CDS utility functions are imported from the base CCdsSyncIO class.
– Note: Using this class requires ASIO services –
Every ASIO based application should derive a handler from this, and must implement the virtual function for handle_response(). Provides the basic functions for handling OOBs and subscriptions, and for discovering and maintaining the map of Device and Channel data.
EXCEPT if you want to use the submit() and its handle_response() callback. The latter will be will be invoked via the associated px::asio::CCdsConnectionCallback, created by the px::asio::CCdsConnection, which uses ASIO functionality.
Definition at line 72 of file cds_handler.hpp.
Member Typedef Documentation
typedef std::function<void (const CCdsDevice &)> px::asio::CCdsHandler::cds_device_callback_t
Define the function object type to handle CCdsDevice additions or updates from the CDS.
Provided as input to the init_device_map() call.
Definition at line 99 of file cds_handler.hpp.
typedef std::function<void (px::id_t)> px::asio::CCdsHandler::device_delete_callback_t
Define the function object type to handle CCdsDevice deletions from the CDS.
Provided as input to the init_device_map() call.
Definition at line 103 of file cds_handler.hpp.
typedef std::function<void (const px::CAlarmUpdate &)> px::asio::CCdsHandler::cds_alarm_callback_t
Define the function object type to handle px::CAlarmUpdate updates from the CDS.
Definition at line 106 of file cds_handler.hpp.
typedef std::function<void (const CCdsDevice &, const std::vector<px::CChannelSettings> &)> px::asio::CCdsHandler::cds_ch_settings_callback_t
Define the function object type to handle px::CGetChannelSettings responses from the CDS.
Definition at line 109 of file cds_handler.hpp.
typedef std::function<void (const std::map<px::id_t, px::CValue> &, const px::CWallTime &)> px::asio::CCdsHandler::cds_ch_values_callback_t
Define the function object type to handle channel value change notifications from the CDS.
Definition at line 112 of file cds_handler.hpp.
typedef struct px::asio::CCdsHandler::ch_val_s px::asio::CCdsHandler::channel_value_t
Define the structure to store each channel's Value, timestamp, etc (Currently there is no "etc" but maybe will add "is_subscribed" flag, etc)
typedef std::map<px::id_t, channel_value_t> px::asio::CCdsHandler::channel_value_map_t
Define the map for Channel Values, keyed by CDS ID.
Definition at line 126 of file cds_handler.hpp.
typedef struct queued_req_s px::asio::CCdsHandler::queued_req_t
Definition at line 144 of file cds_handler.hpp.
Member Enumeration Documentation
enum px::asio::CCdsHandler::queued_req_type
A set of Enums for the types of queued requests handled internally by this class.
Enumerator
RQST_GET_DEVICE
Get the Device data.
RQST_GET_CHANNEL_VALUES
Get all the Channel Values for the Device.
RQST_GET_CHANNEL_SETTINGS
Get all the Channel Settings for the Device.
RQST_SUBSCRIBE_CHANNEL_VALUES
Subscribe to all the Channel Values for this Device.
RQST_MAX
Definition at line 81 of file cds_handler.hpp.
Constructor & Destructor Documentation
px::asio::CCdsHandler::CCdsHandler (const px::string & app_name, uint32_t wait_secs = 60, uint32_t request_queue_size = 4194304, uint32_t response_queue_size = 4194304, const bool enable_data_validation = true)
Constructor.
Parameters
app_name The name which identifies your connections with the CDS. Preferably unique but not enforced
wait_secs Number of seconds to wait until we give up on trying to connect with the CDS. If the CDS is not connected by then the function exits with an exception. We attempt to connect with the CDS once every 5 seconds within this time. If this is set to 0, we will wait forever for the CDS connection (not recommended).
request_queue_size Specifies the memory allocation to buffer pending requests, in bytes. Must be at least 4096.
response_queue_size Specifies the memory allocation to queue responses, in bytes. Must be at least 4096.
enable_data_validation Enable/disable CDS data validation. Defaults to true.
Exceptions
px::generic_err The handler could not initialize or connect to the CDS
Definition at line 36 of file cds_handler.cpp.
References connect_to_cds().
px::asio::CCdsHandler::~CCdsHandler () virtual
Default destructor, a virtual.
Disconnects from the CDS.
Definition at line 82 of file cds_handler.cpp.
References _cds_device_map, closeout_device_map(), px::cds::CClient::disconnect(), and px::cds::CClient::get().
px::asio::CCdsHandler::CCdsHandler (bool is_mock = true) protected
Non-normal Constructor, only useful for non-CDS test.
This is only for tests, where we don't want/need a CDS connection.
Parameters
is_mock Set to true so the constructor can proceed, though it still won't check for the CDS.
Exceptions
px::generic_err The CDS is not checked / initialized
Definition at line 56 of file cds_handler.cpp.
References LIBPX_FERR, and LIBPX_FINFO.
Member Function Documentation
void px::asio::CCdsHandler::connect_to_cds (const px::string & app_name, uint32_t wait_secs = 60, uint32_t request_queue_size = 4194304, uint32_t response_queue_size = 4194304)
Open the connection to the CDS (if not already open).
Parameters
app_name The name which identifies your connections with the CDS. Preferably unique but not enforced
wait_secs Number of seconds to wait until we give up on trying to connect with the CDS. If the CDS is not connected by then the function exits with an exception. We attempt to connect with the CDS once every 5 seconds within this time. If this is set to 0, we will wait forever for the CDS connection (not recommended).
request_queue_size Specifies the memory allocation to buffer pending requests, in bytes. Must be at least 4096.
response_queue_size Specifies the memory allocation to queue responses, in bytes. Must be at least 4096.
Exceptions
px::generic_err The handler could not initialize or connect to the CDS
Definition at line 97 of file cds_handler.cpp.
References px::cds::CSignalPipe::clear(), px::cds::CClient::connect(), px::cds::CSignalPipe::fd(), px::cds::CClient::get(), LIBPX_ERR, LIBPX_INFO, and LIBPX_WARN.
Referenced by CCdsHandler().
virtual PUBLIC void px::asio::CCdsHandler::handle_response (std::shared_ptr< px::cds::CRequestResponse > resp) pure virtual
Called by the ASIO io_service when one or more (normally expected) responses or subscription updates are sent from the CDS.
This will be invoked for the subscription events, or responses to submit(), or (in unusual cases) an unsolicited response from the CDS itself.
Once you have started the ASIO service, this function as well as internal_handle_response() will be given any subscription updates, so your implementation must validate that this message was for one of your own subscriptions.
Your derived class must implement this function and create a CCdsConnectionCallback() instance to get this callback to work.
Parameters
resp The response from the CDS (wrapped in a shared pointer). Must not be null. The resp type is aliased as cds::response_ptr_t
Implemented in TestCdsHandler.
Referenced by px::asio::CCdsConnectionCallback::cds_response_callback().
std::shared_ptr< px::cds::CRequestResponse > px::asio::CCdsHandler::submit_wait (px::cds::CRequestResponse & req) const virtual
Submit a request for CDS processing, waiting for the response and returning it.
(So this is a synchronous CDS call.) Implemented but virtual so it can be overridden in mocking code.
See Also
px/cds/client.hpp for more detail
Parameters
req The request to be given to the CDS.
Exceptions
px::no_connection,: if the connection has not been established or if it drops for some reason px::too_much_data: if the request is too large to ever be able to fit in the buffer
Returns
The response from the CDS (wrapped in a shared pointer).
Definition at line 194 of file cds_handler.cpp.
References _in_callback_guard, _submit_wait_count, px::cds::CClient::am_i_background_thread(), px::cds::CClient::get(), and LIBPX_NOTICE.
Referenced by cds_login(), do_alarm_discovery(), get_channel_value(), get_device(), set_oob(), subscribe_alarm_callback(), and subscribe_device_callbacks().
void px::asio::CCdsHandler::submit_forget (px::cds::CRequestResponse & req, bool sleep_on_full = false) virtual
Submit a request for CDS processing fire and forget style.
See Also
px/cds/client.hpp for more detail
Parameters
req The request to be given to the CDS.
sleep_on_full If true, turns this into a blocking call. Used to slow down the pace of requests if they pile up.
Exceptions
px::no_connection,: if the connection has not been established or if it drops for some reason px::too_much_data: if the request is too large to ever be able to fit in the buffer px::generic_err: This handler was not correctly initialized, or other error.
Definition at line 219 of file cds_handler.cpp.
References CALLBACK_NONE, px::cds::CClient::get(), and px::cds::CClient::submit().
Referenced by check_request_queue(), closeout_device_map(), set_channel_value(), and set_oob().
uint32_t px::asio::CCdsHandler::submit (px::cds::CRequestResponse & req, bool sleep_on_full = false) virtual
Submit a request for CDS processing.
The response will come back to this application thread when handle_response() is invoked by the ASIO io_service (registered when you setup CCdsConnection). (So this is an asynchronous CDS call.)
See Also
px/cds/client.hpp for more detail
If you have not setup CCdsConnection, this call will fail with px::generic_err.
Parameters
req The request to be given to the CDS.
sleep_on_full If true, turns this into a synchronous request. Used to slow down the pace of requests if they pile up.
Exceptions
px::no_connection,: if the connection has not been established or if it drops for some reason px::too_much_data: if the request is too large to ever be able to fit in the buffer px::generic_err: This handler was not correctly initialized, or other error.
Returns
The transaction ID from the CDS for this request (can be used to match the response with this request).
Definition at line 232 of file cds_handler.cpp.
References CALLBACK_NONE, px::cds::CClient::get(), handle, and LIBPX_FERR.
void px::asio::CCdsHandler::ping_watchdog ()
Watchdog Related Asynchronous Member Functions.
Utility function to ping the CDS watchdog timer directly. For most applications, this will be managed automatically by the ASIO CIoManager's ping_timer, but this function is provided for convenience in those times when the manager is not given the chance to run.
Definition at line 251 of file cds_handler.cpp.
References check_awaiting_timeouts(), check_request_queue(), px::cds::CClient::get(), LIBPX_INFO, and px::cds::CClient::submit().
void px::asio::CCdsHandler::set_oob (const px::string & tag, const px::proto::toolkitStruct & data, bool persist = false)
OOB Related Member Functions.
Utility function to set a particular, full OOB object. Does a fire-and-forget if called from inside a callback, otherwise does it synchronously, and waits for and checks the response for any errors.
Differs from set_oob_field() in that it sets a full OOB object rather than just one field in an OOB.
Parameters
tag CDS OOB path/name to write to. Must not be blank.
data The OOB contents to write.
Exceptions
If unable to write to the CDS successfully, will throw px::generic_err with an informative message.
Definition at line 271 of file cds_handler.cpp.
References _in_callback_guard, px::cds::CClient::am_i_background_thread(), px::asio::CCdsSyncIO::check_cds_result(), px::cds::CSetOOBData::data, px::cds::do_not_save, LIBPX_ERR, LIBPX_INFO, px::cds::save_always, submit_forget(), and submit_wait().
bool px::asio::CCdsHandler::get_channel_value (px::id_t channel_id, px::CValue & value)
Channel Related Asynchronous Member Functions.
Utility function to get the current Value of a Channel from cached data or the CDS. If CDS access is required, will make a synchronous call to the CDS. Else (ie, if we are using the Device map and set the _want_channels flag), the Value returned will come from the internal _channel_values map.
Parameters
channel_id The ID of the Channel whose Value is requested. Must be > 0.
[out] value The current Value, from the CDS.
Returns
True if the data is valid on return, else False if the fetch failed (eg, bad channel ID).
Definition at line 1577 of file cds_handler.cpp.
References _channel_map_mutex, _channel_values, px::CValue::as_string(), px::asio::CCdsSyncIO::check_cds_result(), px::cds::CGetChannelValue::ids, px::invalid, LIBPX_DEBUG, LIBPX_WARN, submit_wait(), and px::CValue::type().
bool px::asio::CCdsHandler::get_channel_value (px::id_t channel_id, px::CValue & value, CWallTime & timestamp)
Get the current Value of a Channel based based on a specified timestamp.
i.e. Return a valid value and its timestamp only if the last channel value update occurred after the specified timestamp.
The channel value will be retreived from cached data or the CDS. If CDS access is required, will make a synchronous call to the CDS. Else (ie, if we are using the Device map and set the _want_channels flag), the Value returned will come from the internal _channel_values map.
Parameters
channel_id The ID of the Channel whose Value is requested. Must be > 0.
[out] value The current Value, from the CDS.
timestamp On input, the time that will be compared to the channel last updated timestamp; on output, if the value is valid, will contain the timestamp of the CDS value.
Returns
True if the data is valid on return, else False if the fetch failed (eg, bad channel ID).
Definition at line 1644 of file cds_handler.cpp.
References _channel_map_mutex, _channel_values, px::asio::CCdsSyncIO::check_cds_result(), px::cds::CGetChannelValue::ids, px::invalid, LIBPX_DEBUG, LIBPX_WARN, submit_wait(), and px::CValue::type().
std::map< px::string, px::CChannelSettings > px::asio::CCdsHandler::list_channel_settings (px::id_t dev_id)
Retrieve a map of MCL Channel canonical names to their Channel settings.
Makes a synchronous call to the CDS to get this data.
Parameters
dev_id The CDS device ID whose Channel settings we want to get. Must be > 0.
Returns
The map of MCL Channel canonical names to their Channel settings.
Exceptions
If unable to fetch from CDS, will throw px::generic_err with an informative message.
Definition at line 1549 of file cds_handler.cpp.
References px::asio::CCdsSyncIO::get_channel_settings().
void px::asio::CCdsHandler::set_channel_value (px::id_t channel_id, const px::CValue & value)
Utility function to set the current Value of a Channel into the CDS.
Does a fire-and-forget when writing this out. Will update the internal map of Channel Values, if implemented.
Parameters
channel_id The ID of the Channel whose Value is to be written. Must be > 0.
value The Value to write to the CDS.
Definition at line 1728 of file cds_handler.cpp.
References px::asio::CCdsSyncIO::_bypass_validation, _channel_map_mutex, _channel_values, _want_channels, px::CValue::as_string(), px::cds::CUpdateChannelValue::bypass_validation, LIBPX_DEBUG, LIBPX_ERR, LIBPX_INFO, px::CWallTime::now(), submit_forget(), px::cds::CUpdateChannelValue::updates, px::asio::CCdsHandler::ch_val_s::value, and px::cds::CUpdateChannelValue::when.
px::CDevice px::asio::CCdsHandler::get_device (px::id_t dev_id)
Device Related Asynchronous Member Functions.
Retrieve a single device by its device id. This will return the device data from our internal map, if available, else (eg, if the map hasn't been filled out yet), will make a synchronous CDS request to get the device data.
Parameters
dev_id The ID of the device being requested. Must be > 0.
Returns
A copy of the requested Device object.
Exceptions
If unable to fetch from CDS, will throw px::generic_err with an informative message.
Definition at line 308 of file cds_handler.cpp.
References _cds_device_map, px::asio::CCdsSyncIO::check_cds_result(), get_map_device(), LIBPX_DEBUG, px::cds::CGetDevice::requested_ids, and submit_wait().
bool px::asio::CCdsHandler::is_mock ()
Subscription Related Asynchronous Member Functions.
Getter for the _is_mock flag, set in non-normal construction for tests.
Returns
True if mocking (test mode), else False normally.
Definition at line 927 of file cds_handler.hpp.
References _is_mock.
Referenced by px::asio::CIoManager::CIoManager().
void px::asio::CCdsHandler::set_to_reflexive ()
Simple setter to force all subscriptions entered by the CDS Handler to be reflexive.
A reflexive subscription will notify us even when it is our application that changed the CDS data, causing the notification. False by default, setting the internal flag here is useful, eg, in unit tests, where the same application is making changes but wants to handle the notification callbacks.
Definition at line 929 of file cds_handler.hpp.
References _want_reflexive.
Referenced by TestCdsHandler::TestCdsHandler().
void px::asio::CCdsHandler::init_device_map (const cds_device_callback_t & add_device_callback, const cds_device_callback_t & update_device_callback, const device_delete_callback_t & delete_device_callback, const cds_device_callback_t & device_state_callback, bool want_channels, const cds_ch_settings_callback_t & channel_settings_callback = cds_ch_settings_callback_t())
Member Functions that manage the maps of Devices and Channels, and Alarm handling.
Function to initialize the local map of Device data from the CDS. The application provides its callback functions which will be invoked when a device is added to, updated in, or deleted from the map.
If this function is called early in the system startup, there will probably be a flurry of callbacks until all the devices have been fully discovered and profiled. This function will not return until it has discovered all devices presently available in the CDS, though all the callbacks may not have been processed before it returns. If devices are later added, updated, or removed, the appropriate callbacks will be invoked.
Note that these callbacks happen even though the subscriptions for these types of updates haven't been entered yet.
Parameters
add_device_callback The callback function from the application to let it handle the addition of a new CCdsDevice container to the map, after this handler has filled out its data. This includes the addition of subdevices.
update_device_callback The callback function to the application to let it handle the updating of an existing CCdsDevice container, after this handler has filled out its data. This will be called for px::sub::subscription_type::device_settings changes, but not for px::sub::subscription_type::change_signature updates.
delete_device_callback The callback function to the application to let it handle the removal of an existing CCdsDevice container and its device and channel data.
device_state_callback The callback function to the application to let it handle the changing Device state for an existing CCdsDevice container, after this handler has updated its data.
want_channels Indicates whether or not the application wants the Channel data for each Device to also be discovered and maintained. If this flag is set, we will fetch the Channel settings, and manage the map of Channel Values by fetching and subscribing to Channel Values for each Device. If the application wants to be notified of changed channel values, it must also provide the optional callback via init_channel_values_callback().
channel_settings_callback The optional callback to receive ChannelSettings for each discovered Device.
Definition at line 346 of file cds_handler.cpp.
References _add_dev_sub_id, _add_device_callback, _ch_values_sub_id, _change_signature_sub_id, _channel_settings_callback, _delete_device_callback, _dev_state_sub_id, _device_state_callback, _doing_initial_discovery, _internal_callback, _internal_callback_handle, _update_device_callback, _want_channels, do_static_discovery(), px::cds::CClient::get(), px::asio::CCdsSyncIO::get_subscriber_ids(), PX_ID_ROOT, and px::cds::CClient::register_callback().
void px::asio::CCdsHandler::closeout_device_map ()
Undo the features that we enabled to populate the device map: unsubscribe callbacks, clear the map.
Definition at line 529 of file cds_handler.cpp.
References _add_dev_sub_id, _alarm_sub_id, _cds_device_map, _ch_values_sub_id, _change_signature_sub_id, _channel_map_mutex, _channel_values, _dev_state_sub_id, _device_map_mutex, _internal_callback_handle, _reqst_queue, _reqst_queue_mutex, _want_channels, CALLBACK_NONE, px::cds::CClient::get(), LIBPX_DEBUG, px::sub::max_subscription_type, PX_ID_ROOT, submit_forget(), px::cds::CSubscribe::subscriptions, px::cds::CClient::unregister_callback(), and px::cds::CClient::unregister_unsolicited_callback().
Referenced by do_static_discovery(), and ~CCdsHandler().
void px::asio::CCdsHandler::do_static_discovery (px::id_t starting_dev_id = PX_ID_ROOT)
Perform a static discovery of all device data starting at the given ID.
This involves recursive device processing, so this function will tie up the process for some significant time before returning. If the devices checked have been previously added to our map, then they will be updated or left untouched (if their change_signature is unchanged). Note that this means that on a second pass, if the publisher's change_signature is unchanged, that no further devices will be rechecked.
Parameters
starting_dev_id The Device ID of the first device for discovery; the process is recursive, so its children will also be checked. Must be > 0.
Definition at line 399 of file cds_handler.cpp.
References _cds_device_map, _doing_initial_discovery, _override_pacing, _want_channels, add_msg_to_rqst_queue(), check_request_queue(), closeout_device_map(), ok_to_proceed(), RQST_GET_DEVICE, and RQST_SUBSCRIBE_CHANNEL_VALUES.
Referenced by init_device_map().
bool px::asio::CCdsHandler::check_request_queue ()
See if there is an entry available in our queue of message requests, and, if so, send the request for its CDS data.
This function only sends CDS requests in Async mode: If there is a device ID + message type entry queued up, will kick off an async request for its data, and return.
There is a check first to make sure that we aren't waiting on any pending requests already; in that case, we don't make a new request (yet). To compensate for the possibility of losing a response, we will check the for the response timeout here.
If using the Device Map (and optional Channels) feature of CdsHandler, then you should call this function periodically (eg, within your timeout() handler).
Returns
True if there was any message queued up to be requested, or if we are waiting for any responses, else False if both the request and waiting queues are empty.
Definition at line 1334 of file cds_handler.cpp.
References _awaiting_resps, _awaiting_resps_mutex, _ch_values_sub_id, _internal_callback_handle, _last_transaction_id, _reqst_queue, _reqst_queue_mutex, _want_channels, px::asio::CCdsHandler::queued_req_s::awaiting_timeout, check_awaiting_timeouts(), px::asio::CCdsHandler::queued_req_s::dev_id, px::cds::CClient::get(), px::cds::CGetChannelSettings::ids, px::cds::CGetChannelValue::ids, LIBPX_DEBUG, LIBPX_FWARN, px::CMonoTime::now(), px::asio::CCdsHandler::queued_req_s::req_type, px::cds::CGetDevice::requested_ids, RQST_GET_CHANNEL_SETTINGS, RQST_GET_CHANNEL_VALUES, RQST_GET_DEVICE, RQST_SUBSCRIBE_CHANNEL_VALUES, px::cds::CClient::submit(), submit_forget(), px::cds::CSubscribe::subscriptions, and px::sub::value_update.
Referenced by do_static_discovery(), internal_handle_response(), and ping_watchdog().
void px::asio::CCdsHandler::set_override_pacing (unsigned long int override)
This overrides static discovery pacing.
This allows products to do faster discovery during start up.
NOTE: This must be called before init_device_map().
WARNING: using times < 10 ms may cause a watchdog.
Parameters
override time in nanoseconds of how much to pace between processing of every 4 CDS requests. Must be less than 999999999.
Definition at line 931 of file cds_handler.hpp.
References _override_pacing.
void px::asio::CCdsHandler::subscribe_device_callbacks ()
Enter CDS subscriptions for Device CrUD events to maintain the device map.
When the CDS publishes CrUD updates, we will invoke the callbacks registered in init_device_map() after updating our device map.
Note: originally included in init_device_map(), this was separated out for processes that daemonize after doing their CDS initialization (because the CDS considered that client connection closed and canceled these subscriptions).
Definition at line 471 of file cds_handler.cpp.
References _add_dev_sub_id, _change_signature_sub_id, _dev_state_sub_id, _internal_callback, _internal_callback_handle, CALLBACK_NONE, px::sub::change_signature, px::asio::CCdsSyncIO::check_cds_result(), px::sub::device_create_recursive, px::sub::device_delete_recursive, px::sub::device_settings, px::sub::device_state_recursive, px::cds::CClient::get(), handle, PX_ID_ROOT, px::cds::CClient::register_callback(), px::cds::CClient::register_unsolicited_callback(), submit_wait(), and px::cds::CSubscribe::subscriptions.
bool px::asio::CCdsHandler::init_channel_values_callback (const cds_ch_values_callback_t & update_channel_values_callback)
Function to initialize the optional callback for channel value updates.
The application provides its callback function which will be invoked when any of the channel values are updated (and changed).
Parameters
update_channel_values_callback The callback function for the application to handle the updating of channel values.
Returns
True on success in setting the callback. False indicates a problem, such as channel values are not being monitored.
Definition at line 517 of file cds_handler.cpp.
References _channel_values_callback, and _want_channels.
bool px::asio::CCdsHandler::get_map_device (px::id_t dev_id, cds_device_map_citer_t & map_pos) const
Getter for a CCdsDevice instance in our map, looked up by its Device ID.
Parameters
dev_id The ID of the device we want. Must be > 0.
[out] map_pos The map iterator for the requested device container from the map. On success, the "second" of the pair pointed to by map_pos is the CCdsDevice container.
Returns
True on success (map_pos is valid), or False if there is no such device entry in our map.
Definition at line 727 of file cds_handler.cpp.
References lookup_map_device().
Referenced by get_device(), is_communicating_device(), and process_subscription_update().
bool px::asio::CCdsHandler::is_communicating_device (px::id_t dev_id) const
Checks if we have the requested Device instance in our map, and if its state is enabled and communicating, so that its Channel data will be valid.
Parameters
dev_id The ID of the device we are checking. Must be > 0.
Returns
True on success (we have the Device in our map, and its state is "valid"), or False if there is no such device, or it is disabled or not communicating.
Definition at line 775 of file cds_handler.cpp.
References get_map_device().
void px::asio::CCdsHandler::init_alarm_callback (const cds_alarm_callback_t & update_alarm_callback)
Function to initialize Alarm update callbacks.
The application provides its callback functions which will be invoked when an alarm is updated.
Parameters
update_alarm_callback The callback function to the application to let it handle the updating of an existing px::CAlarmUpdate container, after this handler has filled out its data. This callback is invoked when an alarm is updated (!new alarm id && !closed).
Definition at line 793 of file cds_handler.cpp.
References _update_alarm_callback.
void px::asio::CCdsHandler::do_alarm_discovery (uint64_t starting_global_count = 0)
Perform a static discovery of all alarm updates starting at the given sequence ID.
If alarm update callback has been provided it will call that.
Parameters
starting_global_count The global count of the first alarm for discovery
Definition at line 803 of file cds_handler.cpp.
References _update_alarm_callback, px::asio::CCdsSyncIO::check_cds_result(), px::cds::CGetAlarms::max_result_size, px::cds::CGetAlarms::populate_str_val, px::cds::CGetAlarms::recursive, px::cds::CGetAlarms::start_global_count, and submit_wait().
void px::asio::CCdsHandler::subscribe_alarm_callback ()
Enter CDS subscriptions for Alarm events.
When the CDS publishes Alarm updates, we will invoke the callback registered in init_alarm_callback().
Definition at line 827 of file cds_handler.cpp.
References _alarm_sub_id, px::sub::alarm_recursive, px::asio::CCdsSyncIO::check_cds_result(), px::asio::CCdsSyncIO::get_subscriber_ids(), LIBPX_DEBUG, PX_ID_ROOT, submit_wait(), and px::cds::CSubscribe::subscriptions.
void px::asio::CCdsHandler::internal_handle_response (std::shared_ptr< px::cds::CRequestResponse > resp)
Called by the CDS when one or more unsolicited, subscription update, or solicited responses are ready for the internal handling by this class, eg, for maintaining the device map.
This will be invoked for the local subscription events, or responses to local submit(), or (in unusual cases) an unsolicited response from the CDS itself.
If this class is used when the application uses ASIO support (ie, CCdsConnection, submit() and handle_response()), then this function (if used) will be called after handle_response() if there may be anything for it to process. But it must consequently be quite forgiving of unknown subscription updates and simply ignore anything that was not intended for its own internal handling (eg, maintaining the device map).
Parameters
resp The response or update message from the CDS (wrapped in a shared pointer). Must not be null. The resp type is aliased as cds::response_ptr_t
Definition at line 853 of file cds_handler.cpp.
References _add_dev_sub_id, _alarm_sub_id, _awaiting_resps, _awaiting_resps_mutex, _ch_values_sub_id, _change_signature_sub_id, _dev_state_sub_id, _in_callback_guard, _internal_callback_handle, _last_transaction_id, check_request_queue(), LIBPX_DEBUG, LIBPX_INFO, LIBPX_WARN, process_response_type(), process_subscription_update(), RQST_GET_CHANNEL_SETTINGS, RQST_GET_CHANNEL_VALUES, RQST_GET_DEVICE, and px::cds::SUCCEEDED.
Referenced by px::asio::CCdsConnectionCallback::cds_response_callback(), and px::asio::CCdsHandlerCallback::cds_response_callback().
void px::asio::CCdsHandler::cds_login ()
Do a CDS Client Login (no username or password) to get a session token and permissions.
This is useful for internal processes for which there is no user name or password. Will store the session token to authorize the process' CDS or Mercury requests. The permissions will also be stored and can be checked before attempting an operation that will fail. This is a synchronous CDS call.
Exceptions
Will throw px::generic_err in the unlikely case where this login fails.
Definition at line 1474 of file cds_handler.cpp.
References _my_perms, _session_token, px::cds::FAILED, px::cds::CCdsClientLogin::hard_timeout, px::cds::CCdsClientLogin::idle_timeout, LIBPX_DEBUG, LIBPX_WARN, px::permission::perms_to_short_str(), px::cds::CCdsClientLogin::service, submit_wait(), and px::cds::SUCCEEDED.
Referenced by check_permission(), and get_session_token().
const px::string & px::asio::CCdsHandler::get_session_token ()
Getter for our session token.
Will do a cds_login() if not already done. Most applications will not need this capability.
Returns
The session token to authorize CDS or Mercury requests.
Exceptions
Will throw px::generic_err in the unlikely case where the CDS login fails.
Definition at line 1518 of file cds_handler.cpp.
References _session_token, and cds_login().
bool px::asio::CCdsHandler::check_permission (px::permissions test_perm)
Test to see if we have a given permission (privilege), checking against the privileges for this CDS client.
Will do a cds_login() if not already done.
Parameters
test_perm One of the set of permission enums, the one to test.
Returns
True if have the permission.
Definition at line 1529 of file cds_handler.cpp.
References _my_perms, cds_login(), px::CBitset< T >::empty(), px::CBitset< T >::get(), LIBPX_ERR, and px::generic_err::what().
unsigned int px::asio::CCdsHandler::get_submit_wait_count ()
Getter for the up-counter for each call to submit_wait().
Can be used to detect "unexpected" submit_wait() calls in running code.
Returns
The current value of _submit_wait_count.
Definition at line 933 of file cds_handler.hpp.
References _submit_wait_count.
bool px::asio::CCdsHandler::process_device_data (const px::CDevice & px_device) protected
The recursive function to check this device's data and see if we need to add or update the Device data, or its channels, or (recursively) its child devices.
Any changes will be made to our Device map, and the application callbacks will be invoked as appropriate.
Parameters
px_device The device data of our starting point.
Returns
Returns true if the map was updated, or else False if no changes were discovered or made.
Definition at line 591 of file cds_handler.cpp.
References _add_device_callback, _cds_device_map, px::asio::CCdsDevice::_channel_settings_count, px::asio::CCdsDevice::_channel_values_received, px::asio::CCdsDevice::_channel_values_subscribed, _device_map_mutex, _doing_initial_discovery, px::asio::CCdsDevice::_px_device, _update_device_callback, _want_channels, add_msg_to_rqst_queue(), px::CDevice::change_signature, px::CDevice::channels, px::CDevice::id(), px::asio::CCdsDevice::is_valid_device(), LIBPX_DEBUG, LIBPX_NOTICE, PX_ID_UNSET, RQST_GET_CHANNEL_SETTINGS, RQST_GET_CHANNEL_VALUES, RQST_GET_DEVICE, RQST_SUBSCRIBE_CHANNEL_VALUES, and px::CDevice::sub_devices.
Referenced by process_response_type(), and process_subscription_update().
bool px::asio::CCdsHandler::process_channel_value (px::id_t ch_id, const px::CValue & value, const CWallTime & timestamp) protected
Given the Value for a Channel (from GetValue request or subscription update), save it to our map of channel values.
Parameters
ch_id The CDS ID of the Channel. Must be > 0.
value The new Value for the Channel
timestamp The time this Value was updated
Returns
True if this is a change in value, False if the new and old values are the same.
Definition at line 704 of file cds_handler.cpp.
References _channel_map_mutex, _channel_values, px::asio::CCdsHandler::ch_val_s::value, and px::asio::CCdsHandler::ch_val_s::when.
Referenced by process_response_type(), and process_subscription_update().
bool px::asio::CCdsHandler::process_response_type (queued_req_type exp_req_type, std::shared_ptr< px::cds::CRequestResponse > resp) protected
(Attempt to) Process a CDS response of the given request type.
Will try to cast this response to that type, then handle if successful
Parameters
exp_req_type The expected type of the response message (normally from what was requested)
resp The response or update message from the CDS (wrapped in a shared pointer). Must not be null. The resp type is aliased as cds::response_ptr_t
Returns
True if the expected type of message was found and handled, else False
Definition at line 980 of file cds_handler.cpp.
References _channel_settings_callback, px::cds::CGetSingleChannelValue::id, px::cds::CGetChannelSettings::ids, LIBPX_DEBUG, LIBPX_WARN, lookup_map_device(), ok_to_proceed(), process_channel_value(), process_device_data(), RQST_GET_CHANNEL_SETTINGS, RQST_GET_CHANNEL_VALUES, RQST_GET_DEVICE, px::cds::CGetSingleChannelValue::value, and px::cds::CGetSingleChannelValue::when.
Referenced by internal_handle_response().
void px::asio::CCdsHandler::process_subscription_update (std::shared_ptr< px::cds::CSubscriberNotify > update) protected
Given a subscribed update event, process its contents.
Will key off the event type and process the single or multiple data contents. Mostly will queue up device IDs to be re-processed.
Parameters
update The subscribed update event and its data. Must not be null.
Definition at line 1073 of file cds_handler.cpp.
References _cds_device_map, _channel_map_mutex, _channel_values, _channel_values_callback, px::asio::CCdsDevice::_channel_values_subscribed, _delete_device_callback, _device_map_mutex, _device_state_callback, _doing_initial_discovery, px::asio::CCdsDevice::_px_device, _update_alarm_callback, _update_device_callback, _want_channels, add_msg_to_rqst_queue(), px::sub::alarm, px::sub::alarm_recursive, px::sub::change_signature, px::sub::device_create_recursive, px::sub::device_delete_recursive, px::sub::device_settings, px::sub::device_state, px::sub::device_state_recursive, px::disabled, px::CBitset< T >::get(), get_map_device(), px::CDevice::get_state(), LIBPX_DEBUG, LIBPX_WARN, likely, px::not_communicating, process_channel_value(), process_device_data(), RQST_GET_CHANNEL_SETTINGS, RQST_GET_CHANNEL_VALUES, RQST_GET_DEVICE, RQST_SUBSCRIBE_CHANNEL_VALUES, px::CDevice::set_inherited_state(), px::CDevice::set_state(), and px::sub::value_update.
Referenced by internal_handle_response().
bool px::asio::CCdsHandler::add_msg_to_rqst_queue (queued_req_type msg_type, px::id_t dev_id) protected
Add the given message type and Device ID to our queue of messages to be processed, unless it is already in that queue.
Parameters
msg_type One of the set of queued_req_type enums, for this request.
dev_id The Device ID to check and add. Must be > 0.
Returns
True if was added, False if not (because it was already present)
Definition at line 1283 of file cds_handler.cpp.
References _channel_settings_callback, _reqst_queue, _reqst_queue_mutex, _want_channels, px::asio::CCdsHandler::queued_req_s::awaiting_timeout, px::asio::CCdsHandler::queued_req_s::dev_id, LIBPX_DEBUG, px::asio::CCdsHandler::queued_req_s::req_type, RQST_GET_CHANNEL_SETTINGS, and RQST_GET_DEVICE.
Referenced by check_awaiting_timeouts(), do_static_discovery(), process_device_data(), and process_subscription_update().
bool px::asio::CCdsHandler::check_awaiting_timeouts () protected
Check the expected responses to see if we are past the time when an async response can be expected to arrive for any; in that case, clear that entry but move it back to the end of the request queue.
Returns
True if we are still awaiting any responses, else False if none pending.
Definition at line 1447 of file cds_handler.cpp.
References _awaiting_resps, _awaiting_resps_mutex, add_msg_to_rqst_queue(), LIBPX_DEBUG, and px::CMonoTime::now().
Referenced by check_request_queue(), and ping_watchdog().
bool px::asio::CCdsHandler::lookup_map_device (px::id_t dev_id, cds_device_map_iter_t & map_pos) protected
Getter for a mutable CCdsDevice instance in our map, looked up by its Device ID.
Differs from get_map_device() in that it provides a non-const iterator to access the container, and so this function is protected, not public.
Parameters
dev_id The ID of the device we want. Must be > 0.
[out] map_pos The non-const map iterator for the requested device container from the map. On success, the "second" of the pair pointed to by map_pos is the CCdsDevice container.
Returns
True on success (map_pos is valid), or False if there is no such device entry in our map.
Definition at line 744 of file cds_handler.cpp.
References _cds_device_map, _device_map_mutex, LIBPX_DEBUG, and LIBPX_WARN.
Referenced by get_map_device(), and process_response_type().
bool px::asio::CCdsHandler::ok_to_proceed () protected virtual
Function for the implementation to signal to internal processing of this class' members that they should stop.
Implementations that wish to take advantage of this (eg, to interrupt the static discovery process) should override this function with their implementation.
Returns
True if OK to proceed as usual (the default always provided by this base class), else False if this class should stop doing static discovery.
Definition at line 1775 of file cds_handler.cpp.
Referenced by do_static_discovery(), and process_response_type().
Member Data Documentation
px::cds::CallbackHandle px::asio::CCdsHandler::handle
Callback handle for solicited responses to cds requests.
Need to provide this with asynchronous CDS requests (ie, submit()) to get a response. Normally set by px::asio::CCdsConnection.
Definition at line 664 of file cds_handler.hpp.
Referenced by px::asio::CCdsConnection::CCdsConnection(), px::asio::CCdsConnectionCallback::cds_response_callback(), submit(), and subscribe_device_callbacks().
std::shared_ptr<CCdsHandlerCallback> px::asio::CCdsHandler::_internal_callback
A callback handler for our internal_handle_response().
If filled out by the internal device map handler, will be registered for unsolicited callbacks.
Definition at line 671 of file cds_handler.hpp.
Referenced by px::asio::CCdsConnectionCallback::cds_response_callback(), init_device_map(), and subscribe_device_callbacks().
bool px::asio::CCdsHandler::_is_mock protected
Flags that this is a test instance of this handler.
Used by unit tests when we don't want a real CDS Handler
Definition at line 778 of file cds_handler.hpp.
Referenced by is_mock().
bool px::asio::CCdsHandler::_want_reflexive protected
Flags that all subscriptions entered by this CDS Handler should be reflexive.
A reflexive subscription will notify us even when it is our application that changed the CDS data, causing the notification. False by default, this is useful, eg, in unit tests, where the same application is making changes but wants to handle the notification callbacks.
Definition at line 785 of file cds_handler.hpp.
Referenced by set_to_reflexive().
cds_device_map_t px::asio::CCdsHandler::_cds_device_map protected
A map of the CDS' Device and Channel data, in a px::asio::CCdsDevice container, keyed by each device's CDS ID.
Definition at line 789 of file cds_handler.hpp.
Referenced by closeout_device_map(), do_static_discovery(), get_device(), lookup_map_device(), process_device_data(), process_subscription_update(), and ~CCdsHandler().
std::recursive_mutex px::asio::CCdsHandler::_device_map_mutex mutable protected
A mutex to protect iterative access or updating of the map of Device and Channel data.
Chosen as recursive so this same thread can lock it more than once, which is safe for us to do.
Definition at line 793 of file cds_handler.hpp.
Referenced by closeout_device_map(), lookup_map_device(), process_device_data(), and process_subscription_update().
cds_device_callback_t px::asio::CCdsHandler::_add_device_callback protected
The callback function to the application to let it handle the addition of a new CCdsDevice container to the map, after this handler has filled out its data.
The application gets a read-only (const) copy of the container. This callback operates within the CDS Client background thread.
Definition at line 799 of file cds_handler.hpp.
Referenced by init_device_map(), and process_device_data().
cds_device_callback_t px::asio::CCdsHandler::_update_device_callback protected
The callback function to the application to let it handle the updating of an existing CCdsDevice container, after this handler has updated its data.
The application gets a read-only (const) copy of the container. This callback operates within the CDS Client background thread.
Definition at line 805 of file cds_handler.hpp.
Referenced by init_device_map(), process_device_data(), and process_subscription_update().
device_delete_callback_t px::asio::CCdsHandler::_delete_device_callback protected
The callback function to the application to let it handle the removal of an existing CCdsDevice container and its device and channel data.
The application is just given the Device ID for the container. This application callback is called before this handler removes the CCdsDevice container from the map. This callback operates within the CDS Client background thread.
Definition at line 813 of file cds_handler.hpp.
Referenced by init_device_map(), and process_subscription_update().
cds_device_callback_t px::asio::CCdsHandler::_device_state_callback protected
The callback function to the application to let it handle the changing Device state for an existing CCdsDevice container, after this handler has updated its data.
The application gets a read-only (const) copy of the container. This callback operates within the CDS Client background thread.
Definition at line 819 of file cds_handler.hpp.
Referenced by init_device_map(), and process_subscription_update().
cds_ch_settings_callback_t px::asio::CCdsHandler::_channel_settings_callback protected
The callback function to the application to let it handle the response to a CGetChannelSettings request for one Device.
This class does not retain any of the ChannelSettings data. This callback operates within the CDS Client background thread.
Definition at line 825 of file cds_handler.hpp.
Referenced by add_msg_to_rqst_queue(), init_device_map(), and process_response_type().
cds_ch_values_callback_t px::asio::CCdsHandler::_channel_values_callback protected
The optional callback function for the application to received changed channel values.
This callback operates within the CDS Client background thread, so the application must copy any of the data it wants to retain.
Definition at line 830 of file cds_handler.hpp.
Referenced by init_channel_values_callback(), and process_subscription_update().
px::id_t px::asio::CCdsHandler::_change_signature_sub_id protected
The subscription id for our CDS subscriptions for device Change Signatures.
The subscription notifications for this ID will cover any changes in Devices or Channel structure and some field changes.
Definition at line 835 of file cds_handler.hpp.
Referenced by closeout_device_map(), init_device_map(), internal_handle_response(), and subscribe_device_callbacks().
px::id_t px::asio::CCdsHandler::_add_dev_sub_id protected
The subscription id for our CDS subscriptions for "add device" and "delete device" recursively.
All subscription notifications for this ID will be related to device addition or removal updates.
Definition at line 841 of file cds_handler.hpp.
Referenced by closeout_device_map(), init_device_map(), internal_handle_response(), and subscribe_device_callbacks().
px::id_t px::asio::CCdsHandler::_dev_state_sub_id protected
The subscription id for our CDS subscriptions for device state changes..
Definition at line 844 of file cds_handler.hpp.
Referenced by closeout_device_map(), init_device_map(), internal_handle_response(), and subscribe_device_callbacks().
px::id_t px::asio::CCdsHandler::_ch_values_sub_id protected
The subscription id for all Channel Value updates.
Definition at line 847 of file cds_handler.hpp.
Referenced by check_request_queue(), closeout_device_map(), init_device_map(), and internal_handle_response().
px::id_t px::asio::CCdsHandler::_alarm_sub_id protected
The subscription id for our CDS subscriptions for alarm updates.
Definition at line 850 of file cds_handler.hpp.
Referenced by closeout_device_map(), internal_handle_response(), and subscribe_alarm_callback().
std::deque<queued_req_t> px::asio::CCdsHandler::_reqst_queue protected
A FIFO list of message types and device IDs that we want to process for discovery or maintenance.
Definition at line 856 of file cds_handler.hpp.
Referenced by add_msg_to_rqst_queue(), check_request_queue(), and closeout_device_map().
std::recursive_mutex px::asio::CCdsHandler::_reqst_queue_mutex protected
A mutex to protect access or updating of the deque _reqst_queue.
Need recursive for initialization phase
Definition at line 860 of file cds_handler.hpp.
Referenced by add_msg_to_rqst_queue(), check_request_queue(), and closeout_device_map().
std::map<uint32_t, queued_req_t> px::asio::CCdsHandler::_awaiting_resps protected
A map of the message types and device IDs that are awaiting a response, keyed by the their transaction IDs.
Definition at line 864 of file cds_handler.hpp.
Referenced by check_awaiting_timeouts(), check_request_queue(), and internal_handle_response().
std::recursive_mutex px::asio::CCdsHandler::_awaiting_resps_mutex protected
A recursive mutex to protect access or updating of the map _awaiting_resps.
Definition at line 867 of file cds_handler.hpp.
Referenced by check_awaiting_timeouts(), check_request_queue(), and internal_handle_response().
bool px::asio::CCdsHandler::_doing_initial_discovery protected
A flag that indicates when we are still in the initial static discovery phase, using synchronous CDS calls and with no subscriptions yet enabled.
In this mode, we don't want any callbacks that happen to come in to trigger new device data requests.
Definition at line 873 of file cds_handler.hpp.
Referenced by do_static_discovery(), init_device_map(), process_device_data(), and process_subscription_update().
px::cds::CallbackHandle px::asio::CCdsHandler::_internal_callback_handle protected
If set, this is the handle we got from the CDS when we registered our internal callback for submit() calls for our own internal use.
Definition at line 877 of file cds_handler.hpp.
Referenced by check_request_queue(), closeout_device_map(), init_device_map(), internal_handle_response(), and subscribe_device_callbacks().
bool px::asio::CCdsHandler::_in_callback_guard mutable protected
Set when we enter a callback from the CDS; cleared when we exit it.
Used to guard against making submit_wait() calls from within callbacks, on the CDS Client background thread, which would cause the process to just hang. This member is mutable even when the class instance is const.
Definition at line 883 of file cds_handler.hpp.
Referenced by internal_handle_response(), set_oob(), and submit_wait().
uint32_t px::asio::CCdsHandler::_last_transaction_id protected
Notes the last TransID processed in the internal callback handler Useful so we don't queue "waiting" TransID if it has already immediately been responded to.
Definition at line 887 of file cds_handler.hpp.
Referenced by check_request_queue(), and internal_handle_response().
bool px::asio::CCdsHandler::_want_channels protected
Flag that tells us whether to discover and update Channel data along with device data.
If set, we will fetch the Channel settings, and manage the map of Channel Values in _channel_values by fetching and subscribing to Channel Values for each Device.
Definition at line 892 of file cds_handler.hpp.
Referenced by add_msg_to_rqst_queue(), check_request_queue(), closeout_device_map(), do_static_discovery(), init_channel_values_callback(), init_device_map(), process_device_data(), process_subscription_update(), and set_channel_value().
long int px::asio::CCdsHandler::_override_pacing protected
Definition at line 896 of file cds_handler.hpp.
Referenced by do_static_discovery(), and set_override_pacing().
px::string px::asio::CCdsHandler::_session_token protected
Holds the session token that we are logged into the CDS with.
Definition at line 899 of file cds_handler.hpp.
Referenced by cds_login(), and get_session_token().
px::CBitset<px::permissions> px::asio::CCdsHandler::_my_perms protected
This client's set of permissions.
Definition at line 902 of file cds_handler.hpp.
Referenced by cds_login(), and check_permission().
cds_alarm_callback_t px::asio::CCdsHandler::_update_alarm_callback protected
uniquely maps an alarm ID to a px::CAlarmUpdate object
maps device IDs to all of its' alarm IDs The callback function to the application to let it handle the updating of an existing px::CAlarmUpdate container, after this handler has updated its data. The application gets a read-only (const) copy of the container.
Definition at line 913 of file cds_handler.hpp.
Referenced by do_alarm_discovery(), init_alarm_callback(), and process_subscription_update().
channel_value_map_t px::asio::CCdsHandler::_channel_values protected
Our internal map of all Channel Values (if desired)
Definition at line 916 of file cds_handler.hpp.
Referenced by closeout_device_map(), get_channel_value(), process_channel_value(), process_subscription_update(), and set_channel_value().
std::recursive_mutex px::asio::CCdsHandler::_channel_map_mutex protected
A mutex to protect iterative access or updating of the map of Channel Values.
Definition at line 919 of file cds_handler.hpp.
Referenced by closeout_device_map(), get_channel_value(), process_channel_value(), process_subscription_update(), and set_channel_value().
unsigned int px::asio::CCdsHandler::_submit_wait_count protected
A simple up-counter for each call to submit_wait().
Can be used to detect "unexpected" submit_wait() calls in running code.
Definition at line 923 of file cds_handler.hpp.
Referenced by get_submit_wait_count(), and submit_wait().
The documentation for this class was generated from the following files:
cds_handler.hpp
cds_handler.cpp