libpx: px::db::CIterator Class Reference
px::db::CIterator Class Reference
Iterator into a sorted string table or key/value database.
#include <iterator.hpp>
Public Member Functions
PUBLIC CIterator (leveldb::Iterator *piter, const std::shared_ptr< CIteratorOwner > &owner)
Constructor.
PUBLIC CIterator (CIterator &&orig)
Move constructor.
PUBLIC ~CIterator ()
Destructor.
PUBLIC void close ()
Close the iterator.
PUBLIC bool valid () const
Is the iterator valid?
PUBLIC void first ()
Find the first entry in the table/database.
PUBLIC void last ()
Find the last entry in the table/database.
PUBLIC void seek (const CBlobHolder &key)
Find the first entry >= the given key in the table/database.
PUBLIC CIterator & operator++ ()
Pre-increment operator.
PUBLIC CIterator & operator-- ()
Pre-decrement operator.
PUBLIC leveldb::Slice key () const
Get the key for the current iterator position.
PUBLIC leveldb::Slice value () const
Get the value for the current iterator position.
PUBLIC const unsigned char * key_data () const
Get pointer to key value for the current iterator position.
PUBLIC uint32_t key_size () const
Get length of key value for the current iterator position.
PUBLIC const unsigned char * value_data () const
Get pointer to value value for the current iterator position.
PUBLIC uint32_t value_size () const
Get length of value value for the current iterator position.
Private Member Functions
void check () const
This call will trigger an assertion failure if the iterator points to a table/database that is no longer open.
void force_close ()
Useful for unit testing – force a close of the iterator, bypassing the usual sanity checks.
Private Attributes
std::unique_ptr
< leveldb::Iterator > _iter
Iterator into a sstable or database.
std::weak_ptr< CIteratorOwner > _owner
Dummy "owner" for this iterator.
Detailed Description
Iterator into a sorted string table or key/value database.
This class is a simple wrapper for the underlying implementation's iterator functionality. It's primarily useful because we can use it to enforce good programming, by detecting mis-use when the original table or database is closed while there are still outstanding iterators present.
Definition at line 29 of file iterator.hpp.
Constructor & Destructor Documentation
px::db::CIterator::CIterator (leveldb::Iterator * piter, const std::shared_ptr< CIteratorOwner > & owner)
Constructor.
Creates a new iterator into a sstable or database
Parameters
piter The underlying iterator object
owner The "owner" of this iterator
Definition at line 13 of file iterator.cpp.
References _iter.
px::db::CIterator::CIterator (CIterator && orig)
Move constructor.
Parameters
orig The object to be moved into this one's place
Definition at line 25 of file iterator.cpp.
px::db::CIterator::~CIterator ()
Destructor.
Automatically close()s the iterator, if necessary.
Definition at line 33 of file iterator.cpp.
Member Function Documentation
void px::db::CIterator::close ()
Close the iterator.
This is often not needed, since the iterator will be closed upon destruction. However, it's useful both for unit testing, and in scenarios in which (for whatever reason) you have an iterator object which must live beyond the lifetime of the table/database that it was acquired from.
This call will trigger an assertion failure if the iterator points to a table/database that is no longer open.
Definition at line 41 of file iterator.cpp.
bool px::db::CIterator::valid () const
Is the iterator valid?
This should be called after any of the functions below which modify the iterator's position, to ensure that it's pointing to a valid entry afterward.
Returns
true iff the iterator currently points to a valid entry
Definition at line 49 of file iterator.cpp.
Referenced by px::db::allocate_ids(), BOOST_AUTO_TEST_CASE(), px::db::CheckIDDB(), px::db::CleanupAlarms(), px::db::DeleteAlarms(), px::db::DeleteClosedAlarms(), px::db::DeleteTrends(), px::db::DeleteTrendsInternal(), px::db::DoesKeyExist(), px::db::ExportTrendBucket(), px::db::ExportTrendStage(), px::db::FetchCCLEntry(), px::db::FetchChannels(), px::db::FetchDevices(), px::db::FetchMCLEntry(), px::db::FetchOOB(), px::db::FetchOOBKeys(), px::db::FetchOOBs(), px::db::GetSchemaVersion(), px::db::IsTrendStageDbTombstoned(), px::db::LevelupBucketTrends(), px::db::LevelupBucketTrendsForChannel(), px::db::LoadActiveAlarms(), px::db::MigrateAlarmDB(), px::db::MigrateChannelDB(), px::db::MigrateDeviceDB(), px::db::MoveTrendsFromStageToBucket(), px::db::query_alarm_index_db(), px::db::QueryAlarms(), px::db::QueryAlarmsLatestUpdate(), px::db::QueryTrendStage(), px::db::ReadTrendKey(), px::db::ReadTrendsFromStageRow(), px::db::reserve_ids(), and px::db::SetTrendStageDbTombstoned().
void px::db::CIterator::first ()
Find the first entry in the table/database.
Definition at line 66 of file iterator.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), px::db::CleanupAlarms(), px::db::DeleteAlarms(), px::db::DeleteClosedAlarms(), px::db::ExportTrendStage(), px::db::FetchChannels(), px::db::FetchDevices(), px::db::FetchOOBKeys(), px::db::FetchOOBs(), px::db::MigrateAlarmDB(), px::db::MigrateChannelDB(), px::db::MigrateDeviceDB(), and px::db::MoveTrendsFromStageToBucket().
void px::db::CIterator::last ()
Find the last entry in the table/database.
Definition at line 78 of file iterator.cpp.
Referenced by px::db::CheckIDDB(), px::db::query_alarm_index_db(), px::db::QueryAlarms(), and px::db::QueryAlarmsLatestUpdate().
void px::db::CIterator::seek (const CBlobHolder & key)
Find the first entry >= the given key in the table/database.
Parameters
key The key to search for
Definition at line 90 of file iterator.cpp.
References px::db::CBlobHolder::get().
Referenced by px::db::allocate_ids(), px::db::CheckIDDB(), px::db::DeleteAlarms(), px::db::DeleteTrendsInternal(), px::db::DoesKeyExist(), px::db::ExportTrendBucket(), px::db::ExportTrendStage(), px::db::FetchCCLEntry(), px::db::FetchMCLEntry(), px::db::FetchOOB(), px::db::GetSchemaVersion(), px::db::IsTrendStageDbTombstoned(), px::db::LoadActiveAlarms(), px::db::query_alarm_index_db(), px::db::QueryAlarms(), px::db::QueryTrendStage(), px::db::reserve_ids(), and px::db::SeekTrendIterator().
px::db::CIterator & px::db::CIterator::operator++ ()
Pre-increment operator.
Go to the next entry in the table/database
Definition at line 102 of file iterator.cpp.
px::db::CIterator & px::db::CIterator::operator-- ()
Pre-decrement operator.
Go to the previous entry in the table/database
Definition at line 115 of file iterator.cpp.
leveldb::Slice px::db::CIterator::key () const
Get the key for the current iterator position.
Returns
The binary key for this position in the table/database
Definition at line 128 of file iterator.cpp.
leveldb::Slice px::db::CIterator::value () const
Get the value for the current iterator position.
Returns
The binary value for this position in the table/database
Definition at line 139 of file iterator.cpp.
const unsigned char * px::db::CIterator::key_data () const
Get pointer to key value for the current iterator position.
Returns
unsigned char * pointer to the key data
Definition at line 147 of file iterator.cpp.
Referenced by px::db::allocate_ids(), px::db::CheckIDDB(), px::db::CleanupAlarms(), px::db::DeleteAlarms(), px::db::DeleteTrends(), px::db::DeleteTrendsInternal(), px::db::DoesKeyExist(), px::db::ExportTrendBucket(), px::db::ExportTrendStage(), px::db::FetchCCLEntry(), px::db::FetchChannels(), px::db::FetchDevices(), px::db::FetchMCLEntry(), px::db::FetchOOB(), px::db::FetchOOBKeys(), px::db::FetchOOBs(), px::db::GetSchemaVersion(), px::db::IsTrendStageDbTombstoned(), px::db::LevelupBucketTrendsForChannel(), px::db::LoadActiveAlarms(), px::db::MigrateAlarmDB(), px::db::MigrateChannelDB(), px::db::MigrateDeviceDB(), px::db::MoveTrendsFromStageToBucket(), px::db::query_alarm_index_db(), px::db::QueryAlarms(), px::db::QueryAlarmsLatestUpdate(), px::db::QueryTrendStage(), px::db::ReadTrendKey(), px::db::ReadTrendsFromStageRow(), px::db::reserve_ids(), and px::db::SetTrendStageDbTombstoned().
uint32_t px::db::CIterator::key_size () const
Get length of key value for the current iterator position.
Returns
Integer length of valid data at key_data() (may be 0)
Definition at line 154 of file iterator.cpp.
Referenced by px::db::allocate_ids(), px::db::CheckIDDB(), px::db::CleanupAlarms(), px::db::DeleteAlarms(), px::db::DeleteClosedAlarms(), px::db::DeleteTrends(), px::db::DeleteTrendsInternal(), px::db::DoesKeyExist(), px::db::ExportTrendBucket(), px::db::ExportTrendStage(), px::db::FetchCCLEntry(), px::db::FetchChannels(), px::db::FetchDevices(), px::db::FetchMCLEntry(), px::db::FetchOOB(), px::db::FetchOOBKeys(), px::db::FetchOOBs(), px::db::GetSchemaVersion(), px::db::IsTrendStageDbTombstoned(), px::db::LevelupBucketTrendsForChannel(), px::db::LoadActiveAlarms(), px::db::MigrateAlarmDB(), px::db::MigrateChannelDB(), px::db::MigrateDeviceDB(), px::db::MoveTrendsFromStageToBucket(), px::db::query_alarm_index_db(), px::db::QueryAlarms(), px::db::QueryAlarmsLatestUpdate(), px::db::QueryTrendStage(), px::db::ReadTrendKey(), px::db::reserve_ids(), and px::db::SetTrendStageDbTombstoned().
const unsigned char * px::db::CIterator::value_data () const
Get pointer to value value for the current iterator position.
Returns
unsigned char * pointer to the value data
Definition at line 161 of file iterator.cpp.
Referenced by px::db::allocate_ids(), px::db::CheckIDDB(), px::db::CleanupAlarms(), px::db::DeleteAlarms(), px::db::DeleteClosedAlarms(), px::db::ExportTrendStage(), px::db::ExportTrendStageRow(), px::db::FetchCCLEntry(), px::db::FetchChannels(), px::db::FetchDevices(), px::db::FetchMCLEntry(), px::db::FetchOOB(), px::db::FetchOOBs(), px::db::GetSchemaVersion(), px::db::LevelupBucketTrendsRow(), px::db::LoadActiveAlarms(), px::db::MigrateAlarmDB(), px::db::MigrateChannelDB(), px::db::MigrateDeviceDB(), px::db::MoveTrendsFromStageToBucket(), px::db::query_alarm_index_db(), px::db::QueryAlarms(), px::db::QueryAlarmsLatestUpdate(), px::db::QueryTrendStage(), px::db::ReadTrendsFromBucketRow(), px::db::ReadTrendsFromStageRow(), and px::db::reserve_ids().
uint32_t px::db::CIterator::value_size () const
Get length of value value for the current iterator position.
Returns
Integer length of valid data at value_data() (may be 0)
Definition at line 168 of file iterator.cpp.
Referenced by px::db::CheckIDDB(), px::db::CleanupAlarms(), px::db::DeleteAlarms(), px::db::DeleteClosedAlarms(), px::db::DeleteTrends(), px::db::ExportTrendStage(), px::db::ExportTrendStageRow(), px::db::FetchCCLEntry(), px::db::FetchChannels(), px::db::FetchDevices(), px::db::FetchMCLEntry(), px::db::FetchOOB(), px::db::FetchOOBs(), px::db::GetSchemaVersion(), px::db::LevelupBucketTrendsRow(), px::db::LoadActiveAlarms(), px::db::MigrateAlarmDB(), px::db::MigrateChannelDB(), px::db::MigrateDeviceDB(), px::db::MoveTrendsFromStageToBucket(), px::db::QueryAlarms(), px::db::QueryAlarmsLatestUpdate(), px::db::QueryTrendStage(), px::db::ReadTrendsFromBucketRow(), and px::db::ReadTrendsFromStageRow().
void px::db::CIterator::check () const private
This call will trigger an assertion failure if the iterator points to a table/database that is no longer open.
Will throw px::db_corrupt exception if the _iter leveldb::Iterator status is bad.
Definition at line 178 of file iterator.cpp.
void px::db::CIterator::force_close () private
Useful for unit testing – force a close of the iterator, bypassing the usual sanity checks.
Definition at line 197 of file iterator.cpp.
Referenced by px::db::CTestHelper::iterator_force_close().
Member Data Documentation
std::unique_ptr<leveldb::Iterator> px::db::CIterator::_iter private
Iterator into a sstable or database.
Definition at line 203 of file iterator.hpp.
Referenced by CIterator().
std::weak_ptr<CIteratorOwner> px::db::CIterator::_owner private
Dummy "owner" for this iterator.
Definition at line 208 of file iterator.hpp.
The documentation for this class was generated from the following files:
iterator.hpp
iterator.cpp