libpx: px::generic_err Struct Reference
px::generic_err Struct Reference
Exception class used to indicate a generic error.
#include <exception.hpp>
Public Member Functions
generic_err (const char *desc="") noexcept
Constructor.
generic_err (const std::string &desc) noexcept
Constructor.
generic_err (const px::string &desc) noexcept
Constructor.
virtual const char * what () const noexcept
Private Attributes
px::string _desc
A description for the exception.
Detailed Description
Exception class used to indicate a generic error.
This is used as the fallback error for various corner-case conditions throughout the Toolkit which are "true errors", but don't need a specifically-enumerated exception.
Definition at line 23 of file exception.hpp.
Constructor & Destructor Documentation
px::generic_err::generic_err (const char * desc = "") noexcept
Constructor.
Parameters
desc A description for the exception.
Definition at line 35 of file exception.hpp.
References _desc.
px::generic_err::generic_err (const std::string & desc) noexcept
Constructor.
Parameters
desc A description for the exception.
Definition at line 48 of file exception.hpp.
References _desc.
px::generic_err::generic_err (const px::string & desc) noexcept
Constructor.
Parameters
desc A description for the exception.
Definition at line 58 of file exception.hpp.
References _desc.
Member Function Documentation
virtual const char* px::generic_err::what () const virtual noexcept
Definition at line 64 of file exception.hpp.
References _desc.
Referenced by px::CChannel::CChannel(), px::asio::CCdsSyncIO::cds_login(), px::asio::CCdsHandler::check_permission(), px::image_util::CheckSignature(), px::asio::CCdsSyncIO::clear_oob(), px::asio::CTcpListener::CTcpListener(), px::asio::CCdsSyncIO::delete_channels(), px::db::DeleteAlarms(), px::db::DeleteClosedAlarms(), px::db::DeleteTrends(), px::db::DeleteTrendsInternal(), px::db::FetchMCLEntry(), px::asio::CCdsSyncIO::get_channels(), px::asio::CCdsSyncIO::get_channels_by_name(), px::asio::CCdsSyncIO::get_devices(), px::CChannelSettings::get_field_by_name(), px::CChannel::get_field_by_name(), px::CDevice::get_field_by_name(), px::asio::CCdsSyncIO::get_oob(), px::asio::CCdsSyncIO::get_oob_field(), px::asio::CCdsSyncIO::get_oob_tags(), px::cds::logout_session(), px::db::MigrateAlarmDB(), px::asio::CCdsSyncIO::ping_watchdog_s(), px::asio::CIoManager::run(), px::asio::CCdsSyncIO::set_device_guid(), px::asio::CCdsSyncIO::set_field(), px::asio::CCdsSyncIO::set_oob_wait(), px::cds::CClient::submit(), px::cds::CClient::submit_wait(), px::asio::CCdsSyncIO::subscribe_oob(), and px::asio::CCdsSyncIO::unsubscribe_oob().
Member Data Documentation
px::string px::generic_err::_desc private
A description for the exception.
Implemented here as a string since it must remain valid for the lifetime of the exception object, and can't rely on a static character array from program text
Definition at line 87 of file exception.hpp.
Referenced by generic_err(), and what().
The documentation for this struct was generated from the following file:
exception.hpp