libpx: px::asio::CProtocolHandler Class Reference
px::asio::CProtocolHandler Class Reference abstract
ASIO interface details and general IO functions.
Protocol handler abstraction layerThis ABC defines interfaces that are needed by higher-level code which knows nothing about the specific protocol in question.
#include <protocol_handler.hpp>
Public Member Functions
PUBLIC CProtocolHandler (CIoTransactor *transactor)
Constructor.
virtual PUBLIC ~CProtocolHandler ()
Destructor.
PUBLIC CServerCore & get_server_core () const
Get a handle to the server core under which this actor is running.
virtual bool parse ()=0
Try to parse the given buffer.
virtual std::shared_ptr
< CProtocolHandler > clone (CIoTransactor *transactor) const =0
Clone this protocol object.
virtual px::string protocol () const =0
Getter for the string to identify the protocol for session tracking and debugging purposes.
virtual void close ()=0
called when the transactor is shutting down to clean up protocol handler
Public Attributes
size_t chunk_size
Chunk size for the internal read/write buffer.
Protected Attributes
CIoTransactor * _transactor
The messenger-type actor which owns this protocol handler.
Detailed Description
Protocol handler abstraction layer
This ABC defines interfaces that are needed by higher-level code which knows nothing about the specific protocol in question.
Definition at line 26 of file protocol_handler.hpp.
Constructor & Destructor Documentation
px::asio::CProtocolHandler::CProtocolHandler (CIoTransactor * transactor)
Constructor.
Parameters
transactor The messenger-type actor which owns this handler.
Definition at line 11 of file protocol_handler.cpp.
px::asio::CProtocolHandler::~CProtocolHandler () virtual
Destructor.
Needed when derived classes are freed or memory leak will occur.
Definition at line 20 of file protocol_handler.cpp.
Member Function Documentation
CServerCore & px::asio::CProtocolHandler::get_server_core () const
Get a handle to the server core under which this actor is running.
Returns
The server core object that [ultimately] contains this I/O actor
Definition at line 32 of file protocol_handler.cpp.
References _transactor, and px::asio::CIoActor::get_server_core().
virtual bool px::asio::CProtocolHandler::parse () pure virtual
Try to parse the given buffer.
This call parses an input buffer, assigning internal parameters to match the parsed request wherever possible. If parsing is successful, these internal parameters are used to service the request. No further calls are necessary; the protocol handler will take whatever action is required (generating an error, a valid response, etc.) based on the parsing results, and will invoke callbacks on the messenger to drive it to the next state.
Returns
True if parsing is complete (whether it was successful or an error occurred); false if more data is needed before parsing can proceed.
virtual std::shared_ptr<CProtocolHandler> px::asio::CProtocolHandler::clone (CIoTransactor * transactor) const pure virtual
Clone this protocol object.
This is used to create another suitably-typed protocol object without having any knowledge of the specific kind of object already in use.
Parameters
transactor The messenger-type actor which owns this handler
Returns
A new protocol object whose type/configuration is identical to our own
virtual px::string px::asio::CProtocolHandler::protocol () const pure virtual
Getter for the string to identify the protocol for session tracking and debugging purposes.
Virtual here, to be implemented in the derived class.
Referenced by px::asio::CTcpListener::CTcpListener(), px::asio::CUdpListener::CUdpListener(), px::asio::CUdpSender::CUdpSender(), and px::asio::CUdsDgramListener::CUdsDgramListener().
virtual void px::asio::CProtocolHandler::close () pure virtual
called when the transactor is shutting down to clean up protocol handler
Member Data Documentation
size_t px::asio::CProtocolHandler::chunk_size
Chunk size for the internal read/write buffer.
Definition at line 107 of file protocol_handler.hpp.
CIoTransactor* px::asio::CProtocolHandler::_transactor protected
The messenger-type actor which owns this protocol handler.
Definition at line 117 of file protocol_handler.hpp.
Referenced by get_server_core().
The documentation for this class was generated from the following files:
protocol_handler.hpp
protocol_handler.cpp