libpx: px::eq::detail Namespace Reference
px::eq::detail Namespace Reference
Classes
class binary_eval
This visitor class is used to evaluate a binary expression and produce some result.
class binary_expression
Proxy class for the binary expression variant.
class assign_op
Assignment, i.e.
class index_op
Array-like indexing, i.e.
class plus_op
Addition, i.e.
class minus_op
Subtraction, i.e.
class multiply_op
Multiplication, i.e.
class divide_op
Division, i.e.
class less_than_op
Less-than comparison, i.e.
class greater_than_op
Greater-than comparison, i.e.
class less_equal_op
Less-than-or-equal comparison, i.e.
class greater_equal_op
Greater-than-or-equal comparison, i.e.
class not_equal_op
Not-equal comparison, i.e.
class equal_op
Equality comparison, i.e.
class power_op
Power operation, i.e.
class arithmetic_and_op
Bitwise AND operation, i.e.
class arithmetic_or_op
Bitwise OR operation, i.e.
class logical_and_op
Logical AND operation, i.e.
class logical_or_op
Logical OR operation, i.e.
class rshift_op
Right shift operation, i.e.
class lshift_op
Left shift operation, i.e.
class binary_op
This class template defines the format for a binary operation, which acts on two sub-expressions to produce a singular result.
class exec
This visitor class is used to execute a statement.
class cond_eval
This visitor class is used to evaluate a condition, potentially executing a statement based on the result.
class while_op
This empty class is used to indicate a while() loop condition.
class if_then_op
This empty class is used to indicate an "if/then/else" statement.
class cond_op
This class template defines the format for a condition, which evaluates a single expression, and (based on its results) executes one out of two statements.
class condition
Proxy class for the condition variant.
class constant
Trivial definition for a single input constant.
class eval
This visitor class is used to evaluate an expression and produce some result.
class expression
Proxy class for the expression variant.
class no_op
This is a dummy type used for no-ops.
class statement
Proxy class for the statement variant.
class string_constant
Trivial definition for a single input variable.
class unary_eval
This visitor class is used to evaluate a unary expression and produce some result.
class unary_expression
Proxy class for the unary expression variant.
class arithmetic_negate_op
Arithmetic negation, i.e.
class logical_negate_op
Logical negation, i.e.
class sqrt_op
Square root operation.
class abs_op
Absolute value operation.
class round_op
Round to the nearest integer.
class trunc_op
Truncate (round toward zero)
class ceil_op
Ceiling (round upward)
class floor_op
Floor (round downward)
class exp_op
Exponentiation operation.
class isnan_op
Helpful isnan() operation.
class isinf_op
Helpful isinf() operation.
class unary_op
This class template defines the format for a unary operation, which acts on one sub-expression to produce a singular result.
class variable
Trivial definition for a single input variable.
class variadic_eval
This visitor class is used to evaluate a variadic expression and produce some result.
class min_op
Minimum value of a series of arguments.
class max_op
Maximum value of a series of arguments.
class sum_op
Sum of a series of arguments.
class mean_op
Mean (average) of a series of arguments.
class variadic_op
This class template defines the format for a variadic operation, which acts on a variable number of sub-expressions to produce a singular result.
struct parser_state
Internal options passed around in library scanning/parsing code.
union YYSTYPE
union yyalloc
Typedefs
typedef boost::variant
< boost::recursive_wrapper
< binary_op< assign_op >
>, boost::recursive_wrapper
< binary_op< index_op >
>, boost::recursive_wrapper
< binary_op< plus_op >
>, boost::recursive_wrapper
< binary_op< minus_op >
>, boost::recursive_wrapper
< binary_op< multiply_op >
>, boost::recursive_wrapper
< binary_op< divide_op >
>, boost::recursive_wrapper
< binary_op< less_than_op >
>, boost::recursive_wrapper
< binary_op< greater_than_op >
>, boost::recursive_wrapper
< binary_op< less_equal_op >
>, boost::recursive_wrapper
< binary_op< greater_equal_op >
>, boost::recursive_wrapper
< binary_op< not_equal_op >
>, boost::recursive_wrapper
< binary_op< equal_op >
>, boost::recursive_wrapper
< binary_op< power_op >
>, boost::recursive_wrapper
< binary_op< arithmetic_and_op >
>, boost::recursive_wrapper
< binary_op< arithmetic_or_op >
>, boost::recursive_wrapper
< binary_op< logical_and_op >
>, boost::recursive_wrapper
< binary_op< logical_or_op >
>, boost::recursive_wrapper
< binary_op< rshift_op >
>, boost::recursive_wrapper
< binary_op< lshift_op > > > binary_variant
This defines the various types of binary expressions we support.
typedef boost::variant
< cond_op< while_op >, cond_op
< if_then_op > > condition_variant
This defines the various types of conditions we support.
typedef boost::variant
< constant, string_constant,
variable,
boost::recursive_wrapper
< unary_expression >
, boost::recursive_wrapper
< binary_expression >
, variadic_expression > expression_variant
This defines the various types that can constitute an expression.
typedef boost::variant< no_op,
expression,
boost::recursive_wrapper
< condition >, std::vector
< statement > > statement_variant
This defines the various types that can constitute a statement.
typedef boost::variant
< unary_op
< arithmetic_negate_op >
, unary_op< logical_negate_op >
, unary_op< sqrt_op >
, unary_op< abs_op >, unary_op
< round_op >, unary_op
< trunc_op >, unary_op
< ceil_op >, unary_op
< floor_op >, unary_op< exp_op >
, unary_op< isnan_op >
, unary_op< isinf_op > > unary_variant
This defines the various types of unary expressions we support.
typedef boost::variant
< variadic_op< min_op >
, variadic_op< max_op >
, variadic_op< sum_op >
, variadic_op< mean_op > > variadic_expression
This defines the various types of variadic expressions we support.
typedef union
px::eq::detail::YYSTYPE YYSTYPE
typedef unsigned char yytype_uint8
typedef short int yytype_int8
typedef unsigned short int yytype_uint16
typedef short int yytype_int16
Enumerations
enum yytokentype {
T_STRING_CONSTANT = 258, T_FLOAT = 259, T_IDENTIFIER = 260, T_WHILE = 261,
T_IF = 262, T_SQRT = 263, T_MIN = 264, T_MAX = 265,
T_AVG = 266, T_SUM = 267, T_ABS = 268, T_ROUND = 269,
T_TRUNC = 270, T_CEIL = 271, T_FLOOR = 272, T_EXP = 273,
T_ISNAN = 274, T_ISINF = 275, T_IFX = 276, T_ELSE = 277,
T_OR = 278, T_AND = 279, T_NE = 280, T_EQ = 281,
T_LE = 282, T_GE = 283, T_LSHIFT = 284, T_RSHIFT = 285,
T_UMINUS = 286
}
Functions
static void yyerror (const char *s)
static int yyparse (void *arg)
static int my_yyinput (char *buf, int max_size, void *arg)
static void assign_top_stmt (void *arg, statement *stmt)
YYUSE (yyvaluep)
if (!yymsg)
YY_SYMBOL_PRINT (yymsg, yytype, yyvaluep, yylocationp)
switch (yytype)
int yyparse ()
YYDPRINTF ((stderr,"Starting parse\n"))
if (yyss+yystacksize-1<=yyssp)
YYDPRINTF ((stderr,"Entering state %d\n", yystate))
if (yystate==YYFINAL)
if (yychar==YYEMPTY)
if (yychar<=YYEOF)
YY_SYMBOL_PRINT ("Next token is", yytoken,&yylval,&yylloc)
if ((yyn< 0)||(YYLAST< yyn)||(yycheck[yyn]!=yytoken))
if (yyn<=0)
if (yyerrstatus)
YY_SYMBOL_PRINT ("Shifting", yytoken,&yylval,&yylloc)
if (yyn==0)
YY_REDUCE_PRINT (yyn)
switch (yyn)
YY_SYMBOL_PRINT ("-> $$ =", yyr1[yyn],&yyval,&yyloc)
YYPOPSTACK (yylen)
YY_STACK_PRINT (yyss, yyssp)
if ((0<=yystate)&&(yystate<=YYLAST)&&(yycheck[yystate]==*yyssp))
for (;;)
YY_SYMBOL_PRINT ("Shifting", yystos[yyn], yyvsp, yylsp)
yydestruct ("Cleanup: discarding lookahead", yytoken,&yylval)
while (yyssp!=yyss)
if (yyss!=yyssa)
return (YYID(yyresult))
Variables
static const yytype_uint8 yytranslate []
static const yytype_uint8 yyr1 []
static const yytype_uint8 yyr2 []
static const yytype_uint8 yydefact []
static const yytype_int8 yydefgoto []
static const yytype_int16 yypact []
static const yytype_int16 yypgoto []
static const yytype_uint8 yytable []
static const yytype_int8 yycheck []
static const yytype_uint8 yystos []
static void const char * yymsg
int yytype
YYSTYPE * yyvaluep
int void * YYPARSE_PARAM
YYSTYPE yylval
int yynerrs = 0
int yystate = 0
int yyerrstatus = 0
yytype_int16 yyssa [YYINITDEPTH]
yytype_int16 * yyss = yyssa
yytype_int16 * yyssp = yyss
YYSTYPE yyvsa [YYINITDEPTH]
YYSTYPE * yyvs = yyvsa
YYSTYPE * yyvsp = yyvs
YYSIZE_T yystacksize = YYINITDEPTH
int yyn = yytoken
int yyresult = 2
int yytoken = 0
YYSTYPE yyval = yyvsp[1 - yylen]
int yylen = 0
yychar = YYEMPTY
goto yysetstate
yynewstate __pad0__
yysetstate __pad1__
goto yybackup
yybackup __pad2__
else
goto yynewstate
yydefault __pad3__
goto yyreduce
yyreduce __pad4__
yyerrlab __pad5__
goto yyerrlab1
yyerrorlab __pad6__
yyerrlab1 __pad7__
yyacceptlab __pad8__
goto yyreturn
yyabortlab __pad9__
yyexhaustedlab __pad10__
yyreturn __pad11__
Typedef Documentation
typedef boost::variant< boost::recursive_wrapper<binary_op<assign_op> >, boost::recursive_wrapper<binary_op<index_op> >, boost::recursive_wrapper<binary_op<plus_op> >, boost::recursive_wrapper<binary_op<minus_op> >, boost::recursive_wrapper<binary_op<multiply_op> >, boost::recursive_wrapper<binary_op<divide_op> >, boost::recursive_wrapper<binary_op<less_than_op> >, boost::recursive_wrapper<binary_op<greater_than_op> >, boost::recursive_wrapper<binary_op<less_equal_op> >, boost::recursive_wrapper<binary_op<greater_equal_op> >, boost::recursive_wrapper<binary_op<not_equal_op> >, boost::recursive_wrapper<binary_op<equal_op> >, boost::recursive_wrapper<binary_op<power_op> >, boost::recursive_wrapper<binary_op<arithmetic_and_op> >, boost::recursive_wrapper<binary_op<arithmetic_or_op> >, boost::recursive_wrapper<binary_op<logical_and_op> >, boost::recursive_wrapper<binary_op<logical_or_op> >, boost::recursive_wrapper<binary_op<rshift_op> >, boost::recursive_wrapper<binary_op<lshift_op> > > px::eq::detail::binary_variant
This defines the various types of binary expressions we support.
ToDo: does this declaration need to be improved to satisfy boost::variant's type checking? The warning of "skipping 20 instantiation contexts" suggests this one is at fault boost::recursive_wrapper<> described at http://www.boost.org/doc/libs/1_58_0/doc/html/variant/tutorial.html#variant.tutorial.recursive
Definition at line 40 of file binary_expr.hpp.
typedef boost::variant< cond_op<while_op>, cond_op<if_then_op> > px::eq::detail::condition_variant
This defines the various types of conditions we support.
Definition at line 18 of file condition.hpp.
typedef boost::variant< constant, string_constant, variable, boost::recursive_wrapper<unary_expression>, boost::recursive_wrapper<binary_expression>, variadic_expression > px::eq::detail::expression_variant
This defines the various types that can constitute an expression.
Definition at line 19 of file expression.hpp.
typedef boost::variant< no_op, expression, boost::recursive_wrapper<condition>, std::vector<statement> > px::eq::detail::statement_variant
This defines the various types that can constitute a statement.
Definition at line 19 of file statement.hpp.
typedef boost::variant< unary_op<arithmetic_negate_op>, unary_op<logical_negate_op>, unary_op<sqrt_op>, unary_op<abs_op>, unary_op<round_op>, unary_op<trunc_op>, unary_op<ceil_op>, unary_op<floor_op>, unary_op<exp_op>, unary_op<isnan_op>, unary_op<isinf_op> > px::eq::detail::unary_variant
This defines the various types of unary expressions we support.
Definition at line 27 of file unary_expr.hpp.
typedef boost::variant< variadic_op<min_op>, variadic_op<max_op>, variadic_op<sum_op>, variadic_op<mean_op> > px::eq::detail::variadic_expression
This defines the various types of variadic expressions we support.
Definition at line 20 of file variadic_expr.hpp.
typedef union px::eq::detail::YYSTYPE px::eq::detail::YYSTYPE
typedef unsigned char px::eq::detail::yytype_uint8
Definition at line 289 of file equation.tab.cpp.
typedef short int px::eq::detail::yytype_int8
Definition at line 298 of file equation.tab.cpp.
typedef unsigned short int px::eq::detail::yytype_uint16
Definition at line 304 of file equation.tab.cpp.
typedef short int px::eq::detail::yytype_int16
Definition at line 310 of file equation.tab.cpp.
Enumeration Type Documentation
enum px::eq::detail::yytokentype
Enumerator
T_STRING_CONSTANT
T_FLOAT
T_IDENTIFIER
T_WHILE
T_IF
T_SQRT
T_MIN
T_MAX
T_AVG
T_SUM
T_ABS
T_ROUND
T_TRUNC
T_CEIL
T_FLOOR
T_EXP
T_ISNAN
T_ISINF
T_IFX
T_ELSE
T_OR
T_AND
T_NE
T_EQ
T_LE
T_GE
T_LSHIFT
T_RSHIFT
T_UMINUS
Definition at line 219 of file equation.tab.cpp.
Function Documentation
static void px::eq::detail::yyerror (const char * s) static
Definition at line 2403 of file equation.tab.cpp.
static int px::eq::detail::yyparse (void * arg) static
Referenced by px::eq::CEquation::parse().
static int px::eq::detail::my_yyinput (char * buf, int max_size, void * arg) static
Definition at line 155 of file equation.tab.cpp.
References px::eq::detail::parser_state::input_end, and px::eq::detail::parser_state::input_ptr.
static void px::eq::detail::assign_top_stmt (void * arg, statement * stmt) static
Definition at line 179 of file equation.tab.cpp.
References px::eq::detail::parser_state::stmt, and yyguts_t::yyextra_r.
Referenced by switch().
px::eq::detail::YYUSE (yyvaluep)
px::eq::detail::if (! yymsg)
Definition at line 1425 of file equation.tab.cpp.
px::eq::detail::YY_SYMBOL_PRINT (yymsg , yytype , yyvaluep , yylocationp)
px::eq::detail::switch (yytype)
Definition at line 1431 of file equation.tab.cpp.
int px::eq::detail::yyparse ()
px::eq::detail::YYDPRINTF ((stderr,"Starting parse\n"))
Referenced by if().
px::eq::detail::if (yyss+yystacksize-1<= yyssp)
Definition at line 1564 of file equation.tab.cpp.
References YY_, YYABORT, YYDPRINTF(), YYMAXDEPTH, YYSIZE_T, yyss, YYSTACK_ALLOC, YYSTACK_BYTES, YYSTACK_FREE, YYSTACK_RELOCATE, and yyvs.
px::eq::detail::YYDPRINTF ((stderr,"Entering state %d\n", yystate))
px::eq::detail::if (yystate = = YYFINAL)
Definition at line 1637 of file equation.tab.cpp.
References YYACCEPT.
px::eq::detail::if (yychar = = YYEMPTY)
Definition at line 1662 of file equation.tab.cpp.
References YYDPRINTF(), and YYLEX.
px::eq::detail::if (yychar<= YYEOF)
Definition at line 1668 of file equation.tab.cpp.
References YYDPRINTF(), and YYEOF.
px::eq::detail::YY_SYMBOL_PRINT ("Next token is" , yytoken , & yylval, & yylloc)
px::eq::detail::if ((yyn< 0)||(YYLAST< yyn)||(yycheck[yyn]!=yytoken))
Definition at line 1682 of file equation.tab.cpp.
px::eq::detail::if (yyn<= 0)
Definition at line 1687 of file equation.tab.cpp.
References yyn, yyreduce, and yytable_value_is_error.
px::eq::detail::if (yyerrstatus = = 3)
Definition at line 1699 of file equation.tab.cpp.
px::eq::detail::YY_SYMBOL_PRINT ("Shifting" , yytoken , & yylval, & yylloc)
px::eq::detail::if (yyn = = 0)
Definition at line 1721 of file equation.tab.cpp.
px::eq::detail::YY_REDUCE_PRINT (yyn)
px::eq::detail::switch (yyn)
Definition at line 1747 of file equation.tab.cpp.
References arg_add_to_list(), px::eq::detail::YYSTYPE::arglist_value, assign_top_stmt(), create_arglist(), px::eq::detail::YYSTYPE::expr_value, stmt_add_to_list(), stmt_make_expr(), stmt_make_noop(), and px::eq::detail::YYSTYPE::stmt_value.
px::eq::detail::YY_SYMBOL_PRINT ()
px::eq::detail::YYPOPSTACK (yylen)
Referenced by for(), and while().
px::eq::detail::YY_STACK_PRINT (yyss , yyssp)
Referenced by for().
px::eq::detail::if ((0<=yystate)&&(yystate<=YYLAST)&&(yycheck[yystate]==*yyssp))
Definition at line 2177 of file equation.tab.cpp.
References yystate, and yytable.
px::eq::detail::for (;;)
Definition at line 2299 of file equation.tab.cpp.
References YY_STACK_PRINT(), YYABORT, yycheck, yydestruct(), YYLAST, yyn, yypact, yypact_value_is_default, YYPOPSTACK(), yyssp, yystate, yystos, yytable, and YYTERROR.
px::eq::detail::YY_SYMBOL_PRINT ("Shifting" , yystos [yyn], yyvsp , yylsp)
px::eq::detail::yydestruct ("Cleanup: discarding lookahead" , yytoken , & yylval)
Referenced by for(), and while().
px::eq::detail::while (yyssp! = yyss)
Definition at line 2376 of file equation.tab.cpp.
References yydestruct(), YYPOPSTACK(), and yystos.
px::eq::detail::if (yyss! = yyssa)
Definition at line 2383 of file equation.tab.cpp.
References YYSTACK_FREE.
px::eq::detail::return (YYID(yyresult))
Referenced by input().
Variable Documentation
const yytype_uint8 px::eq::detail::yytranslate[] static
Definition at line 520 of file equation.tab.cpp.
const yytype_uint8 px::eq::detail::yyr1[] static
Initial value:
=
{
        0,    51,    52,    53,    53,    54,    54,    54,    54,    54,
        54,    55,    55,    55,    55,    55,    55,    55,    55,    55,
        55,    55,    55,    55,    55,    55,    55,    55,    55,    55,
        55,    55,    55,    55,    55,    55,    55,    55,    55,    55,
        55,    55,    55,    55,    55,    55,    55,    55,    55,    56,
        56
}
Definition at line 635 of file equation.tab.cpp.
const yytype_uint8 px::eq::detail::yyr2[] static
Initial value:
=
{
        0,     2,     1,     1,     2,     1,     2,     5,     5,     7,
        3,     1,     1,     3,     1,     2,     2,     4,     3,     3,
        3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
        3,     3,     3,     3,     3,     4,     4,     4,     4,     4,
        4,     4,     4,     4,     4,     4,     4,     4,     3,     1,
        3
}
Definition at line 646 of file equation.tab.cpp.
const yytype_uint8 px::eq::detail::yydefact[] static
Initial value:
=
{
        0,    12,    11,    14,     0,     0,     0,     0,     0,     0,
        0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
        0,     5,     0,     0,     0,     2,     3,     0,     0,     0,
        0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
        0,     0,     0,     0,    15,    16,     0,     0,     1,     4,
        0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
        0,     0,     0,     0,     0,     0,     0,     0,     6,    13,
        0,     0,     0,    49,     0,     0,     0,     0,     0,     0,
        0,     0,     0,     0,     0,     0,    48,    10,    32,    31,
        26,    24,    25,    29,    30,    23,    22,    28,    27,    34,
        33,    18,    19,    20,    21,     0,     0,     0,    35,    42,
        0,    43,    45,    44,    36,    37,    38,    39,    40,    41,
        46,    47,    17,     7,     8,    50,     0,     9
}
Definition at line 659 of file equation.tab.cpp.
const yytype_int8 px::eq::detail::yydefgoto[] static
Initial value:
=
{
        -1,    24,    25,    26,    27,    74
}
Definition at line 677 of file equation.tab.cpp.
const yytype_int16 px::eq::detail::yypact[] static
Initial value:
=
{
        127,   -30,   -30,    -4,   -26,    32,    33,    78,    81,   128,
        133,   134,   166,   169,   172,   191,   192,   194,   195,   173,
        173,   -30,   173,   127,    42,   127,   -30,   436,   173,   173,
        173,   173,   173,   173,   173,   173,   173,   173,   173,   173,
        173,   173,   173,   173,   199,   199,   124,    80,   -30,   -30,
        173,   173,   173,   173,   173,   173,   173,   173,   173,   173,
        173,   173,   173,   173,   173,   173,   173,   173,   -30,   479,
        170,   196,   220,   479,   -29,    -6,    72,   119,   244,   268,
        292,   316,   340,   364,   388,   412,   -30,   -30,   498,    37,
        515,   -27,    77,   528,   528,   537,   537,   537,   537,   544,
        544,     0,     0,   199,   199,   458,   127,   127,   -30,   -30,
        173,   -30,   -30,   -30,   -30,   -30,   -30,   -30,   -30,   -30,
        -30,   -30,   -30,   -30,   101,   479,   127,   -30
}
Definition at line 685 of file equation.tab.cpp.
Referenced by for().
const yytype_int16 px::eq::detail::yypgoto[] static
Initial value:
=
{
        -30,   -30,   147,   -25,    -5,    69
}
Definition at line 703 of file equation.tab.cpp.
const yytype_uint8 px::eq::detail::yytable[] static
Definition at line 712 of file equation.tab.cpp.
Referenced by for(), and if().
const yytype_int8 px::eq::detail::yycheck[] static
Definition at line 781 of file equation.tab.cpp.
Referenced by for().
const yytype_uint8 px::eq::detail::yystos[] static
Initial value:
=
{
        0,     3,     4,     5,     6,     7,     8,     9,    10,    11,
        12,    13,    14,    15,    16,    17,    18,    19,    20,    38,
        41,    45,    46,    48,    52,    53,    54,    55,    23,    46,
        46,    46,    46,    46,    46,    46,    46,    46,    46,    46,
        46,    46,    46,    46,    55,    55,    55,    53,     0,    54,
        24,    25,    26,    27,    28,    29,    30,    31,    32,    33,
        34,    35,    36,    37,    38,    39,    40,    43,    45,    55,
        55,    55,    55,    55,    56,    56,    56,    56,    55,    55,
        55,    55,    55,    55,    55,    55,    47,    49,    55,    55,
        55,    55,    55,    55,    55,    55,    55,    55,    55,    55,
        55,    55,    55,    55,    55,    55,    47,    47,    47,    47,
        50,    47,    47,    47,    47,    47,    47,    47,    47,    47,
        47,    47,    44,    54,    54,    55,    22,    54
}
Definition at line 846 of file equation.tab.cpp.
Referenced by for(), and while().
void const char* px::eq::detail::yymsg static
Definition at line 1418 of file equation.tab.cpp.
int px::eq::detail::yytype
Definition at line 1419 of file equation.tab.cpp.
YYSTYPE* px::eq::detail::yyvaluep
Definition at line 1420 of file equation.tab.cpp.
int void* px::eq::detail::YYPARSE_PARAM
Definition at line 1467 of file equation.tab.cpp.
YYSTYPE px::eq::detail::yylval
Initial value:
{
        int yychar
Definition at line 1478 of file equation.tab.cpp.
px::eq::detail::yynerrs = 0
Definition at line 1486 of file equation.tab.cpp.
px::eq::detail::yystate = 0
Definition at line 1488 of file equation.tab.cpp.
Referenced by for(), and if().
px::eq::detail::yyerrstatus = 0
Definition at line 1490 of file equation.tab.cpp.
yytype_int16 px::eq::detail::yyssa[YYINITDEPTH]
Definition at line 1500 of file equation.tab.cpp.
px::eq::detail::yyss = yyssa
Definition at line 1501 of file equation.tab.cpp.
Referenced by if().
px::eq::detail::yyssp = yyss
Definition at line 1502 of file equation.tab.cpp.
Referenced by for().
YYSTYPE px::eq::detail::yyvsa[YYINITDEPTH]
Definition at line 1505 of file equation.tab.cpp.
px::eq::detail::yyvs = yyvsa
Definition at line 1506 of file equation.tab.cpp.
Referenced by if().
* px::eq::detail::yyvsp = yyvs
Definition at line 1507 of file equation.tab.cpp.
px::eq::detail::yystacksize = YYINITDEPTH
Definition at line 1509 of file equation.tab.cpp.
px::eq::detail::yyn = yytoken
Definition at line 1511 of file equation.tab.cpp.
Referenced by for(), and if().
px::eq::detail::yyresult = 2
Definition at line 1512 of file equation.tab.cpp.
px::eq::detail::yytoken = 0
Definition at line 1514 of file equation.tab.cpp.
px::eq::detail::yyval = yyvsp[1 - yylen]
Definition at line 1517 of file equation.tab.cpp.
px::eq::detail::yylen = 0
Definition at line 1530 of file equation.tab.cpp.
px::eq::detail::yychar = YYEMPTY
Definition at line 1542 of file equation.tab.cpp.
goto px::eq::detail::yysetstate
Definition at line 1551 of file equation.tab.cpp.
yynewstate px::eq::detail::__pad0__
Definition at line 1559 of file equation.tab.cpp.
yysetstate px::eq::detail::__pad1__
Definition at line 1562 of file equation.tab.cpp.
goto px::eq::detail::yybackup
Definition at line 1642 of file equation.tab.cpp.
yybackup px::eq::detail::__pad2__
Definition at line 1653 of file equation.tab.cpp.
px::eq::detail::else
Initial value:
{
                yytoken = YYTRANSLATE( yychar )
Definition at line 1674 of file equation.tab.cpp.
goto px::eq::detail::yynewstate
Definition at line 1713 of file equation.tab.cpp.
yydefault px::eq::detail::__pad3__
Definition at line 1720 of file equation.tab.cpp.
goto px::eq::detail::yyreduce
Definition at line 1725 of file equation.tab.cpp.
Referenced by if().
yyreduce px::eq::detail::__pad4__
Definition at line 1733 of file equation.tab.cpp.
yyerrlab px::eq::detail::__pad5__
Definition at line 2195 of file equation.tab.cpp.
goto px::eq::detail::yyerrlab1
Definition at line 2268 of file equation.tab.cpp.
yyerrorlab px::eq::detail::__pad6__
Definition at line 2281 of file equation.tab.cpp.
yyerrlab1 px::eq::detail::__pad7__
Definition at line 2297 of file equation.tab.cpp.
yyacceptlab px::eq::detail::__pad8__
Definition at line 2343 of file equation.tab.cpp.
goto px::eq::detail::yyreturn
Definition at line 2344 of file equation.tab.cpp.
yyabortlab px::eq::detail::__pad9__
Definition at line 2350 of file equation.tab.cpp.
yyexhaustedlab px::eq::detail::__pad10__
Definition at line 2358 of file equation.tab.cpp.
yyreturn px::eq::detail::__pad11__
Definition at line 2368 of file equation.tab.cpp.