libpx: px::asio::CUdsListener Class Reference
px::asio::CUdsListener Class Reference
ASIO interface details and general IO functions. | IO_Actors
Listener class, used to accept new UDS connections on a socket of type stream_protocol::acceptor.
#include <uds_listener.hpp>
Public Member Functions
PUBLIC CUdsListener (CIoManager &manager, const CProtocolHandler &prot, const px::string path)
Constructor.
PUBLIC ~CUdsListener ()
Destructor.
virtual PUBLIC void close ()
Gracefully close this actor.
Public Member Functions inherited from px::asio::CIoActor
CIoActor (CIoManager &manager)
Constructor.
virtual ~CIoActor ()
Destructor.
boost::asio::io_service & get_io_service () const
Get the I/O service associated with the owner of this actor.
PUBLIC CServerCore & get_server_core () const
Get the container for CDS data management.
PUBLIC CCdsHandler & get_cds_handler () const
Get the container for CDS data management.
PUBLIC bool get_quit_status ()
Get the quit status from connection IO manager.
Static Public Member Functions
static PUBLIC std::shared_ptr
< CUdsListener > create (CIoManager &manager, const CProtocolHandler &prot, const px::string path)
Factory function to create a new CUdsListener object.
Private Member Functions
PUBLIC void accept ()
Asynchronously accept a new connection.
PUBLIC void handle_accept (const boost::system::error_code &err, const std::shared_ptr< CUdsConnection > &pconn)
Callback function for Boost.Asio upon accepting a new connection.
Private Attributes
std::unique_ptr
< boost::asio::local::stream_protocol::acceptor > _acceptor
The underlying Boost.Asio UDS acceptor object.
std::shared_ptr< CProtocolHandler > _prot
Protocol-specific handler, used to parse and handle incoming requests and generate responses (needed to assign each accepted connection an appropriate protocol handler)
Additional Inherited Members
Protected Member Functions inherited from px::asio::CIoActor
void remove ()
This method is called when an actor wants to remove itself from the I/O management interface.
Protected Attributes inherited from px::asio::CIoActor
CIoManager & _owner
The I/O manager object that "owns" this connection.
Detailed Description
Listener class, used to accept new UDS connections on a socket of type stream_protocol::acceptor.
May be most useful for bidirectional connections, such as websockets (?)
Definition at line 27 of file uds_listener.hpp.
Constructor & Destructor Documentation
px::asio::CUdsListener::CUdsListener (CIoManager & manager, const CProtocolHandler & prot, const px::string path)
Constructor.
Parameters
manager The I/O manager object to which this listener is to be bound
prot Protocol handler object which is utilized to perform protocol-specific operations in an abstracted manner; the listener doesn't need this directly, but individual connections will
path The UDS path to which we should bind/listen
Exceptions
boost::system::system_error The listener could not be initialized
Definition at line 34 of file uds_listener.cpp.
References _acceptor, _prot, accept(), px::asio::CIoActor::get_io_service(), LIBPX_DEBUG, and LIBPX_FERR.
Referenced by create().
px::asio::CUdsListener::~CUdsListener ()
Destructor.
Definition at line 67 of file uds_listener.cpp.
References close(), and LIBPX_FERR.
Member Function Documentation
std::shared_ptr< CUdsListener > px::asio::CUdsListener::create (CIoManager & manager, const CProtocolHandler & prot, const px::string path) static
Factory function to create a new CUdsListener object.
Parameters
manager The I/O manager object to which this object is to be bound
prot Protocol handler object which is utilized to perform protocol-specific operations in an abstracted manner; the listener doesn't need this directly, but individual connections will
path The UDS path to which we should bind/listen
Exceptions
boost::system::system_error The listener could not be initialized
Returns
Shared pointer containing the new instance of CUdsListener.
Definition at line 19 of file uds_listener.cpp.
References CUdsListener().
void px::asio::CUdsListener::close () virtual
Gracefully close this actor.
This will gracefully close the actor. It is called automatically by the actor's destructor, but any resulting error information will be lost in that case.
Exceptions
boost::system::system_error There was an error when attempting to gracefully shut down / close
Reimplemented from px::asio::CIoActor.
Definition at line 84 of file uds_listener.cpp.
References _acceptor.
Referenced by ~CUdsListener().
void px::asio::CUdsListener::accept () private
Asynchronously accept a new connection.
This call initiates the asynchronous acceptance of a new TCP connection. When a new incoming connection is established, the handle_accept() function is called.
Exceptions
boost::system::system_error The new connection could not be created/accepted
Definition at line 95 of file uds_listener.cpp.
References _acceptor, px::asio::CIoActor::_owner, _prot, px::asio::CUdsConnection::create(), and handle_accept().
Referenced by CUdsListener(), and handle_accept().
void px::asio::CUdsListener::handle_accept (const boost::system::error_code & err, const std::shared_ptr< CUdsConnection > & pconn) private
Callback function for Boost.Asio upon accepting a new connection.
Parameters
err The error code (if any) returned from the asynchronous accept() operation
pconn The new connection object
Definition at line 116 of file uds_listener.cpp.
References _acceptor, px::asio::CIoActor::_owner, accept(), px::asio::CIoManager::add(), LIBPX_DEBUG, and LIBPX_FERR.
Referenced by accept().
Member Data Documentation
std::unique_ptr<boost::asio::local::stream_protocol::acceptor> px::asio::CUdsListener::_acceptor private
The underlying Boost.Asio UDS acceptor object.
Definition at line 128 of file uds_listener.hpp.
Referenced by accept(), close(), CUdsListener(), and handle_accept().
std::shared_ptr<CProtocolHandler> px::asio::CUdsListener::_prot private
Protocol-specific handler, used to parse and handle incoming requests and generate responses (needed to assign each accepted connection an appropriate protocol handler)
Definition at line 135 of file uds_listener.hpp.
Referenced by accept(), and CUdsListener().
The documentation for this class was generated from the following files:
uds_listener.hpp
uds_listener.cpp