libpx: px::CDataType Class Reference
px::CDataType Class Reference
This class enumerates all of the data types available for varidic data within the Toolkit (and exposed via Mercury).
#include "px/enum/datatype.hpp"
Public Member Functions
CDataType (datatype num=datatype::invalid)
Constructor.
CDataType (const char *str, unsigned int len=0)
Copy constructor.
CDataType & operator= (datatype num)
Assignment operator.
CDataType & operator= (const char *str)
Assignment operator.
bool operator== (const CDataType &x) const
Equality comparison operator.
bool operator== (datatype x) const
Equality comparison operator.
bool operator!= (const CDataType &x) const
Non-equality comparison operator.
bool operator!= (datatype x) const
Non-quality comparison operator.
bool operator< (const CDataType &x) const
Less than comparison operator.
datatype val () const
Getter for the underlying datatype enumeration.
PUBLIC const char * str () const
Getter for this canonical string associated with this datatype.
bool is_integral () const
Determine whether this type is integral.
bool is_fp () const
Determine whether this type is a floating-point number.
bool is_numeric () const
Determine whether this type is numeric.
bool is_timestamp () const
Determine whether this type is a CTimestamp.
bool is_string () const
Determine whether this type is a px::string.
bool is_binary () const
Determine whether this type is a binary vector of bytes.
bool is_boolean () const
Determine whether this type is a boolean bytes.
template<class Archive >
void serialize (Archive &ar)
Serializer.
Private Member Functions
PUBLIC void parse (const char *str, unsigned int len)
Parse an input datatype string and assign the corresponding datatype enum.
Private Attributes
datatype _val
The only data member is a single enumeration value.
Detailed Description
This class enumerates all of the data types available for varidic data within the Toolkit (and exposed via Mercury).
This list of types may be expanded in the future as needed.
Objects of this type are intended for use in lieu of the raw enumeration values wherever possible. Despite being first-class objects, they occupy only 1 byte, and impose virtually no overhead.
See px::datatype for the enumeration values used.
Definition at line 21 of file datatype.hpp.
Constructor & Destructor Documentation
px::CDataType::CDataType (datatype num = datatype::invalid)
Constructor.
Parameters
num Initial datatype value to assign to this object
Definition at line 33 of file datatype.hpp.
px::CDataType::CDataType (const char * str, unsigned int len = 0)
Copy constructor.
Parameters
x An existing datatype object whose value we duplicate
TODO: Requires delegating constructors... Constructor
Builds a datatype object from a canonical string name.
Parameters
str The canonical string name of the assigned datatype
len Length of the string; if 0, length will be determined automatically by looking for a NUL terminator
Exceptions
generic_err The provided string is unknown or invalid
Definition at line 60 of file datatype.hpp.
Member Function Documentation
CDataType& px::CDataType::operator= (datatype num)
Assignment operator.
Parameters
num datatype value to assign to this object
Returns
A handle to *this
Definition at line 74 of file datatype.hpp.
CDataType& px::CDataType::operator= (const char * str)
Assignment operator.
Parameters
str The canonical string name of the assigned datatype
Exceptions
generic_err The provided string is unknown or invalid
Returns
A handle to *this
Definition at line 89 of file datatype.hpp.
bool px::CDataType::operator== (const CDataType & x) const
Equality comparison operator.
Parameters
x Existing datatype object whose value is compared against ours
Returns
True iff the datatypes are identical
Definition at line 103 of file datatype.hpp.
References _val.
bool px::CDataType::operator== (datatype x) const
Equality comparison operator.
Parameters
x datatype enumeration whose value is compared against ours
Returns
True iff the datatypes are identical
Definition at line 113 of file datatype.hpp.
bool px::CDataType::operator!= (const CDataType & x) const
Non-equality comparison operator.
Parameters
x Existing datatype object whose value is compared against ours
Returns
True iff the datatypes are not identical
Definition at line 124 of file datatype.hpp.
bool px::CDataType::operator!= (datatype x) const
Non-quality comparison operator.
Parameters
x datatype enumeration whose value is compared against ours
Returns
True iff the datatypes are not identical
Definition at line 134 of file datatype.hpp.
bool px::CDataType::operator< (const CDataType & x) const
Less than comparison operator.
Parameters
x Existing datatype object whose value is compared against ours
Returns
True iff the datatype x is greater
Definition at line 144 of file datatype.hpp.
References _val.
datatype px::CDataType::val () const
Getter for the underlying datatype enumeration.
Returns
The enum value associated with this object
Definition at line 152 of file datatype.hpp.
Referenced by px::CValue::get_type_to_compare(), px::eq::CPxValue::is_64bit(), px::CValue::is_valid(), px::val_impl::as_datatype::operator()(), px::CValue::operator*=(), px::CValue::operator+=(), px::CValue::operator-=(), px::CValue::operator/=(), px::CValue::operator<(), and px::CValue::operator==().
const char * px::CDataType::str () const
Getter for this canonical string associated with this datatype.
Enum to string conversions are supported via an inverse lookup table that maps to the same string entries used by the parse() function. The lookup table is built as a static member, i.e. initialized the first time any part of your program calls this function. After that, string conversions are extremely fast.
Returns
A pointer to the string value in an internal lookup table
Definition at line 39 of file datatype.cpp.
bool px::CDataType::is_integral () const
Determine whether this type is integral.
Returns
True if this is an integral data type
Definition at line 174 of file datatype.hpp.
References px::int32, px::int64, px::uint32, and px::uint64.
bool px::CDataType::is_fp () const
Determine whether this type is a floating-point number.
Returns
True if this is a floating-point data type
Definition at line 187 of file datatype.hpp.
References px::float32, and px::float64.
bool px::CDataType::is_numeric () const
Determine whether this type is numeric.
Returns
True if this is a numeric data type
Definition at line 198 of file datatype.hpp.
Referenced by px::eq::CPxValue::operator/=().
bool px::CDataType::is_timestamp () const
Determine whether this type is a CTimestamp.
Returns
True if this is a timestamp data type
Definition at line 208 of file datatype.hpp.
References px::timestamp.
bool px::CDataType::is_string () const
Determine whether this type is a px::string.
Returns
True if this is a px::string data type
Definition at line 218 of file datatype.hpp.
References px::string.
Referenced by px::CProtoOPS::SetFieldValue().
bool px::CDataType::is_binary () const
Determine whether this type is a binary vector of bytes.
Returns
True if this is a a binary vector of bytes
Definition at line 228 of file datatype.hpp.
References px::binary.
bool px::CDataType::is_boolean () const
Determine whether this type is a boolean bytes.
Returns
True if this is a a boolean bytes
Definition at line 238 of file datatype.hpp.
References px::boolean.
template<class Archive > void px::CDataType::serialize (Archive & ar)
Serializer.
Parameters
ar The archive to [de]serialize from/to
Definition at line 249 of file datatype.hpp.
void px::CDataType::parse (const char * str, unsigned int len) private
Parse an input datatype string and assign the corresponding datatype enum.
This function utilizes a gperf-generated perfect hash table to perform an efficient lookup of the given canonical datatype string, and find its associated enumeration value. Comparisons are case- sensitive, and must match the corresponding canonical string exactly or they will be considered invalid. The result is assigned to _val.
Parameters
str The canonical string name of the assigned datatype. Must not be null nor empty.
len Length of the string; if 0, length will be determined automatically by looking for a NUL terminator
Exceptions
generic_err The provided string is unknown or invalid
Definition at line 16 of file datatype.cpp.
References _val, in_word_set(), and px::invalid.
Member Data Documentation
datatype px::CDataType::_val private
The only data member is a single enumeration value.
Definition at line 288 of file datatype.hpp.
Referenced by operator<(), operator==(), and parse().
The documentation for this class was generated from the following files:
datatype.hpp
datatype.cpp