libpx: px::CValue Class Reference
px::CValue Class Reference
Variadic value.
#include "px/type/value.hpp"
Public Types
typedef boost::variant
< px::invalid_t, bool, int32_t,
int64_t, uint32_t, uint64_t,
float, double, CTimestamp,
px::string, std::vector
< unsigned char > > value_type
Variadic type which can hold any value we might want.
Public Member Functions
CValue ()
Default constructor.
CValue (CValue &&arg)
Move constructor.
CValue (CValue &arg)
Copy constructor.
CValue (const CValue &arg)
template<typename T >
CValue (T &&arg)
Constructor (variadic types)
CValue (timeval arg)
Construct from timestamp.
CValue (const char *arg)
Construct from string.
CValue (std::string &&arg)
CValue (std::string &arg)
CValue (const std::string &arg)
CValue (const px::proto::DataValue &arg)
Construct from protobuf object.
PUBLIC ~CValue ()
Destructor.
PUBLIC bool operator== (const CValue &x) const
Equality operator.
bool operator!= (const CValue &x) const
Inequality operator.
PUBLIC bool operator< (const CValue &x) const
Less-than comparison operator.
bool operator>= (const CValue &x) const
Round out the set of comparison operators.
bool operator> (const CValue &x) const
bool operator<= (const CValue &x) const
PUBLIC bool is_valid () const
Tests whether this CValue contains a valid value.
PUBLIC CValue & operator+= (const CValue &x)
Addition operator.
PUBLIC CValue & operator-= (const CValue &x)
Subtraction operator.
PUBLIC CValue & operator*= (const CValue &x)
Multiplication operator.
PUBLIC CValue & operator/= (const CValue &x)
Division operator.
PUBLIC size_t hash () const
Hash function.
CValue & operator= (CValue &&arg)
Assignment operator (move)
CValue & operator= (CValue &arg)
Assignment operator.
CValue & operator= (const CValue &arg)
template<typename T >
CValue & operator= (T &&arg)
Assignment operator for generic types that don't need translation.
CValue & operator= (timeval arg)
Assignment operator.
CValue & operator= (const char *arg)
String Assignment operators.
CValue & operator= (std::string &&arg)
CValue & operator= (std::string &arg)
CValue & operator= (const std::string &&arg)
PUBLIC CDataType type () const
Get the data type for this value.
PUBLIC void to (CDataType type)
Internal conversion to alternate type.
PUBLIC CValue as (CDataType type) const
Conversion to alternate type.
PUBLIC bool as_bool () const
Conversion to boolean type.
PUBLIC int32_t as_int32 () const
Conversion to int32 type.
PUBLIC int64_t as_int64 () const
Conversion to int64 type.
PUBLIC uint32_t as_uint32 () const
Conversion to uint32 type.
PUBLIC uint64_t as_uint64 () const
Conversion to uint64 type.
PUBLIC float as_float () const
Conversion to float type.
PUBLIC double as_double () const
Conversion to double type.
PUBLIC CTimestamp as_timestamp () const
Conversion to timestamp type.
PUBLIC px::string as_string () const
Conversion to string type.
PUBLIC std::vector< unsigned char > as_binary () const
Conversion to binary type.
template<typename T >
T as () const
Conversion to specified type.
template<typename Archive >
void serialize (Archive &ar)
Serialization function.
PUBLIC void to (px::proto::DataValue &val) const
Initialize a protobuf DataValue object from this value.
PUBLIC void from (const px::proto::DataValue &arg)
Assign this object's value based on a protobuf DataValue object.
template<>
bool as () const
Specialization for bool type.
template<>
int32_t as () const
Specialization for int32 type.
template<>
int64_t as () const
Specialization for int64 type.
template<>
uint32_t as () const
Specialization for uint32 type.
template<>
uint64_t as () const
Specialization for uint64 type.
template<>
float as () const
Specialization for float type.
template<>
double as () const
Specialization for double type.
template<>
CTimestamp as () const
Specialization for timestamp type.
Private Member Functions
px::CDataType get_type_to_compare (px::CDataType other_type) const
Private Attributes
value_type _val
Friends
template<typename T >
bool operator== (const T &x, const CValue &y)
Equality operator.
template<typename T >
bool operator== (const CValue &x, const T &y)
Equality operator.
Detailed Description
Variadic value.
This class implements a variably-typed value. It's useful when dealing with real-time channel measurements, since every channel needs a value, but the actual type is dependent upon whatever the channel's data type happens to be.
Definition at line 34 of file type/value.hpp.
Member Typedef Documentation
typedef boost::variant<px::invalid_t, bool, int32_t, int64_t, uint32_t, uint64_t, float, double, CTimestamp, px::string, std::vector<unsigned char> > px::CValue::value_type
Variadic type which can hold any value we might want.
The types here should be matched in enum class px::datatype
Definition at line 56 of file type/value.hpp.
Constructor & Destructor Documentation
px::CValue::CValue ()
Default constructor.
Definition at line 66 of file type/value.hpp.
px::CValue::CValue (CValue && arg)
Move constructor.
Parameters
arg Object used to initialize this value
Definition at line 75 of file type/value.hpp.
px::CValue::CValue (CValue & arg)
Copy constructor.
Parameters
arg Object used to initialize this value
Definition at line 84 of file type/value.hpp.
px::CValue::CValue (const CValue & arg)
Definition at line 87 of file type/value.hpp.
template<typename T > px::CValue::CValue (T && arg) explicit
Constructor (variadic types)
Parameters
arg Object used to initialize this value
Definition at line 97 of file type/value.hpp.
px::CValue::CValue (timeval arg)
Construct from timestamp.
Parameters
arg Object used to initialize this value
Definition at line 106 of file type/value.hpp.
px::CValue::CValue (const char * arg)
Construct from string.
Parameters
arg Object used to initialize this value
Definition at line 115 of file type/value.hpp.
px::CValue::CValue (std::string && arg)
Definition at line 118 of file type/value.hpp.
px::CValue::CValue (std::string & arg)
Definition at line 121 of file type/value.hpp.
px::CValue::CValue (const std::string & arg)
Definition at line 124 of file type/value.hpp.
px::CValue::CValue (const px::proto::DataValue & arg) explicit
Construct from protobuf object.
Parameters
arg Object used to initialize this value
Exceptions
generic_err Thrown if the protobuf object is invalid
Definition at line 135 of file type/value.hpp.
References from().
px::CValue::~CValue ()
Destructor.
Definition at line 18 of file value.cpp.
Member Function Documentation
bool px::CValue::operator== (const CValue & x) const
Equality operator.
Note that two values with different types may compare as equal, e.g.: int32 and uint32, both having the same value int32 and int64, both having the same value int32 and uint64, both having the same value int32 and float32, both having the same value int32 and float64, both having the same value uint32 and uint64, both having the same value uint32 and int64, both having the same value uint32 and float32, both having the same value uint32 and float64, both having the same value int64 and float32, both having the same value int64 and float64, both having the same value
In general, float32 and float64 will not compare as equal.
Parameters
x Value to compare against
Returns
True if this object's value matches that of x
Definition at line 24 of file value.cpp.
References _val, as_bool(), as_double(), as_float(), as_int32(), as_int64(), as_uint32(), as_uint64(), px::boolean, px::float32, px::float64, px::int32, px::int64, px::uint32, px::uint64, and px::CDataType::val().
bool px::CValue::operator!= (const CValue & x) const
Inequality operator.
Note that two values with different types may be compared as not equal, e.g.: int32 and uint32, having the different values int32 and int64, having the different values int32 and uint64, having the different values int32 and float32, having the different values int32 and float64, having the different values uint32 and uint64, having the different values uint32 and int64, having the different values uint32 and float32, having the different values uint32 and float64,having the different values int64 and float32, having the different values int64 and float64, having the different values
Returns
True if this object's value does not match that of x
Definition at line 218 of file type/value.hpp.
bool px::CValue::operator< (const CValue & x) const
Less-than comparison operator.
This is useful for putting values into an ordered container. Note that types are taken into consideration before actual values are, so that any value of one type will compare less than any value of some other type.
Parameters
x Value to compare against
Returns
True if this object's value is less than that of x
Definition at line 90 of file value.cpp.
References _val, as_bool(), as_double(), as_int64(), as_uint64(), px::boolean, px::float64, px::int64, px::uint64, and px::CDataType::val().
bool px::CValue::operator>= (const CValue & x) const
Round out the set of comparison operators.
Definition at line 240 of file type/value.hpp.
bool px::CValue::operator> (const CValue & x) const
Definition at line 245 of file type/value.hpp.
bool px::CValue::operator<= (const CValue & x) const
Definition at line 250 of file type/value.hpp.
bool px::CValue::is_valid () const
Tests whether this CValue contains a valid value.
Returns
True if this object's value is valid (not default-constructed or px::invalid_t).
Definition at line 729 of file value.cpp.
References px::invalid, and px::CDataType::val().
px::CValue & px::CValue::operator+= (const CValue & x)
Addition operator.
If either "this" or x is non-numeric, "this" will not be altered. x will be converted to this object's type before adding, so "*this" will never change type due to the operation.
Parameters
x Value to add to "*this"
Returns
*this with x added to it.
Definition at line 402 of file value.cpp.
References as_double(), as_float(), as_int32(), as_int64(), as_uint32(), as_uint64(), px::float32, px::float64, px::int32, px::int64, px::uint32, px::uint64, and px::CDataType::val().
px::CValue & px::CValue::operator-= (const CValue & x)
Subtraction operator.
If either "this" or x is non-numeric, "this" will not be altered. x will be converted to this object's type before subtracting, so "*this" will never change type due to the operation. But if "*this" is unsigned and smaller than x, underflow will occur.
Parameters
x Value to subtract from "*this"
Returns
*this with x subtracted from it.
Definition at line 437 of file value.cpp.
References as_double(), as_float(), as_int32(), as_int64(), as_uint32(), as_uint64(), px::float32, px::float64, px::int32, px::int64, px::uint32, px::uint64, and px::CDataType::val().
px::CValue & px::CValue::operator*= (const CValue & x)
Multiplication operator.
If either "this" or x is non-numeric, "this" will not be altered. x will be converted to this object's type before multiplying, so "*this" will never change type due to the operation. Overflow may occur if this*x is too large for *this' type.
Parameters
x Value to multiply "*this" by.
Returns
*this after multiplying it by x.
Definition at line 471 of file value.cpp.
References as_double(), as_float(), as_int32(), as_int64(), as_uint32(), as_uint64(), px::float32, px::float64, px::int32, px::int64, px::uint32, px::uint64, and px::CDataType::val().
px::CValue & px::CValue::operator/= (const CValue & x)
Division operator.
If either "this" or x is non-numeric, "this" will not be altered. Also if x is 0, "this" will not be altered. x will be converted to this object's type before dividing, so "*this" will never change type due to the operation.
Parameters
x Value to divide "*this" by.
Returns
*this after dividing it by x.
Definition at line 505 of file value.cpp.
References as_double(), as_float(), as_int32(), as_int64(), as_uint32(), as_uint64(), px::float32, px::float64, px::int32, INT32_MAX, px::int64, px::uint32, UINT32_MAX, px::uint64, and px::CDataType::val().
size_t px::CValue::hash () const
Hash function.
This call returns a hash value for the underlying variadic value
Returns
A hash value for this object
Definition at line 132 of file value.cpp.
CValue& px::CValue::operator= (CValue && arg)
Assignment operator (move)
Parameters
arg Object used to initialize this value
Returns
*this
Definition at line 340 of file type/value.hpp.
References _val.
CValue& px::CValue::operator= (CValue & arg)
Assignment operator.
Parameters
arg Object used to initialize this value
Returns
*this
Definition at line 353 of file type/value.hpp.
References _val.
CValue& px::CValue::operator= (const CValue & arg)
Definition at line 359 of file type/value.hpp.
References _val.
template<typename T > CValue& px::CValue::operator= (T && arg)
Assignment operator for generic types that don't need translation.
Parameters
arg Object used to initialize this value
Returns
*this
Definition at line 373 of file type/value.hpp.
References _val.
CValue& px::CValue::operator= (timeval arg)
Assignment operator.
Parameters
arg Object used to initialize this value
Returns
*this
Definition at line 386 of file type/value.hpp.
References _val.
CValue& px::CValue::operator= (const char * arg)
String Assignment operators.
Parameters
arg Object used to initialize this value
Returns
*this
Definition at line 399 of file type/value.hpp.
References _val, and px::string.
CValue& px::CValue::operator= (std::string && arg)
Definition at line 405 of file type/value.hpp.
References _val.
CValue& px::CValue::operator= (std::string & arg)
Definition at line 411 of file type/value.hpp.
References _val.
CValue& px::CValue::operator= (const std::string && arg)
Definition at line 417 of file type/value.hpp.
References _val.
px::CDataType px::CValue::type () const
Get the data type for this value.
Returns
A datatype object corresponding to this value's current type (see px::datatype for the enum values)
Definition at line 140 of file value.cpp.
Referenced by px::asio::CCdsHandler::get_channel_value(), px::CChannelSettings::get_field_by_name(), px::CChannel::get_field_by_name(), px::CDevice::get_field_by_name(), px::eq::CPxValue::is_64bit(), px::eq::CPxValue::operator/=(), px::CProtoOPS::SetFieldValue(), and px::CValueAccumulator::update().
void px::CValue::to (px::CDataType type)
Internal conversion to alternate type.
This function makes a best-effort conversion from the current object's type to the one specified.
Parameters
type The desired data type to convert *this to.
Definition at line 146 of file value.cpp.
Referenced by px::db::AddChannelToBatch(), and px::eq::CPxValue::operator/=().
px::CValue px::CValue::as (px::CDataType type) const
Conversion to alternate type.
This function returns a variadic object of the specified type, whose value is made via a best-effort conversion from the current object's value.
Parameters
type The desired data type of the return value
Returns
A variadic value of specified type, whose value is either initialized from *this, or left at a suitable default
Definition at line 160 of file value.cpp.
bool px::CValue::as_bool () const
Conversion to boolean type.
Returns
A best-effort conversion of this object to a bool
Definition at line 168 of file value.cpp.
References px::boolean.
Referenced by px::eq::CPxValue::operator bool(), operator<(), operator==(), and px::CProtoOPS::SetFieldValue().
int32_t px::CValue::as_int32 () const
Conversion to int32 type.
Returns
A best-effort conversion of this object to a int32
Definition at line 178 of file value.cpp.
References px::int32.
Referenced by operator*=(), operator+=(), operator-=(), operator/=(), operator==(), and px::CProtoOPS::SetFieldValue().
int64_t px::CValue::as_int64 () const
Conversion to int64 type.
Returns
A best-effort conversion of this object to a int64
Definition at line 200 of file value.cpp.
References px::int64.
Referenced by px::eq::CPxValue::operator long(), operator*=(), operator+=(), operator-=(), operator/=(), operator<(), operator==(), and px::CProtoOPS::SetFieldValue().
uint32_t px::CValue::as_uint32 () const
Conversion to uint32 type.
Returns
A best-effort conversion of this object to a uint32
Definition at line 222 of file value.cpp.
References px::uint32.
Referenced by px::CChannelSettings::get_field_by_name(), operator*=(), operator+=(), operator-=(), operator/=(), operator==(), px::eq::CPxValue::operator[](), and px::CProtoOPS::SetFieldValue().
uint64_t px::CValue::as_uint64 () const
Conversion to uint64 type.
Returns
A best-effort conversion of this object to a uint64
Definition at line 249 of file value.cpp.
References px::uint64.
Referenced by operator*=(), operator+=(), operator-=(), operator/=(), operator<(), operator==(), px::eq::CPxValue::operator[](), and px::CProtoOPS::SetFieldValue().
float px::CValue::as_float () const
Conversion to float type.
Returns
A best-effort conversion of this object to a float
Definition at line 276 of file value.cpp.
References px::float32.
Referenced by operator*=(), operator+=(), operator-=(), operator/=(), operator==(), and px::CProtoOPS::SetFieldValue().
double px::CValue::as_double () const
Conversion to double type.
Returns
A best-effort conversion of this object to a double
Definition at line 286 of file value.cpp.
References px::float64.
Referenced by px::eq::CPxValue::operator bool(), operator*=(), operator+=(), operator-=(), px::eq::CPxValue::operator/=(), operator/=(), operator<(), operator==(), px::CProtoOPS::SetFieldValue(), and px::CValueAccumulator::update().
px::CTimestamp px::CValue::as_timestamp () const
Conversion to timestamp type.
Returns
A best-effort conversion of this object to a timestamp
Definition at line 296 of file value.cpp.
References px::timestamp.
px::string px::CValue::as_string () const
Conversion to string type.
Returns
A best-effort conversion of this object to a string
Definition at line 307 of file value.cpp.
References px::string.
Referenced by px::asio::CCdsHandler::get_channel_value(), px::CChannel::get_field_by_name(), px::asio::CCdsHandler::set_channel_value(), px::asio::CCdsSyncIO::set_channel_value_s(), px::CProtoOPS::SetFieldValue(), and px::CTrendAccumulator::update().
std::vector< unsigned char > px::CValue::as_binary () const
Conversion to binary type.
Returns
A best-effort conversion of this object to a binary blob
Definition at line 317 of file value.cpp.
References px::binary.
Referenced by px::CProtoOPS::SetFieldValue().
template<typename T > T px::CValue::as () const
Conversion to specified type.
This version helps to simplify template code.
Returns
A best-effort conversion of this object to the given type
template<typename Archive > void px::CValue::serialize (Archive & ar)
Serialization function.
Parameters
ar The archive to save/load to/from
Definition at line 555 of file type/value.hpp.
References _val.
void px::CValue::to (px::proto::DataValue & val) const
Initialize a protobuf DataValue object from this value.
Parameters
val Object whose fields are initialized based on the current value of *this
Definition at line 328 of file value.cpp.
void px::CValue::from (const px::proto::DataValue & arg)
Assign this object's value based on a protobuf DataValue object.
This is essentially the inverse of to().
Parameters
arg Object used to initialize this value
Exceptions
generic_err Thrown if the protobuf object is invalid
Definition at line 336 of file value.cpp.
References px::string.
Referenced by CValue(), px::db::FetchChannels(), and px::CParameterInfo::from().
px::CDataType px::CValue::get_type_to_compare (px::CDataType other_type) const private
Definition at line 588 of file value.cpp.
References px::boolean, px::float32, px::float64, px::int32, px::int64, px::invalid, px::uint32, px::uint64, and px::CDataType::val().
template<> bool px::CValue::as () const
Specialization for bool type.
Definition at line 605 of file type/value.hpp.
template<> int32_t px::CValue::as () const
Specialization for int32 type.
Definition at line 612 of file type/value.hpp.
template<> int64_t px::CValue::as () const
Specialization for int64 type.
Definition at line 619 of file type/value.hpp.
template<> uint32_t px::CValue::as () const
Specialization for uint32 type.
Definition at line 626 of file type/value.hpp.
template<> uint64_t px::CValue::as () const
Specialization for uint64 type.
Definition at line 633 of file type/value.hpp.
template<> float px::CValue::as () const
Specialization for float type.
Definition at line 640 of file type/value.hpp.
template<> double px::CValue::as () const
Specialization for double type.
Definition at line 647 of file type/value.hpp.
template<> CTimestamp px::CValue::as () const
Specialization for timestamp type.
Definition at line 654 of file type/value.hpp.
Friends And Related Function Documentation
template<typename T > bool operator== (const T & x, const CValue & y) friend
Equality operator.
Parameters
x Typed value to compare
y Variadic value which is compared against 'x'
Returns
True if x and y are equal
Definition at line 178 of file type/value.hpp.
template<typename T > bool operator== (const CValue & x, const T & y) friend
Equality operator.
Parameters
x Variadic value which is compared against 'y'
y Typed value to compare
Returns
True if x and y are equal
Definition at line 193 of file type/value.hpp.
Member Data Documentation
value_type px::CValue::_val private
Definition at line 597 of file type/value.hpp.
Referenced by operator<(), operator=(), operator==(), and serialize().
The documentation for this class was generated from the following files:
type/value.hpp
value.cpp