libpx: px::asio::CIoSighandler Class Reference
px::asio::CIoSighandler Class Reference
ASIO interface details and general IO functions. | IO_Actors
The Signal Handling actor, which receives and responds to system Signals.
#include <io_sighandler.hpp>
Public Member Functions
PUBLIC CIoSighandler (CIoManager &manager)
Constructor, which registers the signals to be caught, and then waits for the manager to be run and kick off the ASIO management.
PUBLIC ~CIoSighandler ()
Destructor.
virtual PUBLIC void close ()
Gracefully close this actor.
void handle_signal (const boost::system::error_code &err, int signum)
Handle the arrival of a signal for which we're registered.
void register_temp_handler (void)
Registers an optional "temporary" signal handler, which operates outside of the ASIO framework, and provides signal handling in the early phases of the process startup.
void unregister_temp_handler (void)
Unregister the temporary signal handlers and restore this class' main handlers.
PUBLIC void register_another_handler (sighandler_funcptr_t handler)
Register an additional handler, to be called on any signals.
PUBLIC void unregister_another_handler (sighandler_funcptr_t handler)
Unregister an additional handler.
PUBLIC void add_signal (int signum)
Add a signal to those being caught.
PUBLIC void remove_signal (int signum)
Remove signal from those being caught.
Public Member Functions inherited from px::asio::CIoActor
CIoActor (CIoManager &manager)
Constructor.
virtual ~CIoActor ()
Destructor.
boost::asio::io_service & get_io_service () const
Get the I/O service associated with the owner of this actor.
PUBLIC CServerCore & get_server_core () const
Get the container for CDS data management.
PUBLIC CCdsHandler & get_cds_handler () const
Get the container for CDS data management.
PUBLIC bool get_quit_status ()
Get the quit status from connection IO manager.
Static Public Member Functions
static PUBLIC std::shared_ptr
< CIoSighandler > create (CIoManager &manager)
Factory function to create a new CIoSighandler object.
Private Member Functions
void wait_for_next_signal ()
Wait (asynchronously) for a new incoming signal.
Private Attributes
std::unique_ptr
< boost::asio::signal_set > _sigset
Underlying Asio signal set object.
bool have_temp_sig_handlers
Flag to indicate when we have installed the temporary signal handlers.
struct sigaction main_sig_action
Stores the main ("old") signal action when the temporary signal handler is used; will be used then to restore this action when the temporary signal handler is removed.
std::vector< sighandler_funcptr_t > _additional_handlers
List of the additional handlers registered.
Additional Inherited Members
Protected Member Functions inherited from px::asio::CIoActor
void remove ()
This method is called when an actor wants to remove itself from the I/O management interface.
Protected Attributes inherited from px::asio::CIoActor
CIoManager & _owner
The I/O manager object that "owns" this connection.
Detailed Description
The Signal Handling actor, which receives and responds to system Signals.
This class implements an I/O actor that notifies the I/O management system when a signal is caught. Practically speaking, this is useful for detecting when the application is being killed, so that a graceful shutdown can be performed.
The signals to be handled are SIGPIPE, SIGHUP, SIGINT, SIGQUIT, and SIGTERM.
This class has been extended to also provide an optional "temporary" signal handler to be used before the ASIO manager is "running". This is a useful option since the startup and device discovery phase (if used) can take quite a while to complete, and this is commonly done before the manager runs and the ASIO framework can catch the main signals registered when this class is instantiated. The temporary signal handler should thus be removed before the manager is run.
Definition at line 37 of file io_sighandler.hpp.
Constructor & Destructor Documentation
px::asio::CIoSighandler::CIoSighandler (CIoManager & manager)
Constructor, which registers the signals to be caught, and then waits for the manager to be run and kick off the ASIO management.
Parameters
manager The I/O manager object to which this object is to be bound
Exceptions
boost::system::system_error The connection could not be initialized
Definition at line 49 of file io_sighandler.cpp.
References _sigset, main_sig_action, and wait_for_next_signal().
Referenced by create().
px::asio::CIoSighandler::~CIoSighandler ()
Destructor.
Definition at line 71 of file io_sighandler.cpp.
Member Function Documentation
std::shared_ptr< CIoSighandler > px::asio::CIoSighandler::create (CIoManager & manager) static
Factory function to create a new CIoSighandler object.
Parameters
manager The I/O manager object to which this object is to be bound
Exceptions
boost::system::system_error The signal handler could not be initialized
Returns
Shared pointer containing the new instance of CIoSighandler (an CIoActor).
Definition at line 20 of file io_sighandler.cpp.
References CIoSighandler(), px::asio::global_sig_handler, and LIBPX_FERR.
Referenced by px::asio::CIoManager::CIoManager().
void px::asio::CIoSighandler::close () virtual
Gracefully close this actor.
This will gracefully close the actor. It is called automatically by the actor's destructor, but any resulting error information will be lost in that case.
Exceptions
boost::system::system_error There was an error when attempting to gracefully shut down / close
Reimplemented from px::asio::CIoActor.
Definition at line 79 of file io_sighandler.cpp.
void px::asio::CIoSighandler::handle_signal (const boost::system::error_code & err, int signum)
Handle the arrival of a signal for which we're registered.
Parameters
err The boost error code associated with this signal's arrival
signum The numeric ID of the signal which was caught
Definition at line 87 of file io_sighandler.cpp.
References _additional_handlers, px::asio::CIoActor::_owner, px::asio::CIoManager::is_quit_signal_received(), LIBPX_DEBUG, LIBPX_FERR, likely, px::asio::CIoManager::quit(), and wait_for_next_signal().
Referenced by wait_for_next_signal().
void px::asio::CIoSighandler::register_temp_handler (void)
Registers an optional "temporary" signal handler, which operates outside of the ASIO framework, and provides signal handling in the early phases of the process startup.
(That is, it is functional before the ASIO manager is "running", and should be unregistered immediately before starting to run the ASIO manager.) Registering these handlers will temporarily replace this class' main handlers.
Definition at line 177 of file io_sighandler.cpp.
References have_temp_sig_handlers, main_sig_action, and px::asio::temp_sig_handler().
void px::asio::CIoSighandler::unregister_temp_handler (void)
Unregister the temporary signal handlers and restore this class' main handlers.
This function should be called immediately before starting to run the ASIO manager. If the temporary handlers have not been registered, calling this function will have no effect.
Definition at line 196 of file io_sighandler.cpp.
References have_temp_sig_handlers, and main_sig_action.
void px::asio::CIoSighandler::register_another_handler (sighandler_funcptr_t handler)
Register an additional handler, to be called on any signals.
Parameters
handler Pointer to signal-handling function
Definition at line 212 of file io_sighandler.cpp.
References _additional_handlers.
void px::asio::CIoSighandler::unregister_another_handler (sighandler_funcptr_t handler)
Unregister an additional handler.
Parameters
handler Pointer to signal-handling function
Definition at line 226 of file io_sighandler.cpp.
References _additional_handlers.
void px::asio::CIoSighandler::add_signal (int signum)
Add a signal to those being caught.
Parameters
signum Number of the signal (e.g. 11 for SIGSEGV)
Definition at line 246 of file io_sighandler.cpp.
References _sigset, and likely.
void px::asio::CIoSighandler::remove_signal (int signum)
Remove signal from those being caught.
Parameters
signum Number of the signal
Definition at line 257 of file io_sighandler.cpp.
References _sigset, and likely.
void px::asio::CIoSighandler::wait_for_next_signal () private
Wait (asynchronously) for a new incoming signal.
Definition at line 140 of file io_sighandler.cpp.
References _sigset, handle_signal(), and LIBPX_DEBUG.
Referenced by CIoSighandler(), and handle_signal().
Member Data Documentation
std::unique_ptr<boost::asio::signal_set> px::asio::CIoSighandler::_sigset private
Underlying Asio signal set object.
Definition at line 157 of file io_sighandler.hpp.
Referenced by add_signal(), CIoSighandler(), remove_signal(), and wait_for_next_signal().
bool px::asio::CIoSighandler::have_temp_sig_handlers private
Flag to indicate when we have installed the temporary signal handlers.
Definition at line 162 of file io_sighandler.hpp.
Referenced by register_temp_handler(), and unregister_temp_handler().
struct sigaction px::asio::CIoSighandler::main_sig_action private
Stores the main ("old") signal action when the temporary signal handler is used; will be used then to restore this action when the temporary signal handler is removed.
Definition at line 168 of file io_sighandler.hpp.
Referenced by CIoSighandler(), register_temp_handler(), and unregister_temp_handler().
std::vector<sighandler_funcptr_t> px::asio::CIoSighandler::_additional_handlers private
List of the additional handlers registered.
Definition at line 173 of file io_sighandler.hpp.
Referenced by handle_signal(), register_another_handler(), and unregister_another_handler().
The documentation for this class was generated from the following files:
io_sighandler.hpp
io_sighandler.cpp