libpx: px::cds::CSignalPipe Class Reference
px::cds::CSignalPipe Class Reference
Class for catching UNIX signals & delivering them to the main polling loop.
#include <signal_pipe.hpp>
Classes
struct user_exit
Exception: user-initiated exit.
Public Member Functions
CSignalPipe ()
Constructor.
~CSignalPipe ()
Destructor.
Static Public Member Functions
static int fd ()
Return a file descriptor which is suitable for polling (via select(), epoll(), or similar) for read-readiness.
static void clear ()
Clear notification of the incoming signal so that we can continue normal operation.
static void sig_handler (int signum)
Handle an incoming asynchronous signal.
Static Private Attributes
static int _pipes [2] = {-1, -1}
Read & write ends of the pipe used for notifying the main thread.
static bool _shutdown = false
Flag used to indicate that a shutdown has been requested.
Detailed Description
Class for catching UNIX signals & delivering them to the main polling loop.
This utility class wraps the functionality provided by C-style signals in a class that provides event readiness notification when a signal has been received (via select(), epoll(), etc.) This simplifies signal handling by allowing the main event loop to be awaken when a signal is received.
Definition at line 17 of file signal_pipe.hpp.
Constructor & Destructor Documentation
px::cds::CSignalPipe::CSignalPipe ()
Constructor.
Register a signal handler associated with the constructed object, and initialize a FD which will select() as ready whenever a signal has been received.
Exceptions
generic_err Thrown if the signal handler or pipe cannot be initialized correctly
Definition at line 39 of file signal_pipe.cpp.
References _pipes, _shutdown, LIBPX_FERR, and sigpipe_handler().
px::cds::CSignalPipe::~CSignalPipe ()
Destructor.
Unregister the underlying signal handler and close the allocated FD.
Definition at line 78 of file signal_pipe.cpp.
Member Function Documentation
static int px::cds::CSignalPipe::fd () static
Return a file descriptor which is suitable for polling (via select(), epoll(), or similar) for read-readiness.
When this descriptor polls as read-ready, a signal has been received asynchronously; clear() should be called in order to clear the data from the descriptor.
Returns
A pollable file descriptor
Definition at line 78 of file signal_pipe.hpp.
References _pipes.
Referenced by px::asio::CCdsHandler::connect_to_cds(), and px::cds::CServer::listen().
void px::cds::CSignalPipe::clear () static
Clear notification of the incoming signal so that we can continue normal operation.
This should be called whenever the FD has data to be received.
Exceptions
generic_err Thrown if there is an error and the caller should exit non-gracefully
user_exit Thrown if the signal indicates that the user has requested a shutdown of the CDS
Definition at line 103 of file signal_pipe.cpp.
Referenced by px::asio::CCdsHandler::connect_to_cds(), and px::cds::CServer::get_pending_requests().
void px::cds::CSignalPipe::sig_handler (int signum) static
Handle an incoming asynchronous signal.
This function is invoked whenever one of the signals that we're interested in is delivered to the CDS. It handles the incoming signal appropriately, which usually involves writing to the pipe pair so that fd() will poll as read-ready.
Parameters
signum The signal number that was just received
Definition at line 135 of file signal_pipe.cpp.
Referenced by sigpipe_handler().
Member Data Documentation
int px::cds::CSignalPipe::_pipes = {-1, -1} static private
Read & write ends of the pipe used for notifying the main thread.
Definition at line 116 of file signal_pipe.hpp.
Referenced by CSignalPipe(), and fd().
bool px::cds::CSignalPipe::_shutdown = false static private
Flag used to indicate that a shutdown has been requested.
Definition at line 121 of file signal_pipe.hpp.
Referenced by CSignalPipe().
The documentation for this class was generated from the following files:
signal_pipe.hpp
signal_pipe.cpp