libpx: px::asio::CUdsDgramListener Class Reference
px::asio::CUdsDgramListener Class Reference
ASIO interface details and general IO functions. | IO_Actors
Unix Domain Socket (datagram) Listener classThis class implements a UDS "listener".
#include <uds_dgram_listener.hpp>
Public Member Functions
PUBLIC CUdsDgramListener (CIoManager &manager, const CProtocolHandler &prot, const px::string &path)
Constructor.
PUBLIC ~CUdsDgramListener ()
Destructor.
virtual PUBLIC void close ()
Inherited from CIoActor.
PUBLIC bool is_open ()
Access method to test if the connection is open.
void read_more () override
Inherited from CIoTransactor.
void write_push (std::shared_ptr< io_buf_t > pbuf)
One-way (pushed) write to the socket (whoever's listening).
void reset_socket ()
Create or reset our listening socket, at _path.
const std::string source ()
Return a string representation of the endpoint connected to us.
Public Member Functions inherited from px::asio::CIoTransactor
CIoTransactor (CIoManager &manager, const CProtocolHandler &prot)
Constructor.
virtual ~CIoTransactor ()
Destructor.
PUBLIC void start ()
Kick-start the messenger by waiting for incoming data.
PUBLIC iobuf_const_pair_t get_rbuf ()
Get the currently-read message boundaries.
PUBLIC void clear_rbuf (iobuf_const_iter_t end)
Clear (perhaps only partially) the read-buffer contents after servicing a single request.
PUBLIC bool get_parse_success ()
PUBLIC void set_parse_failed (bool val)
virtual PUBLIC uint16_t source_port ()
Get port number of the source of a message (0 if N/A).
virtual PUBLIC void write (std::shared_ptr< io_buf_t > pbuf)
Write data to the messenger's output channel's outbox.
Public Member Functions inherited from px::asio::CIoActor
CIoActor (CIoManager &manager)
Constructor.
virtual ~CIoActor ()
Destructor.
boost::asio::io_service & get_io_service () const
Get the I/O service associated with the owner of this actor.
PUBLIC CServerCore & get_server_core () const
Get the container for CDS data management.
PUBLIC CCdsHandler & get_cds_handler () const
Get the container for CDS data management.
PUBLIC bool get_quit_status ()
Get the quit status from connection IO manager.
Static Public Member Functions
static PUBLIC std::shared_ptr
< CUdsDgramListener > create (CIoManager &manager, const CProtocolHandler &prot, const px::string &path)
Factory function to create a new CUdsDgramListener object.
Protected Member Functions
void write_more (const std::shared_ptr< io_buf_t > &pbuf) override
Write the data from the outbox to the service.
Protected Member Functions inherited from px::asio::CIoTransactor
void handle_read (const boost::system::error_code &err, size_t bytes_transferred)
Callback function to handle incoming data.
void handle_write (const boost::system::error_code &err, size_t bytes_transferred)
Callback function to handle a completed "write" operation.
void parse ()
Attempt to parse the currently-read data in the buffer.
void clear_outbox ()
Clear the outbox queue.
std::shared_ptr< io_buf_t > get_outbox_front_buf ()
Get the front item from the outbox if any.
Protected Member Functions inherited from px::asio::CIoActor
void remove ()
This method is called when an actor wants to remove itself from the I/O management interface.
Private Member Functions
void on_read (const boost::system::error_code &err, size_t bytes_recvd)
Callback function for Boost.Asio upon accepting a datagram.
void on_write (const boost::system::error_code &err, size_t bytes_transferred)
Callback function for Boost.Asio upon writing a datagram.
Private Attributes
std::unique_ptr
< boost::asio::local::datagram_protocol::socket > _socket
The socket that this Actor will open and listen on.
std::unique_ptr
< boost::asio::local::datagram_protocol::endpoint > _sender_endpoint
The endpoint information of the source of a received packet, and to which we send responses back.
std::unique_ptr
< boost::asio::local::datagram_protocol::endpoint > _orig_dest_endpoint
The endpoint that a received message was originally addressed to (ie, us, but with the specifics of broadcast or directed IP).
std::shared_ptr< CProtocolHandler > _prot
Protocol-specific handler, used to parse and handle incoming requests and generate responses (needed to assign each accepted connection an appropriate protocol handler).
px::string _path
Path of our socket to listen on.
bool _shutdown
Set true by close() for clean, error-free shutdown of a socket.
Additional Inherited Members
Public Attributes inherited from px::asio::CIoTransactor
bool started
True if start() has been called This can be used to distinguish e.g.
Protected Attributes inherited from px::asio::CIoTransactor
io_buf_t _rbuf
I/O buffer used for reading message data.
size_t _offset
Current offset in _rbuf, i.e.
std::shared_ptr< CProtocolHandler > _prot
Protocol-specific handler, used to parse and handle incoming requests and generate responses.
std::queue< std::shared_ptr
< io_buf_t > > _outbox
Queues the outgoing data to send.
Protected Attributes inherited from px::asio::CIoActor
CIoManager & _owner
The I/O manager object that "owns" this connection.
Detailed Description
Unix Domain Socket (datagram) Listener class
This class implements a UDS "listener".
It listens to a specific socket, of type datagram_protocol::socket, and manages responses to the incoming requests. In the normal case, we receive a request on this port, process it, and send a response (unicast) back to the sender.
Note: has no current uses; may need work. However, it has some useful concepts, particularly in the storing of the original address of a received packet. Perhaps it can also be merged with CUdpListener, which seems to have the same intent.
Definition at line 34 of file uds_dgram_listener.hpp.
Constructor & Destructor Documentation
px::asio::CUdsDgramListener::CUdsDgramListener (CIoManager & manager, const CProtocolHandler & prot, const px::string & path)
Constructor.
Parameters
manager The I/O manager object to which this listener is to be bound.
prot Protocol handler object which is utilized to perform protocol-specific operations in an abstracted manner; the listener doesn't need this directly, but individual connections will.
path The filesystem path at which we should listen
Exceptions
boost::system::system_error The listener could not be initialized.
Definition at line 25 of file uds_dgram_listener.cpp.
References _path, _prot, LIBPX_DEBUG, LIBPX_FERR, px::asio::CProtocolHandler::protocol(), reset_socket(), and px::asio::CIoTransactor::start().
Referenced by create().
px::asio::CUdsDgramListener::~CUdsDgramListener ()
Destructor.
Definition at line 53 of file uds_dgram_listener.cpp.
References _path, close(), and LIBPX_FERR.
Member Function Documentation
std::shared_ptr< CUdsDgramListener > px::asio::CUdsDgramListener::create (CIoManager & manager, const CProtocolHandler & prot, const px::string & path) static
Factory function to create a new CUdsDgramListener object.
Parameters
manager The I/O manager object to which this object is to be bound
prot Protocol handler object which is utilized to perform protocol-specific operations in an abstracted manner; the listener doesn't need this directly, but individual connections will.
path The filesystem path at which we should create a listening socket
Exceptions
boost::system::system_error The listener could not be initialized.
Returns
Shared pointer containing the new instance of CUdsDgeramListener.
Definition at line 15 of file uds_dgram_listener.cpp.
References CUdsDgramListener().
void px::asio::CUdsDgramListener::close () virtual
Inherited from CIoActor.
Reimplemented from px::asio::CIoTransactor.
Definition at line 100 of file uds_dgram_listener.cpp.
References _prot, _shutdown, and _socket.
Referenced by ~CUdsDgramListener().
bool px::asio::CUdsDgramListener::is_open ()
Access method to test if the connection is open.
Returns
True if open.
Definition at line 109 of file uds_dgram_listener.cpp.
References _socket.
void px::asio::CUdsDgramListener::read_more () override virtual
Inherited from CIoTransactor.
Implements px::asio::CIoTransactor.
Definition at line 116 of file uds_dgram_listener.cpp.
References px::asio::CIoTransactor::_offset, px::asio::CIoTransactor::_rbuf, _sender_endpoint, _socket, and on_read().
void px::asio::CUdsDgramListener::write_push (std::shared_ptr< io_buf_t > pbuf)
One-way (pushed) write to the socket (whoever's listening).
Parameters
pbuf Buffer of data to send.
void px::asio::CUdsDgramListener::reset_socket ()
Create or reset our listening socket, at _path.
Definition at line 68 of file uds_dgram_listener.cpp.
References _path, _sender_endpoint, _shutdown, _socket, px::asio::CIoActor::get_io_service(), LIBPX_FERR, and LIBPX_INFO.
Referenced by CUdsDgramListener(), on_read(), and on_write().
const std::string px::asio::CUdsDgramListener::source () virtual
Return a string representation of the endpoint connected to us.
Implements px::asio::CIoTransactor.
Definition at line 122 of file uds_dgram_listener.hpp.
void px::asio::CUdsDgramListener::write_more (const std::shared_ptr< io_buf_t > & pbuf) override protected virtual
Write the data from the outbox to the service.
Implements px::asio::CIoTransactor.
Definition at line 186 of file uds_dgram_listener.cpp.
References _sender_endpoint, _socket, LIBPX_DEBUG, LIBPX_WARN, and on_write().
void px::asio::CUdsDgramListener::on_read (const boost::system::error_code & err, size_t bytes_recvd) private
Callback function for Boost.Asio upon accepting a datagram.
Parameters
err The error code (if any) returned from the asynchronous read operation
bytes_recvd The number of bytes received
Definition at line 128 of file uds_dgram_listener.cpp.
References px::asio::CIoTransactor::_offset, px::asio::CIoTransactor::_rbuf, _sender_endpoint, _shutdown, _socket, px::asio::CIoTransactor::handle_read(), LIBPX_DEBUG, LIBPX_FERR, LIBPX_WARN, and reset_socket().
Referenced by read_more().
void px::asio::CUdsDgramListener::on_write (const boost::system::error_code & err, size_t bytes_transferred) private
Callback function for Boost.Asio upon writing a datagram.
Parameters
err The error code (if any) returned from the asynchronous write operation
bytes_transferred The number of bytes received
Definition at line 231 of file uds_dgram_listener.cpp.
References _shutdown, px::asio::CIoTransactor::handle_write(), and reset_socket().
Referenced by write_more().
Member Data Documentation
std::unique_ptr<boost::asio::local::datagram_protocol::socket> px::asio::CUdsDgramListener::_socket private
The socket that this Actor will open and listen on.
Definition at line 166 of file uds_dgram_listener.hpp.
Referenced by close(), is_open(), on_read(), read_more(), reset_socket(), and write_more().
std::unique_ptr<boost::asio::local::datagram_protocol::endpoint> px::asio::CUdsDgramListener::_sender_endpoint private
The endpoint information of the source of a received packet, and to which we send responses back.
Definition at line 172 of file uds_dgram_listener.hpp.
Referenced by on_read(), read_more(), reset_socket(), and write_more().
std::unique_ptr<boost::asio::local::datagram_protocol::endpoint> px::asio::CUdsDgramListener::_orig_dest_endpoint private
The endpoint that a received message was originally addressed to (ie, us, but with the specifics of broadcast or directed IP).
Definition at line 178 of file uds_dgram_listener.hpp.
std::shared_ptr<CProtocolHandler> px::asio::CUdsDgramListener::_prot private
Protocol-specific handler, used to parse and handle incoming requests and generate responses (needed to assign each accepted connection an appropriate protocol handler).
Definition at line 185 of file uds_dgram_listener.hpp.
Referenced by close(), and CUdsDgramListener().
px::string px::asio::CUdsDgramListener::_path private
Path of our socket to listen on.
Definition at line 190 of file uds_dgram_listener.hpp.
Referenced by CUdsDgramListener(), reset_socket(), and ~CUdsDgramListener().
bool px::asio::CUdsDgramListener::_shutdown private
Set true by close() for clean, error-free shutdown of a socket.
Definition at line 195 of file uds_dgram_listener.hpp.
Referenced by close(), on_read(), on_write(), and reset_socket().
The documentation for this class was generated from the following files:
uds_dgram_listener.hpp
uds_dgram_listener.cpp