libpx: px::asio::CTcpConnection Class Reference
px::asio::CTcpConnection Class Reference
ASIO interface details and general IO functions.
TCP Connection class, which manages TCP transactions.
#include <tcp_connection.hpp>
Public Member Functions
CTcpConnection (CIoManager &manager, const CProtocolHandler &prot)
Constructor.
~CTcpConnection ()
Destructor.
virtual PUBLIC const std::string source ()
Get text describing the source of a message (eg, dotted IP address).
virtual PUBLIC uint16_t source_port ()
Get port number of the source of a message.
void close () override
Gracefully close this actor.
void read_more () override
Read more data from the messenger's input source.
Public Member Functions inherited from px::asio::CIoTransactor
CIoTransactor (CIoManager &manager, const CProtocolHandler &prot)
Constructor.
virtual ~CIoTransactor ()
Destructor.
PUBLIC void start ()
Kick-start the messenger by waiting for incoming data.
PUBLIC iobuf_const_pair_t get_rbuf ()
Get the currently-read message boundaries.
PUBLIC void clear_rbuf (iobuf_const_iter_t end)
Clear (perhaps only partially) the read-buffer contents after servicing a single request.
PUBLIC bool get_parse_success ()
PUBLIC void set_parse_failed (bool val)
virtual PUBLIC void write (std::shared_ptr< io_buf_t > pbuf)
Write data to the messenger's output channel's outbox.
Public Member Functions inherited from px::asio::CIoActor
CIoActor (CIoManager &manager)
Constructor.
virtual ~CIoActor ()
Destructor.
boost::asio::io_service & get_io_service () const
Get the I/O service associated with the owner of this actor.
PUBLIC CServerCore & get_server_core () const
Get the container for CDS data management.
PUBLIC CCdsHandler & get_cds_handler () const
Get the container for CDS data management.
PUBLIC bool get_quit_status ()
Get the quit status from connection IO manager.
Static Public Member Functions
static std::shared_ptr
< CTcpConnection > create (CIoManager &manager, const CProtocolHandler &prot)
Factory function to create a new CTcpConnection object.
Protected Member Functions
void write_more (const std::shared_ptr< io_buf_t > &pbuf) override
Write the data from the outbox to the service.
Protected Member Functions inherited from px::asio::CIoTransactor
void handle_read (const boost::system::error_code &err, size_t bytes_transferred)
Callback function to handle incoming data.
void handle_write (const boost::system::error_code &err, size_t bytes_transferred)
Callback function to handle a completed "write" operation.
void parse ()
Attempt to parse the currently-read data in the buffer.
void clear_outbox ()
Clear the outbox queue.
std::shared_ptr< io_buf_t > get_outbox_front_buf ()
Get the front item from the outbox if any.
Protected Member Functions inherited from px::asio::CIoActor
void remove ()
This method is called when an actor wants to remove itself from the I/O management interface.
Private Attributes
std::unique_ptr
< boost::asio::ip::tcp::socket > _sock
The underlying Boost.Asio TCP socket object.
Additional Inherited Members
Public Attributes inherited from px::asio::CIoTransactor
bool started
True if start() has been called This can be used to distinguish e.g.
Protected Attributes inherited from px::asio::CIoTransactor
io_buf_t _rbuf
I/O buffer used for reading message data.
size_t _offset
Current offset in _rbuf, i.e.
std::shared_ptr< CProtocolHandler > _prot
Protocol-specific handler, used to parse and handle incoming requests and generate responses.
std::queue< std::shared_ptr
< io_buf_t > > _outbox
Queues the outgoing data to send.
Protected Attributes inherited from px::asio::CIoActor
CIoManager & _owner
The I/O manager object that "owns" this connection.
Detailed Description
TCP Connection class, which manages TCP transactions.
This class handles all TCP transfers between the server and a single client. It is spawned by the listener when an incoming connection attempt is made, and is used to transfer requests and responses to/from the server.
Definition at line 20 of file tcp_connection.hpp.
Constructor & Destructor Documentation
px::asio::CTcpConnection::CTcpConnection (CIoManager & manager, const CProtocolHandler & prot)
Constructor.
Parameters
manager The I/O manager object to which this connection is to be bound
prot Protocol handler object which is utilized to perform protocol-specific operations on this TCP connection in an abstracted manner
Exceptions
boost::system::system_error The connection could not be initialized
Definition at line 34 of file tcp_connection.cpp.
References _sock, and px::asio::CIoActor::get_io_service().
Referenced by create().
px::asio::CTcpConnection::~CTcpConnection ()
Destructor.
Definition at line 46 of file tcp_connection.cpp.
References close(), LIBPX_ERR, and LIBPX_FDEBUG.
Member Function Documentation
std::shared_ptr< CTcpConnection > px::asio::CTcpConnection::create (CIoManager & manager, const CProtocolHandler & prot) static
Factory function to create a new CTcpConnection object.
Parameters
manager The I/O manager object to which this object is to be bound
prot Protocol handler object which is utilized to perform protocol-specific operations on this TCP connection in an abstracted manner
Exceptions
boost::system::system_error The connection could not be initialized
Returns
Shared pointer containing the new instance of CTcpConnection.
Definition at line 21 of file tcp_connection.cpp.
References CTcpConnection().
Referenced by px::asio::CTcpListener::accept().
virtual PUBLIC const std::string px::asio::CTcpConnection::source () virtual
Get text describing the source of a message (eg, dotted IP address).
Returns
Description or name of the source of this message.
Implements px::asio::CIoTransactor.
Definition at line 72 of file tcp_connection.hpp.
References _sock.
Referenced by close().
virtual PUBLIC uint16_t px::asio::CTcpConnection::source_port () virtual
Get port number of the source of a message.
Returns
Port number of the source of this message.
Reimplemented from px::asio::CIoTransactor.
Definition at line 82 of file tcp_connection.hpp.
References _sock.
void px::asio::CTcpConnection::close () override virtual
Gracefully close this actor.
This will gracefully close the actor. It is called automatically by the actor's destructor, but any resulting error information will be lost in that case.
Exceptions
boost::system::system_error There was an error when attempting to gracefully shut down / close
Reimplemented from px::asio::CIoTransactor.
Definition at line 67 of file tcp_connection.cpp.
References _sock, LIBPX_DEBUG, LIBPX_ERR, and source().
Referenced by ~CTcpConnection().
void px::asio::CTcpConnection::read_more () override virtual
Read more data from the messenger's input source.
This call initiates an asynchronous read operation, filling _rbuf (starting at _offset) with any additional data that can be read.
Implements px::asio::CIoTransactor.
Definition at line 101 of file tcp_connection.cpp.
References px::asio::CIoTransactor::_offset, px::asio::CIoActor::_owner, px::asio::CIoTransactor::_rbuf, _sock, px::asio::CIoTransactor::handle_read(), px::asio::CIoManager::is_quit_signal_received(), LIBPX_ERR, LIBPX_INFO, and LIBPX_WARN.
void px::asio::CTcpConnection::write_more (const std::shared_ptr< io_buf_t > & pbuf) override protected virtual
Write the data from the outbox to the service.
Implements px::asio::CIoTransactor.
Definition at line 160 of file tcp_connection.cpp.
References px::asio::CIoActor::_owner, _sock, px::asio::CIoTransactor::handle_write(), px::asio::CIoManager::is_quit_signal_received(), LIBPX_ERR, LIBPX_INFO, and LIBPX_WARN.
Member Data Documentation
std::unique_ptr<boost::asio::ip::tcp::socket> px::asio::CTcpConnection::_sock private
The underlying Boost.Asio TCP socket object.
Definition at line 117 of file tcp_connection.hpp.
Referenced by close(), CTcpConnection(), read_more(), source(), source_port(), and write_more().
The documentation for this class was generated from the following files:
tcp_connection.hpp
tcp_connection.cpp