libpx: px::CBitset< T > Class Template Reference
px::CBitset< T > Class Template Reference
Stores a bit-field of flags defined by an enumerated type.
#include "px/type/bitset.hpp"
Public Member Functions
CBitset (func_ptr func=nullptr)
Constructor.
bool get (T flg) const
Get the value of a flag.
void set (T flg, bool val=true)
Set the value of a flag.
void reset ()
Zero out all flags.
void mask_set (const CBitset< T > &mask_set)
Set any flag that is set in the given "mask" Bitset.
void mask_clear (const CBitset< T > &mask_set)
Clear any flag that is set in the given "mask" Bitset.
void mask (const CBitset< T > &mask)
Clear any flag that is not set in the given "mask" Bitset.
bool empty () const
bool operator== (const CBitset< T > &x) const
Equality operator.
bool operator!= (const CBitset< T > &x) const
Equality operator.
uint32_t as_uint32 () const
Convert CBitset to uint32_t.
uint64_t as_uint64 () const
Convert CBitset to uint64_t.
template<typename Archive >
void serialize (Archive &ar)
void to (google::protobuf::Message &msg) const
Initialize a protobuf message object from this bitset.
void from (const google::protobuf::Message &msg)
Assign this object's bitset based on a protobuf message object.
void from_repeated_int_array (const google::protobuf::RepeatedField< google::protobuf::uint32 > &iarray)
Assign this object's bitset based on a protobuf integer array.
void to_mutable_int_array (google::protobuf::RepeatedField< google::protobuf::uint32 > *iarray) const
Fill a protobuf integer array based on this object's bitset.
void diff (const CBitset &rhs, std::vector< T > &pos_arr)
It fill the vector with all different bit positions.
px::string flag_to_str (T flag)
Gets the string value of the flag.
void set_to_str (func_ptr to_str)
Function will set the function pointer which will help to convert each flag value to string.
func_ptr get_to_str ()
This function will return the function pointer assigned to it.
Static Public Member Functions
static size_t size ()
Size of bitset.
static size_t nbytes ()
Size of bitset storage, in bytes.
Private Types
typedef std::function
< px::string(T, bool)> func_ptr
Private Attributes
std::array< unsigned char,
_nbytes > _storage
func_ptr _to_str
Static Private Attributes
static const size_t _size = static_cast<size_t>(T::size)
static const size_t _nbytes = (_size + 7) / 8
Detailed Description
template<class T>
class px::CBitset< T >
Stores a bit-field of flags defined by an enumerated type.
It is used to manage multiple bit flags efficiently, as a slightly more elegant alternative to bit-fields. We hand-roll a quick & dirty implementation below rather than using std::bitset, because it allows more efficient serialization (std::bitset doesn't provide access to raw storage, so we're forced to use 1 byte per flag).
The template parameter must define "size" to represent the total number of flags present. This is normally done by just placing it at the end of the list, for example:
enum class flag : uint8_t { flag1=0, flag2, flag3, size };
Definition at line 38 of file bitset.hpp.
Member Typedef Documentation
template<class T> typedef std::function<px::string(T, bool)> px::CBitset< T >::func_ptr private
Definition at line 54 of file bitset.hpp.
Constructor & Destructor Documentation
template<class T> px::CBitset< T >::CBitset (func_ptr func = nullptr)
Constructor.
Initializes all flags to false, set the function pointer to convert each flag to string
Definition at line 66 of file bitset.hpp.
Member Function Documentation
template<class T> bool px::CBitset< T >::get (T flg) const
Get the value of a flag.
Parameters
flg Enumerated flag value to fetch Legal values are from 0 to n-1
Returns
The value of this flag (true or false)
Definition at line 80 of file bitset.hpp.
Referenced by px::CUtil::can_del_perm_oob(), px::CUtil::can_read_oob(), px::CUtil::can_write_oob(), px::asio::CCdsHandler::check_permission(), px::asio::CCdsDevice::is_valid_device(), px::permission::perms_to_short_str(), px::permission::perms_to_str(), px::asio::CCdsHandler::process_subscription_update(), and px::CChannelSettings::require_signature_change().
template<class T> void px::CBitset< T >::set (T flg, bool val = true)
Set the value of a flag.
Parameters
flg Enumerated flag value to set Legal values are from 0 to n-1
val New value of the flag
Definition at line 99 of file bitset.hpp.
Referenced by BOOST_AUTO_TEST_CASE(), px::asio::CCdsSyncIO::enable_device(), px::db::FetchChannels(), px::CBitset< px::channel_flag >::from(), px::CBitset< px::channel_flag >::from_repeated_int_array(), px::asio::CCdsSyncIO::set_channel_communicating(), px::asio::CCdsSyncIO::set_device_communicating(), and px::permission::str_to_perms().
template<class T> void px::CBitset< T >::reset ()
Zero out all flags.
Definition at line 120 of file bitset.hpp.
Referenced by BOOST_AUTO_TEST_CASE(), px::CBitset< px::channel_flag >::CBitset(), px::cds::CCheckSession::clean(), px::cds::CSubsessionLogin::clean(), px::cds::CSetSingleChannelState::CSetSingleChannelState(), px::cds::CSetSingleDeviceState::CSetSingleDeviceState(), px::asio::CCdsSyncIO::enable_device(), px::CBitset< px::channel_flag >::from_repeated_int_array(), px::asio::CCdsSyncIO::set_channel_communicating(), and px::asio::CCdsSyncIO::set_device_communicating().
template<class T> void px::CBitset< T >::mask_set (const CBitset< T > & mask_set)
Set any flag that is set in the given "mask" Bitset.
Parameters
mask_set A Bitset, of the same template type (and hence size), where each bit set in the mask means that its corresponding bit in "this" Bitset must be set.
Definition at line 135 of file bitset.hpp.
Referenced by px::CChannel::get_state(), and px::CDevice::get_state().
template<class T> void px::CBitset< T >::mask_clear (const CBitset< T > & mask_set)
Clear any flag that is set in the given "mask" Bitset.
Parameters
mask_set A Bitset, of the same template type (and hence size), where each bit set in the mask means that its corresponding bit in "this" Bitset must be cleared.
Definition at line 151 of file bitset.hpp.
template<class T> void px::CBitset< T >::mask (const CBitset< T > & mask)
Clear any flag that is not set in the given "mask" Bitset.
Parameters
mask A Bitset to logically "and" with this Bitset
Definition at line 165 of file bitset.hpp.
Referenced by px::CBitset< px::channel_flag >::diff(), and px::permission::perms_overlap().
template<class T> bool px::CBitset< T >::empty () const
Returns
True if no bits are set
Definition at line 177 of file bitset.hpp.
Referenced by px::asio::CCdsHandler::check_permission(), and px::permission::perms_overlap().
template<class T> bool px::CBitset< T >::operator== (const CBitset< T > & x) const
Equality operator.
This is used to check bitsets for equality
Parameters
x Set to compare against
Returns
True if this object has exactly the same bits set as x
Definition at line 198 of file bitset.hpp.
template<class T> bool px::CBitset< T >::operator!= (const CBitset< T > & x) const
Equality operator.
This is used to check bitsets for equality
Parameters
x Set to compare against
Returns
True if this set does not have exactly the same bits set as x
Definition at line 212 of file bitset.hpp.
template<class T> uint32_t px::CBitset< T >::as_uint32 () const
Convert CBitset to uint32_t.
This is used to convert to a CValue compatible value. This mimics the std::bitset to_ulong with the first bit as least significant, and the last bit as most significant. If this CBitset has more than 32 bits, only return the first 32.
Returns
uint32_t representation of CBitset
Definition at line 227 of file bitset.hpp.
template<class T> uint64_t px::CBitset< T >::as_uint64 () const
Convert CBitset to uint64_t.
This is used to convert to a CValue compatible value. This mimics the std::bitset to_ulong with the first bit as least significant, and the last bit as most significant. If this CBitset has more than 64 bits, only return the first 64.
Returns
uint64_t representation of CBitset
Definition at line 254 of file bitset.hpp.
template<class T> template<typename Archive > void px::CBitset< T >::serialize (Archive & ar)
Definition at line 277 of file bitset.hpp.
template<class T> void px::CBitset< T >::to (google::protobuf::Message & msg) const
Initialize a protobuf message object from this bitset.
Parameters
val Object whose fields are initialized based on the current value of *this
Exceptions
generic_err() will throw if the message has any fields other then booleans.
Definition at line 292 of file bitset.hpp.
Referenced by px::db::AddChannelToBatch(), and px::db::AddDeviceToBatch().
template<class T> void px::CBitset< T >::from (const google::protobuf::Message & msg)
Assign this object's bitset based on a protobuf message object.
This is the inverse of to().
Parameters
arg Object used to initialize this value
Exceptions
generic_err Thrown if the protobuf object is invalid
Definition at line 331 of file bitset.hpp.
Referenced by px::db::FetchChannels(), px::db::FetchDevices(), px::CAlarmUpdate::from(), and px::db::MigrateChannelDB().
template<class T> void px::CBitset< T >::from_repeated_int_array (const google::protobuf::RepeatedField< google::protobuf::uint32 > & iarray)
Assign this object's bitset based on a protobuf integer array.
This is a common way for us to initialize Bitsets from configuration data. Any previous contents of the Bitset will be replaced by these new contents.
Parameters
iarray An array of integers corresponding to bits in the Bitset to be set. This array can be empty, resulting in an empty Bitset.
Definition at line 368 of file bitset.hpp.
template<class T> void px::CBitset< T >::to_mutable_int_array (google::protobuf::RepeatedField< google::protobuf::uint32 > * iarray) const
Fill a protobuf integer array based on this object's bitset.
This is the opposite of from_repeated_int_array().
Parameters
iarray A mutable protobuf repeated integer array, which, upon return, will be filled with integers corresponding to those bits of the Bitset which are set. If this Biset is empty, the array will be cleared upon return.
Definition at line 389 of file bitset.hpp.
template<class T> void px::CBitset< T >::diff (const CBitset< T > & rhs, std::vector< T > & pos_arr)
It fill the vector with all different bit positions.
Parameters
rhs - bitset to compare with
pos_arr - vector to hold all different bit positions
Definition at line 408 of file bitset.hpp.
Referenced by px::CBitset< px::channel_flag >::diff().
template<class T> px::string px::CBitset< T >::flag_to_str (T flag)
Gets the string value of the flag.
Parameters
flag - Flag whose value will be converted to string
Returns
flag value in string format
Definition at line 434 of file bitset.hpp.
template<class T> void px::CBitset< T >::set_to_str (func_ptr to_str)
Function will set the function pointer which will help to convert each flag value to string.
Parameters
to_str - Function pointer to convert each flag value to string
Definition at line 450 of file bitset.hpp.
template<class T> func_ptr px::CBitset< T >::get_to_str ()
This function will return the function pointer assigned to it.
Returns
function pointer
Definition at line 459 of file bitset.hpp.
template<class T> static size_t px::CBitset< T >::size () static
Size of bitset.
Returns
The number of flags utilized by this bitset
Definition at line 473 of file bitset.hpp.
Referenced by px::CBitset< px::channel_flag >::diff(), px::CBitset< px::channel_flag >::mask(), px::CBitset< px::channel_flag >::mask_clear(), and px::CBitset< px::channel_flag >::mask_set().
template<class T> static size_t px::CBitset< T >::nbytes () static
Size of bitset storage, in bytes.
Returns
The number of bytes used to store this bitset
Definition at line 483 of file bitset.hpp.
Member Data Documentation
template<class T> const size_t px::CBitset< T >::_size = static_cast<size_t>(T::size) static private
Definition at line 47 of file bitset.hpp.
Referenced by px::CBitset< px::channel_flag >::as_uint32(), px::CBitset< px::channel_flag >::as_uint64(), px::CBitset< px::channel_flag >::diff(), px::CBitset< px::channel_flag >::from_repeated_int_array(), px::CBitset< px::channel_flag >::get(), px::CBitset< px::channel_flag >::mask(), px::CBitset< px::channel_flag >::mask_clear(), px::CBitset< px::channel_flag >::mask_set(), px::CBitset< px::channel_flag >::set(), px::CBitset< px::channel_flag >::size(), and px::CBitset< px::channel_flag >::to_mutable_int_array().
template<class T> const size_t px::CBitset< T >::_nbytes = (_size + 7) / 8 static private
Definition at line 52 of file bitset.hpp.
Referenced by px::CBitset< px::channel_flag >::diff(), px::CBitset< px::channel_flag >::empty(), px::CBitset< px::channel_flag >::get(), px::CBitset< px::channel_flag >::mask(), px::CBitset< px::channel_flag >::mask_clear(), px::CBitset< px::channel_flag >::mask_set(), px::CBitset< px::channel_flag >::nbytes(), px::CBitset< px::channel_flag >::operator==(), and px::CBitset< px::channel_flag >::set().
template<class T> std::array<unsigned char, _nbytes> px::CBitset< T >::_storage private
Definition at line 496 of file bitset.hpp.
Referenced by px::CBitset< px::channel_flag >::diff(), px::CBitset< px::channel_flag >::empty(), px::CBitset< px::channel_flag >::get(), px::CBitset< px::channel_flag >::mask(), px::CBitset< px::channel_flag >::mask_clear(), px::CBitset< px::channel_flag >::mask_set(), px::CBitset< px::channel_flag >::operator==(), px::CBitset< px::channel_flag >::reset(), px::CBitset< px::channel_flag >::serialize(), and px::CBitset< px::channel_flag >::set().
template<class T> func_ptr px::CBitset< T >::_to_str private
Definition at line 501 of file bitset.hpp.
Referenced by px::CBitset< px::channel_flag >::flag_to_str(), px::CBitset< px::channel_flag >::get_to_str(), and px::CBitset< px::channel_flag >::set_to_str().
The documentation for this class was generated from the following file:
bitset.hpp