libpx: px::asio::CUdpSender Class Reference
px::asio::CUdpSender Class Reference
ASIO interface details and general IO functions. | IO_Actors
UDP Socket Sender class, used to Send packets on a UDP portThis class implements a UPD sender.
#include <udp_sender.hpp>
Public Member Functions
PUBLIC CUdpSender (CIoManager &manager, const CProtocolHandler &prot, uint16_t port)
Constructor.
PUBLIC ~CUdpSender ()
Destructor.
virtual PUBLIC void close ()
Inherited from CIoActor.
PUBLIC bool is_open ()
Access method to test if the connection is open.
virtual PUBLIC const std::string source ()
Get the source of a UDP message as dotted IP address text.
void read_more () override
Inherited from CIoTransactor.
void reset_socket ()
Create or reset our sending socket, at _port.
void update_local_port (const uint16_t new_local_port)
Update the local port.
void send (const boost::asio::ip::address &target_addr, const uint16_t target_port, std::shared_ptr< io_buf_t > pbuf)
Unicast sent to the specified target address.
void broadcast (const uint16_t target_port, std::shared_ptr< io_buf_t > pbuf)
Broadcast send out the socket.
Public Member Functions inherited from px::asio::CIoTransactor
CIoTransactor (CIoManager &manager, const CProtocolHandler &prot)
Constructor.
virtual ~CIoTransactor ()
Destructor.
PUBLIC void start ()
Kick-start the messenger by waiting for incoming data.
PUBLIC iobuf_const_pair_t get_rbuf ()
Get the currently-read message boundaries.
PUBLIC void clear_rbuf (iobuf_const_iter_t end)
Clear (perhaps only partially) the read-buffer contents after servicing a single request.
PUBLIC bool get_parse_success ()
PUBLIC void set_parse_failed (bool val)
virtual PUBLIC uint16_t source_port ()
Get port number of the source of a message (0 if N/A).
virtual PUBLIC void write (std::shared_ptr< io_buf_t > pbuf)
Write data to the messenger's output channel's outbox.
Public Member Functions inherited from px::asio::CIoActor
CIoActor (CIoManager &manager)
Constructor.
virtual ~CIoActor ()
Destructor.
boost::asio::io_service & get_io_service () const
Get the I/O service associated with the owner of this actor.
PUBLIC CServerCore & get_server_core () const
Get the container for CDS data management.
PUBLIC CCdsHandler & get_cds_handler () const
Get the container for CDS data management.
PUBLIC bool get_quit_status ()
Get the quit status from connection IO manager.
Static Public Member Functions
static PUBLIC std::shared_ptr
< CUdpSender > create (CIoManager &manager, const CProtocolHandler &prot, uint16_t port)
Factory function to create a new CUdpSender object.
Protected Member Functions
void write_more (const std::shared_ptr< io_buf_t > &pbuf) override
Write the data from the outbox to the service.
Protected Member Functions inherited from px::asio::CIoTransactor
void handle_read (const boost::system::error_code &err, size_t bytes_transferred)
Callback function to handle incoming data.
void handle_write (const boost::system::error_code &err, size_t bytes_transferred)
Callback function to handle a completed "write" operation.
void parse ()
Attempt to parse the currently-read data in the buffer.
void clear_outbox ()
Clear the outbox queue.
std::shared_ptr< io_buf_t > get_outbox_front_buf ()
Get the front item from the outbox if any.
Protected Member Functions inherited from px::asio::CIoActor
void remove ()
This method is called when an actor wants to remove itself from the I/O management interface.
Private Member Functions
void on_write (const boost::system::error_code &err, size_t bytes_transferred)
Callback function for Boost.Asio upon writing UDP data.
Private Attributes
std::unique_ptr
< boost::asio::ip::udp::udp::socket > _udp_socket
The UDP socket that this Actor will open, at _port, and send from.
std::unique_ptr
< boost::asio::ip::udp::udp::endpoint > _local_endpoint
Local endpoint.
std::unique_ptr
< boost::asio::ip::udp::udp::endpoint > _remote_endpoint
Remote endpoint.
std::shared_ptr< CProtocolHandler > _prot
Protocol-specific handler, used to parse and handle incoming requests and generate responses (needed to assign each accepted connection an appropriate protocol handler).
uint16_t _port
Port number that we are sending from and to.
bool _shutdown
Set true by close() for clean, error-free shutdown of a socket.
Additional Inherited Members
Public Attributes inherited from px::asio::CIoTransactor
bool started
True if start() has been called This can be used to distinguish e.g.
Protected Attributes inherited from px::asio::CIoTransactor
io_buf_t _rbuf
I/O buffer used for reading message data.
size_t _offset
Current offset in _rbuf, i.e.
std::shared_ptr< CProtocolHandler > _prot
Protocol-specific handler, used to parse and handle incoming requests and generate responses.
std::queue< std::shared_ptr
< io_buf_t > > _outbox
Queues the outgoing data to send.
Protected Attributes inherited from px::asio::CIoActor
CIoManager & _owner
The I/O manager object that "owns" this connection.
Detailed Description
UDP Socket Sender class, used to Send packets on a UDP port
This class implements a UPD sender.
It sends from a specific UDP port, to the destination address and port that is provided each time.
Note: has no current uses; may need work.
Definition at line 44 of file udp_sender.hpp.
Constructor & Destructor Documentation
px::asio::CUdpSender::CUdpSender (CIoManager & manager, const CProtocolHandler & prot, uint16_t port)
Constructor.
Parameters
manager The I/O manager object to which this sender is to be bound.
prot Protocol handler object which is utilized to perform protocol-specific operations in an abstracted manner
port The local UDP port from which we should send
Exceptions
boost::system::system_error The sender could not be initialized.
Definition at line 43 of file udp_sender.cpp.
References _local_endpoint, _prot, _remote_endpoint, LIBPX_DEBUG, LIBPX_FERR, px::asio::CProtocolHandler::protocol(), reset_socket(), and px::asio::CIoTransactor::start().
Referenced by create().
px::asio::CUdpSender::~CUdpSender ()
Destructor.
Definition at line 81 of file udp_sender.cpp.
References close(), and LIBPX_FERR.
Member Function Documentation
std::shared_ptr< CUdpSender > px::asio::CUdpSender::create (CIoManager & manager, const CProtocolHandler & prot, uint16_t port) static
Factory function to create a new CUdpSender object.
Parameters
manager The I/O manager object to which this object is to be bound
prot Protocol handler object which is utilized to perform protocol-specific operations in an abstracted manner
port The local UDP port from which we should send
Exceptions
boost::system::system_error The sender could not be initialized.
Returns
Shared pointer containing the new instance of CUdpSender.
Definition at line 30 of file udp_sender.cpp.
References CUdpSender().
void px::asio::CUdpSender::close () virtual
Inherited from CIoActor.
Reimplemented from px::asio::CIoTransactor.
Definition at line 123 of file udp_sender.cpp.
References _prot, _shutdown, and _udp_socket.
Referenced by ~CUdpSender().
bool px::asio::CUdpSender::is_open ()
Access method to test if the connection is open.
Returns
True if open.
Definition at line 135 of file udp_sender.cpp.
References _udp_socket.
const std::string px::asio::CUdpSender::source () virtual
Get the source of a UDP message as dotted IP address text.
This function is only here to satisfy inheritance requirements for CIoTransactor. This is a do-nothing function.
Returns
Source address (IPv4 or v6) as dotted decimal text.
Implements px::asio::CIoTransactor.
Definition at line 220 of file udp_sender.hpp.
void px::asio::CUdpSender::read_more () override virtual
Inherited from CIoTransactor.
This function is only here to satisfy inheritance requirements for CIoTransactor. This is a do-nothing function.
Implements px::asio::CIoTransactor.
Definition at line 145 of file udp_sender.cpp.
void px::asio::CUdpSender::reset_socket ()
Create or reset our sending socket, at _port.
Definition at line 95 of file udp_sender.cpp.
References _local_endpoint, _shutdown, _udp_socket, px::asio::CIoActor::get_io_service(), and LIBPX_FERR.
Referenced by CUdpSender(), on_write(), and update_local_port().
void px::asio::CUdpSender::update_local_port (const uint16_t new_local_port)
Update the local port.
Update the local socket as well.
Parameters
new_local_port Local port to bind to
Definition at line 217 of file udp_sender.cpp.
References _local_endpoint, _port, and reset_socket().
void px::asio::CUdpSender::send (const boost::asio::ip::address & target_addr, const uint16_t target_port, std::shared_ptr< io_buf_t > pbuf)
Unicast sent to the specified target address.
Parameters
target_addr Who we will send the message to
target_port Port to send to
pbuf Buffer of data to send.
Definition at line 234 of file udp_sender.cpp.
References _local_endpoint, _port, _remote_endpoint, LIBPX_DEBUG, and px::asio::CIoTransactor::write().
void px::asio::CUdpSender::broadcast (const uint16_t target_port, std::shared_ptr< io_buf_t > pbuf)
Broadcast send out the socket.
Parameters
target_port Port to broadcast to
pbuf Buffer of data to send.
Definition at line 254 of file udp_sender.cpp.
References _local_endpoint, _port, _remote_endpoint, _udp_socket, LIBPX_DEBUG, and px::asio::CIoTransactor::write().
void px::asio::CUdpSender::write_more (const std::shared_ptr< io_buf_t > & pbuf) override protected virtual
Write the data from the outbox to the service.
Implements px::asio::CIoTransactor.
Definition at line 153 of file udp_sender.cpp.
References _remote_endpoint, _udp_socket, LIBPX_DEBUG, LIBPX_WARN, on_write(), and px::string.
void px::asio::CUdpSender::on_write (const boost::system::error_code & err, size_t bytes_transferred) private
Callback function for Boost.Asio upon writing UDP data.
Parameters
err The error code (if any) returned from the asynchronous write operation
bytes_transferred The number of bytes received
Definition at line 190 of file udp_sender.cpp.
References _shutdown, px::asio::CIoTransactor::handle_write(), and reset_socket().
Referenced by write_more().
Member Data Documentation
std::unique_ptr<boost::asio::ip::udp::udp::socket> px::asio::CUdpSender::_udp_socket private
The UDP socket that this Actor will open, at _port, and send from.
Definition at line 185 of file udp_sender.hpp.
Referenced by broadcast(), close(), is_open(), reset_socket(), and write_more().
std::unique_ptr<boost::asio::ip::udp::udp::endpoint> px::asio::CUdpSender::_local_endpoint private
Local endpoint.
Definition at line 190 of file udp_sender.hpp.
Referenced by broadcast(), CUdpSender(), reset_socket(), send(), and update_local_port().
std::unique_ptr<boost::asio::ip::udp::udp::endpoint> px::asio::CUdpSender::_remote_endpoint private
Remote endpoint.
Definition at line 195 of file udp_sender.hpp.
Referenced by broadcast(), CUdpSender(), send(), and write_more().
std::shared_ptr<CProtocolHandler> px::asio::CUdpSender::_prot private
Protocol-specific handler, used to parse and handle incoming requests and generate responses (needed to assign each accepted connection an appropriate protocol handler).
Definition at line 202 of file udp_sender.hpp.
Referenced by close(), and CUdpSender().
uint16_t px::asio::CUdpSender::_port private
Port number that we are sending from and to.
Definition at line 207 of file udp_sender.hpp.
Referenced by broadcast(), send(), and update_local_port().
bool px::asio::CUdpSender::_shutdown private
Set true by close() for clean, error-free shutdown of a socket.
Definition at line 212 of file udp_sender.hpp.
Referenced by close(), on_write(), and reset_socket().
The documentation for this class was generated from the following files:
udp_sender.hpp
udp_sender.cpp