libpx: px::asio::CUdpListener Class Reference
px::asio::CUdpListener Class Reference
ASIO interface details and general IO functions. | IO_Actors
UDP Socket Listener class, used to listen on a UDP port.
#include <udp_listener.hpp>
Public Member Functions
PUBLIC CUdpListener (CIoManager &manager, const CProtocolHandler &prot, uint16_t port)
Constructor.
PUBLIC ~CUdpListener ()
Destructor.
virtual PUBLIC void close ()
Inherited from CIoActor.
PUBLIC bool is_open ()
Access method to test if the connection is open.
virtual PUBLIC const std::string source ()
Get the source of a UDP message as dotted IP address text.
PUBLIC const
boost::asio::ip::address get_source_address (uint16_t &source_port) const
Gets the source address and port of the message currently being processed.
PUBLIC const
boost::asio::ip::address get_destination_address (uint16_t &dest_port) const
Gets the destination address (us) and port of the message currently being processed.
void read_more () override
Inherited from CIoTransactor.
virtual PUBLIC void write (std::shared_ptr< io_buf_t > pbuf)
Override of the base function to write data to the messenger's output channel's outbox.
void write_push (const boost::asio::ip::address &target_addr, uint16_t target_port, std::shared_ptr< io_buf_t > pbuf)
One-way (pushed) write to the specified target address.
void reset_socket ()
Create or reset our listening socket, at _port.
bool was_broadcast ()
Determine if last packet was sent to us as a broadcast or multicast.
void set_want_response ()
Force there to be a response sent to the sender, even if responding to a broadcast request.
void update_local_port (const uint16_t new_local_port)
Update the local port.
void subnet_broadcast (const boost::asio::ip::address_v4 &bcast_addr, const uint16_t target_port, std::shared_ptr< io_buf_t > pbuf)
Send the given buffer to the given port as a local subnet broadcast.
void broadcast (const uint16_t target_port, std::shared_ptr< io_buf_t > pbuf)
Send the given buffer to the given port as a Global broadcast.
Public Member Functions inherited from px::asio::CIoTransactor
CIoTransactor (CIoManager &manager, const CProtocolHandler &prot)
Constructor.
virtual ~CIoTransactor ()
Destructor.
PUBLIC void start ()
Kick-start the messenger by waiting for incoming data.
PUBLIC iobuf_const_pair_t get_rbuf ()
Get the currently-read message boundaries.
PUBLIC void clear_rbuf (iobuf_const_iter_t end)
Clear (perhaps only partially) the read-buffer contents after servicing a single request.
PUBLIC bool get_parse_success ()
PUBLIC void set_parse_failed (bool val)
virtual PUBLIC uint16_t source_port ()
Get port number of the source of a message (0 if N/A).
Public Member Functions inherited from px::asio::CIoActor
CIoActor (CIoManager &manager)
Constructor.
virtual ~CIoActor ()
Destructor.
boost::asio::io_service & get_io_service () const
Get the I/O service associated with the owner of this actor.
PUBLIC CServerCore & get_server_core () const
Get the container for CDS data management.
PUBLIC CCdsHandler & get_cds_handler () const
Get the container for CDS data management.
PUBLIC bool get_quit_status ()
Get the quit status from connection IO manager.
Static Public Member Functions
static PUBLIC std::shared_ptr
< CUdpListener > create (CIoManager &manager, const CProtocolHandler &prot, uint16_t port)
Factory function to create a new CUdpListener instance.
Protected Member Functions
void write_more (const std::shared_ptr< io_buf_t > &pbuf) override
Write the data from the outbox to the service.
Protected Member Functions inherited from px::asio::CIoTransactor
void handle_read (const boost::system::error_code &err, size_t bytes_transferred)
Callback function to handle incoming data.
void handle_write (const boost::system::error_code &err, size_t bytes_transferred)
Callback function to handle a completed "write" operation.
void parse ()
Attempt to parse the currently-read data in the buffer.
void clear_outbox ()
Clear the outbox queue.
std::shared_ptr< io_buf_t > get_outbox_front_buf ()
Get the front item from the outbox if any.
Protected Member Functions inherited from px::asio::CIoActor
void remove ()
This method is called when an actor wants to remove itself from the I/O management interface.
Private Member Functions
void on_read (const boost::system::error_code &err, size_t bytes_recvd)
Callback function for Boost.Asio upon accepting UDP data.
size_t read_with_msgs (boost::system::error_code &ec)
Read incoming UDP packet and receive header message indicating original destination address.
void on_write (const boost::system::error_code &err, size_t bytes_transferred)
Callback function for Boost.Asio upon writing UDP data.
Private Attributes
std::unique_ptr
< boost::asio::ip::udp::udp::socket > _udp_socket
The UDP socket that this Actor will open, at _port, and listen on.
std::unique_ptr
< boost::asio::ip::udp::udp::endpoint > _sender_endpoint
Normally, the endpoint information of the source of a received packet, to which we will send response(s) back.
std::queue< std::shared_ptr
< boost::asio::ip::udp::udp::endpoint > > _endpoint_queue
Queues the endpoint address to send with each output buffer.
std::unique_ptr
< boost::asio::ip::udp::udp::endpoint > _local_endpoint
I think this is meant to be your actual IP address and port, as you would get from ifconfig.
std::unique_ptr
< boost::asio::ip::udp::udp::endpoint > _orig_dest_endpoint
The endpoint that a received message was originally addressed to (ie, us, but with the specifics of broadcast or directed IP).
std::shared_ptr< CProtocolHandler > _prot
Protocol-specific handler, used to parse and handle incoming requests and generate responses (needed to assign each accepted connection an appropriate protocol handler).
uint16_t _port
Port number that we are listening on.
bool _shutdown
Set true by close() for clean, error-free shutdown of a socket.
bool _want_response
Flag to indicate if we should send a response message.
Additional Inherited Members
Public Attributes inherited from px::asio::CIoTransactor
bool started
True if start() has been called This can be used to distinguish e.g.
Protected Attributes inherited from px::asio::CIoTransactor
io_buf_t _rbuf
I/O buffer used for reading message data.
size_t _offset
Current offset in _rbuf, i.e.
std::shared_ptr< CProtocolHandler > _prot
Protocol-specific handler, used to parse and handle incoming requests and generate responses.
std::queue< std::shared_ptr
< io_buf_t > > _outbox
Queues the outgoing data to send.
Protected Attributes inherited from px::asio::CIoActor
CIoManager & _owner
The I/O manager object that "owns" this connection.
Detailed Description
UDP Socket Listener class, used to listen on a UDP port.
This class implements a UDP "listener". It listens to a specific UDP port and manages responses to the incoming requests. In the normal case, we receive a request on this port, process it, and send a response (unicast) back to the sender. If the incoming message was broadcast to us, the _want_response flag is cleared and the default response is to send no reply to this message; if you do want to reply to a broadcast input, then you need to set the _want_response flag.
This class does keep a queue of destination endpoints to match the queue of output buffers (messages) to be sent.
This class is not a good choice if you need to send messages out for which you expect a reply (matched somehow to your request), at least as currently designed. However, there is a simple write_push() provided to send a oneway message out.
Definition at line 55 of file udp_listener.hpp.
Constructor & Destructor Documentation
px::asio::CUdpListener::CUdpListener (CIoManager & manager, const CProtocolHandler & prot, uint16_t port)
Constructor.
Parameters
manager The I/O manager object to which this listener is to be bound.
prot Protocol handler object which is utilized to perform protocol-specific operations in an abstracted manner; the listener doesn't need this directly, but individual connections will.
port The UDP port to which we should listen
Exceptions
boost::system::system_error The listener could not be initialized.
Definition at line 44 of file udp_listener.cpp.
References _prot, LIBPX_DEBUG, LIBPX_FERR, px::asio::CProtocolHandler::protocol(), reset_socket(), and px::asio::CIoTransactor::start().
Referenced by create().
px::asio::CUdpListener::~CUdpListener ()
Destructor.
Definition at line 75 of file udp_listener.cpp.
References close(), LIBPX_FDEBUG, and LIBPX_FERR.
Member Function Documentation
std::shared_ptr< CUdpListener > px::asio::CUdpListener::create (CIoManager & manager, const CProtocolHandler & prot, uint16_t port) static
Factory function to create a new CUdpListener instance.
Parameters
manager The I/O manager object to which this object is to be bound
prot Protocol handler object which is utilized to perform protocol-specific operations in an abstracted manner; the listener doesn't need this directly, but individual connections will.
port The UDP port to which we should listen
Exceptions
boost::system::system_error The listener could not be initialized.
Returns
Shared pointer containing the new instance of CUdpListener.
Definition at line 31 of file udp_listener.cpp.
References CUdpListener().
void px::asio::CUdpListener::close () virtual
Inherited from CIoActor.
Reimplemented from px::asio::CIoTransactor.
Definition at line 138 of file udp_listener.cpp.
References _prot, _shutdown, _udp_socket, and LIBPX_FDEBUG.
Referenced by ~CUdpListener().
bool px::asio::CUdpListener::is_open ()
Access method to test if the connection is open.
Returns
True if open.
Definition at line 151 of file udp_listener.cpp.
References _udp_socket.
const std::string px::asio::CUdpListener::source () virtual
Get the source of a UDP message as dotted IP address text.
Returns
Source address (IPv4 or v6) as dotted decimal text.
Implements px::asio::CIoTransactor.
Definition at line 346 of file udp_listener.hpp.
References _sender_endpoint.
const boost::asio::ip::address px::asio::CUdpListener::get_source_address (uint16_t & source_port) const
Gets the source address and port of the message currently being processed.
Parameters
[out] source_port Port number of the source of the current received message.
Returns
The IP Address of the source of the current message. This is the generic ASIO ip::address type, so it will work for either IPv4 or v6.
Definition at line 492 of file udp_listener.cpp.
References _sender_endpoint.
const boost::asio::ip::address px::asio::CUdpListener::get_destination_address (uint16_t & dest_port) const
Gets the destination address (us) and port of the message currently being processed.
Parameters
[out] dest_port Port number of the destination of the current received message.
Returns
The IP Address of the destination of the current message. Normally will be the same as our IP address, but could be a broadcast address. This is the generic ASIO ip::address type, so it will work for either IPv4 or v6.
Definition at line 505 of file udp_listener.cpp.
References _orig_dest_endpoint.
void px::asio::CUdpListener::read_more () override virtual
Inherited from CIoTransactor.
Implements px::asio::CIoTransactor.
Definition at line 160 of file udp_listener.cpp.
References px::asio::CIoTransactor::_offset, _port, px::asio::CIoTransactor::_rbuf, _sender_endpoint, _udp_socket, LIBPX_DEBUG, on_read(), and UDP_VER.
void px::asio::CUdpListener::write (std::shared_ptr< io_buf_t > pbuf) virtual
Override of the base function to write data to the messenger's output channel's outbox.
This call queues the data to the outbox, which will eventually be sent to the asio channel asynchronously. The reason it is overridden here is to also queue up the current _send_endpoint, which has presumably been filled out by the receiving function with the source's address. This function also checks the _want_response flag, and just drops the packet if not set.
This is the "normal" response function; the write functions in this class let you set a specific target address or broadcast address. (These also end by calling this function.)
Parameters
pbuf The buffer of IO data to be written (ie, the message). Must not be null.
Reimplemented from px::asio::CIoTransactor.
Definition at line 332 of file udp_listener.cpp.
References _endpoint_queue, _local_endpoint, _orig_dest_endpoint, _sender_endpoint, _want_response, LIBPX_DEBUG, LIBPX_WARN, px::string, and px::asio::CIoTransactor::write().
Referenced by broadcast(), subnet_broadcast(), and write_push().
void px::asio::CUdpListener::write_push (const boost::asio::ip::address & target_addr, uint16_t target_port, std::shared_ptr< io_buf_t > pbuf)
One-way (pushed) write to the specified target address.
Allows you to write data out when there hasn't been a corresponding input to "respond" to, as is the normal case where write() is called. So no response is expected, though we resume listening for input after sending.
Parameters
target_addr Who we will send the message to; allowed to be a broadcast address.
target_port Port to write to on the target.
pbuf Buffer of data to send. Must not be null.
Definition at line 471 of file udp_listener.cpp.
References _sender_endpoint, _want_response, LIBPX_DEBUG, and write().
void px::asio::CUdpListener::reset_socket ()
Create or reset our listening socket, at _port.
Definition at line 90 of file udp_listener.cpp.
References _port, _sender_endpoint, _shutdown, _udp_socket, px::asio::CIoActor::get_io_service(), LIBPX_DEBUG, LIBPX_FDEBUG, LIBPX_FERR, LIBPX_INFO, and UDP_VER.
Referenced by CUdpListener(), on_read(), on_write(), and update_local_port().
bool px::asio::CUdpListener::was_broadcast ()
Determine if last packet was sent to us as a broadcast or multicast.
Returns
true if last packet was broadcast or multicast, false otherwise
Definition at line 307 of file udp_listener.cpp.
References _local_endpoint, _orig_dest_endpoint, and _sender_endpoint.
Referenced by on_read().
void px::asio::CUdpListener::set_want_response ()
Force there to be a response sent to the sender, even if responding to a broadcast request.
This will override the default for broadcast inputs, which is to not respond. Normally this response will be unicast; however, if _sender_endpoint is overridden to be a broadcast address, then the response will be a broadcast.
Definition at line 351 of file udp_listener.hpp.
References _want_response.
void px::asio::CUdpListener::update_local_port (const uint16_t new_local_port)
Update the local port.
Update the local socket as well.
Parameters
new_local_port Local port to bind to
Definition at line 517 of file udp_listener.cpp.
References _port, _sender_endpoint, LIBPX_INFO, reset_socket(), and UDP_VER.
void px::asio::CUdpListener::subnet_broadcast (const boost::asio::ip::address_v4 & bcast_addr, const uint16_t target_port, std::shared_ptr< io_buf_t > pbuf)
Send the given buffer to the given port as a local subnet broadcast.
Sets _sender_endpoint to the subnet broadcast address for this device.
Parameters
bcast_addr IPv4 Boost ASIO IP address
target_port Port to broadcast to
pbuf Buffer of data to send. Must not be null.
Definition at line 554 of file udp_listener.cpp.
References _sender_endpoint, _want_response, LIBPX_DEBUG, LIBPX_WARN, and write().
void px::asio::CUdpListener::broadcast (const uint16_t target_port, std::shared_ptr< io_buf_t > pbuf)
Send the given buffer to the given port as a Global broadcast.
Sets _sender_endpoint to the global broadcast IP address.
Parameters
target_port Port to broadcast to
pbuf Buffer of data to send. Must not be null.
Definition at line 535 of file udp_listener.cpp.
References _sender_endpoint, _want_response, LIBPX_DEBUG, and write().
void px::asio::CUdpListener::write_more (const std::shared_ptr< io_buf_t > & pbuf) override protected virtual
Write the data from the outbox to the service.
This implements the virtual function for the UdpListener class.
Parameters
pbuf One buffer of data to write out.
Implements px::asio::CIoTransactor.
Definition at line 371 of file udp_listener.cpp.
References _endpoint_queue, _udp_socket, LIBPX_DEBUG, LIBPX_WARN, and on_write().
void px::asio::CUdpListener::on_read (const boost::system::error_code & err, size_t bytes_recvd) private
Callback function for Boost.Asio upon accepting UDP data.
Parameters
err The error code (if any) returned from the asynchronous read operation
bytes_recvd The number of bytes received
Definition at line 179 of file udp_listener.cpp.
References _orig_dest_endpoint, _sender_endpoint, _shutdown, _want_response, px::asio::CIoTransactor::handle_read(), LIBPX_DEBUG, LIBPX_FERR, LIBPX_WARN, read_with_msgs(), reset_socket(), and was_broadcast().
Referenced by read_more().
size_t px::asio::CUdpListener::read_with_msgs (boost::system::error_code & ec) private
Read incoming UDP packet and receive header message indicating original destination address.
Parameters
err The error code (if any) returned from socket operations
Returns
number of message data bytes received
Definition at line 227 of file udp_listener.cpp.
References _local_endpoint, px::asio::CIoTransactor::_offset, _orig_dest_endpoint, _port, px::asio::CIoTransactor::_rbuf, _sender_endpoint, _udp_socket, LIBPX_DEBUG, and UDP_VER.
Referenced by on_read().
void px::asio::CUdpListener::on_write (const boost::system::error_code & err, size_t bytes_transferred) private
Callback function for Boost.Asio upon writing UDP data.
Parameters
err The error code (if any) returned from the asynchronous write operation
bytes_transferred The number of bytes received
Definition at line 422 of file udp_listener.cpp.
References _endpoint_queue, px::asio::CIoTransactor::_outbox, _port, _sender_endpoint, _shutdown, px::asio::CIoTransactor::handle_write(), LIBPX_DEBUG, LIBPX_WARN, reset_socket(), and UDP_VER.
Referenced by write_more().
Member Data Documentation
std::unique_ptr<boost::asio::ip::udp::udp::socket> px::asio::CUdpListener::_udp_socket private
The UDP socket that this Actor will open, at _port, and listen on.
Definition at line 284 of file udp_listener.hpp.
Referenced by close(), is_open(), read_more(), read_with_msgs(), reset_socket(), and write_more().
std::unique_ptr<boost::asio::ip::udp::udp::endpoint> px::asio::CUdpListener::_sender_endpoint private
Normally, the endpoint information of the source of a received packet, to which we will send response(s) back.
Some of the broadcast sending functions also set this directly. When the message is ready to write, this will be pushed onto the _endpoint_queue.
Definition at line 292 of file udp_listener.hpp.
Referenced by broadcast(), get_source_address(), on_read(), on_write(), read_more(), read_with_msgs(), reset_socket(), source(), subnet_broadcast(), update_local_port(), was_broadcast(), write(), and write_push().
std::queue<std::shared_ptr<boost::asio::ip::udp::udp::endpoint> > px::asio::CUdpListener::_endpoint_queue private
Queues the endpoint address to send with each output buffer.
This queue is necessary for UDP messages since there is no single "connection" to the other end, as there is for TCP connections. This queue parallels the _outbox message buffer queue, and must be kept in sync with that queue.
Definition at line 300 of file udp_listener.hpp.
Referenced by on_write(), write(), and write_more().
std::unique_ptr<boost::asio::ip::udp::udp::endpoint> px::asio::CUdpListener::_local_endpoint private
I think this is meant to be your actual IP address and port, as you would get from ifconfig.
Definition at line 305 of file udp_listener.hpp.
Referenced by read_with_msgs(), was_broadcast(), and write().
std::unique_ptr<boost::asio::ip::udp::udp::endpoint> px::asio::CUdpListener::_orig_dest_endpoint private
The endpoint that a received message was originally addressed to (ie, us, but with the specifics of broadcast or directed IP).
Definition at line 311 of file udp_listener.hpp.
Referenced by get_destination_address(), on_read(), read_with_msgs(), was_broadcast(), and write().
std::shared_ptr<CProtocolHandler> px::asio::CUdpListener::_prot private
Protocol-specific handler, used to parse and handle incoming requests and generate responses (needed to assign each accepted connection an appropriate protocol handler).
Definition at line 318 of file udp_listener.hpp.
Referenced by close(), and CUdpListener().
uint16_t px::asio::CUdpListener::_port private
Port number that we are listening on.
Definition at line 323 of file udp_listener.hpp.
Referenced by on_write(), read_more(), read_with_msgs(), reset_socket(), and update_local_port().
bool px::asio::CUdpListener::_shutdown private
Set true by close() for clean, error-free shutdown of a socket.
Definition at line 328 of file udp_listener.hpp.
Referenced by close(), on_read(), on_write(), and reset_socket().
bool px::asio::CUdpListener::_want_response private
Flag to indicate if we should send a response message.
Will be set true if received was not broadcast or if was received as a broadcast but has been overriden by a call to set_want_response().
If this flag is cleared (ie, received as a broadcast) when we write, we actually just drop any response and send nothing back.
Definition at line 338 of file udp_listener.hpp.
Referenced by broadcast(), on_read(), set_want_response(), subnet_broadcast(), write(), and write_push().
The documentation for this class was generated from the following files:
udp_listener.hpp
udp_listener.cpp