libpx: px::db::CBatch Class Reference
px::db::CBatch Class Reference
Batch of Database Operations.
#include <batch.hpp>
Public Types
typedef std::pair
< std::shared_ptr< CBlobHolder >
, std::shared_ptr< CBlobHolder > > key_value_pair_t
Public Member Functions
PUBLIC CBatch ()
Constructor.
PUBLIC ~CBatch ()
Destructor.
PUBLIC void clear ()
Clear the current batch, and the key/value blobs buffer.
PUBLIC void add (CBlobHolder &&key, CBlobHolder &&value, bool ensure_unique=true)
Add an entry (key/value row) to the database.
PUBLIC void remove (CBlobHolder &&key)
Remove entries from the database (the key will be duplicated in the buffer)
Private Attributes
std::unique_ptr
< leveldb::WriteBatch > _batch
Batch of writes to be applied to the database.
std::vector< key_value_pair_t > _key_value_pairs
Cached key/value pairs for the write operation.
Detailed Description
Batch of Database Operations.
When modifying a key/value database, this class is used to lump together all of the modifications into a single atomic unit. This is beneficial both semantically (e.g. to ensure that the database isn't partially updated in the case of a crash), as well as for performance reasons. This class maintain the key/value blobs to be live until the clear or delete, because the levelDB write batch require the buffer to be alive.
Definition at line 28 of file batch.hpp.
Member Typedef Documentation
typedef std::pair<std::shared_ptr<CBlobHolder>, std::shared_ptr<CBlobHolder> > px::db::CBatch::key_value_pair_t
Definition at line 85 of file batch.hpp.
Constructor & Destructor Documentation
px::db::CBatch::CBatch ()
Constructor.
Creates an empty batch
Definition at line 12 of file batch.cpp.
px::db::CBatch::~CBatch ()
Destructor.
Definition at line 19 of file batch.cpp.
Member Function Documentation
void px::db::CBatch::clear ()
Clear the current batch, and the key/value blobs buffer.
This call re-initializes the batch contents, so that all operations accumulated so far are discarded.
Definition at line 25 of file batch.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), px::db::CleanupAlarms(), px::db::DeleteClosedAlarms(), px::db::DeleteTrends(), px::db::DeleteTrendsInternal(), and px::db::StoreTrendBucketsToDb().
void px::db::CBatch::add (CBlobHolder && key, CBlobHolder && value, bool ensure_unique = true)
Add an entry (key/value row) to the database.
This call adds a set/write/put operation to the batch, which (when applied) will append the given key/value pair to the database. The key/value contents should not be modified in any way.
Parameters
key The key for this entry
value The value for this entry
ensure_unique If true, this call will remove any existing entries which match 'key' prior to adding the new entry
Definition at line 36 of file batch.cpp.
Referenced by px::db::AddChannelToBatch(), px::db::AddDeviceToBatch(), px::db::AddOOBToBatch(), px::db::AddTrendBucketToBatch(), px::db::AddTrendStageToBatch(), px::db::allocate_ids(), px::db::CheckIDDB(), px::db::CleanupAlarms(), px::db::reserve_ids(), px::db::SaveAlarmUpdates(), px::db::SetSchemaVersion(), and px::db::SetTrendStageDbTombstoned().
void px::db::CBatch::remove (CBlobHolder && key)
Remove entries from the database (the key will be duplicated in the buffer)
This call will remove any entries in the database whose keys match the supplied key
Parameters
key The key used to find matching entries for removal
Definition at line 61 of file batch.cpp.
Referenced by px::db::AddClearOOBToBatch(), px::db::AddDeleteChannelToBatch(), px::db::AddDeleteDeviceToBatch(), px::db::CleanupAlarms(), px::db::DeleteAlarms(), px::db::DeleteClosedAlarms(), px::db::DeleteTrends(), px::db::DeleteTrendsInternal(), px::db::LevelupBucketTrendsForChannel(), px::db::MigrateAlarmDB(), and px::db::SetTrendStageDbTombstoned().
Member Data Documentation
std::unique_ptr<leveldb::WriteBatch> px::db::CBatch::_batch private
Batch of writes to be applied to the database.
Definition at line 98 of file batch.hpp.
Referenced by px::db::CKeyValueStore::write().
std::vector<key_value_pair_t> px::db::CBatch::_key_value_pairs private
Cached key/value pairs for the write operation.
Definition at line 103 of file batch.hpp.
The documentation for this class was generated from the following files:
batch.hpp
batch.cpp