libpx: px::eq::CPxValue Class Reference
px::eq::CPxValue Class Reference
Define a class with all necessary function overloads for performing supported equation operations on a px::CValue object.
#include <px_value.hpp>
Public Member Functions
CPxValue (px::CValue d=px::CValue((float) NAN))
Constructor.
CPxValue (const float &fval)
Copy Constructors to satisfy boost translatable.
CPxValue (const double &dval)
CPxValue (const px::string &sval)
operator bool () const
operator long () const
CPxValue operator[] (CPxValue x) const
CPxValue operator/= (size_t x)
Static Public Member Functions
static bool is_64bit (const px::CValue &x)
Public Attributes
px::CValue val
The actual underlying value.
Friends
CPxValue operator- (CPxValue x)
CPxValue operator! (CPxValue x)
CPxValue sqrt (CPxValue x)
CPxValue abs (CPxValue x)
CPxValue round (CPxValue x)
CPxValue trunc (CPxValue x)
CPxValue ceil (CPxValue x)
CPxValue floor (CPxValue x)
CPxValue exp (CPxValue x)
CPxValue is_nan (CPxValue x)
CPxValue is_inf (CPxValue x)
CPxValue index (CPxValue x, CPxValue y)
CPxValue operator+ (CPxValue x, CPxValue y)
CPxValue operator- (CPxValue x, CPxValue y)
CPxValue operator* (CPxValue x, CPxValue y)
CPxValue operator/ (CPxValue x, CPxValue y)
CPxValue operator< (CPxValue x, CPxValue y)
CPxValue operator> (CPxValue x, CPxValue y)
CPxValue operator<= (CPxValue x, CPxValue y)
CPxValue operator>= (CPxValue x, CPxValue y)
CPxValue operator!= (CPxValue x, CPxValue y)
CPxValue operator== (CPxValue x, CPxValue y)
CPxValue pow (CPxValue x, CPxValue y)
CPxValue operator& (CPxValue x, CPxValue y)
CPxValue operator| (CPxValue x, CPxValue y)
CPxValue operator&& (CPxValue x, CPxValue y)
CPxValue operator|| (CPxValue x, CPxValue y)
CPxValue operator>> (CPxValue x, CPxValue y)
CPxValue operator<< (CPxValue x, CPxValue y)
CPxValue min (const std::vector< CPxValue > &x)
CPxValue max (const std::vector< CPxValue > &x)
CPxValue sum (const std::vector< CPxValue > &x)
CPxValue avg (const std::vector< CPxValue > &x)
Detailed Description
Define a class with all necessary function overloads for performing supported equation operations on a px::CValue object.
This class is a modified version of CSimpleVal, with the templating removed and the specific variadic casting functions of px::CValue used instead.
Definition at line 19 of file px_value.hpp.
Constructor & Destructor Documentation
px::eq::CPxValue::CPxValue (px::CValue d = px::CValue((float) NAN))
Constructor.
Parameters
d Value to assign to this value; if none is provided, it's initialized to NaN
Definition at line 47 of file px_value.hpp.
Referenced by operator[]().
px::eq::CPxValue::CPxValue (const float & fval)
Copy Constructors to satisfy boost translatable.
Definition at line 53 of file px_value.hpp.
px::eq::CPxValue::CPxValue (const double & dval)
Definition at line 56 of file px_value.hpp.
px::eq::CPxValue::CPxValue (const px::string & sval)
Definition at line 59 of file px_value.hpp.
Member Function Documentation
static bool px::eq::CPxValue::is_64bit (const px::CValue & x) static
Definition at line 67 of file px_value.hpp.
References px::float64, px::int64, px::CValue::type(), px::uint64, and px::CDataType::val().
px::eq::CPxValue::operator bool () const
Definition at line 85 of file px_value.hpp.
References px::CValue::as_bool(), px::CValue::as_double(), and val.
px::eq::CPxValue::operator long () const
Definition at line 89 of file px_value.hpp.
References px::CValue::as_int64(), and val.
CPxValue px::eq::CPxValue::operator[] (CPxValue x) const
Definition at line 244 of file px_value.hpp.
References px::CValue::as_uint32(), px::CValue::as_uint64(), CPxValue(), and val.
CPxValue px::eq::CPxValue::operator/= (size_t x)
Definition at line 276 of file px_value.hpp.
References px::CValue::as_double(), px::CDataType::is_numeric(), px::CValue::to(), px::CValue::type(), and val.
Friends And Related Function Documentation
CPxValue operator- (CPxValue x) friend
Definition at line 93 of file px_value.hpp.
CPxValue operator! (CPxValue x) friend
Definition at line 109 of file px_value.hpp.
CPxValue sqrt (CPxValue x) friend
Definition at line 114 of file px_value.hpp.
CPxValue abs (CPxValue x) friend
Definition at line 128 of file px_value.hpp.
CPxValue round (CPxValue x) friend
Definition at line 145 of file px_value.hpp.
CPxValue trunc (CPxValue x) friend
Definition at line 162 of file px_value.hpp.
CPxValue ceil (CPxValue x) friend
Definition at line 180 of file px_value.hpp.
CPxValue floor (CPxValue x) friend
Definition at line 198 of file px_value.hpp.
CPxValue exp (CPxValue x) friend
Definition at line 215 of file px_value.hpp.
CPxValue is_nan (CPxValue x) friend
Definition at line 233 of file px_value.hpp.
CPxValue is_inf (CPxValue x) friend
Definition at line 238 of file px_value.hpp.
CPxValue index (CPxValue x, CPxValue y) friend
Definition at line 254 of file px_value.hpp.
CPxValue operator+ (CPxValue x, CPxValue y) friend
Definition at line 292 of file px_value.hpp.
CPxValue operator- (CPxValue x, CPxValue y) friend
Definition at line 313 of file px_value.hpp.
CPxValue operator* (CPxValue x, CPxValue y) friend
Definition at line 334 of file px_value.hpp.
CPxValue operator/ (CPxValue x, CPxValue y) friend
Definition at line 355 of file px_value.hpp.
CPxValue operator< (CPxValue x, CPxValue y) friend
Definition at line 376 of file px_value.hpp.
CPxValue operator> (CPxValue x, CPxValue y) friend
Definition at line 384 of file px_value.hpp.
CPxValue operator<= (CPxValue x, CPxValue y) friend
Definition at line 394 of file px_value.hpp.
CPxValue operator>= (CPxValue x, CPxValue y) friend
Definition at line 402 of file px_value.hpp.
CPxValue operator!= (CPxValue x, CPxValue y) friend
Definition at line 411 of file px_value.hpp.
CPxValue operator== (CPxValue x, CPxValue y) friend
Definition at line 419 of file px_value.hpp.
CPxValue pow (CPxValue x, CPxValue y) friend
Definition at line 427 of file px_value.hpp.
CPxValue operator& (CPxValue x, CPxValue y) friend
Definition at line 445 of file px_value.hpp.
CPxValue operator| (CPxValue x, CPxValue y) friend
Definition at line 460 of file px_value.hpp.
CPxValue operator&& (CPxValue x, CPxValue y) friend
Definition at line 475 of file px_value.hpp.
CPxValue operator|| (CPxValue x, CPxValue y) friend
Definition at line 483 of file px_value.hpp.
CPxValue operator>> (CPxValue x, CPxValue y) friend
Definition at line 491 of file px_value.hpp.
CPxValue operator<< (CPxValue x, CPxValue y) friend
Definition at line 506 of file px_value.hpp.
CPxValue min (const std::vector< CPxValue > & x) friend
Definition at line 521 of file px_value.hpp.
CPxValue max (const std::vector< CPxValue > & x) friend
Definition at line 535 of file px_value.hpp.
CPxValue sum (const std::vector< CPxValue > & x) friend
Definition at line 550 of file px_value.hpp.
CPxValue avg (const std::vector< CPxValue > & x) friend
Definition at line 569 of file px_value.hpp.
Member Data Documentation
px::CValue px::eq::CPxValue::val
The actual underlying value.
Definition at line 593 of file px_value.hpp.
Referenced by operator bool(), operator long(), operator/=(), and operator[]().
The documentation for this class was generated from the following file:
px_value.hpp