libpx: px::eq::CEquation Class Reference
px::eq::CEquation Class Reference
Equation class.
#include <equation.hpp>
Public Member Functions
CEquation (const px::string &eq)
Constructor.
CEquation (CEquation &&eq)
Move constructor.
PUBLIC ~CEquation ()
Destructor.
operator unspecified_bool_type () const
Boolean conversion specifier.
PUBLIC void parse (const px::string &eq)
Parse the given equation string.
template<typename Translator >
void evaluate (Translator &t) const
Execute this equation, utilizing the given translator to perform GETs, SETs, etc.
template<typename Translator >
void test_evaluate (Translator &t) const
This functions like evaluate(), except that it does a "test run" execution.
Private Types
typedef void(CEquation::* unspecified_bool_type)() const
Private Member Functions
void does_not_support_compare () const
Private Attributes
std::unique_ptr
< detail::statement > _eq
Top-level statement in the AST; executing this statement will thus evaluate the entire equation.
Detailed Description
Equation class.
This class supports the parsing and evaluation of equations. Equation syntax is C-like, and described in detail by an EBNF grammar utilized by Bison to generate the equation parser. Most equations which would work in a C program will also work with this class.
It has been noted that the order of precedence for operations is not entirely correct, eg, for power operations mixed with addition. However, this is presently seen as acceptable, as our users are probably not well enough versed in correct precedence anyway, so the solution is always to "when in doubt, use parentheses".
The functionality of this class is split into two phases, which operate quite differently:
The parsing phase takes a string equation as input, and builds an abstract syntax tree (AST) from the equation, much like a compiler. Scanning is performed by a Flex-generated token scanner, while parsing is performed by a Bison-generated LR parser. The scanning & parsing code is compiled in to this class, since it functions the same regardless of what kinds of objects are being translated. Parsing is relatively expensive, and should typically only be done once for a given equation.
The evaluation phase takes a "translator" as input – an object which is capable of getting and setting variables as they are encountered during equation execution. For example, in the equation "A = B + C;", the translator must 1) GET the value of "B", then 2) GET the value of "C", then 3) SET the value of "A". This code is template-based, which allows the caller to translate any kind of value they want, so long as the value conforms to the "Translatable" concept.
Common implementations of the "Translatable" object are provided by CSimpleVal and CValArray.
Definition at line 75 of file equation.hpp.
Member Typedef Documentation
typedef void(CEquation::* px::eq::CEquation::unspecified_bool_type)() const private
Definition at line 82 of file equation.hpp.
Constructor & Destructor Documentation
px::eq::CEquation::CEquation (const px::string & eq)
Constructor.
See Also
parse
Parameters
eq Equation string to be parsed
Exceptions
parse_error Thrown if the equation contains a parse error
Definition at line 99 of file equation.hpp.
References parse().
px::eq::CEquation::CEquation (CEquation && eq)
Move constructor.
Parameters
eq Equation to be moved to 'this'
Definition at line 109 of file equation.hpp.
px::eq::CEquation::~CEquation ()
Destructor.
Definition at line 12 of file equation.cpp.
Member Function Documentation
void px::eq::CEquation::does_not_support_compare () const private
Definition at line 83 of file equation.hpp.
Referenced by operator unspecified_bool_type().
px::eq::CEquation::operator unspecified_bool_type () const
Boolean conversion specifier.
Returns true iff this is a valid equation object, ready to be evaluated
Definition at line 125 of file equation.hpp.
References _eq, and does_not_support_compare().
void px::eq::CEquation::parse (const px::string & eq)
Parse the given equation string.
The given equation is parsed and stored internally for later use. If another equation was previously in use at this location, it is destroyed and replaced with the new one. Equation must not be empty.
Exceptions
parse_error Thrown if the equation contains a parse error (in which case the object is unchanged)
Definition at line 115 of file equation.tab.cpp.
References _eq, yylex_destroy(), yylex_init(), and px::eq::detail::yyparse().
Referenced by CEquation().
template<typename Translator > void px::eq::CEquation::evaluate (Translator & t) const
Execute this equation, utilizing the given translator to perform GETs, SETs, etc.
based on translation.
Parameters
t The translator to use for equation evaluation
Exceptions
px::generic_err if any toolkit exception is thrown by the handler (Eg, Divide by zero)
px::eq::not_found if an equation Source or Target isn't found There may be other (eg, math lib) exceptions thrown, so the calling function should be prepared to catch any exception.
Definition at line 156 of file equation.hpp.
References _eq, and px::eq::BOOST_CONCEPT_ASSERT().
template<typename Translator > void px::eq::CEquation::test_evaluate (Translator & t) const
This functions like evaluate(), except that it does a "test run" execution.
Test runs still call get() and set() on the given translator like a real execution, but all statements are evaluated rather than just those which are on some conditionally-true path.
For example, if given the equation: "if (a==0) b=c; else b=d;", test_evaluate() will always GET "a", "c", and "d". evaluate(), by contrast, will first GET "a", then depending on its value will either GET "c" or "d" (not both), depending on a's value.
Parameters
t The translator to use for equation evaluation
Exceptions
px::generic_err if any toolkit exception is thrown by the handler (Eg, Divide by zero)
px::eq::not_found if an equation Source or Target isn't found There may be other (eg, math lib) exceptions thrown, so the calling function should be prepared to catch any exception.
Definition at line 188 of file equation.hpp.
References _eq, and px::eq::BOOST_CONCEPT_ASSERT().
Member Data Documentation
std::unique_ptr<detail::statement> px::eq::CEquation::_eq private
Top-level statement in the AST; executing this statement will thus evaluate the entire equation.
Definition at line 209 of file equation.hpp.
Referenced by evaluate(), operator unspecified_bool_type(), parse(), and test_evaluate().
The documentation for this class was generated from the following files:
equation.hpp
equation.cpp
equation.tab.cpp