libpx: px::db Namespace Reference
px::db Namespace Reference
px::db is the namespace for all the classes that provide the database access for Power Xpert Toolkit applications.
Classes
class CBatch
Batch of Database Operations.
class CBlobHolder
Binary Blob Holder class.
class CIterator
Iterator into a sorted string table or key/value database.
class CIteratorOwner
Per-database iterator "owner" class.
class CKeyValueStore
Read-write Key/Value Store.
class CLevelDBLogger
Implement a log-file handler for LevelDB that limits the logs to a fixed size, rotating as necessary.
class CNullMask
Null mask class.
class CSSTable
Read-only Sorted String Table.
class CTestHelper
Unit-test Helper Class.
Enumerations
enum alarm_index_entry_type : uint8_t { alarm_index_entry_type::alarm_id = 1, alarm_index_entry_type::timestamp = 2, alarm_index_entry_type::deletion_note = 3, alarm_index_entry_type::open_scan_start_point = 4 }
enum id_type : uint8_t { id_type::devicechannel = 1, id_type::alarm = 2, id_type::globalcount = 3 }
Functions
PUBLIC uint32_t GetSchemaVersion (CKeyValueStore &db, uint32_t key_len, uint32_t def_ver=0)
Get/set schema version for a database.
PUBLIC void SetSchemaVersion (CKeyValueStore &db, uint32_t key_len, uint32_t version)
PUBLIC void MigrateOOBDB (CKeyValueStore &db)
Given one of our databases, check to see if migration is needed, and perform such migration if so.
PUBLIC void MigrateDeviceDB (CKeyValueStore &db)
PUBLIC void MigrateChannelDB (CKeyValueStore &db, CIterator &mcl_iter)
PUBLIC void MigrateIDDB (CKeyValueStore &db)
PUBLIC void MigrateAlarmDB (CKeyValueStore &db, const std::map< px::id_t, px::CChannel > &channel_map, const std::map< px::id_t, px::CDevice > &device_map)
PUBLIC void MigrateAlarmIndexDB (CKeyValueStore &db)
PUBLIC void AddOOBToBatch (CBatch &batch, const px::string &key, const px::proto::toolkitStruct &value)
Set up a CBatch update to the OOB-data persistent key-value store.
PUBLIC void AddClearOOBToBatch (CBatch &batch, const px::string &key)
PUBLIC bool FetchOOB (CKeyValueStore &db, const px::string &key, px::proto::toolkitStruct &data)
Fetch an OOB data value from the store.
PUBLIC std::vector< px::string > FetchOOBKeys (CKeyValueStore &db)
Fetch a list of all keys in the persistent OOB database.
PUBLIC void FetchOOBs (CKeyValueStore &db, std::map< px::string, px::proto::toolkitStruct > &map)
Fetch all OOB objects from the database, into a map.
PUBLIC void AddDeviceToBatch (CBatch &batch, const px::CDevice &device)
Set up a CBatch update to the device database.
PUBLIC void AddDeleteDeviceToBatch (CBatch &batch, px::id_t device_id)
Set up a CBatch update to the device database.
PUBLIC void FetchDevices (CKeyValueStore &db, std::map< px::id_t, px::CDevice > &map)
Fetch all devices from the database, into a map.
PUBLIC void AddChannelToBatch (CBatch &batch, CIterator &mcl_iter, const px::CChannel &channel)
Set up a CBatch update to the channel database.
PUBLIC void AddDeleteChannelToBatch (CBatch &batch, px::id_t channel_id)
PUBLIC void FetchChannels (CKeyValueStore &db, CIterator &mcl_iter, std::map< px::id_t, px::CChannel > &map, std::map< px::id_t, px::CDevice > &devs)
Fetch all channels from the database, into a map.
PUBLIC px::proto::MclEntry FetchMCLEntry (CIterator &mcl_iter, const px::string &channel_name)
Get an MCL entry, in the form of a channel protobuf.
PUBLIC px::proto::CommandInfo FetchCCLEntry (CIterator &ccl_iter, const px::string &command_name)
Get an CCL entry, in the form of a CommandInfo protobuf.
PUBLIC void QueryAlarms (CKeyValueStore &alarm_db, CKeyValueStore &alarm_index_db, size_t max_result_size, uint64_t start_global_count, const px::CWallTime *start_update_time, const px::CWallTime *end_update_time, const std::unordered_set< px::id_t > *device_ids, const std::unordered_set< px::id_t > *channel_ids, const std::set< px::id_t > *alarm_ids, const std::set< px::id_t > *exclude_alarm_ids, uint32_t starting_sequence_index, bool first_updates_only, bool go_backwards, std::vector< px::CAlarmUpdate > &result, const volatile bool &exit_req, size_t *count_found=nullptr, bool count_all=false, uint32_t trigger_level=0, px::CAlarmTriggerType trigger_type=px::alarm_trigger_type::invalid, bool gt_equal=false)
Return a list of alarm updates, that meet all of the specified criteria, from the alarm history database.
PUBLIC void QueryAlarmsLatestUpdate (CKeyValueStore &alarm_db, CKeyValueStore &alarm_index_db, size_t max_result_size, uint64_t start_global_count, const px::CWallTime *start_first_occur_time, const px::CWallTime *end_first_occur_time, const std::unordered_set< px::id_t > *device_ids, const std::unordered_set< px::id_t > *channel_ids, const std::set< px::id_t > *alarm_ids, const std::set< px::id_t > *exclude_alarm_ids, std::vector< px::CAlarmUpdate > &result, const volatile bool &exit_req, size_t *count_found, bool count_all, uint32_t trigger_level=0, px::CAlarmTriggerType trigger_type=px::alarm_trigger_type::invalid, bool gt_equal=false)
Given alarm parameters, return the most recent update for each matching entry in the database.
PUBLIC void LoadActiveAlarms (CKeyValueStore &alarm_db, CKeyValueStore &alarm_index_db, std::map< px::id_t, px::CAlarmUpdate > &alarms)
Load active alarms from the database into the given map.
PUBLIC void SaveAlarmUpdates (CKeyValueStore &alarm_db, CKeyValueStore &alarm_index_db, const std::vector< px::CAlarmUpdate > &updates, const volatile bool &exit_req)
Add an alarm update to the history database, update the index DB as needed.
PUBLIC void NoteAlarmsToDelete (CKeyValueStore &alarm_index_db, const std::unordered_set< px::id_t > &ids)
Persistently note that alarms with these device and/or channel IDs are to be deleted.
PUBLIC void DeleteAlarms (CKeyValueStore &alarm_db, CKeyValueStore &alarm_index_db, const std::unordered_set< px::id_t > &ids, const volatile bool &exit_req)
Delete alarm updates for the specified devices/channels.
PUBLIC void DeleteClosedAlarms (CKeyValueStore &alarm_db, px::cds::CDeleteAlarms &alms, const volatile bool &exit_req, const std::unordered_set< px::id_t > *device_ids=nullptr, const std::unordered_set< px::id_t > *channel_ids=nullptr)
Delete alarm updates, for the specified alarm ids or those which satify given crieria of end_time, level and keep_count.
PUBLIC void CleanupAlarms (CKeyValueStore &alarm_db, CKeyValueStore &alarm_index_db, uint32_t max_size, const volatile bool &exit_req)
Roll off old alarms if the database has gotten too large.
PUBLIC void CheckIDDB (CKeyValueStore &id_db, CKeyValueStore &device_db, CKeyValueStore &channel_db, CKeyValueStore &alarm_db)
Double-check the ID database against the channel and device DBs, update the last-issued ID to be higher if necessary.
PUBLIC std::vector< px::id_t > AllocateDeviceIDs (CKeyValueStore &id_db, unsigned int num_requested)
Allocate device IDs.
PUBLIC std::vector< px::id_t > AllocateChannelIDs (CKeyValueStore &id_db, unsigned int num_requested)
Allocate channel IDs.
PUBLIC std::vector< px::id_t > AllocateAlarmIDs (CKeyValueStore &id_db, unsigned int num_requested)
Allocate alarm IDs.
PUBLIC std::vector< uint64_t > AllocateGlobalCounts (CKeyValueStore &id_db, unsigned int num_requested)
Allocate alarm global counts.
PUBLIC void ReserveDeviceIDs (CKeyValueStore &id_db, const std::vector< px::id_t > &ids)
Reserve a set of device IDs so that they will not be automatically assigned by AllocateDeviceIDs().
PUBLIC void ReserveChannelIDs (CKeyValueStore &id_db, const std::vector< px::id_t > &ids)
Reserve a set of channel IDs so that they will not be automatically assigned by AllocateChannelIDs().
PUBLIC void ReserveAlarmIDs (CKeyValueStore &id_db, const std::vector< px::id_t > &ids)
Reserve a set of alarm IDs so that they will not be automatically assigned by AllocateAlarmIDs().
PUBLIC void ReserveGlobalCounts (CKeyValueStore &id_db, const std::vector< uint64_t > &ids)
Reserve a set of alarm global counts so that they will not be automatically assigned by AllocateGlobalCounts().
PUBLIC void AddTrendStageToBatch (CBatch &batch, std::vector< std::shared_ptr< px::CTrendStageUpdate > > &updates, int start_index=0, int end_index=-1)
Add the trends from the accumulators to the batch to be stored in trend stage db.
PUBLIC px::CChannelTrends QueryTrendStage (CKeyValueStore &trend_stage_db, const uint32_t channel_id, uint32_t start_time, uint32_t end_time)
Return a list of trends from the stage db, based on the channel id and time range.
void DumpHex (std::ofstream &file, const unsigned char *data, const int length)
Dump the hex string from a binary blob.
void ExportTrendStageRow (const uint32_t channel_id, const uint32_t time, CIterator &iterator, std::ofstream &file, const bool include_avg, const bool include_min, const bool include_max, const bool include_actual, unsigned int &values_count)
Export a record from the trend stage db to an opened file stream.
PUBLIC void ExportTrendStage (CKeyValueStore &trend_stage_db, std::ofstream &file, const std::vector< uint32_t > &channel_ids, uint32_t start_time, uint32_t end_time, const bool include_avg, const bool include_min, const bool include_max, const bool include_actual, const bool include_invalid, const unsigned int row_count_limit, bool &more_data, unsigned int &values_count, unsigned int &row_count, const volatile bool &exit_req)
Export all trends from the stage db to a csv file, returns the exported trends count.
PUBLIC void ExportTrendStageHeaderRow (std::ofstream &file)
Write the header (title) row to the stage trends export CSV file: channel_id, time, mask, avg, min, max, actual.
PUBLIC void ImportTrendStage (const px::string &file_path, std::function< void(std::vector< std::shared_ptr< px::CTrendStageUpdate > > &)> func, int &row_count, int &value_count, const volatile bool &exit_req)
Import trends from a csv file to the daily stage db(s) based on the timestamps; return the imported rows and values count.
PUBLIC void ImportTrendBucket (CKeyValueStore &trend_bucket_db, const px::string &file_path, int &row_count, int &value_count, const volatile bool &exit_req)
Import trends from a csv file to the bucket db, return the imported rows and values count.
PUBLIC bool AddTrendBucketToBatch (CBatch &batch, const std::shared_ptr< px::CTrendBucketUpdate > update)
Add the trend bucket to the batch to be stored in the bucket db.
PUBLIC void StoreTrendBucketsToDb (CKeyValueStore &trend_bucket_db, const std::map< uint32_t, std::shared_ptr< px::CTrendBucketUpdate > > &cache, bool sync_db, const volatile bool &exit_req)
Stores a list of buckets to the bucket db.
PUBLIC void SimulateTrendBucket (CKeyValueStore &trend_bucket_db, const std::vector< uint32_t > &channel_ids, int period, const px::CWallTime &start, const px::CWallTime &end, int &trends_count)
Simulates the data to fill up the trend bucket.
PUBLIC void ReadTrendsFromBucketRow (CIterator &iterator, std::vector< px::CChannelTrend > &result, const uint32_t bucket_end_time, const uint32_t start_minutes, const uint32_t end_minutes, const int request_period, const bool include_avg, const bool include_min, const bool include_max, const bool include_actual, int &read_period, bool &is_double, const unsigned int row_count_limit, unsigned int &row_count, unsigned int &rtn_values_count, bool newest_first=false, bool include_holes=true)
Read trends from a bucket row to the result, based on time range and traits.
PUBLIC void ReadTrendsFromStageRow (px::db::CIterator &it, std::vector< px::CChannelTrend > &trends, const bool include_avg, const bool include_min, const bool include_max, const bool include_actual, bool &is_double, unsigned int &row_count, unsigned int &rtn_values_count)
Read trends from a stage row to the result, based on the traits.
PUBLIC void ExportTrendBucketHeaderRow (std::ofstream &file, const std::vector< uint32_t > &channel_ids, const bool include_avg, const bool include_min, const bool include_max, const bool include_actual)
Write the header (title) row to the bucket trends export CSV file: channel_id, time, mask, avg, min, max, actual Channel IDs must not be empty.
PUBLIC void ExportTrendBucket (CKeyValueStore &trend_bucket_db, std::ofstream &file, const std::vector< uint32_t > &channel_ids, uint32_t start_minutes, uint32_t end_minutes, const bool include_avg, const bool include_min, const bool include_max, const bool include_actual, const unsigned int row_count_limit, bool &more_data, unsigned int &values_count, unsigned int &row_count, const volatile bool &exit_req)
Export a list of channels' trends from the bucket db to a csv file, returns the exported trends count.
PUBLIC void ExportTrendsHeaderRow (std::ofstream &file, const std::vector< uint32_t > &channel_ids, const std::unordered_map< uint32_t, uint32_t > &channel_device_map, const std::unordered_map< uint32_t, px::shared_string > &channel_name_map, const std::unordered_map< uint32_t, px::shared_string > &device_name_map, const bool separate_date_time, const bool include_period, const bool include_avg, const bool include_min, const bool include_min_time, const bool include_max, const bool include_max_time, const bool include_actual)
Write the header (title) row to the trends export (from bucket only) CSV file: time, period, channel_id(trait), channel_id(trait), ...
PUBLIC void ExportTrendsHeaderRow (std::ofstream &file, const std::vector< uint32_t > &channel_ids, const std::unordered_map< uint32_t, std::bitset< 4 > > &channel_traits_map, const std::unordered_map< uint32_t, uint32_t > &channel_device_map, const std::unordered_map< uint32_t, px::shared_string > &channel_name_map, const std::unordered_map< uint32_t, px::shared_string > &device_name_map, const bool separate_date_time, const bool include_period, const bool include_avg, const bool include_min, const bool include_min_time, const bool include_max, const bool include_max_time, const bool include_actual)
Write the header (title) row to the trends export (from both stage and bucket) CSV file: time, period, channel_id(trait), channel_id(trait), ...
PUBLIC void MoveTrendsFromStageToBucket (CKeyValueStore &trend_stage_db, CKeyValueStore &trend_bucket_db, uint32_t mature_minutes, const volatile bool &exit_req)
Move trends from stage to bucket if the timestamps are matured (older than the UTC today + 1 hour grace duration) The grace duration is added to avoid expensive out of order updates due to the clock adjustment, which is usually a few seconds.
PUBLIC void LevelupBucketTrends (CKeyValueStore &bucket_db, const uint32_t time_threshold_5min, const uint32_t time_threshold_15min, const uint32_t time_threshold_60min, unsigned int &count_5min, unsigned int &count_15min, const volatile bool &exit_req, const size_t num_trended_channels)
Level up (replace) the bucket trends based on the age threshold for 5, 15, and 60 minutes.
bool LevelupBucketTrendsRow (CKeyValueStore &bucket_db, CIterator &it, const uint32_t channel_id, const uint32_t bucket_end_time, const int period)
Level up (replace) the current bucket (pointed by the it) to the target period if haven't.
std::shared_ptr
< px::CTrendBucketUpdate > AggregateTrends (const uint32_t channel_id, const uint32_t bucket_end_time, bool is_double, const std::vector< px::CChannelTrend > &trends, const unsigned int period, const unsigned int aggr_period)
Aggregate a list of trends from a period to an bigger period.
PUBLIC void SeekTrendIterator (CIterator &it, const uint32_t channel_id, const uint32_t time)
Move the iterator from the current position to the next position in either stage or bucket db.
PUBLIC bool ReadTrendKey (CIterator &it, uint32_t &channel_id, uint32_t &time)
Read the Key (channel id + key) from either stage or bucket db.
PUBLIC bool DeleteTrends (CKeyValueStore &trend_bucket_db, const std::unordered_set< uint32_t > &channel_ids, uint32_t start_day, uint32_t end_day, const volatile bool &exit_req)
Delete complete trend records, by date and channel, from bucket database.
PUBLIC bool DeleteTrends (CKeyValueStore &trend_bucket_db, uint32_t start_day, uint32_t end_day, const volatile bool &exit_req)
Delete complete trend records, by date, from bucket database.
PUBLIC bool DeleteTrends (CKeyValueStore &trend_bucket_db, const uint32_t earlist_min, const std::unordered_set< uint32_t > &existing_channels, const volatile bool &exit_req)
Delete the bucket trend records, if the date is ealier than the earlist_min, or if the channel is not in the set.
PUBLIC void get_normalized_interval_timestamp (const px::CWallTime &timestamp, const uint32_t aligned_minutes, uint32_t &interval_timestamp, bool &on_interval)
Gets the minutes since epoch, or zero if invalid, optionally aligned to an interval in minutes; and a flag indicating if the timestamp is exactly on that interval upper bound (only when aligned).
PUBLIC void get_normalized_interval_timestamp (const uint32_t minutes, const uint32_t aligned_minutes, uint32_t &interval_timestamp, bool &on_interval)
Gets the minutes since epoch, or zero if invalid, optionally aligned to an interval in minutes; and a flag indicating if the timestamp is exactly on that interval upper bound (only when aligned).
PUBLIC px::CWallTime get_walltime (const uint32_t minutes)
Gets a CWallTime from the minutes since 1970 UTC.
PUBLIC px::CWallTime get_walltime (const px::CWallTime &period_end_time, const uint32_t offset)
Gets a CWallTime from the period end CWallTime minus the 1/10 seconds offset.
PUBLIC leveldb::Status DestroyDb (const px::string &name)
Physically delete a database's folder/files.
PUBLIC bool DoesKeyExist (CKeyValueStore &db, CBlobHolder &key_blob)
Check to see if a key exists in the database.
PUBLIC bool DoesKeyExist (CKeyValueStore &db, const uint32_t channel_id, const uint32_t time)
Check to see if a key exists in the database.
PUBLIC bool IsTrendStageDbTombstoned (CKeyValueStore &db)
Check to see if a Tombstone flag is set on a stage db.
PUBLIC void SetTrendStageDbTombstoned (CKeyValueStore &db, bool tombstoned)
Set or clear the tombstone flag on a stage db.
static void u16be_to_buf (unsigned char *buf, int offset, uint16_t val)
static uint16_t buf_to_u16be (const unsigned char *buf, int offset)
static uint32_t buf_to_u32be (const unsigned char *buf)
static uint32_t buf_to_u32be (const unsigned char *buf, int offset)
static void u32be_to_buf (unsigned char *buf, uint32_t val)
Convert 32-bit unsigned integer to 4 bytes big-endian.
static void u32be_to_buf (unsigned char *buf, int offset, uint32_t val)
Convert 32-bit unsigned integer to 4 bytes big-endian.
static uint64_t buf_to_u64be (const unsigned char *buf)
static void u64be_to_buf (unsigned char *buf, uint64_t val)
Convert 64-bit unsigned integer to 8 bytes big-endian.
static uint64_t query_alarm_index_db (CKeyValueStore &alarm_index_db, alarm_index_entry_type type, uint64_t key_value, uint64_t *found_key_value)
static std::vector< px::id_t > allocate_ids (CKeyValueStore &id_db, unsigned int num_requested, id_type type_requested)
static void reserve_ids (CKeyValueStore &id_db, const std::vector< px::id_t > &ids, id_type type_requested)
void compact_trend_bucket_channel_range (CKeyValueStore &trend_bucket_db, uint32_t start_channel, uint32_t end_channel)
bool DeleteTrendsInternal (CKeyValueStore &trend_bucket_db, const uint32_t start_min, const uint32_t end_min, const volatile bool &exit_req, const std::unordered_set< uint32_t > &keep_channels, const bool ignore_channels)
void LevelupBucketTrendsForChannel (CKeyValueStore &bucket_db, const uint32_t time_threshold_5min, const uint32_t time_threshold_15min, const uint32_t time_threshold_60min, unsigned int &count_5min, unsigned int &count_15min, const volatile bool &exit_req, const uint32_t channel_id)
Variables
const px::string device_db_name = "devices"
Database file names, defined in adapter.cpp.
const px::string channel_db_name = "channels"
const px::string oob_db_name = "oob"
const px::string id_db_name = "ids"
const px::string alarm_db_name = "alarms"
const px::string alarm_index_db_name = "alarm_index"
const unsigned char _avg_trend_mask = 0x01
const unsigned char _min_trend_mask = 0x02
const unsigned char _max_trend_mask = 0x04
const unsigned char _actual_trend_mask = 0x08
const unsigned char _null_trend_mask = 0x10
const unsigned char _double_trend_mask = 0x80
const unsigned char _tomestone = 0x00
const size_t _avg_bit = 0
const size_t _min_bit = 1
const size_t _max_bit = 2
const size_t _actual_bit = 3
static std::mutex id_db_mutex
Detailed Description
px::db is the namespace for all the classes that provide the database access for Power Xpert Toolkit applications.
Enumeration Type Documentation
enum px::db::alarm_index_entry_type : uint8_t strong
Enumerator
alarm_id
timestamp
deletion_note
open_scan_start_point
Definition at line 833 of file adapter.cpp.
enum px::db::id_type : uint8_t strong
Enumerator
devicechannel
alarm
globalcount
Definition at line 2267 of file adapter.cpp.
Function Documentation
uint32_t px::db::GetSchemaVersion (CKeyValueStore & db, uint32_t key_len, uint32_t def_ver = 0)
Get/set schema version for a database.
This is always stored with a key of "key_len" zeroes, and data of big-endian uint32 version number. GetSchemaVersion will add a version tag of "def_ver" to the DB if none is found.
Definition at line 132 of file adapter.cpp.
References px::db::CBlobHolder::append(), buf_to_u32be(), px::db::CKeyValueStore::iterator(), px::db::CIterator::key_data(), px::db::CIterator::key_size(), px::db::CIterator::seek(), SetSchemaVersion(), unlikely, px::db::CIterator::valid(), px::db::CIterator::value_data(), and px::db::CIterator::value_size().
Referenced by MigrateAlarmDB(), MigrateAlarmIndexDB(), MigrateChannelDB(), MigrateDeviceDB(), MigrateIDDB(), and MigrateOOBDB().
void px::db::SetSchemaVersion (CKeyValueStore & db, uint32_t key_len, uint32_t version)
Definition at line 114 of file adapter.cpp.
References px::db::CBatch::add(), px::db::CBlobHolder::append(), u32be_to_buf(), and px::db::CKeyValueStore::write().
Referenced by GetSchemaVersion(), MigrateAlarmDB(), MigrateChannelDB(), and MigrateDeviceDB().
void px::db::MigrateOOBDB (CKeyValueStore & db)
Given one of our databases, check to see if migration is needed, and perform such migration if so.
Definition at line 163 of file adapter.cpp.
References GetSchemaVersion().
Referenced by BOOST_AUTO_TEST_CASE().
void px::db::MigrateDeviceDB (CKeyValueStore & db)
Definition at line 175 of file adapter.cpp.
References AddDeviceToBatch(), px::db::CKeyValueStore::compact(), px::db::CIterator::first(), GetSchemaVersion(), px::db::CKeyValueStore::iterator(), px::db::CIterator::key_data(), px::db::CIterator::key_size(), likely, px::CWallTime::now(), px::CDevice::set_inherited_state(), px::CDevice::set_state(), SetSchemaVersion(), px::CDevice::state_timestamp, px::db::CIterator::valid(), px::db::CIterator::value_data(), px::db::CIterator::value_size(), and px::db::CKeyValueStore::write().
Referenced by BOOST_AUTO_TEST_CASE().
void px::db::MigrateChannelDB (CKeyValueStore & db, CIterator & mcl_iter)
Definition at line 228 of file adapter.cpp.
References AddChannelToBatch(), px::db::CKeyValueStore::compact(), px::db::CIterator::first(), px::CBitset< T >::from(), GetSchemaVersion(), px::db::CKeyValueStore::iterator(), px::db::CIterator::key_data(), px::db::CIterator::key_size(), likely, px::not_communicating, px::CChannel::set_state(), SetSchemaVersion(), unlikely, px::db::CIterator::valid(), px::db::CIterator::value_data(), px::db::CIterator::value_size(), and px::db::CKeyValueStore::write().
Referenced by BOOST_AUTO_TEST_CASE().
void px::db::MigrateIDDB (CKeyValueStore & db)
Definition at line 309 of file adapter.cpp.
References GetSchemaVersion().
Referenced by BOOST_AUTO_TEST_CASE().
void px::db::MigrateAlarmDB (CKeyValueStore & db, const std::map< px::id_t, px::CChannel > & channel_map, const std::map< px::id_t, px::CDevice > & device_map)
Definition at line 731 of file adapter.cpp.
References px::db::CBlobHolder::append(), buf_to_u64be(), px::db::CKeyValueStore::compact(), px::db::CIterator::first(), GetSchemaVersion(), px::db::CKeyValueStore::iterator(), px::db::CIterator::key_data(), px::db::CIterator::key_size(), LIBPX_ERR, LIBPX_INFO, px::db::CBatch::remove(), SetSchemaVersion(), unlikely, px::db::CIterator::valid(), px::db::CIterator::value_data(), px::db::CIterator::value_size(), px::generic_err::what(), and px::db::CKeyValueStore::write().
void px::db::MigrateAlarmIndexDB (CKeyValueStore & db)
Definition at line 800 of file adapter.cpp.
References GetSchemaVersion().
void px::db::AddOOBToBatch (CBatch & batch, const px::string & key, const px::proto::toolkitStruct & value)
Set up a CBatch update to the OOB-data persistent key-value store.
See adapter.cpp for on-disk data format.
OOB key must not be empty.
Definition at line 328 of file adapter.cpp.
References px::db::CBatch::add(), and unlikely.
Referenced by BOOST_AUTO_TEST_CASE().
void px::db::AddClearOOBToBatch (CBatch & batch, const px::string & key)
Definition at line 348 of file adapter.cpp.
References px::db::CBlobHolder::append(), and px::db::CBatch::remove().
Referenced by BOOST_AUTO_TEST_CASE().
bool px::db::FetchOOB (CKeyValueStore & db, const px::string & key, px::proto::toolkitStruct & data)
Fetch an OOB data value from the store.
Populates the protobuf object passed in as 'data'. Returns true if the key is found or false if not (if not found, there is no modification of the 'data' object).
OOB key must not be empty.
Definition at line 359 of file adapter.cpp.
References px::db::CKeyValueStore::iterator(), px::db::CIterator::key_data(), px::db::CIterator::key_size(), px::db::CIterator::seek(), px::db::CIterator::valid(), px::db::CIterator::value_data(), and px::db::CIterator::value_size().
Referenced by BOOST_AUTO_TEST_CASE().
std::vector< px::string > px::db::FetchOOBKeys (CKeyValueStore & db)
Fetch a list of all keys in the persistent OOB database.
Definition at line 383 of file adapter.cpp.
References px::db::CIterator::first(), px::db::CKeyValueStore::iterator(), px::db::CIterator::key_data(), px::db::CIterator::key_size(), likely, and px::db::CIterator::valid().
Referenced by BOOST_AUTO_TEST_CASE().
void px::db::FetchOOBs (CKeyValueStore & db, std::map< px::string, px::proto::toolkitStruct > & map)
Fetch all OOB objects from the database, into a map.
Definition at line 407 of file adapter.cpp.
References px::db::CIterator::first(), px::db::CKeyValueStore::iterator(), px::db::CIterator::key_data(), px::db::CIterator::key_size(), likely, px::db::CIterator::valid(), px::db::CIterator::value_data(), and px::db::CIterator::value_size().
void px::db::AddDeviceToBatch (CBatch & batch, const px::CDevice & device)
Set up a CBatch update to the device database.
See adapter.cpp for on-disk data format.
Device id must not be empty.
Definition at line 440 of file adapter.cpp.
References px::db::CBatch::add(), px::CDevice::config_file, px::CDevice::get_own_state(), px::CDevice::id(), px::CDevice::profile_file, px::CDevice::state_timestamp, px::CDevice::to(), px::CBitset< T >::to(), px::CTimestamp::to(), u64be_to_buf(), and unlikely.
Referenced by BOOST_AUTO_TEST_CASE(), and MigrateDeviceDB().
void px::db::AddDeleteDeviceToBatch (CBatch & batch, px::id_t device_id)
Set up a CBatch update to the device database.
See adapter.cpp for on-disk data format.
Device id must not be empty.
Definition at line 475 of file adapter.cpp.
References px::db::CBlobHolder::append(), px::db::CBatch::remove(), and u64be_to_buf().
Referenced by BOOST_AUTO_TEST_CASE().
void px::db::FetchDevices (CKeyValueStore & db, std::map< px::id_t, px::CDevice > & map)
Fetch all devices from the database, into a map.
Definition at line 488 of file adapter.cpp.
References px::db::CIterator::first(), px::CBitset< T >::from(), px::db::CKeyValueStore::iterator(), px::db::CIterator::key_data(), px::db::CIterator::key_size(), likely, px::not_communicating, px::db::CIterator::valid(), px::db::CIterator::value_data(), and px::db::CIterator::value_size().
Referenced by BOOST_AUTO_TEST_CASE().
void px::db::AddChannelToBatch (CBatch & batch, CIterator & mcl_iter, const px::CChannel & channel)
Set up a CBatch update to the channel database.
See adapter.cpp for on-disk data format.
Channel id must be > 0.
Definition at line 527 of file adapter.cpp.
References px::db::CBatch::add(), px::CChannel::channel_settings, FetchMCLEntry(), px::CChannel::get_own_state(), px::CChannel::id(), likely, px::CProtoOPS::ListUnsetFields(), px::persist_value, px::CProtoOPS::Subtract(), px::CChannel::timestamp, px::CChannel::to(), px::CBitset< T >::to(), px::CValue::to(), px::CTimestamp::to(), u64be_to_buf(), unlikely, and px::CChannel::value.
Referenced by BOOST_AUTO_TEST_CASE(), and MigrateChannelDB().
void px::db::AddDeleteChannelToBatch (CBatch & batch, px::id_t channel_id)
Definition at line 580 of file adapter.cpp.
References px::db::CBlobHolder::append(), px::db::CBatch::remove(), and u64be_to_buf().
Referenced by BOOST_AUTO_TEST_CASE().
void px::db::FetchChannels (CKeyValueStore & db, CIterator & mcl_iter, std::map< px::id_t, px::CChannel > & map, std::map< px::id_t, px::CDevice > & devs)
Fetch all channels from the database, into a map.
Definition at line 593 of file adapter.cpp.
References px::CChannel::channel_settings, px::CProtoOPS::ClearFields(), FetchMCLEntry(), px::db::CIterator::first(), px::CBitset< T >::from(), px::CTimestamp::from(), px::CValue::from(), px::CChannel::id(), px::db::CKeyValueStore::iterator(), px::db::CIterator::key_data(), px::db::CIterator::key_size(), likely, px::not_communicating, px::CChannel::parent(), px::persist_value, px::CBitset< T >::set(), px::CChannel::set_state(), px::CChannel::timestamp, px::CProtoOPS::Update(), px::db::CIterator::valid(), px::CChannel::value, px::db::CIterator::value_data(), and px::db::CIterator::value_size().
Referenced by BOOST_AUTO_TEST_CASE().
px::proto::MclEntry px::db::FetchMCLEntry (CIterator & mcl_iter, const px::string & channel_name)
Get an MCL entry, in the form of a channel protobuf.
Can use the same iterator forever as that DB is read-only.
Channel name must not be empty.
Definition at line 662 of file adapter.cpp.
References px::db::CBlobHolder::append(), px::db::CIterator::key_data(), px::db::CIterator::key_size(), LIBPX_ERR, px::db::CIterator::seek(), px::db::CIterator::valid(), px::db::CIterator::value_data(), px::db::CIterator::value_size(), and px::generic_err::what().
Referenced by AddChannelToBatch(), and FetchChannels().
px::proto::CommandInfo px::db::FetchCCLEntry (CIterator & ccl_iter, const px::string & command_name)
Get an CCL entry, in the form of a CommandInfo protobuf.
Can use the same iterator forever as that DB is read-only.
Device command name must not be empty.
Definition at line 705 of file adapter.cpp.
References px::db::CBlobHolder::append(), px::db::CIterator::key_data(), px::db::CIterator::key_size(), px::db::CIterator::seek(), px::db::CIterator::valid(), px::db::CIterator::value_data(), and px::db::CIterator::value_size().
void px::db::QueryAlarms (CKeyValueStore & alarm_db, CKeyValueStore & alarm_index_db, size_t max_result_size, uint64_t start_global_count, const px::CWallTime * start_update_time, const px::CWallTime * end_update_time, const std::unordered_set< px::id_t > * device_ids, const std::unordered_set< px::id_t > * channel_ids, const std::set< px::id_t > * alarm_ids, const std::set< px::id_t > * exclude_alarm_ids, uint32_t starting_sequence_index, bool first_updates_only, bool go_backwards, std::vector< px::CAlarmUpdate > & result, const volatile bool & exit_req, size_t * count_found = nullptr, bool count_all = false, uint32_t trigger_level = 0, px::CAlarmTriggerType trigger_type = px::alarm_trigger_type::invalid, bool gt_equal = false)
Return a list of alarm updates, that meet all of the specified criteria, from the alarm history database.
Oldest first.
Definition at line 1021 of file adapter.cpp.
References alarm_id, px::db::CBlobHolder::append(), buf_to_u32be(), buf_to_u64be(), px::invalid, px::db::CKeyValueStore::iterator(), px::db::CIterator::key_data(), px::db::CIterator::key_size(), px::db::CIterator::last(), LIBPX_DEBUG, likely, query_alarm_index_db(), px::db::CIterator::seek(), timestamp, u64be_to_buf(), UINT32_MAX, unlikely, px::db::CIterator::valid(), px::db::CIterator::value_data(), and px::db::CIterator::value_size().
void px::db::QueryAlarmsLatestUpdate (CKeyValueStore & alarm_db, CKeyValueStore & alarm_index_db, size_t max_result_size, uint64_t start_global_count, const px::CWallTime * start_first_occur_time, const px::CWallTime * end_first_occur_time, const std::unordered_set< px::id_t > * device_ids, const std::unordered_set< px::id_t > * channel_ids, const std::set< px::id_t > * alarm_ids, const std::set< px::id_t > * exclude_alarm_ids, std::vector< px::CAlarmUpdate > & result, const volatile bool & exit_req, size_t * count_found, bool count_all, uint32_t trigger_level = 0, px::CAlarmTriggerType trigger_type = px::alarm_trigger_type::invalid, bool gt_equal = false)
Given alarm parameters, return the most recent update for each matching entry in the database.
Can be slow. Only returns updates with global count <= start_global_count. If start_global_count=0, starts from the latest. Returns in reverse global-count order.
Definition at line 1450 of file adapter.cpp.
References buf_to_u64be(), px::invalid, px::db::CKeyValueStore::iterator(), px::db::CIterator::key_data(), px::db::CIterator::key_size(), px::db::CIterator::last(), LIBPX_DEBUG, likely, UINT32_MAX, unlikely, px::db::CIterator::valid(), px::db::CIterator::value_data(), and px::db::CIterator::value_size().
PUBLIC void px::db::LoadActiveAlarms (CKeyValueStore & alarm_db, CKeyValueStore & alarm_index_db, std::map< px::id_t, px::CAlarmUpdate > & alarms)
Load active alarms from the database into the given map.
Definition at line 1652 of file adapter.cpp.
References buf_to_u64be(), px::db::CBlobHolder::get_mutable_ptr(), px::db::CKeyValueStore::iterator(), px::db::CIterator::key_data(), px::db::CIterator::key_size(), likely, open_scan_start_point, px::db::CBlobHolder::reset(), px::db::CIterator::seek(), u64be_to_buf(), unlikely, px::db::CIterator::valid(), px::db::CIterator::value_data(), and px::db::CIterator::value_size().
void px::db::SaveAlarmUpdates (CKeyValueStore & alarm_db, CKeyValueStore & alarm_index_db, const std::vector< px::CAlarmUpdate > & updates, const volatile bool & exit_req)
Add an alarm update to the history database, update the index DB as needed.
See adapter.cpp for the on-disk data format.
Definition at line 885 of file adapter.cpp.
References px::db::CBatch::add(), alarm_id, px::db::CBlobHolder::append(), likely, PX_ID_UNSET, query_alarm_index_db(), timestamp, u32be_to_buf(), u64be_to_buf(), unlikely, and px::db::CKeyValueStore::write().
void px::db::NoteAlarmsToDelete (CKeyValueStore & alarm_index_db, const std::unordered_set< px::id_t > & ids)
Persistently note that alarms with these device and/or channel IDs are to be deleted.
DeleteAlarms() will include them in addition to the set with which it is called, when it runs. This allows an interrupted DeleteAlarms() to be completed later.
Alarm IDs must not be empty.
Definition at line 1718 of file adapter.cpp.
References deletion_note, px::db::CBlobHolder::get_mutable_ptr(), px::db::CBlobHolder::reset(), unlikely, and px::db::CKeyValueStore::write().
void px::db::DeleteAlarms (CKeyValueStore & alarm_db, CKeyValueStore & alarm_index_db, const std::unordered_set< px::id_t > & ids, const volatile bool & exit_req)
Delete alarm updates for the specified devices/channels.
Also deletes any that have been formerly noted by NoteAlarmsToDelete(), if they are still around.
Definition at line 1739 of file adapter.cpp.
References px::db::CBlobHolder::append(), buf_to_u64be(), px::db::CKeyValueStore::compact(), deletion_note, px::db::CIterator::first(), px::db::CBlobHolder::get_mutable_ptr(), px::db::CKeyValueStore::iterator(), px::db::CIterator::key_data(), px::db::CIterator::key_size(), LIBPX_DEBUG, LIBPX_ERR, likely, px::db::CBatch::remove(), px::db::CBlobHolder::reset(), px::db::CIterator::seek(), unlikely, px::db::CIterator::valid(), px::db::CIterator::value_data(), px::db::CIterator::value_size(), px::generic_err::what(), and px::db::CKeyValueStore::write().
void px::db::DeleteClosedAlarms (CKeyValueStore & alarm_db, px::cds::CDeleteAlarms & alms, const volatile bool & exit_req, const std::unordered_set< px::id_t > * device_ids = nullptr, const std::unordered_set< px::id_t > * channel_ids = nullptr)
Delete alarm updates, for the specified alarm ids or those which satify given crieria of end_time, level and keep_count.
Definition at line 1822 of file adapter.cpp.
References px::cds::CDeleteAlarms::alarm_ids, px::db::CBlobHolder::append(), buf_to_u64be(), px::db::CBatch::clear(), px::db::CKeyValueStore::compact(), px::cds::CDeleteAlarms::end_time, px::db::CIterator::first(), px::CTimestamp::get_time_str(), px::db::CKeyValueStore::iterator(), px::cds::CDeleteAlarms::keep_count, px::db::CIterator::key_size(), px::cds::CDeleteAlarms::level, LIBPX_DEBUG, LIBPX_ERR, likely, px::db::CBatch::remove(), px::db::CBlobHolder::reset(), u64be_to_buf(), unlikely, px::db::CIterator::valid(), px::db::CIterator::value_data(), px::db::CIterator::value_size(), px::generic_err::what(), and px::db::CKeyValueStore::write().
void px::db::CleanupAlarms (CKeyValueStore & alarm_db, CKeyValueStore & alarm_index_db, uint32_t max_size, const volatile bool & exit_req)
Roll off old alarms if the database has gotten too large.
Also update index.
Definition at line 1992 of file adapter.cpp.
References px::db::CBatch::add(), px::db::CBlobHolder::append(), buf_to_u32be(), buf_to_u64be(), px::db::CBatch::clear(), px::db::CKeyValueStore::compact(), px::db::CIterator::first(), px::db::CBlobHolder::get_mutable_ptr(), px::db::CKeyValueStore::iterator(), px::db::CIterator::key_data(), px::db::CIterator::key_size(), LIBPX_DEBUG, LIBPX_WARN, likely, open_scan_start_point, px::db::CBatch::remove(), px::db::CBlobHolder::reset(), u64be_to_buf(), unlikely, px::db::CIterator::valid(), px::db::CIterator::value_data(), px::db::CIterator::value_size(), and px::db::CKeyValueStore::write().
void px::db::CheckIDDB (CKeyValueStore & id_db, CKeyValueStore & device_db, CKeyValueStore & channel_db, CKeyValueStore & alarm_db)
Double-check the ID database against the channel and device DBs, update the last-issued ID to be higher if necessary.
Definition at line 2276 of file adapter.cpp.
References px::db::CBatch::add(), alarm, px::db::CBlobHolder::append(), buf_to_u64be(), devicechannel, globalcount, id_db_mutex, px::db::CKeyValueStore::iterator(), px::db::CIterator::key_data(), px::db::CIterator::key_size(), px::db::CIterator::last(), likely, px::db::CBlobHolder::reset(), px::db::CIterator::seek(), u64be_to_buf(), unlikely, px::db::CIterator::valid(), px::db::CIterator::value_data(), px::db::CIterator::value_size(), and px::db::CKeyValueStore::write().
Referenced by BOOST_AUTO_TEST_CASE().
std::vector< px::id_t > px::db::AllocateDeviceIDs (CKeyValueStore & id_db, unsigned int num_requested)
Allocate device IDs.
Returns a list. ID-tracking DB is committed to disk before this returns. May throw generic_err().
Definition at line 2498 of file adapter.cpp.
References allocate_ids(), and devicechannel.
Referenced by BOOST_AUTO_TEST_CASE().
std::vector< px::id_t > px::db::AllocateChannelIDs (CKeyValueStore & id_db, unsigned int num_requested)
Allocate channel IDs.
Returns a list. ID-tracking DB is committed to disk before this returns. May throw generic_err().
Definition at line 2504 of file adapter.cpp.
References allocate_ids(), and devicechannel.
std::vector< px::id_t > px::db::AllocateAlarmIDs (CKeyValueStore & id_db, unsigned int num_requested)
Allocate alarm IDs.
Returns a list. ID-tracking DB is committed to disk before this returns. May throw generic_err().
Definition at line 2510 of file adapter.cpp.
References alarm, and allocate_ids().
std::vector< px::id_t > px::db::AllocateGlobalCounts (CKeyValueStore & id_db, unsigned int num_requested)
Allocate alarm global counts.
Returns a list. ID-tracking DB is committed to disk before this returns. May throw generic_err().
Definition at line 2516 of file adapter.cpp.
References allocate_ids(), and globalcount.
void px::db::ReserveDeviceIDs (CKeyValueStore & id_db, const std::vector< px::id_t > & ids)
Reserve a set of device IDs so that they will not be automatically assigned by AllocateDeviceIDs().
Device IDs must not be empty.
Definition at line 2581 of file adapter.cpp.
References devicechannel, and reserve_ids().
void px::db::ReserveChannelIDs (CKeyValueStore & id_db, const std::vector< px::id_t > & ids)
Reserve a set of channel IDs so that they will not be automatically assigned by AllocateChannelIDs().
Channel IDs must not be empty.
Definition at line 2586 of file adapter.cpp.
References devicechannel, and reserve_ids().
void px::db::ReserveAlarmIDs (CKeyValueStore & id_db, const std::vector< px::id_t > & ids)
Reserve a set of alarm IDs so that they will not be automatically assigned by AllocateAlarmIDs().
Alarm IDs must not be empty.
Definition at line 2592 of file adapter.cpp.
References alarm, and reserve_ids().
void px::db::ReserveGlobalCounts (CKeyValueStore & id_db, const std::vector< uint64_t > & ids)
Reserve a set of alarm global counts so that they will not be automatically assigned by AllocateGlobalCounts().
IDs must not be empty.
Definition at line 2597 of file adapter.cpp.
References globalcount, and reserve_ids().
void px::db::AddTrendStageToBatch (CBatch & batch, std::vector< std::shared_ptr< px::CTrendStageUpdate > > & updates, int start_index = 0, int end_index = -1)
Add the trends from the accumulators to the batch to be stored in trend stage db.
Definition at line 2603 of file adapter.cpp.
References _actual_trend_mask, _avg_trend_mask, _double_trend_mask, _max_trend_mask, _min_trend_mask, px::db::CBatch::add(), px::double_to_big_endian(), px::float_to_big_endian(), px::db::CBlobHolder::get_mutable_ptr(), px::has_actual, px::has_avg, px::has_max, px::has_min, px::db::CBlobHolder::reset(), u16be_to_buf(), and u32be_to_buf().
PUBLIC px::CChannelTrends px::db::QueryTrendStage (CKeyValueStore & trend_stage_db, const uint32_t channel_id, uint32_t start_time, uint32_t end_time)
Return a list of trends from the stage db, based on the channel id and time range.
Channel id must be > 0.
Definition at line 2807 of file adapter.cpp.
References _actual_trend_mask, _avg_trend_mask, _double_trend_mask, _max_trend_mask, _min_trend_mask, px::CChannelTrend::actual, px::CChannelTrend::avg, buf_to_u16be(), buf_to_u32be(), px::CChannelTrends::channel_id, px::CChannelTrends::data_type, px::double_from_big_endian(), px::float32, px::float64, px::float_from_big_endian(), px::db::CBlobHolder::get_mutable_ptr(), px::has_actual, px::has_avg, px::has_max, px::has_min, px::db::CKeyValueStore::iterator(), px::db::CIterator::key_data(), px::db::CIterator::key_size(), px::CChannelTrend::max, px::CChannelTrend::max_time_offset, px::CChannelTrend::min, px::CChannelTrend::min_time_offset, px::CChannelTrend::period, px::db::CBlobHolder::reset(), px::db::CIterator::seek(), px::CChannelTrend::time, px::CChannelTrends::trends, u32be_to_buf(), unlikely, px::db::CIterator::valid(), px::db::CIterator::value_data(), and px::db::CIterator::value_size().
void px::db::DumpHex (std::ofstream & file, const unsigned char * data, const int length)
Dump the hex string from a binary blob.
data must not be null. length must be > 0.
Definition at line 3009 of file adapter.cpp.
Referenced by ExportTrendStage().
void px::db::ExportTrendStageRow (const uint32_t channel_id, const uint32_t time, CIterator & it, std::ofstream & file, const bool include_avg, const bool include_min, const bool include_max, const bool include_actual, unsigned int & values_count)
Export a record from the trend stage db to an opened file stream.
Export a row from the trend stage db to an opened file stream.
(The row key/value sizes are already validated before calling this method.
Channel ID must be > 0.
Return true if the row is exported as a valid trend.
Definition at line 3033 of file adapter.cpp.
References _actual_trend_mask, _avg_trend_mask, _double_trend_mask, _max_trend_mask, _min_trend_mask, buf_to_u16be(), px::double_from_big_endian(), px::float_from_big_endian(), get_walltime(), px::CTimestamp::gmtime_str(), px::has_actual, px::has_avg, px::has_max, px::has_min, px::db::CIterator::value_data(), and px::db::CIterator::value_size().
Referenced by ExportTrendStage().
void px::db::ExportTrendStage (CKeyValueStore & trend_stage_db, std::ofstream & file, const std::vector< uint32_t > & channel_ids, uint32_t start_time, uint32_t end_time, const bool include_avg, const bool include_min, const bool include_max, const bool include_actual, const bool include_invalid, const unsigned int row_count_limit, bool & more_data, unsigned int & values_count, unsigned int & row_count, const volatile bool & exit_req)
Export all trends from the stage db to a csv file, returns the exported trends count.
Export all trends from the stage db to a csv file.
csv format: channel_id, time, mask, avg, min, max, actual (the value can be null or nan.) invalid, key, value (HEX dump when the key/value is invalid)
If channel_ids is empty, all channels in the stage are exported.
csv format: channel_id, time_minutes, time, mask, avg, min, min_time, max, max_time, actual (the value can be null or nan) invalid, key, value (HEX dump when the key/value is invalid)
Definition at line 3191 of file adapter.cpp.
References buf_to_u32be(), DumpHex(), ExportTrendStageRow(), px::db::CIterator::first(), px::db::CBlobHolder::get_mutable_ptr(), px::db::CKeyValueStore::iterator(), px::db::CIterator::key_data(), px::db::CIterator::key_size(), px::db::CBlobHolder::reset(), px::db::CIterator::seek(), u32be_to_buf(), unlikely, px::db::CIterator::valid(), px::db::CIterator::value_data(), and px::db::CIterator::value_size().
void px::db::ExportTrendStageHeaderRow (std::ofstream & file)
Write the header (title) row to the stage trends export CSV file: channel_id, time, mask, avg, min, max, actual.
Definition at line 3384 of file adapter.cpp.
void px::db::ImportTrendStage (const px::string & file_path, std::function< void(std::vector< std::shared_ptr< px::CTrendStageUpdate > > &)> func, int & row_count, int & value_count, const volatile bool & exit_req)
Import trends from a csv file to the daily stage db(s) based on the timestamps; return the imported rows and values count.
Import trends from a csv file to the stage db, return the imported trends count csv format: channel_id, time, value_type(float32/float64), avg, min, max, actual (the value can be null or nan) The time can be an integer indicating the minutes since epoch time, or in the format of YYYY-MM-DD HH:MM:SS in UTC.
csv format: channel_id, time (YYYY-MM-DD HH:MM:SS UTC), value_type(float32/float64), avg, min, max, actual (the value can be null or nan.) The time can be an integer indicating the minutes since epoch time, or in the format of YYYY-MM-DD HH:MM:SS in UTC. All times will be normalized to 5-minutes interval. The data in the CSV file must be sorted in the time ascending order (You can manually add some out of order data to test/simulate the system clock adjustments.)
Path to the file must not be empty.
All times will be normalized to 5-minutes interval.
Definition at line 3396 of file adapter.cpp.
References px::actual, px::avg, px::float32, px::float64, get_normalized_interval_timestamp(), px::has_actual, px::has_avg, px::has_max, px::has_min, likely, px::max, px::min, px::safe_line_split(), px::string, and unlikely.
void px::db::ImportTrendBucket (CKeyValueStore & trend_bucket_db, const px::string & file_path, int & row_count, int & value_count, const volatile bool & exit_req)
Import trends from a csv file to the bucket db, return the imported rows and values count.
Import trends from a csv file to the bucket db, return the imported trends count.
csv format: channel_id, time, mask, avg, min, max, actual (the value can be null or nan.)
Path to the file must not be empty.
Notes: the rows in the csv file must be pre-sorted by time. csv format: time, period, channelid1(avg), channelid1(min), channelid1(max), channelid1(actual), ... (the value can be null or nan) 9/1/2013 20:00, 5, 1.2, 1.3, , nan, null, ...
Definition at line 3695 of file adapter.cpp.
References px::actual, px::avg, px::float32, get_normalized_interval_timestamp(), likely, px::max, px::min, px::safe_line_split(), px::size, StoreTrendBucketsToDb(), px::string, and unlikely.
bool px::db::AddTrendBucketToBatch (CBatch & batch, const std::shared_ptr< px::CTrendBucketUpdate > update)
Add the trend bucket to the batch to be stored in the bucket db.
Adds or updates trend bucket db.
returns true if the updates are successfully added to the batch; otherwise, the updates are ignored, due to the invalid contents.
The data are indexed by the channel id.
Definition at line 4117 of file adapter.cpp.
References _actual_trend_mask, _avg_trend_mask, _double_trend_mask, _max_trend_mask, _min_trend_mask, _null_trend_mask, px::db::CBatch::add(), px::db::CNullMask::byte_size(), px::double_to_big_endian(), px::float_to_big_endian(), px::db::CNullMask::get_byte_size(), px::db::CBlobHolder::get_mutable_ptr(), px::db::CBlobHolder::reset(), px::db::CNullMask::set(), px::db::CBlobHolder::size(), px::db::CNullMask::to_buf(), u16be_to_buf(), and u32be_to_buf().
Referenced by LevelupBucketTrendsRow(), MoveTrendsFromStageToBucket(), and StoreTrendBucketsToDb().
void px::db::StoreTrendBucketsToDb (CKeyValueStore & trend_bucket_db, const std::map< uint32_t, std::shared_ptr< px::CTrendBucketUpdate > > & cache, bool sync_db, const volatile bool & exit_req)
Stores a list of buckets to the bucket db.
Definition at line 4086 of file adapter.cpp.
References AddTrendBucketToBatch(), px::db::CBatch::clear(), unlikely, and px::db::CKeyValueStore::write().
Referenced by ImportTrendBucket(), and SimulateTrendBucket().
PUBLIC void px::db::SimulateTrendBucket (CKeyValueStore & trend_bucket_db, const std::vector< uint32_t > & channel_ids, int period, const px::CWallTime & start, const px::CWallTime & end, int & trends_count)
Simulates the data to fill up the trend bucket.
Channel IDs must note be empty and start must be before the end.
Definition at line 4497 of file adapter.cpp.
References px::actual, px::avg, px::float32, get_normalized_interval_timestamp(), px::max, px::min, and StoreTrendBucketsToDb().
void px::db::ReadTrendsFromBucketRow (CIterator & iterator, std::vector< px::CChannelTrend > & result, const uint32_t bucket_end_time, const uint32_t start_minutes, const uint32_t end_minutes, const int request_period, const bool include_avg, const bool include_min, const bool include_max, const bool include_actual, int & read_period, bool & is_double, const unsigned int row_count_limit, unsigned int & row_count, unsigned int & rtn_values_count, bool newest_first = false, bool include_holes = true)
Read trends from a bucket row to the result, based on time range and traits.
The nulls (gap) will be kept in the result. Therefore, the number of values depends on the time range and the period. The data beyond the query time range will not be included in the result. The only valid request_period are 0 (any period in the db), 5, 15, 60, and 60*24 (daily).
Definition at line 4614 of file adapter.cpp.
References _actual_trend_mask, _avg_trend_mask, _double_trend_mask, _max_trend_mask, _min_trend_mask, _null_trend_mask, px::actual, px::avg, buf_to_u16be(), buf_to_u32be(), px::double_from_big_endian(), px::float_from_big_endian(), px::db::CNullMask::get_byte_size(), px::has_actual, px::has_avg, px::has_max, px::has_min, likely, px::max, px::min, px::db::CIterator::value_data(), and px::db::CIterator::value_size().
Referenced by ExportTrendBucket(), and LevelupBucketTrendsRow().
void px::db::ReadTrendsFromStageRow (px::db::CIterator & it, std::vector< px::CChannelTrend > & trends, const bool include_avg, const bool include_min, const bool include_max, const bool include_actual, bool & is_double, unsigned int & row_count, unsigned int & rtn_values_count)
Read trends from a stage row to the result, based on the traits.
Definition at line 5013 of file adapter.cpp.
References _actual_trend_mask, _avg_trend_mask, _double_trend_mask, _max_trend_mask, _min_trend_mask, px::CChannelTrend::actual, px::CChannelTrend::avg, buf_to_u16be(), px::double_from_big_endian(), px::float_from_big_endian(), px::has_actual, px::has_avg, px::has_max, px::has_min, px::db::CIterator::key_data(), px::CChannelTrend::max, px::CChannelTrend::max_time_offset, px::CChannelTrend::min, px::CChannelTrend::min_time_offset, px::CChannelTrend::period, px::CChannelTrend::time, unlikely, px::db::CIterator::valid(), px::db::CIterator::value_data(), and px::db::CIterator::value_size().
void px::db::ExportTrendBucketHeaderRow (std::ofstream & file, const std::vector< uint32_t > & channel_ids, const bool include_avg, const bool include_min, const bool include_max, const bool include_actual)
Write the header (title) row to the bucket trends export CSV file: channel_id, time, mask, avg, min, max, actual Channel IDs must not be empty.
Write the header (title) row to the bucket trends export CSV file: time, period (5, 15 or 60), channel_id(trait), channel_id(trait), ...
Definition at line 5174 of file adapter.cpp.
void px::db::ExportTrendBucket (CKeyValueStore & trend_bucket_db, std::ofstream & file, const std::vector< uint32_t > & channel_ids, uint32_t start_minutes, uint32_t end_minutes, const bool include_avg, const bool include_min, const bool include_max, const bool include_actual, const unsigned int row_count_limit, bool & more_data, unsigned int & values_count, unsigned int & row_count, const volatile bool & exit_req)
Export a list of channels' trends from the bucket db to a csv file, returns the exported trends count.
The csv format: time, period (5, 15 or 60), channel_id(trait), channel_id(trait), ... (the values can be valid floating numbers, nan, or empty(indicating null). Channel IDs must not be empty.
The csv format: time, period (5, 15 or 60), channel_id(trait), channel_id(trait), ... (the values can be valid floating numbers, nan, or empty(indicating null).
Definition at line 5377 of file adapter.cpp.
References buf_to_u32be(), px::db::CBlobHolder::get_mutable_ptr(), get_normalized_interval_timestamp(), get_walltime(), px::CTimestamp::gmtime_str(), px::db::CKeyValueStore::iterator(), px::db::CIterator::key_data(), px::db::CIterator::key_size(), ReadTrendsFromBucketRow(), px::db::CBlobHolder::reset(), px::db::CIterator::seek(), u32be_to_buf(), unlikely, and px::db::CIterator::valid().
void px::db::ExportTrendsHeaderRow (std::ofstream & file, const std::vector< uint32_t > & channel_ids, const std::unordered_map< uint32_t, uint32_t > & channel_device_map, const std::unordered_map< uint32_t, px::shared_string > & channel_name_map, const std::unordered_map< uint32_t, px::shared_string > & device_name_map, const bool separate_date_time, const bool include_period, const bool include_avg, const bool include_min, const bool include_min_time, const bool include_max, const bool include_max_time, const bool include_actual)
Write the header (title) row to the trends export (from bucket only) CSV file: time, period, channel_id(trait), channel_id(trait), ...
Channel IDs must not be empty.
Definition at line 5206 of file adapter.cpp.
void px::db::ExportTrendsHeaderRow (std::ofstream & file, const std::vector< uint32_t > & channel_ids, const std::unordered_map< uint32_t, std::bitset< 4 > > & channel_traits_map, const std::unordered_map< uint32_t, uint32_t > & channel_device_map, const std::unordered_map< uint32_t, px::shared_string > & channel_name_map, const std::unordered_map< uint32_t, px::shared_string > & device_name_map, const bool separate_date_time, const bool include_period, const bool include_avg, const bool include_min, const bool include_min_time, const bool include_max, const bool include_max_time, const bool include_actual)
Write the header (title) row to the trends export (from both stage and bucket) CSV file: time, period, channel_id(trait), channel_id(trait), ...
Channel IDs must not be empty.
Definition at line 5280 of file adapter.cpp.
References px::has_actual, px::has_avg, px::has_max, and px::has_min.
void px::db::MoveTrendsFromStageToBucket (CKeyValueStore & trend_stage_db, CKeyValueStore & trend_bucket_db, uint32_t mature_minutes, const volatile bool & exit_req)
Move trends from stage to bucket if the timestamps are matured (older than the UTC today + 1 hour grace duration) The grace duration is added to avoid expensive out of order updates due to the clock adjustment, which is usually a few seconds.
Move trends from stage to bucket if the timestamps are matured (older than the UTC today + 60 minutes holding duration) The holding duration is added to avoid expensive out of order updates due to the clock adjustment, which is usually a few seconds.
This method can be called at any time, and should continue to work after being interrupted (killed) before.
This method can be called at any time, and should continue to work after being interrupted (killed) before. The mature_minutes 2010-09-23 0:0:0 UTC indicates that any data on or before it are matured data that should be moved. It must be the day with 0:0:0.
Definition at line 5655 of file adapter.cpp.
References _actual_trend_mask, _avg_trend_mask, _double_trend_mask, _max_trend_mask, _min_trend_mask, px::actual, AddTrendBucketToBatch(), px::avg, buf_to_u16be(), buf_to_u32be(), px::double_from_big_endian(), px::db::CIterator::first(), px::float_from_big_endian(), get_normalized_interval_timestamp(), px::has_actual, px::has_avg, px::has_max, px::has_min, px::db::CKeyValueStore::iterator(), px::db::CIterator::key_data(), px::db::CIterator::key_size(), px::max, px::min, unlikely, px::db::CIterator::valid(), px::db::CIterator::value_data(), px::db::CIterator::value_size(), and px::db::CKeyValueStore::write().
void px::db::LevelupBucketTrends (CKeyValueStore & bucket_db, const uint32_t time_threshold_5min, const uint32_t time_threshold_15min, const uint32_t time_threshold_60min, unsigned int & count_5min, unsigned int & count_15min, const volatile bool & exit_req, const size_t num_trended_channels)
Level up (replace) the bucket trends based on the age threshold for 5, 15, and 60 minutes.
The bucket will be leveled up if the bucket's time is earlier than or equal to the threshold. The number of channels is a hint to us to determine how often to compact.
Definition at line 6240 of file adapter.cpp.
References compact_trend_bucket_channel_range(), px::db::CKeyValueStore::iterator(), LevelupBucketTrendsForChannel(), LIBPX_DEBUG, LIBPX_ERR, likely, ReadTrendKey(), SeekTrendIterator(), unlikely, and px::db::CIterator::valid().
bool px::db::LevelupBucketTrendsRow (CKeyValueStore & bucket_db, CIterator & it, const uint32_t channel_id, const uint32_t bucket_end_time, const int period)
Level up (replace) the current bucket (pointed by the it) to the target period if haven't.
Returns true if the row is updated(leveled up), or false if the row is already leveled up and no chnage.
Definition at line 6311 of file adapter.cpp.
References AddTrendBucketToBatch(), AggregateTrends(), px::db::CBlobHolder::get_mutable_ptr(), ReadTrendsFromBucketRow(), px::db::CBlobHolder::reset(), u32be_to_buf(), px::db::CIterator::value_data(), px::db::CIterator::value_size(), and px::db::CKeyValueStore::write().
Referenced by LevelupBucketTrendsForChannel().
std::shared_ptr< px::CTrendBucketUpdate > px::db::AggregateTrends (const uint32_t channel_id, const uint32_t bucket_end_time, bool is_double, const std::vector< px::CChannelTrend > & trends, const unsigned int period, const unsigned int aggr_period)
Aggregate a list of trends from a period to an bigger period.
Definition at line 6395 of file adapter.cpp.
References px::actual, px::avg, px::CTrendBucketUpdate::channel_id, px::float32, px::float64, get_normalized_interval_timestamp(), px::has_actual, px::has_avg, px::has_max, px::has_min, px::max, and px::min.
Referenced by LevelupBucketTrendsRow().
void px::db::SeekTrendIterator (CIterator & it, const uint32_t channel_id, const uint32_t time)
Move the iterator from the current position to the next position in either stage or bucket db.
Channel ID of 0 means seek to the beginning.
Definition at line 5921 of file adapter.cpp.
References px::db::CBlobHolder::get_mutable_ptr(), px::db::CBlobHolder::reset(), px::db::CIterator::seek(), and u32be_to_buf().
Referenced by DeleteTrends(), LevelupBucketTrends(), and LevelupBucketTrendsForChannel().
bool px::db::ReadTrendKey (CIterator & it, uint32_t & channel_id, uint32_t & time)
Read the Key (channel id + key) from either stage or bucket db.
Return false if the iterator is invalid.
Definition at line 5939 of file adapter.cpp.
References buf_to_u32be(), px::db::CIterator::key_data(), px::db::CIterator::key_size(), likely, and px::db::CIterator::valid().
Referenced by DeleteTrends(), DeleteTrendsInternal(), LevelupBucketTrends(), and LevelupBucketTrendsForChannel().
bool px::db::DeleteTrends (CKeyValueStore & trend_bucket_db, const std::unordered_set< uint32_t > & channel_ids, uint32_t start_day, uint32_t end_day, const volatile bool & exit_req)
Delete complete trend records, by date and channel, from bucket database.
Only complete (full day) records will be removed.
Dates are based on UTC, in days since epoch, inclusive on both sides; unbounded if zero; Return false if the db corrupted. Channel IDs must not be empty.
Definition at line 5974 of file adapter.cpp.
References px::db::CBlobHolder::append(), px::db::CBatch::clear(), compact_trend_bucket_channel_range(), px::db::CKeyValueStore::iterator(), px::db::CIterator::key_data(), px::db::CIterator::key_size(), LIBPX_DEBUG, LIBPX_ERR, likely, ReadTrendKey(), px::db::CBatch::remove(), px::db::CBlobHolder::reset(), SeekTrendIterator(), unlikely, px::db::CIterator::valid(), px::db::CIterator::value_size(), px::generic_err::what(), and px::db::CKeyValueStore::write().
bool px::db::DeleteTrends (CKeyValueStore & trend_bucket_db, uint32_t start_day, uint32_t end_day, const volatile bool & exit_req)
Delete complete trend records, by date, from bucket database.
Only complete (full day) records will be removed.
Dates are based on UTC, in days since epoch, inclusive on both sides; unbounded if zero Return false if the db corrupted.
Definition at line 6155 of file adapter.cpp.
References DeleteTrendsInternal().
bool px::db::DeleteTrends (CKeyValueStore & trend_bucket_db, const uint32_t earlist_min, const std::unordered_set< uint32_t > & existing_channels, const volatile bool & exit_req)
Delete the bucket trend records, if the date is ealier than the earlist_min, or if the channel is not in the set.
Dates are based on UTC, in days since epoch, inclusive on both sides; not applied if zero Return false if the db corrupted.
Definition at line 6149 of file adapter.cpp.
References DeleteTrendsInternal().
void px::db::get_normalized_interval_timestamp (const px::CWallTime & timestamp, const uint32_t aligned_minutes, uint32_t & interval_timestamp, bool & on_interval)
Gets the minutes since epoch, or zero if invalid, optionally aligned to an interval in minutes; and a flag indicating if the timestamp is exactly on that interval upper bound (only when aligned).
e.g. 5-minute interval: 1:05 covers range (1:00, 1:05].
Definition at line 5552 of file adapter.cpp.
Referenced by AggregateTrends(), ExportTrendBucket(), ImportTrendBucket(), ImportTrendStage(), MinutesTrigger::in_range(), MoveTrendsFromStageToBucket(), SimulateTrendBucket(), and px::CTrendAccumulator::update().
void px::db::get_normalized_interval_timestamp (const uint32_t minutes, const uint32_t aligned_minutes, uint32_t & interval_timestamp, bool & on_interval)
Gets the minutes since epoch, or zero if invalid, optionally aligned to an interval in minutes; and a flag indicating if the timestamp is exactly on that interval upper bound (only when aligned).
e.g. 5-minute interval: 1:05 covers range (1:00, 1:05].
Definition at line 5592 of file adapter.cpp.
px::CWallTime px::db::get_walltime (const uint32_t minutes)
Gets a CWallTime from the minutes since 1970 UTC.
Definition at line 5621 of file adapter.cpp.
Referenced by ExportTrendBucket(), and ExportTrendStageRow().
px::CWallTime px::db::get_walltime (const px::CWallTime & period_end_time, const uint32_t offset)
Gets a CWallTime from the period end CWallTime minus the 1/10 seconds offset.
Definition at line 5630 of file adapter.cpp.
leveldb::Status px::db::DestroyDb (const px::string & name)
Physically delete a database's folder/files.
Name must not be empty.
Definition at line 5868 of file adapter.cpp.
References px::string.
bool px::db::DoesKeyExist (CKeyValueStore & db, CBlobHolder & key_blob)
Check to see if a key exists in the database.
Definition at line 5880 of file adapter.cpp.
References px::db::CBlobHolder::get_ptr(), px::db::CKeyValueStore::iterator(), px::db::CIterator::key_data(), px::db::CIterator::key_size(), px::db::CIterator::seek(), px::db::CBlobHolder::size(), and px::db::CIterator::valid().
Referenced by DoesKeyExist().
bool px::db::DoesKeyExist (CKeyValueStore & db, const uint32_t channel_id, const uint32_t time)
Check to see if a key exists in the database.
Channel ID must be > 0
Definition at line 5900 of file adapter.cpp.
References DoesKeyExist(), px::db::CBlobHolder::get_mutable_ptr(), px::db::CBlobHolder::reset(), and u32be_to_buf().
bool px::db::IsTrendStageDbTombstoned (CKeyValueStore & db)
Check to see if a Tombstone flag is set on a stage db.
This feature is designed to handle the stage db deletion in a robust and redundant way.
Definition at line 6573 of file adapter.cpp.
References _tomestone, px::db::CBlobHolder::append(), px::db::CKeyValueStore::iterator(), px::db::CIterator::key_data(), px::db::CIterator::key_size(), px::db::CIterator::seek(), and px::db::CIterator::valid().
void px::db::SetTrendStageDbTombstoned (CKeyValueStore & db, bool tombstoned)
Set or clear the tombstone flag on a stage db.
Definition at line 6586 of file adapter.cpp.
References _tomestone, px::db::CBatch::add(), px::db::CBlobHolder::append(), px::db::CKeyValueStore::iterator(), px::db::CIterator::key_data(), px::db::CIterator::key_size(), px::db::CBatch::remove(), px::db::CIterator::valid(), and px::db::CKeyValueStore::write().
static void px::db::u16be_to_buf (unsigned char * buf, int offset, uint16_t val) static
Definition at line 42 of file adapter.cpp.
Referenced by AddTrendBucketToBatch(), and AddTrendStageToBatch().
static uint16_t px::db::buf_to_u16be (const unsigned char * buf, int offset) static
Definition at line 48 of file adapter.cpp.
Referenced by ExportTrendStageRow(), MoveTrendsFromStageToBucket(), QueryTrendStage(), ReadTrendsFromBucketRow(), and ReadTrendsFromStageRow().
static uint32_t px::db::buf_to_u32be (const unsigned char * buf) static
Definition at line 53 of file adapter.cpp.
Referenced by allocate_ids(), buf_to_u64be(), CleanupAlarms(), ExportTrendBucket(), ExportTrendStage(), GetSchemaVersion(), MoveTrendsFromStageToBucket(), QueryAlarms(), QueryTrendStage(), ReadTrendKey(), ReadTrendsFromBucketRow(), and reserve_ids().
static uint32_t px::db::buf_to_u32be (const unsigned char * buf, int offset) static
Definition at line 59 of file adapter.cpp.
static void px::db::u32be_to_buf (unsigned char * buf, uint32_t val) static
Convert 32-bit unsigned integer to 4 bytes big-endian.
Definition at line 68 of file adapter.cpp.
Referenced by AddTrendBucketToBatch(), AddTrendStageToBatch(), compact_trend_bucket_channel_range(), DoesKeyExist(), ExportTrendBucket(), ExportTrendStage(), LevelupBucketTrendsRow(), QueryTrendStage(), SaveAlarmUpdates(), SeekTrendIterator(), and SetSchemaVersion().
static void px::db::u32be_to_buf (unsigned char * buf, int offset, uint32_t val) static
Convert 32-bit unsigned integer to 4 bytes big-endian.
Definition at line 79 of file adapter.cpp.
static uint64_t px::db::buf_to_u64be (const unsigned char * buf) static
Definition at line 87 of file adapter.cpp.
References buf_to_u32be().
Referenced by allocate_ids(), CheckIDDB(), CleanupAlarms(), DeleteAlarms(), DeleteClosedAlarms(), LoadActiveAlarms(), MigrateAlarmDB(), query_alarm_index_db(), QueryAlarms(), QueryAlarmsLatestUpdate(), and reserve_ids().
static void px::db::u64be_to_buf (unsigned char * buf, uint64_t val) static
Convert 64-bit unsigned integer to 8 bytes big-endian.
Definition at line 100 of file adapter.cpp.
Referenced by AddChannelToBatch(), AddDeleteChannelToBatch(), AddDeleteDeviceToBatch(), AddDeviceToBatch(), allocate_ids(), CheckIDDB(), CleanupAlarms(), DeleteClosedAlarms(), LoadActiveAlarms(), query_alarm_index_db(), QueryAlarms(), reserve_ids(), and SaveAlarmUpdates().
static uint64_t px::db::query_alarm_index_db (CKeyValueStore & alarm_index_db, alarm_index_entry_type type, uint64_t key_value, uint64_t * found_key_value) static
Definition at line 840 of file adapter.cpp.
References px::db::CBlobHolder::append(), buf_to_u64be(), px::db::CBlobHolder::get_ptr(), px::db::CKeyValueStore::iterator(), px::db::CIterator::key_data(), px::db::CIterator::key_size(), px::db::CIterator::last(), likely, px::db::CIterator::seek(), u64be_to_buf(), unlikely, px::db::CIterator::valid(), and px::db::CIterator::value_data().
Referenced by QueryAlarms(), and SaveAlarmUpdates().
static std::vector<px::id_t> px::db::allocate_ids (CKeyValueStore & id_db, unsigned int num_requested, id_type type_requested) static
Definition at line 2450 of file adapter.cpp.
References px::db::CBatch::add(), px::db::CBlobHolder::append(), buf_to_u32be(), buf_to_u64be(), id_db_mutex, px::db::CKeyValueStore::iterator(), px::db::CIterator::key_data(), px::db::CIterator::key_size(), px::db::CIterator::seek(), u64be_to_buf(), unlikely, px::db::CIterator::valid(), px::db::CIterator::value_data(), and px::db::CKeyValueStore::write().
Referenced by AllocateAlarmIDs(), AllocateChannelIDs(), AllocateDeviceIDs(), and AllocateGlobalCounts().
static void px::db::reserve_ids (CKeyValueStore & id_db, const std::vector< px::id_t > & ids, id_type type_requested) static
Definition at line 2522 of file adapter.cpp.
References px::db::CBatch::add(), px::db::CBlobHolder::append(), buf_to_u32be(), buf_to_u64be(), id_db_mutex, px::db::CKeyValueStore::iterator(), px::db::CIterator::key_data(), px::db::CIterator::key_size(), px::db::CBlobHolder::reset(), px::db::CIterator::seek(), u64be_to_buf(), unlikely, px::db::CIterator::valid(), px::db::CIterator::value_data(), and px::db::CKeyValueStore::write().
Referenced by ReserveAlarmIDs(), ReserveChannelIDs(), ReserveDeviceIDs(), and ReserveGlobalCounts().
void px::db::compact_trend_bucket_channel_range (CKeyValueStore & trend_bucket_db, uint32_t start_channel, uint32_t end_channel)
Definition at line 5960 of file adapter.cpp.
References px::db::CKeyValueStore::compact(), px::db::CBlobHolder::get_mutable_ptr(), px::db::CBlobHolder::reset(), and u32be_to_buf().
Referenced by DeleteTrends(), and LevelupBucketTrends().
bool px::db::DeleteTrendsInternal (CKeyValueStore & trend_bucket_db, const uint32_t start_min, const uint32_t end_min, const volatile bool & exit_req, const std::unordered_set< uint32_t > & keep_channels, const bool ignore_channels)
Definition at line 6056 of file adapter.cpp.
References px::db::CBlobHolder::append(), px::db::CBatch::clear(), px::db::CKeyValueStore::compact(), px::db::CKeyValueStore::iterator(), px::db::CIterator::key_data(), px::db::CIterator::key_size(), LIBPX_DEBUG, LIBPX_ERR, ReadTrendKey(), px::db::CBatch::remove(), px::db::CBlobHolder::reset(), px::db::CIterator::seek(), unlikely, px::db::CIterator::valid(), px::generic_err::what(), and px::db::CKeyValueStore::write().
Referenced by DeleteTrends().
void px::db::LevelupBucketTrendsForChannel (CKeyValueStore & bucket_db, const uint32_t time_threshold_5min, const uint32_t time_threshold_15min, const uint32_t time_threshold_60min, unsigned int & count_5min, unsigned int & count_15min, const volatile bool & exit_req, const uint32_t channel_id)
Definition at line 6167 of file adapter.cpp.
References px::db::CBlobHolder::append(), px::db::CKeyValueStore::iterator(), px::db::CIterator::key_data(), px::db::CIterator::key_size(), LevelupBucketTrendsRow(), LIBPX_DEBUG, ReadTrendKey(), px::db::CBatch::remove(), SeekTrendIterator(), unlikely, px::db::CIterator::valid(), and px::db::CKeyValueStore::write().
Referenced by LevelupBucketTrends().
Variable Documentation
const px::string px::db::device_db_name = "devices"
Database file names, defined in adapter.cpp.
Definition at line 40 of file adapter.hpp.
const px::string px::db::channel_db_name = "channels"
Definition at line 41 of file adapter.hpp.
const px::string px::db::oob_db_name = "oob"
Definition at line 42 of file adapter.hpp.
const px::string px::db::id_db_name = "ids"
Definition at line 43 of file adapter.hpp.
const px::string px::db::alarm_db_name = "alarms"
Definition at line 44 of file adapter.hpp.
const px::string px::db::alarm_index_db_name = "alarm_index"
Definition at line 45 of file adapter.hpp.
const unsigned char px::db::_avg_trend_mask = 0x01
Definition at line 678 of file adapter.hpp.
Referenced by AddTrendBucketToBatch(), AddTrendStageToBatch(), ExportTrendStageRow(), MoveTrendsFromStageToBucket(), QueryTrendStage(), ReadTrendsFromBucketRow(), and ReadTrendsFromStageRow().
const unsigned char px::db::_min_trend_mask = 0x02
Definition at line 679 of file adapter.hpp.
Referenced by AddTrendBucketToBatch(), AddTrendStageToBatch(), ExportTrendStageRow(), MoveTrendsFromStageToBucket(), QueryTrendStage(), ReadTrendsFromBucketRow(), and ReadTrendsFromStageRow().
const unsigned char px::db::_max_trend_mask = 0x04
Definition at line 680 of file adapter.hpp.
Referenced by AddTrendBucketToBatch(), AddTrendStageToBatch(), ExportTrendStageRow(), MoveTrendsFromStageToBucket(), QueryTrendStage(), ReadTrendsFromBucketRow(), and ReadTrendsFromStageRow().
const unsigned char px::db::_actual_trend_mask = 0x08
Definition at line 681 of file adapter.hpp.
Referenced by AddTrendBucketToBatch(), AddTrendStageToBatch(), ExportTrendStageRow(), MoveTrendsFromStageToBucket(), QueryTrendStage(), ReadTrendsFromBucketRow(), and ReadTrendsFromStageRow().
const unsigned char px::db::_null_trend_mask = 0x10
Definition at line 682 of file adapter.hpp.
Referenced by AddTrendBucketToBatch(), and ReadTrendsFromBucketRow().
const unsigned char px::db::_double_trend_mask = 0x80
Definition at line 683 of file adapter.hpp.
Referenced by AddTrendBucketToBatch(), AddTrendStageToBatch(), ExportTrendStageRow(), MoveTrendsFromStageToBucket(), QueryTrendStage(), ReadTrendsFromBucketRow(), and ReadTrendsFromStageRow().
const unsigned char px::db::_tomestone = 0x00
Definition at line 685 of file adapter.hpp.
Referenced by IsTrendStageDbTombstoned(), and SetTrendStageDbTombstoned().
const size_t px::db::_avg_bit = 0
Definition at line 688 of file adapter.hpp.
const size_t px::db::_min_bit = 1
Definition at line 689 of file adapter.hpp.
const size_t px::db::_max_bit = 2
Definition at line 690 of file adapter.hpp.
const size_t px::db::_actual_bit = 3
Definition at line 691 of file adapter.hpp.
std::mutex px::db::id_db_mutex static
Definition at line 2274 of file adapter.cpp.
Referenced by allocate_ids(), CheckIDDB(), and reserve_ids().