libpx: px::sub::CSubscriberInfo Class Reference
px::sub::CSubscriberInfo Class Reference
Per-subscriber information.
#include <subscriber_info.hpp>
Public Member Functions
CSubscriberInfo (CSubscriberInfo &&x)
Move constructor.
CSubscriberInfo & operator= (CSubscriberInfo &&x)
Move assignment operator.
uint64_t get_id () const
Getter for user-visible subscriber ID.
const std::vector< CItemId > & get_items () const
Getter for the list of subscribed items.
void add_item (CItemId item)
Add a new subscribed-to item to the list.
void remove_item (CItemId item)
Remove a subscribed-to item from the list.
bool get_reflexive () const
Getter for reflexive property.
void set_reflexive (bool reflexive)
Setter for reflexive property.
Static Public Member Functions
static CSubscriberInfo create ()
Factory function to create a new subscriber.
Private Member Functions
CSubscriberInfo (uint64_t id)
Constructor.
Private Attributes
uint64_t _id
Externally-visible subscriber ID; this does not change for the lifetime of the subscription.
std::vector< CItemId > _items
A list of items which have been subscribed to by this subscriber.
bool _reflexive
True if subscriber should receive reflexive (self triggered) notifications.
Static Private Attributes
static uint64_t _max_id = 1
Maximum subscriber ID currently in use.
Detailed Description
Per-subscriber information.
This class tracks information for each subscriber, including a user-visible subscription ID and a list of all current subscribed-to items. The latter allows the subscription subsystem to clean up data structures when a subscriber is removed; without this info, a badly-behaving client (for example) would cause a build-up of extraneous information in the internal subscription data structures.
Definition at line 23 of file subscriber_info.hpp.
Constructor & Destructor Documentation
px::sub::CSubscriberInfo::CSubscriberInfo (CSubscriberInfo && x)
Move constructor.
Parameters
x The object to move into this one's place
Definition at line 28 of file subscriber_info.cpp.
Referenced by create().
px::sub::CSubscriberInfo::CSubscriberInfo (uint64_t id) private
Constructor.
Parameters
id The new, unique ID to assign to this object
Definition at line 94 of file subscriber_info.cpp.
Member Function Documentation
px::sub::CSubscriberInfo px::sub::CSubscriberInfo::create () static
Factory function to create a new subscriber.
Returns
A new subscriber, with a subscription ID that is guaranteed to be unique across instances
Definition at line 17 of file subscriber_info.cpp.
References _max_id, CSubscriberInfo(), and LIBPX_DEBUG.
Referenced by px::sub::CSubscriptionManager::new_subscriber().
px::sub::CSubscriberInfo & px::sub::CSubscriberInfo::operator= (CSubscriberInfo && x)
Move assignment operator.
Parameters
x The object to move into this one's place
Definition at line 39 of file subscriber_info.cpp.
References _id.
uint64_t px::sub::CSubscriberInfo::get_id () const
Getter for user-visible subscriber ID.
Returns
The unique ID for this subscriber
Definition at line 64 of file subscriber_info.hpp.
References _id.
Referenced by px::sub::CSubscriptionManager::remove_subscriber().
const std::vector<CItemId>& px::sub::CSubscriberInfo::get_items () const
Getter for the list of subscribed items.
Returns
The list of subscribed items for this subscriber
Definition at line 72 of file subscriber_info.hpp.
References _items.
Referenced by px::sub::CSubscriptionManager::remove_subscriber().
void px::sub::CSubscriberInfo::add_item (CItemId item)
Add a new subscribed-to item to the list.
Parameters
item The new item to add (ignored if already present)
Definition at line 51 of file subscriber_info.cpp.
References px::lower_bound.
void px::sub::CSubscriberInfo::remove_item (CItemId item)
Remove a subscribed-to item from the list.
Parameters
item The item to removed (ignored if not present)
Definition at line 74 of file subscriber_info.cpp.
References px::lower_bound.
bool px::sub::CSubscriberInfo::get_reflexive () const
Getter for reflexive property.
Returns
value indicating if subscriber should receive reflexive (self-triggered) notifications
Definition at line 96 of file subscriber_info.hpp.
References _reflexive.
void px::sub::CSubscriberInfo::set_reflexive (bool reflexive)
Setter for reflexive property.
Parameters
reflexive indicates whether subscriber should
Definition at line 104 of file subscriber_info.hpp.
References _reflexive.
Member Data Documentation
uint64_t px::sub::CSubscriberInfo::_id private
Externally-visible subscriber ID; this does not change for the lifetime of the subscription.
Definition at line 127 of file subscriber_info.hpp.
Referenced by get_id(), and operator=().
std::vector<CItemId> px::sub::CSubscriberInfo::_items private
A list of items which have been subscribed to by this subscriber.
This is maintained as a sorted vector, which makes certain operations simpler
Definition at line 135 of file subscriber_info.hpp.
Referenced by get_items().
bool px::sub::CSubscriberInfo::_reflexive private
True if subscriber should receive reflexive (self triggered) notifications.
Definition at line 141 of file subscriber_info.hpp.
Referenced by get_reflexive(), and set_reflexive().
uint64_t px::sub::CSubscriberInfo::_max_id = 1 static private
Maximum subscriber ID currently in use.
Definition at line 151 of file subscriber_info.hpp.
Referenced by create().
The documentation for this class was generated from the following files:
subscriber_info.hpp
subscriber_info.cpp