libpx: px::val_impl::as_datatype Class Reference
px::val_impl::as_datatype Class Reference
Visitor function that converts one value into another.
#include <as_datatype.hpp>
Public Member Functions
as_datatype (CDataType type)
CValue operator() (px::invalid_t) const
CValue operator() (bool val) const
template<typename T >
CValue operator() (T val, __REQUIRE(std::is_arithmetic< T >::value)) const
CValue operator() (const CTimestamp &val) const
CValue operator() (const px::string &val) const
CValue operator() (const std::vector< unsigned char > &val) const
Private Attributes
CDataType _type
Detailed Description
Visitor function that converts one value into another.
Definition at line 17 of file as_datatype.hpp.
Constructor & Destructor Documentation
px::val_impl::as_datatype::as_datatype (CDataType type)
Definition at line 20 of file as_datatype.hpp.
Member Function Documentation
CValue px::val_impl::as_datatype::operator() (px::invalid_t) const
Definition at line 27 of file as_datatype.hpp.
References _type, px::binary, px::boolean, px::float32, px::float64, px::int32, px::int64, px::invalid, px::string, px::timestamp, px::uint32, px::uint64, and px::CDataType::val().
CValue px::val_impl::as_datatype::operator() (bool val) const
Definition at line 72 of file as_datatype.hpp.
References _type, px::binary, px::boolean, px::float32, px::float64, px::int32, px::int64, px::invalid, px::string, px::timestamp, px::uint32, px::uint64, and px::CDataType::val().
template<typename T > CValue px::val_impl::as_datatype::operator() (T val, __REQUIRE(std::is_arithmetic< T >::value)) const
Definition at line 119 of file as_datatype.hpp.
References _type, px::binary, px::boolean, px::float32, px::float64, px::int32, px::int64, px::invalid, px::max, px::string, px::timestamp, px::uint32, px::uint64, and px::CDataType::val().
CValue px::val_impl::as_datatype::operator() (const CTimestamp & val) const
Definition at line 180 of file as_datatype.hpp.
References _type, px::binary, px::boolean, px::float32, px::float64, px::CTimestamp::gmtime_str(), px::int32, px::int64, px::invalid, px::max, px::string, px::timestamp, px::CTimestamp::to_float(), px::uint32, px::uint64, and px::CDataType::val().
CValue px::val_impl::as_datatype::operator() (const px::string & val) const
Definition at line 226 of file as_datatype.hpp.
References _type, px::binary, px::boolean, px::CBase64Converter::decode(), px::float32, px::float64, px::int32, px::int64, px::invalid, px::string, px::timestamp, px::uint32, px::uint64, and px::CDataType::val().
CValue px::val_impl::as_datatype::operator() (const std::vector< unsigned char > & val) const
Definition at line 361 of file as_datatype.hpp.
References _type, px::binary, px::boolean, px::CBase64Converter::encode(), px::float32, px::float64, px::int32, px::int64, px::invalid, px::string, px::timestamp, px::uint32, px::uint64, and px::CDataType::val().
Member Data Documentation
CDataType px::val_impl::as_datatype::_type private
Definition at line 404 of file as_datatype.hpp.
Referenced by operator()().
The documentation for this class was generated from the following file:
as_datatype.hpp