libpx: px::asio::CTcpSslConnection Class Reference
px::asio::CTcpSslConnection Class Reference
ASIO interface details and general IO functions.
TCP Connection class, which manages TCP transactions.
#include <tcp_ssl_connection.hpp>
Public Types
typedef
boost::asio::ssl::stream
< boost::asio::ip::tcp::socket > ssl_socket
ssl tcp sockets need to be of type ssl::stream
Public Member Functions
CTcpSslConnection (CIoManager &manager, const CProtocolHandler &prot, boost::asio::ssl::context &ctx)
Constructor.
~CTcpSslConnection ()
Destructor.
virtual PUBLIC const std::string source ()
simple getter to access who the source of this connection is.
virtual PUBLIC uint16_t source_port ()
Get port number of the source of a message.
void close () override
Inherited from CIoTransactor when the socket connection is gone, the remote_endpoint may throw an exception.
void read_more () override
Inherited from CIoTransactor when the socket connection is gone, the remote_endpoint may throw an exception.
void start_handshake ()
initiate the ssl handshake
void handle_handshake (const boost::system::error_code &error)
Callback to handle a successful handshake and kick off the connection.
Public Member Functions inherited from px::asio::CIoTransactor
CIoTransactor (CIoManager &manager, const CProtocolHandler &prot)
Constructor.
virtual ~CIoTransactor ()
Destructor.
PUBLIC void start ()
Kick-start the messenger by waiting for incoming data.
PUBLIC iobuf_const_pair_t get_rbuf ()
Get the currently-read message boundaries.
PUBLIC void clear_rbuf (iobuf_const_iter_t end)
Clear (perhaps only partially) the read-buffer contents after servicing a single request.
PUBLIC bool get_parse_success ()
PUBLIC void set_parse_failed (bool val)
virtual PUBLIC void write (std::shared_ptr< io_buf_t > pbuf)
Write data to the messenger's output channel's outbox.
Public Member Functions inherited from px::asio::CIoActor
CIoActor (CIoManager &manager)
Constructor.
virtual ~CIoActor ()
Destructor.
boost::asio::io_service & get_io_service () const
Get the I/O service associated with the owner of this actor.
PUBLIC CServerCore & get_server_core () const
Get the container for CDS data management.
PUBLIC CCdsHandler & get_cds_handler () const
Get the container for CDS data management.
PUBLIC bool get_quit_status ()
Get the quit status from connection IO manager.
Static Public Member Functions
static std::shared_ptr
< CTcpSslConnection > create (CIoManager &manager, const CProtocolHandler &prot, boost::asio::ssl::context &ctx)
Factory function to create a new CTcpSslConnection object.
Protected Member Functions
void write_more (const std::shared_ptr< io_buf_t > &pbuf) override
Write the data from the outbox to the service.
Protected Member Functions inherited from px::asio::CIoTransactor
void handle_read (const boost::system::error_code &err, size_t bytes_transferred)
Callback function to handle incoming data.
void handle_write (const boost::system::error_code &err, size_t bytes_transferred)
Callback function to handle a completed "write" operation.
void parse ()
Attempt to parse the currently-read data in the buffer.
void clear_outbox ()
Clear the outbox queue.
std::shared_ptr< io_buf_t > get_outbox_front_buf ()
Get the front item from the outbox if any.
Protected Member Functions inherited from px::asio::CIoActor
void remove ()
This method is called when an actor wants to remove itself from the I/O management interface.
Private Attributes
std::unique_ptr< ssl_socket > _sock
The underlying Boost.Asio TCP socket object.
bool handshake_in_progress
Indicates if SSL handshake in progress.
Additional Inherited Members
Public Attributes inherited from px::asio::CIoTransactor
bool started
True if start() has been called This can be used to distinguish e.g.
Protected Attributes inherited from px::asio::CIoTransactor
io_buf_t _rbuf
I/O buffer used for reading message data.
size_t _offset
Current offset in _rbuf, i.e.
std::shared_ptr< CProtocolHandler > _prot
Protocol-specific handler, used to parse and handle incoming requests and generate responses.
std::queue< std::shared_ptr
< io_buf_t > > _outbox
Queues the outgoing data to send.
Protected Attributes inherited from px::asio::CIoActor
CIoManager & _owner
The I/O manager object that "owns" this connection.
Detailed Description
TCP Connection class, which manages TCP transactions.
This class handles all TCP transfers between the server and a single client. It is spawned by the listener when an incoming connection attempt is made, and is used to transfer requests and responses to/from the server. Patterned after the CTcpConnection class
Definition at line 22 of file tcp_ssl_connection.hpp.
Member Typedef Documentation
typedef boost::asio::ssl::stream<boost::asio::ip::tcp::socket> px::asio::CTcpSslConnection::ssl_socket
ssl tcp sockets need to be of type ssl::stream
Definition at line 33 of file tcp_ssl_connection.hpp.
Constructor & Destructor Documentation
px::asio::CTcpSslConnection::CTcpSslConnection (CIoManager & manager, const CProtocolHandler & prot, boost::asio::ssl::context & ctx)
Constructor.
Parameters
manager The I/O manager object to which this connection is to be bound
prot Protocol handler object which is utilized to perform protocol-specific operations on this TCP connection in an abstracted manner
ctx Used to get at the SSL options such as verification mode, certificate files, and so on.
Exceptions
boost::system::system_error The connection could not be initialized
Definition at line 30 of file tcp_ssl_connection.cpp.
References _sock, and px::asio::CIoActor::get_io_service().
px::asio::CTcpSslConnection::~CTcpSslConnection ()
Destructor.
Definition at line 44 of file tcp_ssl_connection.cpp.
References close(), and LIBPX_FDEBUG.
Member Function Documentation
std::shared_ptr< CTcpSslConnection > px::asio::CTcpSslConnection::create (CIoManager & manager, const CProtocolHandler & prot, boost::asio::ssl::context & ctx) static
Factory function to create a new CTcpSslConnection object.
Parameters
manager The I/O manager object to which this object is to be bound
prot Protocol handler object which is utilized to perform protocol-specific operations on this TCP connection in an abstracted manner
ctx Used to get at the SSL options such as verification mode, certificate files, and so on.
Exceptions
boost::system::system_error The connection could not be initialized
Returns
Shared pointer containing the new instance of CTcpSslConnection.
Definition at line 18 of file tcp_ssl_connection.cpp.
Referenced by px::asio::CTcpListener::ssl_accept().
virtual PUBLIC const std::string px::asio::CTcpSslConnection::source () virtual
simple getter to access who the source of this connection is.
Implements px::asio::CIoTransactor.
Definition at line 96 of file tcp_ssl_connection.hpp.
References _sock.
Referenced by close().
virtual PUBLIC uint16_t px::asio::CTcpSslConnection::source_port () virtual
Get port number of the source of a message.
Returns
Port number of the source of this message.
Reimplemented from px::asio::CIoTransactor.
Definition at line 106 of file tcp_ssl_connection.hpp.
References _sock.
void px::asio::CTcpSslConnection::close () override virtual
Inherited from CIoTransactor when the socket connection is gone, the remote_endpoint may throw an exception.
Reimplemented from px::asio::CIoTransactor.
Definition at line 61 of file tcp_ssl_connection.cpp.
References _sock, handshake_in_progress, LIBPX_DEBUG, and source().
Referenced by handle_handshake(), and ~CTcpSslConnection().
void px::asio::CTcpSslConnection::read_more () override virtual
Inherited from CIoTransactor when the socket connection is gone, the remote_endpoint may throw an exception.
Implements px::asio::CIoTransactor.
Definition at line 98 of file tcp_ssl_connection.cpp.
References px::asio::CIoTransactor::_offset, px::asio::CIoActor::_owner, px::asio::CIoTransactor::_rbuf, _sock, px::asio::CIoTransactor::handle_read(), px::asio::CIoManager::is_quit_signal_received(), and LIBPX_INFO.
void px::asio::CTcpSslConnection::start_handshake ()
initiate the ssl handshake
Definition at line 170 of file tcp_ssl_connection.cpp.
References _sock, handle_handshake(), and handshake_in_progress.
void px::asio::CTcpSslConnection::handle_handshake (const boost::system::error_code & error)
Callback to handle a successful handshake and kick off the connection.
Definition at line 151 of file tcp_ssl_connection.cpp.
References close(), handshake_in_progress, and px::asio::CIoTransactor::start().
Referenced by start_handshake().
void px::asio::CTcpSslConnection::write_more (const std::shared_ptr< io_buf_t > & pbuf) override protected virtual
Write the data from the outbox to the service.
This operation is implemented in terms of zero or more calls to the stream's async_write_some function, and is known as a composed operation. The program must ensure that the stream performs no other write operations (such as async_write, the stream's async_write_some function, or any other composed operations that perform writes) until this operation completes.
Implements px::asio::CIoTransactor.
Definition at line 126 of file tcp_ssl_connection.cpp.
References px::asio::CIoActor::_owner, _sock, px::asio::CIoTransactor::handle_write(), px::asio::CIoManager::is_quit_signal_received(), and LIBPX_INFO.
Member Data Documentation
std::unique_ptr<ssl_socket> px::asio::CTcpSslConnection::_sock private
The underlying Boost.Asio TCP socket object.
Definition at line 159 of file tcp_ssl_connection.hpp.
Referenced by close(), CTcpSslConnection(), read_more(), source(), source_port(), start_handshake(), and write_more().
bool px::asio::CTcpSslConnection::handshake_in_progress private
Indicates if SSL handshake in progress.
Definition at line 164 of file tcp_ssl_connection.hpp.
Referenced by close(), handle_handshake(), and start_handshake().
The documentation for this class was generated from the following files:
tcp_ssl_connection.hpp
tcp_ssl_connection.cpp