libpx: util.cpp File Reference
util.cpp File Reference
#include <random>
#include <cstdlib>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <fcntl.h>
#include <string.h>
#include <sched.h>
#include <pwd.h>
#include <assert.h>
#include <errno.h>
#include <sys/prctl.h>
#include <linux/capability.h>
#include <sys/syscall.h>
#include <sys/resource.h>
#include <grp.h>
#include <arpa/inet.h>
#include <pthread.h>
#include "openssl/sha.h"
#include <dirent.h>
#include "px_config.h"
#include "px/proto/ToolkitConfiguration.hpp"
#include "px/util/util.hpp"
#include "px/util/string_util.hpp"
#include "px/type/string.hpp"
#include "log.hpp"
Classes
struct _uuid_t
Macros
#define LIBPX_LOG_SUBSYSTEM LIBPX_LOG_DEFAULT
#define REDIRECT_STDERR " 2>&1"
#define CMD_OUTPUT_MAX 512
#define UUID_MIN_ALLOC 37
Typedefs
typedef struct _uuid_t _uuid_t
Functions
std::mt19937 rand_gen (rd())
static void coverage_compensate (uid_t dest_uid)
void format_uuid_v3or5 (_uuid_t *uuid, unsigned char hash[16], int v)
void uuid_create_sha1_from_name (_uuid_t *uuid, const void *name, unsigned long namelen)
Variables
std::random_device rd
Macro Definition Documentation
#define LIBPX_LOG_SUBSYSTEM LIBPX_LOG_DEFAULT
Definition at line 20 of file util.cpp.
#define REDIRECT_STDERR " 2>&1"
Definition at line 53 of file util.cpp.
#define CMD_OUTPUT_MAX 512
Definition at line 55 of file util.cpp.
#define UUID_MIN_ALLOC 37
Definition at line 716 of file util.cpp.
Referenced by px::CUtil::create_uuid().
Typedef Documentation
typedef struct _uuid_t _uuid_t
Function Documentation
std::mt19937 rand_gen (rd())
Referenced by px::CUtil::create_random_uuid().
static void coverage_compensate (uid_t dest_uid) static
Definition at line 347 of file util.cpp.
References LIBPX_DEBUG.
Referenced by px::CUtil::set_euid(), and px::CUtil::set_uid().
void format_uuid_v3or5 (_uuid_t * uuid, unsigned char hash[16], int v)
Definition at line 684 of file util.cpp.
References _uuid_t::clock_seq_hi_and_reserved, _uuid_t::time_hi_and_version, _uuid_t::time_low, and _uuid_t::time_mid.
Referenced by uuid_create_sha1_from_name().
void uuid_create_sha1_from_name (_uuid_t * uuid, const void * name, unsigned long namelen)
Definition at line 700 of file util.cpp.
References format_uuid_v3or5(), and hash().
Referenced by px::CUtil::create_uuid().
Variable Documentation
std::random_device rd
Definition at line 73 of file util.cpp.