libpx: json_protobuf.cpp File Reference
json_protobuf.cpp File Reference
#include <json_spirit_reader_template.h>
#include <json_spirit_writer_template.h>
#include <sstream>
#include <google/protobuf/descriptor.h>
#include <cstdlib>
#include <cmath>
#include "px/util/json_protobuf.hpp"
#include "px/util/b64_converter.hpp"
#include "px/util/string_util.hpp"
#include "px/exception.hpp"
#include "log.hpp"
Macros
#define MAX_ERR_TEXT 120
Functions
static px::string parse_one_message (const ::json_spirit::Object &object, const google::protobuf::Descriptor *desc, google::protobuf::Message *msg)
static px::string serialize_one_message (const google::protobuf::Message *msg, bool pretty_print, bool noextraspace, bool numeric_enums, int tabs=0)
static const char * parse_err_msg (const char *text, const google::protobuf::FieldDescriptor *fd)
static px::string set_single_value (const ::json_spirit::Value &val, google::protobuf::Message *msg, const google::protobuf::Reflection *r, const google::protobuf::FieldDescriptor *fd)
static px::string new_message_given_name (const px::string &name, google::protobuf::Message **ppMsg, const google::protobuf::Descriptor **ppDesc)
static px::string json_to_protobuf_internal (bool is_qualified, const px::string &json, const px::string &protobuf_type, std::vector< std::shared_ptr< google::protobuf::Message > > &msgs)
static char hex_char (const unsigned char c)
static px::string json_string_escape (const px::string &in)
Provide escaping of any chars that JSON requires be escaped.
static void float_format (float num, std::ostringstream &s)
static void double_format (double num, std::ostringstream &s)
static px::string serialize_field_value (const google::protobuf::Message *msg, const google::protobuf::FieldDescriptor *fld_desc, bool pretty_print, bool noextraspace, bool numeric_enums, int tabs)
static px::string serialize_one_repeated_field_value (const google::protobuf::Message *msg, const google::protobuf::FieldDescriptor *fld_desc, unsigned int index, bool pretty_print, bool noextraspace, bool numeric_enums, int tabs)
static px::string protobuf_to_json_internal (bool is_qualified, px::string &protobuf_type, std::vector< std::shared_ptr< google::protobuf::Message > > &msgs, bool pretty_print, bool noextraspace, bool nolist, bool numeric_enums)
Variables
static char err_text [MAX_ERR_TEXT]
Macro Definition Documentation
#define MAX_ERR_TEXT 120
Definition at line 18 of file json_protobuf.cpp.
Referenced by parse_err_msg().
Function Documentation
static px::string parse_one_message (const ::json_spirit::Object & object, const google::protobuf::Descriptor * desc, google::protobuf::Message * msg) static
Definition at line 315 of file json_protobuf.cpp.
References set_single_value(), and unlikely.
Referenced by json_to_protobuf_internal(), and set_single_value().
static px::string serialize_one_message (const google::protobuf::Message * msg, bool pretty_print, bool noextraspace, bool numeric_enums, int tabs = 0) static
Definition at line 1058 of file json_protobuf.cpp.
References serialize_field_value(), serialize_one_repeated_field_value(), and unlikely.
Referenced by protobuf_to_json_internal(), serialize_field_value(), and serialize_one_repeated_field_value().
static const char* parse_err_msg (const char * text, const google::protobuf::FieldDescriptor * fd) static
Definition at line 23 of file json_protobuf.cpp.
References err_text, and MAX_ERR_TEXT.
Referenced by set_single_value().
static px::string set_single_value (const ::json_spirit::Value & val, google::protobuf::Message * msg, const google::protobuf::Reflection * r, const google::protobuf::FieldDescriptor * fd) static
Definition at line 29 of file json_protobuf.cpp.
References px::CBase64Converter::decode(), likely, parse_err_msg(), parse_one_message(), and unlikely.
Referenced by parse_one_message().
static px::string new_message_given_name (const px::string & name, google::protobuf::Message ** ppMsg, const google::protobuf::Descriptor ** ppDesc) static
Definition at line 385 of file json_protobuf.cpp.
References unlikely.
Referenced by json_to_protobuf_internal().
static px::string json_to_protobuf_internal (bool is_qualified, const px::string & json, const px::string & protobuf_type, std::vector< std::shared_ptr< google::protobuf::Message > > & msgs) static
Definition at line 432 of file json_protobuf.cpp.
References new_message_given_name(), and parse_one_message().
Referenced by px::JSON2Protobuf(), and px::QualifiedJSON2Protobuf().
static char hex_char (const unsigned char c) static
Definition at line 703 of file json_protobuf.cpp.
Referenced by json_string_escape().
static px::string json_string_escape (const px::string & in) static
Provide escaping of any chars that JSON requires be escaped.
String is assumed to be UTF-8 encoded (ASCII 0x20-0x7f is valid UTF-8)
Parameters
in The input string from the Protobuf message
Returns
The output string, suitable for JSON, with an characters that need it escaped
Definition at line 724 of file json_protobuf.cpp.
References hex_char(), likely, px::pxstr_first_utf8_codepoint(), and unlikely.
Referenced by serialize_field_value(), and serialize_one_repeated_field_value().
static void float_format (float num, std::ostringstream & s) static
Definition at line 781 of file json_protobuf.cpp.
References unlikely.
Referenced by serialize_field_value(), and serialize_one_repeated_field_value().
static void double_format (double num, std::ostringstream & s) static
Definition at line 805 of file json_protobuf.cpp.
References unlikely.
Referenced by serialize_field_value(), and serialize_one_repeated_field_value().
static px::string serialize_field_value (const google::protobuf::Message * msg, const google::protobuf::FieldDescriptor * fld_desc, bool pretty_print, bool noextraspace, bool numeric_enums, int tabs) static
Definition at line 831 of file json_protobuf.cpp.
References double_format(), px::CBase64Converter::encode(), float_format(), json_string_escape(), and serialize_one_message().
Referenced by serialize_one_message().
static px::string serialize_one_repeated_field_value (const google::protobuf::Message * msg, const google::protobuf::FieldDescriptor * fld_desc, unsigned int index, bool pretty_print, bool noextraspace, bool numeric_enums, int tabs) static
Definition at line 946 of file json_protobuf.cpp.
References double_format(), px::CBase64Converter::encode(), float_format(), json_string_escape(), and serialize_one_message().
Referenced by serialize_one_message().
static px::string protobuf_to_json_internal (bool is_qualified, px::string & protobuf_type, std::vector< std::shared_ptr< google::protobuf::Message > > & msgs, bool pretty_print, bool noextraspace, bool nolist, bool numeric_enums) static
Definition at line 1224 of file json_protobuf.cpp.
References serialize_one_message(), and unlikely.
Referenced by px::Protobuf2JSON(), and px::Protobuf2QualifiedJSON().
Variable Documentation
char err_text[MAX_ERR_TEXT] static
Definition at line 19 of file json_protobuf.cpp.
Referenced by parse_err_msg(), and px::proto::CMercuryHeader::parse_header_only().