libpx: px::asio::CIoActor Class Reference
px::asio::CIoActor Class Reference
ASIO interface details and general IO functions. | IO_Actors
The I/O "Actor" base class.
#include <io_actor.hpp>
Public Member Functions
CIoActor (CIoManager &manager)
Constructor.
virtual ~CIoActor ()
Destructor.
virtual void close ()
Gracefully close this actor.
boost::asio::io_service & get_io_service () const
Get the I/O service associated with the owner of this actor.
PUBLIC CServerCore & get_server_core () const
Get the container for CDS data management.
PUBLIC CCdsHandler & get_cds_handler () const
Get the container for CDS data management.
PUBLIC bool get_quit_status ()
Get the quit status from connection IO manager.
Protected Member Functions
void remove ()
This method is called when an actor wants to remove itself from the I/O management interface.
Protected Attributes
CIoManager & _owner
The I/O manager object that "owns" this connection.
Detailed Description
The I/O "Actor" base class.
The base class for all I/O actors in the ASIO system.
Definition at line 39 of file io_actor.hpp.
Constructor & Destructor Documentation
px::asio::CIoActor::CIoActor (CIoManager & manager)
Constructor.
Parameters
manager The I/O manager object to which this object is to be bound
Exceptions
boost::system::system_error The actor could not be initialized
Definition at line 11 of file io_actor.cpp.
px::asio::CIoActor::~CIoActor () virtual
Destructor.
Definition at line 20 of file io_actor.cpp.
References close(), and LIBPX_FERR.
Member Function Documentation
void px::asio::CIoActor::close () virtual
Gracefully close this actor.
This will gracefully close the actor. It is called automatically by the actor's destructor, but any resulting error information will be lost in that case.
Exceptions
boost::system::system_error There was an error when attempting to gracefully shut down / close
Reimplemented in px::asio::CIoTransactor, px::asio::CUdpListener, px::asio::CTcpSslConnection, px::asio::CTcpListener, px::asio::CUdpSender, px::asio::CUdsDgramListener, px::asio::CTcpConnection, px::asio::CUdsListener, px::asio::CIoSighandler, px::asio::CCdsConnection, px::asio::CUdsConnection, px::asio::CWatchdogTimer, and px::asio::CMsecTimer.
Definition at line 37 of file io_actor.cpp.
Referenced by ~CIoActor().
boost::asio::io_service & px::asio::CIoActor::get_io_service () const
Get the I/O service associated with the owner of this actor.
Returns
A reference to the I/O manager's service object
Definition at line 45 of file io_actor.cpp.
References _owner, px::asio::CIoManager::_service, and likely.
Referenced by px::asio::CTcpConnection::CTcpConnection(), px::asio::CTcpListener::CTcpListener(), px::asio::CTcpSslConnection::CTcpSslConnection(), px::asio::CUdsConnection::CUdsConnection(), px::asio::CUdsListener::CUdsListener(), px::asio::CIoTimer::do_synchronous_wait(), px::asio::CIoUsecTimer::do_synchronous_wait(), px::asio::CUdsDgramListener::reset_socket(), px::asio::CUdpSender::reset_socket(), and px::asio::CUdpListener::reset_socket().
CServerCore & px::asio::CIoActor::get_server_core () const
Get the container for CDS data management.
Returns
A reference to the I/O manager's server core object
Definition at line 61 of file io_actor.cpp.
References px::asio::CIoManager::_core, and _owner.
Referenced by px::asio::CProtocolHandler::get_server_core().
CCdsHandler & px::asio::CIoActor::get_cds_handler () const
Get the container for CDS data management.
Returns
A reference to the I/O manager's cds handler object
Definition at line 71 of file io_actor.cpp.
References px::asio::CIoManager::_cds, and _owner.
Referenced by px::asio::CCdsConnection::CCdsConnection().
bool px::asio::CIoActor::get_quit_status ()
Get the quit status from connection IO manager.
This quit is related to Quit signal received for stopping the server and the same is cascaded to next level.
Returns
A quite status - false or true
Definition at line 79 of file io_actor.cpp.
References _owner, and px::asio::CIoManager::is_quit_signal_received().
void px::asio::CIoActor::remove () protected
This method is called when an actor wants to remove itself from the I/O management interface.
Definition at line 87 of file io_actor.cpp.
References _owner, and px::asio::CIoManager::close().
Member Data Documentation
CIoManager& px::asio::CIoActor::_owner protected
The I/O manager object that "owns" this connection.
Definition at line 127 of file io_actor.hpp.
Referenced by px::asio::CUdsListener::accept(), px::asio::CTcpListener::accept(), get_cds_handler(), get_io_service(), get_quit_status(), get_server_core(), px::asio::CUdsListener::handle_accept(), px::asio::CTcpListener::handle_accept(), px::asio::CIoSighandler::handle_signal(), px::asio::CTcpListener::handle_ssl_accept(), px::asio::CTcpConnection::read_more(), px::asio::CTcpSslConnection::read_more(), remove(), px::asio::CTcpListener::ssl_accept(), px::asio::CTcpConnection::write_more(), and px::asio::CTcpSslConnection::write_more().
The documentation for this class was generated from the following files:
io_actor.hpp
io_actor.cpp