libpx: px::permission Namespace Reference
px::permission Namespace Reference
Functions
PUBLIC px::permissions str_to_perm (const px::string &str)
Convert a string to a permission enum. String must not be empty.
PUBLIC px::string perm_to_str (const px::permissions &perm)
Convert a permission enum to a string.
PUBLIC px::CBitset
< px::permissions > str_to_perms (const std::vector< px::string > &strs)
Convert a set of strings to a set of permissions.
PUBLIC std::vector< px::string > perms_to_str (const px::CBitset< px::permissions > &perms)
Convert a set of permissions to a set of strings.
PUBLIC bool perms_overlap (const px::CBitset< px::permissions > &a, const px::CBitset< px::permissions > &b)
Permission check: do a and b have any in common?
PUBLIC px::string perms_to_short_str (const px::CBitset< px::permissions > &perms)
Short string for display, like "ls -l" file permissions Format: per_user, data r/w/admin, config r/w/file, control basic/oper/setpoints, event-ack, security read/admin, install, internal_app/troubleshoot.
Function Documentation
px::permissions px::permission::str_to_perm (const px::string & str)
Convert a string to a permission enum. String must not be empty.
Definition at line 7 of file permission.cpp.
References px::config_file, px::config_read, px::config_write, px::control_basic, px::control_oper, px::data_admin, px::data_read, px::data_write, px::event_ack, px::install, px::internal_app, px::per_user, px::security_admin, px::security_read, px::setpoints, px::troubleshoot, TRY_STR, and px::unknown.
Referenced by str_to_perms().
px::string px::permission::perm_to_str (const px::permissions & perm)
Convert a permission enum to a string.
Definition at line 32 of file permission.cpp.
References px::config_file, px::config_read, px::config_write, px::control_basic, px::control_oper, px::data_admin, px::data_read, px::data_write, px::event_ack, px::install, px::internal_app, px::per_user, px::security_admin, px::security_read, px::setpoints, px::troubleshoot, and px::unknown.
Referenced by perms_to_str().
px::CBitset< px::permissions > px::permission::str_to_perms (const std::vector< px::string > & strs)
Convert a set of strings to a set of permissions.
Definition at line 236 of file permission.cpp.
References px::CBitset< T >::set(), and str_to_perm().
std::vector< px::string > px::permission::perms_to_str (const px::CBitset< px::permissions > & perms)
Convert a set of permissions to a set of strings.
Definition at line 247 of file permission.cpp.
References px::CBitset< T >::get(), perm_to_str(), and px::size.
bool px::permission::perms_overlap (const px::CBitset< px::permissions > & a, const px::CBitset< px::permissions > & b)
Permission check: do a and b have any in common?
Definition at line 261 of file permission.cpp.
References px::CBitset< T >::empty(), and px::CBitset< T >::mask().
px::string px::permission::perms_to_short_str (const px::CBitset< px::permissions > & perms)
Short string for display, like "ls -l" file permissions Format: per_user, data r/w/admin, config r/w/file, control basic/oper/setpoints, event-ack, security read/admin, install, internal_app/troubleshoot.
Full permissions looks like this: erwa/rwf/BOS/k/aA/i/ID Only per_user, data-read & alarm ack: er–/—/—/k/–/-/–
Definition at line 92 of file permission.cpp.
References px::config_file, px::config_read, px::config_write, px::control_basic, px::control_oper, px::data_admin, px::data_read, px::data_write, px::event_ack, px::CBitset< T >::get(), px::install, px::internal_app, px::per_user, px::security_admin, px::security_read, px::setpoints, px::size, and px::troubleshoot.
Referenced by px::asio::CCdsSyncIO::cds_login(), and px::asio::CCdsHandler::cds_login().