libpx: px::asio::CIoTransactor Class Reference
px::asio::CIoTransactor Class Reference abstract
ASIO interface details and general IO functions. | IO_Actors
The abstract I/O "Messenger" class that will be implemented in the TCP and UDP connection classes.
#include <io_transactor.hpp>
Public Member Functions
CIoTransactor (CIoManager &manager, const CProtocolHandler &prot)
Constructor.
virtual ~CIoTransactor ()
Destructor.
PUBLIC void start ()
Kick-start the messenger by waiting for incoming data.
PUBLIC iobuf_const_pair_t get_rbuf ()
Get the currently-read message boundaries.
PUBLIC void clear_rbuf (iobuf_const_iter_t end)
Clear (perhaps only partially) the read-buffer contents after servicing a single request.
PUBLIC bool get_parse_success ()
PUBLIC void set_parse_failed (bool val)
virtual void read_more ()=0
Read more data from the messenger's input source.
virtual PUBLIC const std::string source ()=0
Get text describing the source of a message (eg, dotted IP address).
virtual PUBLIC uint16_t source_port ()
Get port number of the source of a message (0 if N/A).
virtual PUBLIC void write (std::shared_ptr< io_buf_t > pbuf)
Write data to the messenger's output channel's outbox.
virtual PUBLIC void close ()
Gracefully close this actor.
Public Member Functions inherited from px::asio::CIoActor
CIoActor (CIoManager &manager)
Constructor.
virtual ~CIoActor ()
Destructor.
boost::asio::io_service & get_io_service () const
Get the I/O service associated with the owner of this actor.
PUBLIC CServerCore & get_server_core () const
Get the container for CDS data management.
PUBLIC CCdsHandler & get_cds_handler () const
Get the container for CDS data management.
PUBLIC bool get_quit_status ()
Get the quit status from connection IO manager.
Public Attributes
bool started
True if start() has been called This can be used to distinguish e.g.
Protected Member Functions
void handle_read (const boost::system::error_code &err, size_t bytes_transferred)
Callback function to handle incoming data.
void handle_write (const boost::system::error_code &err, size_t bytes_transferred)
Callback function to handle a completed "write" operation.
void parse ()
Attempt to parse the currently-read data in the buffer.
virtual void write_more (const std::shared_ptr< io_buf_t > &pbuf)=0
Write the data from the outbox to the service.
void clear_outbox ()
Clear the outbox queue.
std::shared_ptr< io_buf_t > get_outbox_front_buf ()
Get the front item from the outbox if any.
Protected Member Functions inherited from px::asio::CIoActor
void remove ()
This method is called when an actor wants to remove itself from the I/O management interface.
Protected Attributes
io_buf_t _rbuf
I/O buffer used for reading message data.
size_t _offset
Current offset in _rbuf, i.e.
std::shared_ptr< CProtocolHandler > _prot
Protocol-specific handler, used to parse and handle incoming requests and generate responses.
std::queue< std::shared_ptr
< io_buf_t > > _outbox
Queues the outgoing data to send.
Protected Attributes inherited from px::asio::CIoActor
CIoManager & _owner
The I/O manager object that "owns" this connection.
Private Member Functions
void write_outbox ()
Write the first item from the outbox if not empty.
Private Attributes
bool _read_in_progress
Indicates that an async read is in progress.
bool _write_in_progress
Indicates that an async write is in progress.
bool _read_handle_parse_error
Indicates that an asyn read has failed while parse_request in CModbusProtocolHandler due to "Zero length in request" from CModbusTcpAdu::parse.
Detailed Description
The abstract I/O "Messenger" class that will be implemented in the TCP and UDP connection classes.
An I/O messenger (CIoTransactor or descendant) is a special kind of actor: one that can receive external messages and service them. Not all actors are messengers; for example, signal handlers, timers, or TCP listening sockets don't actually do anything directly in response to external input. But things like established TCP or UDP connections handle input directly, and therefore share this same "messenger" interface.
One of the important features of these Transactors is the use of the outbox message queue; the outbox contains an array of pending message buffers, which are sent one at a time, and in order. After a message has been sent, it is cleared from this queue.
Definition at line 32 of file io_transactor.hpp.
Constructor & Destructor Documentation
px::asio::CIoTransactor::CIoTransactor (CIoManager & manager, const CProtocolHandler & prot)
Constructor.
Parameters
manager The I/O manager object to which this object is to be bound
prot The Protocol Handler to be used by this messenger. The Protocol Handler instance will be cloned and the clone stored in this object.
Exceptions
boost::system::system_error The messenger could not be initialized
Definition at line 14 of file io_transactor.cpp.
References _rbuf.
px::asio::CIoTransactor::~CIoTransactor () virtual
Destructor.
Definition at line 31 of file io_transactor.cpp.
References _prot, close(), and LIBPX_FERR.
Member Function Documentation
void px::asio::CIoTransactor::start ()
Kick-start the messenger by waiting for incoming data.
Definition at line 52 of file io_transactor.cpp.
References _offset, _prot, _rbuf, _read_in_progress, _write_in_progress, read_more(), and started.
Referenced by px::asio::CUdpListener::CUdpListener(), px::asio::CUdpSender::CUdpSender(), px::asio::CUdsDgramListener::CUdsDgramListener(), and px::asio::CTcpSslConnection::handle_handshake().
iobuf_const_pair_t px::asio::CIoTransactor::get_rbuf ()
Get the currently-read message boundaries.
Returns
Iterators to the beginning & end of the buffer
Definition at line 73 of file io_transactor.cpp.
References _offset, _prot, _rbuf, and LIBPX_ERR.
void px::asio::CIoTransactor::clear_rbuf (iobuf_const_iter_t end)
Clear (perhaps only partially) the read-buffer contents after servicing a single request.
Parameters
end Iterator to the point in the buffer to which we should erase its contents
Definition at line 91 of file io_transactor.cpp.
References _offset, _prot, _rbuf, and LIBPX_ERR.
bool px::asio::CIoTransactor::get_parse_success ()
Returns
False if "Error encountered while parsing ADU"
Definition at line 132 of file io_transactor.cpp.
References _read_handle_parse_error.
Referenced by parse().
void px::asio::CIoTransactor::set_parse_failed (bool val)
Parameters
val set as True after handling error "Error encountered while parsing ADU"
Definition at line 140 of file io_transactor.cpp.
References _read_handle_parse_error.
Referenced by parse().
virtual void px::asio::CIoTransactor::read_more () pure virtual
Read more data from the messenger's input source.
This call initiates an asynchronous read operation, filling _rbuf (starting at _offset) with any additional data that can be read.
Implemented in px::asio::CUdpListener, px::asio::CUdpSender, px::asio::CTcpSslConnection, px::asio::CUdsDgramListener, px::asio::CTcpConnection, and px::asio::CUdsConnection.
Referenced by handle_write(), parse(), and start().
virtual PUBLIC const std::string px::asio::CIoTransactor::source () pure virtual
Get text describing the source of a message (eg, dotted IP address).
Returns
Description or name of the source of this message.
Implemented in px::asio::CUdpListener, px::asio::CUdsDgramListener, px::asio::CUdpSender, px::asio::CTcpSslConnection, px::asio::CTcpConnection, and px::asio::CUdsConnection.
virtual PUBLIC uint16_t px::asio::CIoTransactor::source_port () virtual
Get port number of the source of a message (0 if N/A).
Returns
Port number of the source of this message.
Reimplemented in px::asio::CTcpSslConnection, and px::asio::CTcpConnection.
Definition at line 115 of file io_transactor.hpp.
void px::asio::CIoTransactor::write (std::shared_ptr< io_buf_t > pbuf) virtual
Write data to the messenger's output channel's outbox.
This call queues the buffer to the outbox, which will eventually be sent to the asio channel asynchronously. Most implementations will use this class' version of this function, but it can be overridden.
Parameters
pbuf The buffer of IO data to be written (ie, the message)/ Must not be null.
Reimplemented in px::asio::CUdpListener.
Definition at line 229 of file io_transactor.cpp.
References _outbox, LIBPX_WARN, px::size, and write_outbox().
Referenced by px::asio::CUdpSender::broadcast(), px::asio::CUdpSender::send(), and px::asio::CUdpListener::write().
void px::asio::CIoTransactor::close () virtual
Gracefully close this actor.
This will gracefully close the actor. It is called automatically by the actor's destructor, but any resulting error information will be lost in that case.
Exceptions
boost::system::system_error There was an error when attempting to gracefully shut down / close
Reimplemented from px::asio::CIoActor.
Reimplemented in px::asio::CUdpListener, px::asio::CTcpSslConnection, px::asio::CUdpSender, px::asio::CUdsDgramListener, px::asio::CTcpConnection, and px::asio::CUdsConnection.
Definition at line 148 of file io_transactor.cpp.
References clear_outbox(), and started.
Referenced by ~CIoTransactor().
void px::asio::CIoTransactor::handle_read (const boost::system::error_code & err, size_t bytes_transferred) protected
Callback function to handle incoming data.
Parameters
err The error code associated with this read operation
bytes_transferred The number of bytes read by the messenger
Definition at line 169 of file io_transactor.cpp.
References _offset, _rbuf, _read_in_progress, _write_in_progress, LIBPX_DEBUG, LIBPX_ERR, LIBPX_FERR, and parse().
Referenced by px::asio::CUdsDgramListener::on_read(), px::asio::CUdpListener::on_read(), px::asio::CUdsConnection::read_more(), px::asio::CTcpConnection::read_more(), and px::asio::CTcpSslConnection::read_more().
void px::asio::CIoTransactor::handle_write (const boost::system::error_code & err, size_t bytes_transferred) protected
Callback function to handle a completed "write" operation.
Parameters
err The error code associated with this write operation
bytes_transferred The number of bytes written by the messenger
Definition at line 268 of file io_transactor.cpp.
References _offset, _outbox, _read_in_progress, _write_in_progress, LIBPX_DBGDUMP, LIBPX_DEBUG, LIBPX_FERR, LIBPX_WARN, parse(), read_more(), and write_outbox().
Referenced by px::asio::CUdsDgramListener::on_write(), px::asio::CUdpSender::on_write(), px::asio::CUdpListener::on_write(), px::asio::CUdsConnection::write_more(), px::asio::CTcpConnection::write_more(), and px::asio::CTcpSslConnection::write_more().
void px::asio::CIoTransactor::parse () protected
Attempt to parse the currently-read data in the buffer.
Definition at line 342 of file io_transactor.cpp.
References _offset, _prot, _rbuf, _read_in_progress, _write_in_progress, get_parse_success(), LIBPX_DBGDUMP, LIBPX_DEBUG, LIBPX_ERR, LIBPX_FERR, read_more(), and set_parse_failed().
Referenced by handle_read(), and handle_write().
virtual void px::asio::CIoTransactor::write_more (const std::shared_ptr< io_buf_t > & pbuf) protected pure virtual
Write the data from the outbox to the service.
Implemented in px::asio::CUdpListener, px::asio::CUdpSender, px::asio::CTcpSslConnection, px::asio::CUdsDgramListener, px::asio::CTcpConnection, and px::asio::CUdsConnection.
Referenced by write_outbox().
void px::asio::CIoTransactor::clear_outbox () protected
Clear the outbox queue.
Definition at line 155 of file io_transactor.cpp.
References _outbox.
Referenced by close().
std::shared_ptr<io_buf_t> px::asio::CIoTransactor::get_outbox_front_buf () protected
Get the front item from the outbox if any.
Returns
the front buffer from the outbox.
Definition at line 188 of file io_transactor.hpp.
void px::asio::CIoTransactor::write_outbox () private
Write the first item from the outbox if not empty.
Definition at line 253 of file io_transactor.cpp.
References _outbox, _write_in_progress, and write_more().
Referenced by handle_write(), and write().
Member Data Documentation
bool px::asio::CIoTransactor::started
True if start() has been called This can be used to distinguish e.g.
a TCP connection that's just waiting for the next accept vs. one that's connected to an endpoint.
Definition at line 141 of file io_transactor.hpp.
Referenced by close(), and start().
io_buf_t px::asio::CIoTransactor::_rbuf protected
I/O buffer used for reading message data.
Definition at line 200 of file io_transactor.hpp.
Referenced by CIoTransactor(), clear_rbuf(), get_rbuf(), handle_read(), px::asio::CUdsDgramListener::on_read(), parse(), px::asio::CUdsConnection::read_more(), px::asio::CTcpConnection::read_more(), px::asio::CUdsDgramListener::read_more(), px::asio::CTcpSslConnection::read_more(), px::asio::CUdpListener::read_more(), px::asio::CUdpListener::read_with_msgs(), and start().
size_t px::asio::CIoTransactor::_offset protected
Current offset in _rbuf, i.e.
the number of valid bytes
Definition at line 205 of file io_transactor.hpp.
Referenced by clear_rbuf(), get_rbuf(), handle_read(), handle_write(), px::asio::CUdsDgramListener::on_read(), parse(), px::asio::CUdsConnection::read_more(), px::asio::CTcpConnection::read_more(), px::asio::CUdsDgramListener::read_more(), px::asio::CTcpSslConnection::read_more(), px::asio::CUdpListener::read_more(), px::asio::CUdpListener::read_with_msgs(), and start().
std::shared_ptr<CProtocolHandler> px::asio::CIoTransactor::_prot protected
Protocol-specific handler, used to parse and handle incoming requests and generate responses.
Definition at line 211 of file io_transactor.hpp.
Referenced by clear_rbuf(), get_rbuf(), parse(), start(), and ~CIoTransactor().
std::queue<std::shared_ptr<io_buf_t> > px::asio::CIoTransactor::_outbox protected
Queues the outgoing data to send.
This queue is designed to solve the I/O interleaving problem.
Definition at line 217 of file io_transactor.hpp.
Referenced by clear_outbox(), handle_write(), px::asio::CUdpListener::on_write(), write(), and write_outbox().
bool px::asio::CIoTransactor::_read_in_progress private
Indicates that an async read is in progress.
This flag is designed to avoid the I/O interleaving problem.
Definition at line 229 of file io_transactor.hpp.
Referenced by handle_read(), handle_write(), parse(), and start().
bool px::asio::CIoTransactor::_write_in_progress private
Indicates that an async write is in progress.
This flag is designed to avoid the I/O interleaving problem.
Definition at line 235 of file io_transactor.hpp.
Referenced by handle_read(), handle_write(), parse(), start(), and write_outbox().
bool px::asio::CIoTransactor::_read_handle_parse_error private
Indicates that an asyn read has failed while parse_request in CModbusProtocolHandler due to "Zero length in request" from CModbusTcpAdu::parse.
This error leads to fd leak while modbus fuzz test beacuse of not closing the connection. This flag used to close the connection.
Definition at line 243 of file io_transactor.hpp.
Referenced by get_parse_success(), and set_parse_failed().
The documentation for this class was generated from the following files:
io_transactor.hpp
io_transactor.cpp