libpx: px::asio::CCdsConnection Class Reference
px::asio::CCdsConnection Class Reference
ASIO interface details and general IO functions. | IO_Actors
CDS I/O actor which listens for CDS notifications.
#include <cds_connection.hpp>
Public Member Functions
PUBLIC CCdsConnection (CIoManager &manager)
Constructor.
virtual PUBLIC ~CCdsConnection ()
Default destructor, a virtual.
virtual PUBLIC void close ()
Gracefully close this actor.
Public Member Functions inherited from px::asio::CIoActor
CIoActor (CIoManager &manager)
Constructor.
virtual ~CIoActor ()
Destructor.
boost::asio::io_service & get_io_service () const
Get the I/O service associated with the owner of this actor.
PUBLIC CServerCore & get_server_core () const
Get the container for CDS data management.
PUBLIC CCdsHandler & get_cds_handler () const
Get the container for CDS data management.
PUBLIC bool get_quit_status ()
Get the quit status from connection IO manager.
Static Public Member Functions
static PUBLIC std::shared_ptr
< CIoActor > create (CIoManager &manager)
Factory function.
Private Attributes
std::unique_ptr
< boost::asio::io_service::work > _work
Used as a placeholder to keep this actor registered with the owning I/O service.
std::shared_ptr
< CCdsConnectionCallback > _callback
A small Callback handler used internally for handling responses to subscribe() calls.
Additional Inherited Members
Protected Member Functions inherited from px::asio::CIoActor
void remove ()
This method is called when an actor wants to remove itself from the I/O management interface.
Protected Attributes inherited from px::asio::CIoActor
CIoManager & _owner
The I/O manager object that "owns" this connection.
Detailed Description
CDS I/O actor which listens for CDS notifications.
This actor is custom (not based on one of the out-of-the-box Boost.Asio I/O object types). It is designed to signal the main I/O service and cause a handler to be invoked when there are responses ready to be read from the CDS.
Definition at line 34 of file cds_connection.hpp.
Constructor & Destructor Documentation
px::asio::CCdsConnection::CCdsConnection (CIoManager & manager)
Constructor.
Parameters
manager The I/O manager object to which this object is to be bound
Exceptions
px::generic_err The actor could not be initialized CDS
boost::system::system_error The actor could not be initialized
Definition at line 30 of file cds_connection.cpp.
References _callback, CALLBACK_NONE, px::cds::CClient::connect(), px::cds::CClient::get(), px::asio::CIoActor::get_cds_handler(), px::asio::CCdsHandler::handle, LIBPX_INFO, px::cds::CClient::register_callback(), px::cds::CClient::register_unsolicited_callback(), and px::cds::CClient::unregister_unsolicited_callback().
Referenced by create().
px::asio::CCdsConnection::~CCdsConnection () virtual
Default destructor, a virtual.
Needed when derived classes are freed or memory leak will occur.
Definition at line 63 of file cds_connection.cpp.
Member Function Documentation
std::shared_ptr< CIoActor > px::asio::CCdsConnection::create (CIoManager & manager) static
Factory function.
This call creates a new CCdsConnection object
Parameters
manager The I/O manager object to which this object is to be bound
Exceptions
boost::system::system_error The signal handler could not be initialized
Definition at line 19 of file cds_connection.cpp.
References CCdsConnection().
Referenced by px::asio::CIoManager::CIoManager().
void px::asio::CCdsConnection::close () virtual
Gracefully close this actor.
This will gracefully close the actor. It is called automatically by the actor's destructor, but any resulting error information will be lost in that case.
Exceptions
boost::system::system_error There was an error when attempting to gracefully shut down / close
Reimplemented from px::asio::CIoActor.
Definition at line 71 of file cds_connection.cpp.
References _work.
Member Data Documentation
std::unique_ptr<boost::asio::io_service::work> px::asio::CCdsConnection::_work private
Used as a placeholder to keep this actor registered with the owning I/O service.
Definition at line 102 of file cds_connection.hpp.
Referenced by close().
std::shared_ptr<CCdsConnectionCallback> px::asio::CCdsConnection::_callback private
A small Callback handler used internally for handling responses to subscribe() calls.
Definition at line 107 of file cds_connection.hpp.
Referenced by CCdsConnection().
The documentation for this class was generated from the following files:
cds_connection.hpp
cds_connection.cpp