libpx: px::db::CLevelDBLogger Class Reference
px::db::CLevelDBLogger Class Reference
Implement a log-file handler for LevelDB that limits the logs to a fixed size, rotating as necessary.
#include <leveldb_logger.hpp>
Public Member Functions
CLevelDBLogger (const px::string &dir)
Public Member Functions.
virtual ~CLevelDBLogger ()
Destructor.
virtual void Logv (const char *format, va_list ap)
Write a message to the log.
Static Public Attributes
static constexpr const off_t max_size = 16777216
Public Constants.
static constexpr const char * current_file_name = "LOG"
Current file name.
static constexpr const char * prev_file_name = "LOG.old"
Previous file name.
static constexpr const size_t max_message = 4096
Max size of a log message.
static constexpr const size_t max_time_size = 48
Max size of time prefix.
Private Member Functions
void check_and_rotate ()
Private Member Functions.
void log_str (const char *str,...)
Log a format string and parameters.
Private Attributes
px::string _path
Private Data Members.
int _fd
Descriptor of current log file.
std::mutex _mutex
Mutex to make sure writes don't overlap with each other or with rotations.
char _buf [max_message]
Static buffer to log into.
char _time_buf [max_time_size]
Static buffer for current time.
Detailed Description
Implement a log-file handler for LevelDB that limits the logs to a fixed size, rotating as necessary.
Definition at line 17 of file leveldb_logger.hpp.
Constructor & Destructor Documentation
px::db::CLevelDBLogger::CLevelDBLogger (const px::string & dir)
Public Member Functions.
Constructor
Parameters
dir Directory log files are placed into. Should be the same as the LevelDB directory.
Definition at line 61 of file leveldb_logger.cpp.
References _buf, _path, _time_buf, check_and_rotate(), LIBPX_DEBUG, log_str(), max_message, max_size, max_time_size, prev_file_name, and unlikely.
px::db::CLevelDBLogger::~CLevelDBLogger () virtual
Destructor.
Definition at line 92 of file leveldb_logger.cpp.
Member Function Documentation
void px::db::CLevelDBLogger::Logv (const char * format, va_list ap) virtual
Write a message to the log.
Definition at line 100 of file leveldb_logger.cpp.
References get_tid(), LIBPX_ERR, likely, px::CWallTime::now(), and unlikely.
void px::db::CLevelDBLogger::check_and_rotate () private
Private Member Functions.
Check the log size, rotate if needed
Definition at line 20 of file leveldb_logger.cpp.
References _fd, _path, current_file_name, LIBPX_DEBUG, LIBPX_ERR, LIBPX_WARN, max_size, and prev_file_name.
Referenced by CLevelDBLogger().
void px::db::CLevelDBLogger::log_str (const char * str, ...) private
Log a format string and parameters.
Definition at line 154 of file leveldb_logger.cpp.
Referenced by CLevelDBLogger().
Member Data Documentation
constexpr const off_t px::db::CLevelDBLogger::max_size = 16777216 static
Public Constants.
Max size for a log file, rotated thereafter
Definition at line 49 of file leveldb_logger.hpp.
Referenced by check_and_rotate(), and CLevelDBLogger().
constexpr const char* px::db::CLevelDBLogger::current_file_name = "LOG" static
Current file name.
Definition at line 54 of file leveldb_logger.hpp.
Referenced by check_and_rotate().
constexpr const char* px::db::CLevelDBLogger::prev_file_name = "LOG.old" static
Previous file name.
Definition at line 59 of file leveldb_logger.hpp.
Referenced by check_and_rotate(), and CLevelDBLogger().
constexpr const size_t px::db::CLevelDBLogger::max_message = 4096 static
Max size of a log message.
Definition at line 64 of file leveldb_logger.hpp.
Referenced by CLevelDBLogger().
constexpr const size_t px::db::CLevelDBLogger::max_time_size = 48 static
Max size of time prefix.
Definition at line 69 of file leveldb_logger.hpp.
Referenced by CLevelDBLogger().
px::string px::db::CLevelDBLogger::_path private
Private Data Members.
Directory path to log into
Definition at line 93 of file leveldb_logger.hpp.
Referenced by check_and_rotate(), and CLevelDBLogger().
int px::db::CLevelDBLogger::_fd private
Descriptor of current log file.
Definition at line 98 of file leveldb_logger.hpp.
Referenced by check_and_rotate().
std::mutex px::db::CLevelDBLogger::_mutex mutable private
Mutex to make sure writes don't overlap with each other or with rotations.
Definition at line 104 of file leveldb_logger.hpp.
char px::db::CLevelDBLogger::_buf[max_message] private
Static buffer to log into.
Definition at line 109 of file leveldb_logger.hpp.
Referenced by CLevelDBLogger().
char px::db::CLevelDBLogger::_time_buf[max_time_size] private
Static buffer for current time.
Definition at line 114 of file leveldb_logger.hpp.
Referenced by CLevelDBLogger().
The documentation for this class was generated from the following files:
leveldb_logger.hpp
leveldb_logger.cpp