libpx: px::cds Namespace Reference
px::cds Namespace Reference
px::cds is the namespace for all the classes that provide the object types and client and server functions for Power Xpert Toolkit applications to communicate with its Core Data Store (cds).
Classes
class CAckSingleAlarm
Data necessary to ack a single active alarm, given its ID.
class CAckDeviceAlarms
Data necessary to ack all active alarms on a device or tree thereof.
class CAckAlarms
Acknowledge alarms.
class CCdsDataInterface
class CCheckSession
Check a session token for validity, and return the permissions granted to it.
class CClearOOBData
Erase OOB data items.
class CClearWatchdog
Undoes the effect of CRegisterWatchdog.
class CCallback
The abstract Callback prototype for CDS responses.
class CClient
Singleton class to manage a connection to the CDS, from client side.
class CCreateSingleChannel
Represents a single channel-creation request.
class CCreateChannel
Create one or more channels.
class CCreateDevice
Create one or more devices.
class CDeleteAlarms
Delete a list of alarms.
class CDeleteChannel
Delete a list of channels.
class CDeleteDevice
Delete a list of devices.
class CDeleteRole
Delete a role from the system.
class CDeleteTrends
Delete trend storage by date range and channel ID.
class CDeleteUser
Remove a user from the system.
class CExecuteDeviceCommand
Execute a device command/control operation.
class CExportConfig
Client fills in a file path name, which must be writable by the CDS.
class CExportTrend
Exports data from the trend storage to a CSV file.
class CGetActiveAlarmsIds
Get the IDs for all currently-open alarms.
class CSingleAlarmConfig
Represents a single channel's alarm configuration, with a channel ID and a list of px::CAlarmTrigger objects.
class CGetAlarmConfig
Get the alarm configuration for one or more channels.
class CGetAlarmUpdateGlobalCount
Get the latest alarm update global count that has been used.
class CGetAlarms
Returns alarms updates in the system (active or both active and historical) according to the ANDing of all criteria specified.
class CGetSingleChannel
Structure of a single channel.
class CGetChannel
Get all the CDS's information about a list of channels.
class CGetChannelSettings
Get the current settings for a channel.
class CGetSingleChannelValue
Data returned by CDS for px::Cds::CGetChannelValue.
class CGetChannelValue
Get channels' realtime values and states.
class CGetDevice
Get list of devices from the CDS.
class CGetDeviceCommandResult
Get a device command/control result after execution.
class CGetDeviceCommands
Gets a list of commands supported by a device, put there by px::cds::CSetDeviceCommands.
class CSingleField
Singular get/set field request.
class CGetFieldValue
Get single fields of devices, channels, or commands.
class CGetOOBDataUnit
Encapsulates a unit of OOB data: tag, protobuf object, whether data is present or not The API object will contain a list thereof.
class CGetOOBData
Get the OOB data corresponding to a list of tags.
class CGetOOBTags
Get a list of current OOB tags.
class CGetRole
Get a list of defined roles and/or details about them.
class CGetSubscriptionDetails
Get details (e.g.
class CGetSubscriptionIds
Get existing subscription IDs, for yourself or all clients.
class CGetUserInfo
Get a list of users in the system, and details about them.
class CSingleUserPassword
Represents the password information for a single user.
class CGetUserPassword
Get a user's password hashes.
class CGetUserPolicy
Retrieve global password-management policy, such as expiration and complexity requirements.
class CImportFile
Defines the base class to import a file (such as trends, updates, etc) to the CDS.
class CImportTrend
class CInsertAlarmUpdates
Adds alarm updates in 'requests' directly to the table of alarms, without them needing to be triggered by a change in a channel's value.
class CLevelupTrend
Trigger an immediate trend-cleanup task, that will aggregate and/or delete trend data according to the OOB object tagged "DatabaseSettings".
class CSingleSession
Encaptulates returned information for a single active login session.
class CListSessions
List the current active login sessions in the system.
class CLogin
Log a human user in to the CDS with a username and password.
class CSubsessionLogin
Login a subsession of an existing parent session.
class CCdsClientLogin
Login with the credentials assigned to this process by virtue of its Linux user ID (assigned by "uid_perms" CDS configuration files).
class CLogout
Ends a login session.
class CManageSubscriberIDs
This message is used to add and remove subscription IDs.
class CNotifyCompletion
Return when previously-queued messages have been processed.
class CPingWatchdog
Notifies the CDS that the client is still alive.
class CQueryTrends
Return data from channel trend storage.
class CQuiesceServer
Puts the CDS into an inactive state for a specified time period.
class CRegisterWatchdog
Used to request that the CDS reboot the system if this client does not send any messages to the CDS for some defined amount of time.
class CRequestResponse
All CDS interprocess messages are subclasses of this.
class CServer
Singleton class to manage CDS connections, from server side.
class CServerConnection
Class to manage a single CDS connection from the CDS side.
class CSetAlarmConfig
Set the alarm configuration for a channel or channels.
class CSetSingleChannelState
Describe the requested changes of Realtime State bits for one channel The CDS API object, px::cds::CSetChannelState, will contain a list of objects of this class.
class CSetChannelSelectorState
Describe the requested changes of Realtime State bits for channels covered by one ChannelSelector object.
class CSetChannelState
Change the realtime state of a set of channels.
class CSetDeviceCommandResult
Set a device command/control result after execution.
class CSetDeviceCommands
Sets the list of commands supported by a device, nonpersistently.
class CSetSingleDeviceState
Describe the requested changes of Device State bits for one Device The CDS API object, px::cds::CSetDeviceState, will contain a list of objects of this class.
class CSetDeviceSelectorState
Set state for all devices covered by a DeviceSelector object.
class CSetDeviceState
Change the state of a device or devices.
class CSetFieldValue
Set single fields of devices, channels, or commands.
class CSetOOBDataUnit
Encapsulates a unit of OOB data: tag, data, whether data should be persisted to disk or not The API object will contain a list thereof.
class CSetOOBData
Update OOB data items in the CDS.
class CSetPassword
Change a user's password.
class CSetUserInfo
Create or update users.
class CSetUserPolicy
Configures global password-management policy, such as expiration and complexity requirements, and maximum allowed concurrent login sessions.
class CSignalPipe
Class for catching UNIX signals & delivering them to the main polling loop.
class CSubscribeSingle
Represents a single subscription (or un-subscripton): the (enumerated) type of subscription, the object it applies to, and which subscriber ID is asking (a CDS client can get more than one subscriber ID if it desires, for multiplexing).
class CSubscribe
Manage subscriptions, to get notified when CDS data objects change.
class CSubscriberNotify
Sent, unsolicited, from CDS to clients in response to a subscribed event or change, or a login session ending.
class CTerminateSessions
Force login sessions to log out.
class CUpdateChannelSettingsSingleResponse
Indicates whether a requested channel update succeeded or not.
class CUpdateChannelSettings
Request an update to a channel's settings.
class CUpdateSingleChannelValue
Structure of a single channel value update (channel ID and variadic value).
class CUpdateChannelValue
Update a set of channels' realtime values.
class CUpdateDeviceSingleResponse
Response indicating the status of a device update.
class CUpdateDevice
Request an update to a Device object.
class CUpdateRole
Create or update a role (which assigns permissions to users).
class CUpdateTrends
Unimplemented, do not use.
class CWaveformCaptured
Used by device handlers to notify CDS of a waveform-capture event.
class CSubmitWaitCallback
Typedefs
using response_callback_t = std::function< void(std::shared_ptr< CRequestResponse >)>
The typedef of the standard CDS response callback function.
typedef uint16_t CallbackHandle
Assigned by CDS when callbacks are registered, this identifies where to send responses.
typedef uint16_t ClientID
Used on the server side to identify which client submitted the request.
Enumerations
enum field_message_type {
unknown = 0, field_message_type::device, field_message_type::channel, field_message_type::channel_name,
field_message_type::config, field_message_type::command, field_message_type::channel_value_by_id, field_message_type::channel_value_by_name_group_id,
field_message_type::max_type
}
What type of object are we getting / setting a field of?
enum RequestStatus {
INCOMPLETE = 0, SUCCEEDED, FAILED, QUEUE_FULL,
RESPONSE_TOO_BIG, TIMEOUT, PERMISSION_DENIED, BAD_PARAMETER,
EMPTY_RESULT, NOT_ABLE_TO_EXECUTE
}
Status values.
enum state_op : uint8_t { state_op::op_set_flags = 1, state_op::op_clear_flags, state_op::op_set_all_flags }
Whether to set or clear the given states.
enum persistence { persistence::save_always, persistence::save_if_saved_before, persistence::do_not_save, persistence::clear_saved }
Describes the persistence-to-disk behavior we want from a set operation.
enum password_type : uint8_t { password_type::plain_text = 0, password_type::hash, password_type::htdigest_hash }
Type of password to set.
enum requestresponsetype {
unknown = 0, unknown = 0, request_response, clear_oob_data,
create_channel, create_device, delete_channel, delete_device,
get_alarms, get_active_alarms_ids, get_channel_settings, get_channel_value,
get_device, get_field_value, get_oob_data, set_device_state,
set_field_value, set_oob_data, update_channel_settings, update_channel_value,
update_device, notify_completion, get_oob_tags, set_channel_state,
export_config, subscriber_notify, manage_subscriber_ids, subscribe,
insert_alarm_updates, get_alarm_config, set_alarm_config, ack_alarms,
delete_alarms, get_alarm_update_global_count, get_subscription_ids, get_subscription_details,
query_trends, quiesce_server, ping_watchdog, register_watchdog,
clear_watchdog, update_trends, get_channel, import_trend,
export_trend, delete_trends, set_device_commands, get_device_commands,
execute_device_command, get_device_command_result, set_device_command_result, get_user_info,
set_user_info, set_password, delete_user, levelup,
waveform_captured, login, subsess_login, client_login,
logout, check_session, list_sessions, terminate_sessions,
update_role, delete_role, get_role, get_user_password,
get_user_policy, set_user_policy
}
requestresponsetype enumeration
Functions
PUBLIC void logout_session (CClient *cds_client, const px::string &session_token)
Convenience function to fire-and-forget a CLogout message for the given session.
PUBLIC unsigned int req_pack (const CRequestResponse *req, unsigned char *buf, unsigned int len)
PUBLIC std::shared_ptr
< CRequestResponse > req_unpack (unsigned char *buf, unsigned int len, unsigned int *remaining_len)
PUBLIC px::string req_name (const CRequestResponse *req)
Return the string name of a RequestResponse command.
static requestresponsetype get_request_response_type (const CRequestResponse *req)
Given a CRequestResponse pointer, return the type enumeration value.
Variables
static CClient * g_cdsClient = nullptr
static std::mutex g_cdsClient_mutex
static CServer * g_cdsServer = nullptr
static std::mutex g_cdsServer_mutex
Detailed Description
px::cds is the namespace for all the classes that provide the object types and client and server functions for Power Xpert Toolkit applications to communicate with its Core Data Store (cds).
px::cds contains the CDS API objects - these are passed to and from the CDS using px::cds::CClient::submit() and related functions, to request that the Core Data Store do stuff.
Typedef Documentation
using px::cds::response_callback_t = typedef std::function<void (std::shared_ptr<CRequestResponse>)>
The typedef of the standard CDS response callback function.
The callback function has one argument, a shared pointer to a (derivative of) the CRequestResponse class, containing the response information. The callback has no return (void).
Definition at line 29 of file client.hpp.
typedef uint16_t px::cds::CallbackHandle
Assigned by CDS when callbacks are registered, this identifies where to send responses.
Definition at line 45 of file request_response.hpp.
typedef uint16_t px::cds::ClientID
Used on the server side to identify which client submitted the request.
Definition at line 48 of file request_response.hpp.
Enumeration Type Documentation
enum px::cds::field_message_type strong
What type of object are we getting / setting a field of?
Enumerator
unknown
device
Device.
channel
Channel (by ID)
channel_name
Channel (by canonical_name)
config
OOB object.
command
Execute a parameterless device control command (on set), or get the status of a running command (on get).
channel_value_by_id
Channel value (by channel ID)
channel_value_by_name_group_id
Channel value using parent Device ID and canonical_name.
If this enum is used, then all the Channels added to a CGetFieldValue request must use the same Device ID.
max_type
Definition at line 32 of file get_field_value.hpp.
enum px::cds::RequestStatus
Status values.
Enumerator
INCOMPLETE
Request has not finished processing.
SUCCEEDED
Finished, good.
FAILED
Finished, bad (some kind of Failure)
QUEUE_FULL
Queue too full to fit response. Might work later.
RESPONSE_TOO_BIG
Response is itself too large to fit in an empty queue, it will never succeed.
TIMEOUT
Expiration time has passed.
PERMISSION_DENIED
Client session or user not permitted to do this.
BAD_PARAMETER
Fails due to invalid, missing, or bad parameter.
EMPTY_RESULT
Failed with no results to return, but there should have been.
Normally because input parameters are entirely missing.
NOT_ABLE_TO_EXECUTE
Failed because system or device was too busy or was unable to execute the request for some other reason.
Definition at line 56 of file request_response.hpp.
enum px::cds::state_op : uint8_t strong
Whether to set or clear the given states.
Since no one process is responsible for setting all the Device State bits, probably the first two operations will be the only ones used in practice.
Enumerator
op_set_flags
Turn ON specified state flags, leaving others alone.
op_clear_flags
Turn OFF specified state flags, leaving others alone.
op_set_all_flags
Set device state to exact value given.
Definition at line 22 of file set_device_state.hpp.
enum px::cds::persistence strong
Describes the persistence-to-disk behavior we want from a set operation.
Enumerator
save_always
Unconditionally save to persistent storage.
save_if_saved_before
Save if data for this tag is already persisted.
This is the default.
do_not_save
Do not persist this data, whether this tag is already persisted or not.
clear_saved
Erase any persistent copy of this tag's data (but keep in memory)
Definition at line 19 of file set_oob_data.hpp.
enum px::cds::password_type : uint8_t strong
Type of password to set.
Enumerator
plain_text
Default: plain text.
hash
Hashed.
htdigest_hash
Hashed htdigest-style.
Definition at line 16 of file set_password.hpp.
enum px::cds::requestresponsetype
requestresponsetype enumeration
One unique value for each subclass of CRequestResponse.
Enumerator
unknown
unknown
request_response
clear_oob_data
create_channel
create_device
delete_channel
delete_device
get_alarms
get_active_alarms_ids
get_channel_settings
get_channel_value
get_device
get_field_value
get_oob_data
set_device_state
set_field_value
set_oob_data
update_channel_settings
update_channel_value
update_device
notify_completion
get_oob_tags
set_channel_state
export_config
subscriber_notify
manage_subscriber_ids
subscribe
insert_alarm_updates
get_alarm_config
set_alarm_config
ack_alarms
delete_alarms
get_alarm_update_global_count
get_subscription_ids
get_subscription_details
query_trends
quiesce_server
ping_watchdog
register_watchdog
clear_watchdog
update_trends
get_channel
import_trend
export_trend
delete_trends
set_device_commands
get_device_commands
execute_device_command
get_device_command_result
set_device_command_result
get_user_info
set_user_info
set_password
delete_user
levelup
waveform_captured
login
subsess_login
client_login
logout
check_session
list_sessions
terminate_sessions
update_role
delete_role
get_role
get_user_password
get_user_policy
set_user_policy
Definition at line 18 of file packer.cpp.
Function Documentation
void px::cds::logout_session (CClient * cds_client, const px::string & session_token)
Convenience function to fire-and-forget a CLogout message for the given session.
Parameters
cds_client Pointer to the CDS Client instance for this application. Must not be null. Since not handling a callback for response, the simple Client pointer is sufficient.
session_token The token that the CDS provided to identify the session.
Definition at line 21 of file msg_utils.cpp.
References LIBPX_ERR, px::cds::CRequestResponse::session_token, px::cds::CClient::submit(), and px::generic_err::what().
unsigned int px::cds::req_pack (const CRequestResponse * req, unsigned char * buf, unsigned int len)
Definition at line 1150 of file packer.cpp.
References ack_alarms, check_session, clear_oob_data, clear_watchdog, client_login, create_channel, create_device, delete_alarms, delete_channel, delete_device, delete_role, delete_trends, delete_user, execute_device_command, export_config, export_trend, get_active_alarms_ids, get_alarm_config, get_alarm_update_global_count, get_alarms, get_channel, get_channel_settings, get_channel_value, get_device, get_device_command_result, get_device_commands, get_field_value, get_oob_data, get_oob_tags, get_request_response_type(), get_role, get_subscription_details, get_subscription_ids, get_user_info, get_user_password, get_user_policy, import_trend, insert_alarm_updates, levelup, list_sessions, login, logout, manage_subscriber_ids, notify_completion, ping_watchdog, px::poly_cast(), query_trends, quiesce_server, register_watchdog, request_response, set_alarm_config, set_channel_state, set_device_command_result, set_device_commands, set_device_state, set_field_value, set_oob_data, set_password, set_user_info, set_user_policy, px::serialize::CByteCounter::size(), subscribe, subscriber_notify, subsess_login, terminate_sessions, unknown, unlikely, update_channel_settings, update_channel_value, update_device, update_role, and waveform_captured.
Referenced by px::cds::CServer::send_response(), and px::cds::CClient::submit().
std::shared_ptr< CRequestResponse > px::cds::req_unpack (unsigned char * buf, unsigned int len, unsigned int * remaining_len)
Definition at line 643 of file packer.cpp.
References ack_alarms, check_session, clear_oob_data, clear_watchdog, client_login, create_channel, create_device, delete_alarms, delete_channel, delete_device, delete_role, delete_trends, delete_user, execute_device_command, export_config, export_trend, get_active_alarms_ids, get_alarm_config, get_alarm_update_global_count, get_alarms, get_channel, get_channel_settings, get_channel_value, get_device, get_device_command_result, get_device_commands, get_field_value, get_oob_data, get_oob_tags, get_role, get_subscription_details, get_subscription_ids, get_user_info, get_user_password, get_user_policy, import_trend, insert_alarm_updates, levelup, list_sessions, login, logout, manage_subscriber_ids, notify_completion, ping_watchdog, query_trends, quiesce_server, register_watchdog, request_response, set_alarm_config, set_channel_state, set_device_command_result, set_device_commands, set_device_state, set_field_value, set_oob_data, set_password, set_user_info, set_user_policy, subscribe, subscriber_notify, subsess_login, terminate_sessions, unknown, unlikely, update_channel_settings, update_channel_value, update_device, update_role, and waveform_captured.
Referenced by px::cds::CClient::bg_thread_func(), and px::cds::CServer::get_pending_requests().
px::string px::cds::req_name (const CRequestResponse * req)
Return the string name of a RequestResponse command.
Used for debug and error logging.
Parameters
req Request response. Must not be null.
Definition at line 439 of file packer.cpp.
References ack_alarms, check_session, clear_oob_data, clear_watchdog, create_channel, create_device, delete_alarms, delete_channel, delete_device, delete_role, delete_user, execute_device_command, export_config, export_trend, get_active_alarms_ids, get_alarm_config, get_alarm_update_global_count, get_alarms, get_channel, get_channel_settings, get_channel_value, get_device, get_device_command_result, get_device_commands, get_field_value, get_oob_data, get_oob_tags, get_request_response_type(), get_role, get_subscription_details, get_subscription_ids, get_user_info, get_user_password, get_user_policy, import_trend, insert_alarm_updates, levelup, list_sessions, login, logout, manage_subscriber_ids, notify_completion, ping_watchdog, query_trends, quiesce_server, register_watchdog, request_response, set_alarm_config, set_channel_state, set_device_command_result, set_device_commands, set_device_state, set_field_value, set_oob_data, set_password, set_user_info, set_user_policy, subscribe, subscriber_notify, terminate_sessions, update_channel_settings, update_channel_value, update_device, update_role, and update_trends.
Referenced by px::asio::CCdsSyncIO::check_cds_result().
static requestresponsetype px::cds::get_request_response_type (const CRequestResponse * req) static
Given a CRequestResponse pointer, return the type enumeration value.
Definition at line 95 of file packer.cpp.
References ack_alarms, check_session, clear_oob_data, clear_watchdog, client_login, create_channel, create_device, delete_alarms, delete_channel, delete_device, delete_role, delete_trends, delete_user, execute_device_command, export_config, export_trend, get_active_alarms_ids, get_alarm_config, get_alarm_update_global_count, get_alarms, get_channel, get_channel_settings, get_channel_value, get_device, get_device_command_result, get_device_commands, get_field_value, get_oob_data, get_oob_tags, get_role, get_subscription_details, get_subscription_ids, get_user_info, get_user_password, get_user_policy, import_trend, insert_alarm_updates, levelup, list_sessions, login, logout, manage_subscriber_ids, notify_completion, ping_watchdog, query_trends, quiesce_server, register_watchdog, request_response, set_alarm_config, set_channel_state, set_device_command_result, set_device_commands, set_device_state, set_field_value, set_oob_data, set_password, set_user_info, set_user_policy, subscribe, subscriber_notify, subsess_login, terminate_sessions, unknown, update_channel_settings, update_channel_value, update_device, update_role, and waveform_captured.
Referenced by req_name(), and req_pack().
Variable Documentation
CClient* px::cds::g_cdsClient = nullptr static
Definition at line 28 of file client.cpp.
Referenced by px::cds::CClient::get(), and px::cds::CClient::~CClient().
std::mutex px::cds::g_cdsClient_mutex static
Definition at line 30 of file client.cpp.
Referenced by px::cds::CClient::get(), and px::cds::CClient::~CClient().
CServer* px::cds::g_cdsServer = nullptr static
Definition at line 27 of file server.cpp.
Referenced by px::cds::CServer::get().
std::mutex px::cds::g_cdsServer_mutex static
Definition at line 29 of file server.cpp.
Referenced by px::cds::CServer::get().