libpx: px::cds::CRequestResponse Class Reference
px::cds::CRequestResponse Class Reference
All CDS interprocess messages are subclasses of this.
#include "px/cds/request_response.hpp"
Inherited by px::cds::CAckAlarms, px::cds::CCdsClientLogin, px::cds::CCheckSession, px::cds::CClearOOBData, px::cds::CClearWatchdog, px::cds::CCreateChannel, px::cds::CCreateDevice, px::cds::CDeleteAlarms, px::cds::CDeleteChannel, px::cds::CDeleteDevice, px::cds::CDeleteRole, px::cds::CDeleteTrends, px::cds::CDeleteUser, px::cds::CExecuteDeviceCommand, px::cds::CExportConfig, px::cds::CExportTrend, px::cds::CGetActiveAlarmsIds, px::cds::CGetAlarmConfig, px::cds::CGetAlarms, px::cds::CGetAlarmUpdateGlobalCount, px::cds::CGetChannel, px::cds::CGetChannelSettings, px::cds::CGetChannelValue, px::cds::CGetDevice, px::cds::CGetDeviceCommandResult, px::cds::CGetDeviceCommands, px::cds::CGetFieldValue, px::cds::CGetOOBData, px::cds::CGetOOBTags, px::cds::CGetRole, px::cds::CGetSubscriptionDetails, px::cds::CGetSubscriptionIds, px::cds::CGetUserInfo, px::cds::CGetUserPassword, px::cds::CGetUserPolicy, px::cds::CImportFile, px::cds::CInsertAlarmUpdates, px::cds::CLevelupTrend, px::cds::CListSessions, px::cds::CLogin, px::cds::CLogout, px::cds::CManageSubscriberIDs, px::cds::CNotifyCompletion, px::cds::CPingWatchdog, px::cds::CQueryTrends, px::cds::CQuiesceServer, px::cds::CRegisterWatchdog, px::cds::CSetAlarmConfig, px::cds::CSetChannelState, px::cds::CSetDeviceCommandResult, px::cds::CSetDeviceCommands, px::cds::CSetDeviceState, px::cds::CSetFieldValue, px::cds::CSetOOBData, px::cds::CSetPassword, px::cds::CSetUserInfo, px::cds::CSetUserPolicy, px::cds::CSubscribe, px::cds::CSubscriberNotify, px::cds::CSubsessionLogin, px::cds::CTerminateSessions, px::cds::CUpdateChannelSettings, px::cds::CUpdateChannelValue, px::cds::CUpdateDevice, px::cds::CUpdateRole, px::cds::CUpdateTrends, and px::cds::CWaveformCaptured.
Public Member Functions
CRequestResponse ()
Default constructor.
bool is_subscription ()
True if this response was not in response to any request from this client.
bool is_unsolicited ()
True if this response was not in response to any request from this client.
virtual ~CRequestResponse ()
Destructor must be virtual for proper inheritance.
template<typename Archive >
void serialize (Archive &ar)
virtual void clean ()
PUBLIC const char * get_status_text () const
Return a text representation of 'status', for debugging / log messages.
PUBLIC const char * get_source_appname_text () const
Get the name of the application from 'appName', if available.
PUBLIC const char * get_response_error_text () const
Get the reponse of the error reported in cds Return the respective error string.
Public Attributes
RequestStatus status
Has this request finished CDS processing, and how did it go?
CallbackHandle callback_handle
Which client-side callback do we call when response is ready? Set to one of the special values, or a value returned by px::cds::CClient::register_callback().
uint32_t transaction_id
Set by CDS to the same value returned by px::cds::CClient::submit().
ClientID client_id
Set by CDS for tracking purposes, to remmember to whom to respond.
px::string appName
Requester sets this for tracking purposes.
px::string session_token
Opaque string token to identify with which login session this request is associated.
px::string response_error
Added string to encapsulate any response error and make it available from cds.
px::CMonoTime expiration_time
Cancel this request, returning error RequestStatus::TIMEOUT if not complete by this time.
Detailed Description
All CDS interprocess messages are subclasses of this.
Definition at line 96 of file request_response.hpp.
Constructor & Destructor Documentation
px::cds::CRequestResponse::CRequestResponse ()
Default constructor.
Definition at line 106 of file request_response.hpp.
virtual px::cds::CRequestResponse::~CRequestResponse () virtual
Destructor must be virtual for proper inheritance.
Definition at line 132 of file request_response.hpp.
Member Function Documentation
bool px::cds::CRequestResponse::is_subscription ()
True if this response was not in response to any request from this client.
Definition at line 115 of file request_response.hpp.
References callback_handle, and CALLBACK_SUBSCRIPTION.
bool px::cds::CRequestResponse::is_unsolicited ()
True if this response was not in response to any request from this client.
Definition at line 124 of file request_response.hpp.
References callback_handle, and CALLBACK_UNSOLICITED.
template<typename Archive > void px::cds::CRequestResponse::serialize (Archive & ar)
Definition at line 140 of file request_response.hpp.
References appName, callback_handle, client_id, expiration_time, response_error, session_token, status, and transaction_id.
virtual void px::cds::CRequestResponse::clean () virtual
Reimplemented in px::cds::CGetFieldValue, px::cds::CCdsClientLogin, px::cds::CSubscriberNotify, px::cds::CSetDeviceState, px::cds::CAckAlarms, px::cds::CSubsessionLogin, px::cds::CSetChannelState, px::cds::CSubscribe, px::cds::CSetOOBData, px::cds::CCreateChannel, px::cds::CListSessions, px::cds::CGetOOBData, px::cds::CGetUserPassword, px::cds::CGetChannel, px::cds::CGetChannelValue, px::cds::CUpdateChannelValue, px::cds::CUpdateDevice, px::cds::CUpdateChannelSettings, px::cds::CGetAlarmConfig, px::cds::CGetAlarms, px::cds::CLogin, px::cds::CSetPassword, px::cds::CExportTrend, px::cds::CQueryTrends, px::cds::CExportConfig, px::cds::CSetDeviceCommandResult, px::cds::CGetChannelSettings, px::cds::CManageSubscriberIDs, px::cds::CWaveformCaptured, px::cds::CSetUserInfo, px::cds::CSetAlarmConfig, px::cds::CUpdateRole, px::cds::CDeleteTrends, px::cds::CGetDeviceCommands, px::cds::CGetRole, px::cds::CInsertAlarmUpdates, px::cds::CCheckSession, px::cds::CCreateDevice, px::cds::CSetDeviceCommands, px::cds::CGetDevice, px::cds::CClearOOBData, px::cds::CDeleteDevice, px::cds::CDeleteRole, px::cds::CLevelupTrend, px::cds::CTerminateSessions, px::cds::CDeleteChannel, px::cds::CDeleteUser, px::cds::CGetOOBTags, px::cds::CGetUserInfo, px::cds::CSetFieldValue, px::cds::CUpdateTrends, px::cds::CGetActiveAlarmsIds, px::cds::CGetSubscriptionDetails, px::cds::CSetUserPolicy, px::cds::CGetSubscriptionIds, px::cds::CGetUserPolicy, px::cds::CImportFile, and px::cds::CLogout.
Definition at line 156 of file request_response.hpp.
References appName, response_error, and session_token.
Referenced by px::cds::CLogout::clean(), px::cds::CImportFile::clean(), px::cds::CGetUserPolicy::clean(), px::cds::CGetSubscriptionIds::clean(), px::cds::CGetSubscriptionDetails::clean(), px::cds::CSetUserPolicy::clean(), px::cds::CGetActiveAlarmsIds::clean(), px::cds::CSetFieldValue::clean(), px::cds::CUpdateTrends::clean(), px::cds::CDeleteUser::clean(), px::cds::CGetOOBTags::clean(), px::cds::CDeleteChannel::clean(), px::cds::CGetUserInfo::clean(), px::cds::CDeleteRole::clean(), px::cds::CDeleteDevice::clean(), px::cds::CTerminateSessions::clean(), px::cds::CLevelupTrend::clean(), px::cds::CClearOOBData::clean(), px::cds::CGetDevice::clean(), px::cds::CCreateDevice::clean(), px::cds::CSetDeviceCommands::clean(), px::cds::CCheckSession::clean(), px::cds::CGetDeviceCommands::clean(), px::cds::CGetRole::clean(), px::cds::CInsertAlarmUpdates::clean(), px::cds::CUpdateRole::clean(), px::cds::CSetAlarmConfig::clean(), px::cds::CSetUserInfo::clean(), px::cds::CGetChannelSettings::clean(), px::cds::CManageSubscriberIDs::clean(), px::cds::CWaveformCaptured::clean(), px::cds::CSetDeviceCommandResult::clean(), px::cds::CExportConfig::clean(), px::cds::CQueryTrends::clean(), px::cds::CExportTrend::clean(), px::cds::CSetPassword::clean(), px::cds::CLogin::clean(), px::cds::CGetAlarms::clean(), px::cds::CGetAlarmConfig::clean(), px::cds::CUpdateChannelSettings::clean(), px::cds::CUpdateDevice::clean(), px::cds::CUpdateChannelValue::clean(), px::cds::CGetChannelValue::clean(), px::cds::CGetChannel::clean(), px::cds::CGetOOBData::clean(), px::cds::CGetUserPassword::clean(), px::cds::CListSessions::clean(), px::cds::CCreateChannel::clean(), px::cds::CSetOOBData::clean(), px::cds::CSubscribe::clean(), px::cds::CSetChannelState::clean(), px::cds::CSubsessionLogin::clean(), px::cds::CAckAlarms::clean(), px::cds::CSetDeviceState::clean(), px::cds::CSubscriberNotify::clean(), px::cds::CCdsClientLogin::clean(), and px::cds::CGetFieldValue::clean().
const char * px::cds::CRequestResponse::get_status_text () const
Return a text representation of 'status', for debugging / log messages.
Definition at line 6 of file request_response.cpp.
References px::cds::BAD_PARAMETER, px::cds::EMPTY_RESULT, px::cds::FAILED, px::cds::INCOMPLETE, px::cds::NOT_ABLE_TO_EXECUTE, px::cds::PERMISSION_DENIED, px::cds::QUEUE_FULL, px::cds::RESPONSE_TOO_BIG, status, px::cds::SUCCEEDED, and px::cds::TIMEOUT.
PUBLIC const char* px::cds::CRequestResponse::get_source_appname_text () const
Get the name of the application from 'appName', if available.
Returns
appName given be the request originator
Definition at line 172 of file request_response.hpp.
References appName.
PUBLIC const char* px::cds::CRequestResponse::get_response_error_text () const
Get the reponse of the error reported in cds Return the respective error string.
Definition at line 181 of file request_response.hpp.
References response_error.
Member Data Documentation
RequestStatus px::cds::CRequestResponse::status
Has this request finished CDS processing, and how did it go?
Definition at line 191 of file request_response.hpp.
Referenced by BOOST_AUTO_TEST_CASE(), get_status_text(), serialize(), and px::cds::CClient::submit().
CallbackHandle px::cds::CRequestResponse::callback_handle
Which client-side callback do we call when response is ready? Set to one of the special values, or a value returned by px::cds::CClient::register_callback().
Default is CALLBACK_NONE.
Definition at line 196 of file request_response.hpp.
Referenced by is_subscription(), is_unsolicited(), serialize(), and px::cds::CClient::submit().
uint32_t px::cds::CRequestResponse::transaction_id
Set by CDS to the same value returned by px::cds::CClient::submit().
Can be used by client to disambiguate responses.
Definition at line 200 of file request_response.hpp.
Referenced by serialize(), px::cds::CClient::submit(), and px::cds::CClient::submit_wait().
ClientID px::cds::CRequestResponse::client_id
Set by CDS for tracking purposes, to remmember to whom to respond.
Definition at line 203 of file request_response.hpp.
Referenced by serialize().
px::string px::cds::CRequestResponse::appName
Requester sets this for tracking purposes.
Definition at line 206 of file request_response.hpp.
Referenced by clean(), get_source_appname_text(), and serialize().
px::string px::cds::CRequestResponse::session_token
Opaque string token to identify with which login session this request is associated.
Leave blank or set to the session_token returned in the response to the relevant px::cds::CLogin request. If left blank, CDS authorizes this request with the permissions (if any) associated with the client's Linux user ID.
Definition at line 214 of file request_response.hpp.
Referenced by clean(), px::cds::logout_session(), and serialize().
px::string px::cds::CRequestResponse::response_error
Added string to encapsulate any response error and make it available from cds.
Definition at line 217 of file request_response.hpp.
Referenced by clean(), get_response_error_text(), and serialize().
px::CMonoTime px::cds::CRequestResponse::expiration_time
Cancel this request, returning error RequestStatus::TIMEOUT if not complete by this time.
If the client won't care about the response if it comes after some certain time (e.g. a data server will return a timeout to its client after this time, so no need for CDS to respond after then). Default = never.
Definition at line 225 of file request_response.hpp.
Referenced by serialize().
The documentation for this class was generated from the following files:
request_response.hpp
request_response.cpp