libpx: datatype.h File Reference
datatype.h File Reference
Classes
struct string_struct_t
struct stringpool_t
Macros
#define stringpool ((const char *) &stringpool_contents)
Enumerations
enum {
TOTAL_KEYWORDS = 10, MIN_WORD_LENGTH = 4, MAX_WORD_LENGTH = 6, MIN_HASH_VALUE = 4,
MAX_HASH_VALUE = 21
}
Functions
static unsigned int hash (register const char *str, register unsigned int len)
static struct string_struct_t * in_word_set (register const char *str, register unsigned int len)
Variables
static struct stringpool_t stringpool_contents
static struct string_struct_t wordlist []
Macro Definition Documentation
#define stringpool ((const char *) &stringpool_contents)
Definition at line 143 of file datatype.h.
Referenced by in_word_set(), and px::reverse_lookup().
Enumeration Type Documentation
anonymous enum
Enumerator
TOTAL_KEYWORDS
MIN_WORD_LENGTH
MAX_WORD_LENGTH
MIN_HASH_VALUE
MAX_HASH_VALUE
Definition at line 64 of file datatype.h.
Function Documentation
static unsigned int hash (register const char * str, register unsigned int len) static
Definition at line 82 of file datatype.h.
Referenced by in_word_set(), and uuid_create_sha1_from_name().
static struct string_struct_t* in_word_set (register const char * str, register unsigned int len) static
Definition at line 188 of file datatype.h.
References hash(), MAX_HASH_VALUE, MAX_WORD_LENGTH, MIN_WORD_LENGTH, string_struct_t::offset, and stringpool.
Referenced by px::COverrideLevel::parse(), px::CDeviceRole::parse(), and px::CDataType::parse().
Variable Documentation
struct stringpool_t stringpool_contents static
Initial value:
=
{
        "TIME",
        "FLOAT",
        "DOUBLE",
        "BOOL",
        "INT64",
        "UINT64",
        "INT32",
        "UINT32",
        "STRING",
        "BINARY"
}
Definition at line 130 of file datatype.h.
struct string_struct_t wordlist[] static
Initial value:
=
{
        {-1, px::datatype::invalid}, {-1, px::datatype::invalid},
        {-1, px::datatype::invalid}, {-1, px::datatype::invalid},
        {( int )( long )&( ( struct stringpool_t * )0 )->stringpool_str4, px::datatype::timestamp},
        {( int )( long )&( ( struct stringpool_t * )0 )->stringpool_str5, px::datatype::float32},
        {( int )( long )&( ( struct stringpool_t * )0 )->stringpool_str6, px::datatype::float64},
        {-1, px::datatype::invalid}, {-1, px::datatype::invalid},
        {( int )( long )&( ( struct stringpool_t * )0 )->stringpool_str9, px::datatype::boolean},
        {( int )( long )&( ( struct stringpool_t * )0 )->stringpool_str10, px::datatype::int64},
        {( int )( long )&( ( struct stringpool_t * )0 )->stringpool_str11, px::datatype::uint64},
        {-1, px::datatype::invalid}, {-1, px::datatype::invalid},
        {-1, px::datatype::invalid},
        {( int )( long )&( ( struct stringpool_t * )0 )->stringpool_str15, px::datatype::int32},
        {( int )( long )&( ( struct stringpool_t * )0 )->stringpool_str16, px::datatype::uint32},
        {-1, px::datatype::invalid}, {-1, px::datatype::invalid},
        {-1, px::datatype::invalid},
        {( int )( long )&( ( struct stringpool_t * )0 )->stringpool_str20, px::datatype::string},
        {( int )( long )&( ( struct stringpool_t * )0 )->stringpool_str21, px::datatype::binary}
}
Definition at line 145 of file datatype.h.
Referenced by px::reverse_lookup(), and px::reverse_lookup_idx().