libpx: px::eq Namespace Reference
px::eq Namespace Reference
px::eq is the namespace for the classes that provide equation parsing and evaluation support for Power Xpert Toolkit applications.
Namespaces
detail
Classes
class Callable
class callable_archetype
class Translatable
class translatable_archetype
struct parse_error
Thrown upon encountering a parse error.
class CEquation
Equation class.
class CPxValue
Define a class with all necessary function overloads for performing supported equation operations on a px::CValue object.
class CSimpleVal
Define a class with all necessary function overloads for performing supported operations on a floating-point value.
struct not_found
The get or set failed to find the targeted object.
class CTranslator
A translator class which defines the interface between the user's code and the generic equation code.
class CValueBase
Since equation evaluation is template-based, the value is free to be any type which implements the required interfaces.
class CValArray
Define a class with all necessary function overloads for performing supported operations on an array of values.
Typedefs
typedef CSimpleVal< float > CFloatVal
typedef CSimpleVal< double > CDoubleVal
typedef CSimpleVal< long double > CQuadVal
typedef CTranslator< CFloatVal > CFloatTranslator
typedef CTranslator< CDoubleVal > CDoubleTranslator
typedef CTranslator< CQuadVal > CQuadTranslator
typedef CTranslator< CFloatArray > CFloatArrayTranslator
typedef CTranslator< CDoubleArray > CDoubleArrayTranslator
typedef CTranslator< CQuadArray > CQuadArrayTranslator
typedef CTranslator< CPxValue > CPxValueTranslator
Define a Translator type for px::CValue-based data.
typedef CValArray< CFloatVal > CFloatArray
typedef CValArray< CDoubleVal > CDoubleArray
typedef CValArray< CQuadVal > CQuadArray
Functions
BOOST_CONCEPT_ASSERT ((Callable< callable_archetype<> >))
BOOST_CONCEPT_ASSERT ((Translatable< translatable_archetype<> >))
BOOST_CONCEPT_ASSERT ((Translatable< CPxValue >))
BOOST_CONCEPT_ASSERT ((Translatable< CFloatVal >))
BOOST_CONCEPT_ASSERT ((Translatable< CDoubleVal >))
BOOST_CONCEPT_ASSERT ((Translatable< CQuadVal >))
BOOST_CONCEPT_ASSERT ((Callable< CFloatTranslator >))
BOOST_CONCEPT_ASSERT ((Callable< CDoubleTranslator >))
BOOST_CONCEPT_ASSERT ((Callable< CQuadTranslator >))
BOOST_CONCEPT_ASSERT ((Callable< CFloatArrayTranslator >))
BOOST_CONCEPT_ASSERT ((Callable< CDoubleArrayTranslator >))
BOOST_CONCEPT_ASSERT ((Callable< CQuadArrayTranslator >))
BOOST_CONCEPT_ASSERT ((Callable< CPxValueTranslator >))
BOOST_CONCEPT_ASSERT ((Translatable< CValueBase >))
BOOST_CONCEPT_ASSERT ((Translatable< CFloatArray >))
BOOST_CONCEPT_ASSERT ((Translatable< CDoubleArray >))
BOOST_CONCEPT_ASSERT ((Translatable< CQuadArray >))
Detailed Description
px::eq is the namespace for the classes that provide equation parsing and evaluation support for Power Xpert Toolkit applications.
Typedef Documentation
typedef CSimpleVal<float> px::eq::CFloatVal
Definition at line 372 of file simple_value.hpp.
typedef CSimpleVal<double> px::eq::CDoubleVal
Definition at line 373 of file simple_value.hpp.
typedef CSimpleVal<long double> px::eq::CQuadVal
Definition at line 374 of file simple_value.hpp.
typedef CTranslator<CFloatVal> px::eq::CFloatTranslator
Definition at line 134 of file translator.hpp.
typedef CTranslator<CDoubleVal> px::eq::CDoubleTranslator
Definition at line 135 of file translator.hpp.
typedef CTranslator<CQuadVal> px::eq::CQuadTranslator
Definition at line 136 of file translator.hpp.
typedef CTranslator<CFloatArray> px::eq::CFloatArrayTranslator
Definition at line 146 of file translator.hpp.
typedef CTranslator<CDoubleArray> px::eq::CDoubleArrayTranslator
Definition at line 147 of file translator.hpp.
typedef CTranslator<CQuadArray> px::eq::CQuadArrayTranslator
Definition at line 148 of file translator.hpp.
typedef CTranslator<CPxValue> px::eq::CPxValueTranslator
Define a Translator type for px::CValue-based data.
Definition at line 158 of file translator.hpp.
typedef CValArray<CFloatVal> px::eq::CFloatArray
Definition at line 616 of file value_array.hpp.
typedef CValArray<CDoubleVal> px::eq::CDoubleArray
Definition at line 617 of file value_array.hpp.
typedef CValArray<CQuadVal> px::eq::CQuadArray
Definition at line 618 of file value_array.hpp.
Function Documentation
px::eq::BOOST_CONCEPT_ASSERT ((Callable< callable_archetype<> >))
Referenced by px::eq::Callable< X >::BOOST_CONCEPT_USAGE(), px::eq::CEquation::evaluate(), and px::eq::CEquation::test_evaluate().
px::eq::BOOST_CONCEPT_ASSERT ((Translatable< translatable_archetype<> >))
px::eq::BOOST_CONCEPT_ASSERT ((Translatable< CPxValue >))
px::eq::BOOST_CONCEPT_ASSERT ((Translatable< CFloatVal >))
px::eq::BOOST_CONCEPT_ASSERT ((Translatable< CDoubleVal >))
px::eq::BOOST_CONCEPT_ASSERT ((Translatable< CQuadVal >))
px::eq::BOOST_CONCEPT_ASSERT ((Callable< CFloatTranslator >))
px::eq::BOOST_CONCEPT_ASSERT ((Callable< CDoubleTranslator >))
px::eq::BOOST_CONCEPT_ASSERT ((Callable< CQuadTranslator >))
px::eq::BOOST_CONCEPT_ASSERT ((Callable< CFloatArrayTranslator >))
px::eq::BOOST_CONCEPT_ASSERT ((Callable< CDoubleArrayTranslator >))
px::eq::BOOST_CONCEPT_ASSERT ((Callable< CQuadArrayTranslator >))
px::eq::BOOST_CONCEPT_ASSERT ((Callable< CPxValueTranslator >))
px::eq::BOOST_CONCEPT_ASSERT ((Translatable< CValueBase >))
px::eq::BOOST_CONCEPT_ASSERT ((Translatable< CFloatArray >))
px::eq::BOOST_CONCEPT_ASSERT ((Translatable< CDoubleArray >))
px::eq::BOOST_CONCEPT_ASSERT ((Translatable< CQuadArray >))