libpx: px::CTimestamp Class Reference
px::CTimestamp Class Reference
Wrapper around a "timespec" structure that provides additional useful functionality.
#include "px/type/timestamp.hpp"
Public Member Functions
CTimestamp ()
Constructor.
CTimestamp (time_t time)
Constructor.
CTimestamp & operator= (const char *time)
timeval to_timeval () const
Convert to "struct timeval".
double to_float () const
Convert to a floating-point value.
PUBLIC void normalize ()
Keep signs of sec & sub-sec consistent and within standard range.
px::string gmtime_str () const
Generate a string representation of this timestamp, assuming UTC time.
px::string localtime_str () const
Generate a string representation of this timestamp, assuming local time.
PUBLIC px::string get_time_str (bool is_utc, const char *strftime_format) const
Gets string representation of this timestamp in separate date (e.g.
template<typename Archive >
void serialize (Archive &ar)
PUBLIC void to (px::proto::Timestamp &val) const
Initialize a protobuf Timestamp object from this value.
PUBLIC void from (const px::proto::Timestamp &arg)
Assign this object's value based on a protobuf Timestamp object.
PUBLIC int64_t msec () const
Get the time in milliseconds.
PUBLIC size_t hash () const
Hash function.
Private Types
typedef void(CTimestamp::* unspecified_bool_type)() const
Private Member Functions
void does_not_support_compare () const
PUBLIC px::string time_str (bool is_utc) const
Private Attributes
const char * _str_fmt = "%F %T"
Detailed Description
Wrapper around a "timespec" structure that provides additional useful functionality.
Definition at line 26 of file timestamp.hpp.
Member Typedef Documentation
typedef void(CTimestamp::* px::CTimestamp::unspecified_bool_type)() const private
Definition at line 33 of file timestamp.hpp.
Constructor & Destructor Documentation
px::CTimestamp::CTimestamp ()
Constructor.
The default timestamp constructor creates an invalid timestamp (time_t of -1)
Definition at line 47 of file timestamp.hpp.
px::CTimestamp::CTimestamp (time_t time) explicit
Constructor.
This version constructs a timestamp with 0 sub-seconds from a time_t
Parameters
time The value to use for 'tv_sec'
Definition at line 58 of file timestamp.hpp.
Member Function Documentation
void px::CTimestamp::does_not_support_compare () const private
Definition at line 34 of file timestamp.hpp.
px::CTimestamp & px::CTimestamp::operator= (const char * time)
Definition at line 382 of file timestamp.hpp.
timeval px::CTimestamp::to_timeval () const
Convert to "struct timeval".
Returns
A timeval struct equivalent to this time
Definition at line 392 of file timestamp.hpp.
double px::CTimestamp::to_float () const
Convert to a floating-point value.
Returns
The number of seconds represented by this timestamp
Definition at line 402 of file timestamp.hpp.
Referenced by px::val_impl::as_datatype::operator()().
void px::CTimestamp::normalize ()
Keep signs of sec & sub-sec consistent and within standard range.
Definition at line 44 of file timestamp.cpp.
px::string px::CTimestamp::gmtime_str () const
Generate a string representation of this timestamp, assuming UTC time.
Returns
A string representation of the time
Definition at line 419 of file timestamp.hpp.
References time_str().
Referenced by px::db::ExportTrendBucket(), px::db::ExportTrendStageRow(), and px::val_impl::as_datatype::operator()().
px::string px::CTimestamp::localtime_str () const
Generate a string representation of this timestamp, assuming local time.
Returns
A string representation of the time
Definition at line 428 of file timestamp.hpp.
References time_str().
Referenced by px::asio::CCdsSyncIO::get_device_trend_row().
px::string px::CTimestamp::get_time_str (bool is_utc, const char * strftime_format) const
Gets string representation of this timestamp in separate date (e.g.
1/20/2014) and time (e.g. 14:20:03) fields. The ns information is always skipped. strftime_format must not be null.
Definition at line 142 of file timestamp.cpp.
References unlikely.
Referenced by px::db::DeleteClosedAlarms().
template<typename Archive > void px::CTimestamp::serialize (Archive & ar)
Definition at line 442 of file timestamp.hpp.
void px::CTimestamp::to (px::proto::Timestamp & val) const
Initialize a protobuf Timestamp object from this value.
Parameters
val Object whose fields are initialized based on the current value of *this
Definition at line 73 of file timestamp.cpp.
References px::max.
Referenced by px::db::AddChannelToBatch(), px::db::AddDeviceToBatch(), and px::val_impl::to_protobuf::operator()().
void px::CTimestamp::from (const px::proto::Timestamp & arg)
Assign this object's value based on a protobuf Timestamp object.
This is the inverse of from().
Parameters
arg Object used to initialize this value
Exceptions
generic_err Thrown if the protobuf object is invalid
Returns
*this
Definition at line 82 of file timestamp.cpp.
References unlikely.
Referenced by px::db::FetchChannels().
int64_t px::CTimestamp::msec () const
Get the time in milliseconds.
Returns the timestamp value in milliseconds. This is mainly useful when dealing with elapsed time.
Returns
The timestamp value, in milliseconds
Definition at line 171 of file timestamp.cpp.
size_t px::CTimestamp::hash () const
Hash function.
This call returns a hash value for the underlying timestamp
Returns
A hash value for this object
Definition at line 183 of file timestamp.cpp.
px::string px::CTimestamp::time_str (bool is_utc) const private
Definition at line 108 of file timestamp.cpp.
References unlikely.
Referenced by gmtime_str(), and localtime_str().
Member Data Documentation
const char* px::CTimestamp::_str_fmt = "%F %T" private
Definition at line 515 of file timestamp.hpp.
The documentation for this class was generated from the following files:
timestamp.hpp
timestamp.cpp