libpx: px::db::CNullMask Class Reference
px::db::CNullMask Class Reference
Null mask class.
#include <null_mask.hpp>
Public Member Functions
CNullMask (size_t bit_size)
Constructor.
bool test (size_t pos) const
Test a bit at a position.
void set (size_t pos, bool val=true)
Set a bit at a position.
size_t byte_size () const
Gets the byte size.
void to_buf (unsigned char *buf, const int offset) const
Serialize to a pre-allocated byte buffer with an offset.
void from_buf (unsigned char *buf, const int offset)
Deserialize to a pre-allocated byte buffer with an offset The null mask should be created with the correct size in advance.
void set (const size_t offset, const std::vector< boost::optional< double > > &values, const size_t expected_count)
Sets the null bits (starting from an offset) based on the values.
void set (const size_t offset, const std::vector< boost::optional< std::pair< double, uint16_t > > > &values, const size_t expected_count)
Sets the null bits (starting from an offset) based on the values.
Static Public Member Functions
static size_t get_byte_size (size_t bit_size)
Private Member Functions
void get_bytes_index_from_bit_pos (const size_t pos, size_t &index, size_t &offset) const
Private Attributes
std::vector< unsigned char > _mask
Internal buffer used to store the bits.
size_t _bit_size
Detailed Description
Null mask class.
A null mask (an array of bits) to indicate the null in the array of values.
Definition at line 17 of file null_mask.hpp.
Constructor & Destructor Documentation
px::db::CNullMask::CNullMask (size_t bit_size)
Constructor.
Definition at line 7 of file null_mask.cpp.
References _bit_size, _mask, and get_byte_size().
Member Function Documentation
bool px::db::CNullMask::test (size_t pos) const
Test a bit at a position.
Definition at line 16 of file null_mask.cpp.
void px::db::CNullMask::set (size_t pos, bool val = true)
Set a bit at a position.
Definition at line 31 of file null_mask.cpp.
Referenced by px::db::AddTrendBucketToBatch().
size_t px::db::CNullMask::byte_size () const
Gets the byte size.
Definition at line 42 of file null_mask.hpp.
References _mask.
Referenced by px::db::AddTrendBucketToBatch().
void px::db::CNullMask::to_buf (unsigned char * buf, const int offset) const
Serialize to a pre-allocated byte buffer with an offset.
Definition at line 50 of file null_mask.hpp.
References _mask, and px::size.
Referenced by px::db::AddTrendBucketToBatch().
void px::db::CNullMask::from_buf (unsigned char * buf, const int offset)
Deserialize to a pre-allocated byte buffer with an offset The null mask should be created with the correct size in advance.
Definition at line 64 of file null_mask.hpp.
References _mask, and px::size.
void px::db::CNullMask::set (const size_t offset, const std::vector< boost::optional< double > > & values, const size_t expected_count)
Sets the null bits (starting from an offset) based on the values.
Definition at line 54 of file null_mask.cpp.
void px::db::CNullMask::set (const size_t offset, const std::vector< boost::optional< std::pair< double, uint16_t > > > & values, const size_t expected_count)
Sets the null bits (starting from an offset) based on the values.
Definition at line 86 of file null_mask.cpp.
static size_t px::db::CNullMask::get_byte_size (size_t bit_size) static
Definition at line 88 of file null_mask.hpp.
Referenced by px::db::AddTrendBucketToBatch(), CNullMask(), and px::db::ReadTrendsFromBucketRow().
void px::db::CNullMask::get_bytes_index_from_bit_pos (const size_t pos, size_t & index, size_t & offset) const private
Definition at line 95 of file null_mask.hpp.
Member Data Documentation
std::vector<unsigned char> px::db::CNullMask::_mask private
Internal buffer used to store the bits.
The lower bit maps to the lower index in the array of values; the lower bytes maps to the lower index in the array of values.
Definition at line 111 of file null_mask.hpp.
Referenced by byte_size(), CNullMask(), from_buf(), and to_buf().
size_t px::db::CNullMask::_bit_size private
Definition at line 113 of file null_mask.hpp.
Referenced by CNullMask().
The documentation for this class was generated from the following files:
null_mask.hpp
null_mask.cpp