libpx: px::serialize Namespace Reference
px::serialize Namespace Reference
px::serialize is the namespace for the classes that provide serialization/deserialization support for Power Xpert Toolkit applications.
Classes
class CDynamicArchive
Dynamic, self-sizing data archive.
class CRawArchive
High-performance "raw" data archive.
class CByteCounter
Byte counter class.
class CDeserializer
De-Serializer object.
class CSerializer
Serializer object.
struct variant_save_visitor
Utility class to save a variant's value.
struct variant_loader
Utility class to load a variant's value.
Functions
template<class Archive , typename T , size_t N>
static void save (Archive &ar, const std::array< T, N > &val)
Output function for a std::array.
template<class Archive , typename T , size_t N>
static void load (Archive &ar, std::array< T, N > &val)
Input function for a std::array.
template<class Archive , typename T >
static void save (Archive &ar, const T &val, __REQUIRE(std::is_arithmetic< T >::value||std::is_enum< T >::value))
Output function for trivial types (integral, floats, enums, etc.)
template<class Archive , typename T >
static void load (Archive &ar, T &val, __REQUIRE(std::is_arithmetic< T >::value||std::is_enum< T >::value))
Input function for trivial types (integral, floats, enums, etc.)
template<class Archive , typename T >
static void save (Archive &ar, const T &val, __REQUIRE(!std::is_arithmetic< T >::value &&!std::is_enum< T >::value), __REQUIRE(__HAS_SAVE(T, Archive)))
Output function for non-trivial types.
template<class Archive , typename T >
static void save (Archive &ar, const T &val, __REQUIRE(!std::is_arithmetic< T >::value &&!std::is_enum< T >::value), __REQUIRE(!__HAS_SAVE(T, Archive)))
Output function for non-trivial types.
template<class Archive , typename T >
static void load (Archive &ar, T &val, __REQUIRE(!std::is_arithmetic< T >::value &&!std::is_enum< T >::value), __REQUIRE(__HAS_LOAD(T, Archive)))
Input function for non-trivial types.
template<class Archive , typename T >
static void load (Archive &ar, T &val, __REQUIRE(!std::is_arithmetic< T >::value &&!std::is_enum< T >::value), __REQUIRE(!__HAS_LOAD(T, Archive)))
Input function for non-trivial types.
template<class Archive , typename T >
static void save (Archive &ar, const std::deque< T > &val)
Output function for a std::deque.
template<class Archive , typename T >
static void load (Archive &ar, std::deque< T > &val)
Input function for a std::deque.
template<class Archive , typename T , typename... Params>
static void save (Archive &ar, const boost::flyweight< T, Params...> &val)
Output function for a boost::flyweight.
template<class Archive , typename T , typename... Params>
static void load (Archive &ar, boost::flyweight< T, Params...> &val)
Input function for a boost::flyweight.
template<class Archive , typename T >
static void save (Archive &ar, const std::list< T > &val)
Output function for a std::list.
template<class Archive , typename T >
static void load (Archive &ar, std::list< T > &val)
Input function for a std::list.
template<class Archive , typename T , typename U >
static void save (Archive &ar, const std::map< T, U > &val)
Output function for a std::map.
template<class Archive , typename T , typename U >
static void load (Archive &ar, std::map< T, U > &val)
Input function for a std::map.
template<class Archive , typename T , typename U >
static void save (Archive &ar, const std::multimap< T, U > &val)
Output function for a std::multimap.
template<class Archive , typename T , typename U >
static void load (Archive &ar, std::multimap< T, U > &val)
Input function for a std::multimap.
template<class Archive >
static void save (Archive &ar, const px::proto::toolkitStruct &val)
OOB protobufs go through our serialization process relatively often.
template<class Archive >
static void load (Archive &ar, px::proto::toolkitStruct &val)
template<class Archive , typename T >
static void save (Archive &ar, const boost::optional< T > &val)
Output function for a boost::optional.
template<class Archive , typename T >
static void load (Archive &ar, boost::optional< T > &val)
Input function for a boost::optional.
template<class Archive , typename T , typename U >
static void save (Archive &ar, const std::pair< T, U > &val)
Output function for a std::pair.
template<class Archive , typename T , typename U >
static void load (Archive &ar, std::pair< T, U > &val)
Input function for a std::pair.
template<class Archive >
static void save (Archive &ar, const google::protobuf::MessageLite &val)
Output function for a protobuf object.
template<class Archive >
static void load (Archive &ar, google::protobuf::MessageLite &val)
Input function for a protobuf object.
template<class Archive >
static void save (Archive &ar, const px::string &val)
Output function for a px::string.
template<class Archive >
static void load (Archive &ar, px::string &val)
Input function for a px::string.
template<class Archive , typename T >
static void save (Archive &ar, const std::set< T > &val)
Output function for a std::set.
template<class Archive , typename T >
static void load (Archive &ar, std::set< T > &val)
Input function for a std::set.
template<class Archive , typename T >
static void save (Archive &ar, const std::multiset< T > &val)
Output function for a std::multiset.
template<class Archive , typename T >
static void load (Archive &ar, std::multiset< T > &val)
Input function for a std::multiset.
template<class Archive , typename T >
static void save (Archive &ar, const std::shared_ptr< T > &val)
Output function for a std::unique_ptr.
template<class Archive , typename T >
static void load (Archive &ar, std::shared_ptr< T > &val)
Input function for a std::shared_ptr.
template<class Archive >
static void save (Archive &ar, const std::string &val)
Output function for a std::string.
template<class Archive >
static void load (Archive &ar, std::string &val)
Input function for a std::string.
template<class Archive >
static void save (Archive &ar, const boost::tribool &val)
Output function for a boost::tribool.
template<class Archive >
static void load (Archive &ar, boost::tribool &val)
Input function for a boost::tribool.
template<class Archive , typename T >
static void save (Archive &ar, const std::unique_ptr< T > &val)
Output function for a std::unique_ptr.
template<class Archive , typename T >
static void load (Archive &ar, std::unique_ptr< T > &val)
Input function for a std::unique_ptr.
template<class Archive , typename T , typename U >
static void save (Archive &ar, const std::unordered_map< T, U > &val)
Output function for a std::unordered_map.
template<class Archive , typename T , typename U >
static void load (Archive &ar, std::unordered_map< T, U > &val)
Input function for a std::unordered_map.
template<class Archive , typename T , typename U >
static void save (Archive &ar, const std::unordered_multimap< T, U > &val)
Output function for a std::unordered_multimap.
template<class Archive , typename T , typename U >
static void load (Archive &ar, std::unordered_multimap< T, U > &val)
Input function for a std::unordered_multimap.
template<class Archive , typename T >
static void save (Archive &ar, const std::unordered_set< T > &val)
Output function for a std::unordered_set.
template<class Archive , typename T >
static void load (Archive &ar, std::unordered_set< T > &val)
Input function for a std::unordered_set.
template<class Archive , typename T >
static void save (Archive &ar, const std::unordered_multiset< T > &val)
Output function for a std::unordered_multiset.
template<class Archive , typename T >
static void load (Archive &ar, std::unordered_multiset< T > &val)
Input function for a std::unordered_multiset.
template<class Archive , BOOST_VARIANT_ENUM_PARAMS(typename T) >
static void save (Archive &ar, const boost::variant< BOOST_VARIANT_ENUM_PARAMS(T)> &val)
Output function for a boost::variant.
template<class Archive , BOOST_VARIANT_ENUM_PARAMS(typename T) >
static void load (Archive &ar, boost::variant< BOOST_VARIANT_ENUM_PARAMS(T)> &val)
Input function for a boost::variant.
template<class Archive , typename T >
static void save (Archive &ar, const std::vector< T > &val)
Output function for a std::vector.
template<class Archive , typename T >
static void load (Archive &ar, std::vector< T > &val)
Input function for a std::vector.
Detailed Description
px::serialize is the namespace for the classes that provide serialization/deserialization support for Power Xpert Toolkit applications.
Function Documentation
template<class Archive , typename T , size_t N> static void px::serialize::save (Archive & ar, const std::array< T, N > & val) static
Output function for a std::array.
Parameters
ar The output archive / serializer
val The input value
Definition at line 19 of file array.hpp.
Referenced by px::serialize::CByteCounter::operator&(), px::serialize::CSerializer< Archive >::operator&(), and px::serialize::variant_save_visitor< Archive >::operator()().
template<class Archive , typename T , size_t N> static void px::serialize::load (Archive & ar, std::array< T, N > & val) static
Input function for a std::array.
Parameters
ar The input archive / deserializer
val The output value
Definition at line 35 of file array.hpp.
Referenced by px::serialize::CDeserializer< Archive >::operator&(), and px::serialize::variant_loader< S >::load_type::run().
template<class Archive , typename T > static void px::serialize::save (Archive & ar, const T & val, __REQUIRE(std::is_arithmetic< T >::value||std::is_enum< T >::value)) static
Output function for trivial types (integral, floats, enums, etc.)
Parameters
ar The output archive / serializer
val The input value
Definition at line 62 of file serialization/type/common.hpp.
References px::to_big_endian().
template<class Archive , typename T > static void px::serialize::load (Archive & ar, T & val, __REQUIRE(std::is_arithmetic< T >::value||std::is_enum< T >::value)) static
Input function for trivial types (integral, floats, enums, etc.)
Parameters
ar The input archive / deserializer
val The output value
Definition at line 79 of file serialization/type/common.hpp.
References px::from_big_endian().
template<class Archive , typename T > static void px::serialize::save (Archive & ar, const T & val, __REQUIRE(!std::is_arithmetic< T >::value &&!std::is_enum< T >::value) , __REQUIRE(__HAS_SAVE(T, Archive))) static
Output function for non-trivial types.
This is not one of the types that we specifically know about; therefore we forward to that type's own implementation of save().
Parameters
ar The output archive / serializer
val The input value
Definition at line 100 of file serialization/type/common.hpp.
template<class Archive , typename T > static void px::serialize::save (Archive & ar, const T & val, __REQUIRE(!std::is_arithmetic< T >::value &&!std::is_enum< T >::value) , __REQUIRE(!__HAS_SAVE(T, Archive))) static
Output function for non-trivial types.
This is not one of the types that we specifically know about; therefore we forward to that type's own implementation of serialize(), since there's no save() defined for it.
Parameters
ar The output archive / serializer
val The input value
Definition at line 120 of file serialization/type/common.hpp.
template<class Archive , typename T > static void px::serialize::load (Archive & ar, T & val, __REQUIRE(!std::is_arithmetic< T >::value &&!std::is_enum< T >::value) , __REQUIRE(__HAS_LOAD(T, Archive))) static
Input function for non-trivial types.
This is not one of the types that we specifically know about; therefore we forward to that type's own implementation of load().
Parameters
ar The input archive / deserializer
val The output value
Definition at line 139 of file serialization/type/common.hpp.
template<class Archive , typename T > static void px::serialize::load (Archive & ar, T & val, __REQUIRE(!std::is_arithmetic< T >::value &&!std::is_enum< T >::value) , __REQUIRE(!__HAS_LOAD(T, Archive))) static
Input function for non-trivial types.
This is not one of the types that we specifically know about; therefore we forward to that type's own implementation of serialize(), since there's no load() defined for it.
Parameters
ar The input archive / deserializer
val The output value
Definition at line 159 of file serialization/type/common.hpp.
template<class Archive , typename T > static void px::serialize::save (Archive & ar, const std::deque< T > & val) static
Output function for a std::deque.
Parameters
ar The output archive / serializer
val The input value
Definition at line 19 of file deque.hpp.
template<class Archive , typename T > static void px::serialize::load (Archive & ar, std::deque< T > & val) static
Input function for a std::deque.
Parameters
ar The input archive / deserializer
val The output value
Definition at line 38 of file deque.hpp.
template<class Archive , typename T , typename... Params> static void px::serialize::save (Archive & ar, const boost::flyweight< T, Params...> & val) static
Output function for a boost::flyweight.
Parameters
ar The output archive / serializer
val The input value
Definition at line 19 of file flyweight.hpp.
template<class Archive , typename T , typename... Params> static void px::serialize::load (Archive & ar, boost::flyweight< T, Params...> & val) static
Input function for a boost::flyweight.
Parameters
ar The input archive / deserializer
val The output value
Definition at line 32 of file flyweight.hpp.
template<class Archive , typename T > static void px::serialize::save (Archive & ar, const std::list< T > & val) static
Output function for a std::list.
Parameters
ar The output archive / serializer
val The input value
Definition at line 19 of file list.hpp.
template<class Archive , typename T > static void px::serialize::load (Archive & ar, std::list< T > & val) static
Input function for a std::list.
Parameters
ar The input archive / deserializer
val The output value
Definition at line 39 of file list.hpp.
template<class Archive , typename T , typename U > static void px::serialize::save (Archive & ar, const std::map< T, U > & val) static
Output function for a std::map.
Parameters
ar The output archive / serializer
val The input value
Definition at line 20 of file map.hpp.
template<class Archive , typename T , typename U > static void px::serialize::load (Archive & ar, std::map< T, U > & val) static
Input function for a std::map.
Parameters
ar The input archive / deserializer
val The output value
Definition at line 39 of file map.hpp.
template<class Archive , typename T , typename U > static void px::serialize::save (Archive & ar, const std::multimap< T, U > & val) static
Output function for a std::multimap.
Parameters
ar The output archive / serializer
val The input value
Definition at line 62 of file map.hpp.
template<class Archive , typename T , typename U > static void px::serialize::load (Archive & ar, std::multimap< T, U > & val) static
Input function for a std::multimap.
Parameters
ar The input archive / deserializer
val The output value
Definition at line 81 of file map.hpp.
template<class Archive > static void px::serialize::save (Archive & ar, const px::proto::toolkitStruct & val) static
OOB protobufs go through our serialization process relatively often.
Use the generic protobuf serialization.
Definition at line 16 of file oob.hpp.
References px::poly_cast().
template<class Archive > static void px::serialize::load (Archive & ar, px::proto::toolkitStruct & val) static
Definition at line 22 of file oob.hpp.
References px::poly_cast().
template<class Archive , typename T > static void px::serialize::save (Archive & ar, const boost::optional< T > & val) static
Output function for a boost::optional.
Parameters
ar The output archive / serializer
val The input value
Definition at line 19 of file optional.hpp.
template<class Archive , typename T > static void px::serialize::load (Archive & ar, boost::optional< T > & val) static
Input function for a boost::optional.
Parameters
ar The input archive / deserializer
val The output value
Definition at line 38 of file optional.hpp.
References px::none.
template<class Archive , typename T , typename U > static void px::serialize::save (Archive & ar, const std::pair< T, U > & val) static
Output function for a std::pair.
Parameters
ar The output archive / serializer
val The input value
Definition at line 19 of file pair.hpp.
template<class Archive , typename T , typename U > static void px::serialize::load (Archive & ar, std::pair< T, U > & val) static
Input function for a std::pair.
Parameters
ar The input archive / deserializer
val The output value
Definition at line 33 of file pair.hpp.
template<class Archive > static void px::serialize::save (Archive & ar, const google::protobuf::MessageLite & val) static
Output function for a protobuf object.
Parameters
ar The output archive / serializer
val The input value
Definition at line 19 of file protobuf.hpp.
template<class Archive > static void px::serialize::load (Archive & ar, google::protobuf::MessageLite & val) static
Input function for a protobuf object.
Parameters
ar The input archive / deserializer
val The output value
Definition at line 39 of file protobuf.hpp.
template<class Archive > static void px::serialize::save (Archive & ar, const px::string & val) static
Output function for a px::string.
Parameters
ar The output archive / serializer
val The input value
Definition at line 19 of file px_string.hpp.
template<class Archive > static void px::serialize::load (Archive & ar, px::string & val) static
Input function for a px::string.
Parameters
ar The input archive / deserializer
val The output value
Definition at line 38 of file px_string.hpp.
template<class Archive , typename T > static void px::serialize::save (Archive & ar, const std::set< T > & val) static
Output function for a std::set.
Parameters
ar The output archive / serializer
val The input value
Definition at line 19 of file set.hpp.
template<class Archive , typename T > static void px::serialize::load (Archive & ar, std::set< T > & val) static
Input function for a std::set.
Parameters
ar The input archive / deserializer
val The output value
Definition at line 38 of file set.hpp.
template<class Archive , typename T > static void px::serialize::save (Archive & ar, const std::multiset< T > & val) static
Output function for a std::multiset.
Parameters
ar The output archive / serializer
val The input value
Definition at line 63 of file set.hpp.
template<class Archive , typename T > static void px::serialize::load (Archive & ar, std::multiset< T > & val) static
Input function for a std::multiset.
Parameters
ar The input archive / deserializer
val The output value
Definition at line 82 of file set.hpp.
template<class Archive , typename T > static void px::serialize::save (Archive & ar, const std::shared_ptr< T > & val) static
Output function for a std::unique_ptr.
Parameters
ar The output archive / serializer
val The input value
Definition at line 19 of file shared_ptr.hpp.
template<class Archive , typename T > static void px::serialize::load (Archive & ar, std::shared_ptr< T > & val) static
Input function for a std::shared_ptr.
Parameters
ar The input archive / deserializer
val The output value
Definition at line 38 of file shared_ptr.hpp.
template<class Archive > static void px::serialize::save (Archive & ar, const std::string & val) static
Output function for a std::string.
Parameters
ar The output archive / serializer
val The input value
Definition at line 19 of file serialization/type/string.hpp.
template<class Archive > static void px::serialize::load (Archive & ar, std::string & val) static
Input function for a std::string.
Parameters
ar The input archive / deserializer
val The output value
Definition at line 38 of file serialization/type/string.hpp.
template<class Archive > static void px::serialize::save (Archive & ar, const boost::tribool & val) static
Output function for a boost::tribool.
Parameters
ar The output archive / serializer
val The input value
Definition at line 17 of file tribool.hpp.
template<class Archive > static void px::serialize::load (Archive & ar, boost::tribool & val) static
Input function for a boost::tribool.
Parameters
ar The input archive / serializer
val The output value
Definition at line 41 of file tribool.hpp.
template<class Archive , typename T > static void px::serialize::save (Archive & ar, const std::unique_ptr< T > & val) static
Output function for a std::unique_ptr.
Parameters
ar The output archive / serializer
val The input value
Definition at line 19 of file unique_ptr.hpp.
template<class Archive , typename T > static void px::serialize::load (Archive & ar, std::unique_ptr< T > & val) static
Input function for a std::unique_ptr.
Parameters
ar The input archive / deserializer
val The output value
Definition at line 38 of file unique_ptr.hpp.
template<class Archive , typename T , typename U > static void px::serialize::save (Archive & ar, const std::unordered_map< T, U > & val) static
Output function for a std::unordered_map.
Parameters
ar The output archive / serializer
val The input value
Definition at line 20 of file unordered_map.hpp.
template<class Archive , typename T , typename U > static void px::serialize::load (Archive & ar, std::unordered_map< T, U > & val) static
Input function for a std::unordered_map.
Parameters
ar The input archive / deserializer
val The output value
Definition at line 39 of file unordered_map.hpp.
template<class Archive , typename T , typename U > static void px::serialize::save (Archive & ar, const std::unordered_multimap< T, U > & val) static
Output function for a std::unordered_multimap.
Parameters
ar The output archive / serializer
val The input value
Definition at line 62 of file unordered_map.hpp.
template<class Archive , typename T , typename U > static void px::serialize::load (Archive & ar, std::unordered_multimap< T, U > & val) static
Input function for a std::unordered_multimap.
Parameters
ar The input archive / deserializer
val The output value
Definition at line 81 of file unordered_map.hpp.
template<class Archive , typename T > static void px::serialize::save (Archive & ar, const std::unordered_set< T > & val) static
Output function for a std::unordered_set.
Parameters
ar The output archive / serializer
val The input value
Definition at line 19 of file unordered_set.hpp.
template<class Archive , typename T > static void px::serialize::load (Archive & ar, std::unordered_set< T > & val) static
Input function for a std::unordered_set.
Parameters
ar The input archive / deserializer
val The output value
Definition at line 38 of file unordered_set.hpp.
template<class Archive , typename T > static void px::serialize::save (Archive & ar, const std::unordered_multiset< T > & val) static
Output function for a std::unordered_multiset.
Parameters
ar The output archive / serializer
val The input value
Definition at line 63 of file unordered_set.hpp.
template<class Archive , typename T > static void px::serialize::load (Archive & ar, std::unordered_multiset< T > & val) static
Input function for a std::unordered_multiset.
Parameters
ar The input archive / deserializer
val The output value
Definition at line 82 of file unordered_set.hpp.
template<class Archive , BOOST_VARIANT_ENUM_PARAMS(typename T) > static void px::serialize::save (Archive & ar, const boost::variant< BOOST_VARIANT_ENUM_PARAMS(T)> & val) static
Output function for a boost::variant.
Parameters
ar The output archive / serializer
val The input value
Definition at line 94 of file variant.hpp.
template<class Archive , BOOST_VARIANT_ENUM_PARAMS(typename T) > static void px::serialize::load (Archive & ar, boost::variant< BOOST_VARIANT_ENUM_PARAMS(T)> & val) static
Input function for a boost::variant.
Parameters
ar The input archive / deserializer
val The output value
Definition at line 112 of file variant.hpp.
References px::serialize::variant_loader< S >::doload().
template<class Archive , typename T > static void px::serialize::save (Archive & ar, const std::vector< T > & val) static
Output function for a std::vector.
Parameters
ar The output archive / serializer
val The input value
Definition at line 19 of file vector.hpp.
template<class Archive , typename T > static void px::serialize::load (Archive & ar, std::vector< T > & val) static
Input function for a std::vector.
Parameters
ar The input archive / deserializer
val The output value
Definition at line 38 of file vector.hpp.