libpx: px::asio::CIoUsecTimer Class Reference
px::asio::CIoUsecTimer Class Reference
ASIO interface details and general IO functions.
The I/O Microsecond Timer class for ASIO Actors.
#include <io_usec_timer.hpp>
Public Member Functions
PUBLIC ~CIoUsecTimer ()
Destructor.
PUBLIC void assign (CTimedUsecObject *obj)
Assign the timer to a new object.
PUBLIC void cancel ()
Cancel the timer if currently running.
void reset (uint64_t usec)
Reset the timer, so that it will expire relative to the current time rather than when it was created (or previously reset)
uint64_t get_timeout () const
Getter method for timeout value.
uint64_t get_time_remaining () const
Gets the time remaining on the running timer for this cycle.
Static Public Member Functions
static PUBLIC std::shared_ptr
< CIoUsecTimer > create (const CIoActor &actor, uint64_t usec)
Factory function to create and start a new CIoUsecTimer object.
static boost::system::error_code do_synchronous_wait (const CIoActor &actor, uint64_t usec)
Static utility function to perform a synchronous wait for a monotonic delay, and return when complete.
Private Member Functions
PUBLIC CIoUsecTimer (const CIoActor &actor, uint64_t usec)
Constructor.
PUBLIC void wait ()
Perform an asynchronous wait on this timer.
PUBLIC void handle_timeout (const boost::system::error_code &err, const std::shared_ptr< CIoUsecTimer > &ptimer)
Callback invoked when the timer expires; will call the timeout() function of the CTimedUsecObject that was assigned to this timer class.
Private Attributes
CTimedUsecObject * _obj
The I/O actor performing the operation for which this timer is counting down.
boost::asio::steady_timer _timer
Timer object which is used to wait the specified amount of time.
boost::recursive_mutex _mutex
Mutex used to protect the timer; this is needed because the timer may be bound to a command that is trying to manipulate it (e.g.
uint64_t _usec
The timeout value, in microseconds.
Detailed Description
The I/O Microsecond Timer class for ASIO Actors.
This class implements an async I/O microsecond timer that is bound to a specific object. This is typically used to place an upper bound on some I/O operation.
Definition at line 61 of file io_usec_timer.hpp.
Constructor & Destructor Documentation
px::asio::CIoUsecTimer::~CIoUsecTimer ()
Destructor.
Definition at line 45 of file io_usec_timer.cpp.
References cancel().
px::asio::CIoUsecTimer::CIoUsecTimer (const CIoActor & actor, uint64_t usec) private
Constructor.
Parameters
actor A related I/O actor, from which we extract the underlying I/O service to register this time with
usec The timeout value, in microseconds
Exceptions
boost::system::system_error An error occurred when creating the timer
Definition at line 31 of file io_usec_timer.cpp.
References _timer.
Referenced by create().
Member Function Documentation
std::shared_ptr< CIoUsecTimer > px::asio::CIoUsecTimer::create (const CIoActor & actor, uint64_t usec) static
Factory function to create and start a new CIoUsecTimer object.
The timer will be running after being created.
Parameters
actor A related I/O actor, from which we extract the underlying I/O service to register this time with
usec The timeout value, in microseconds
Exceptions
boost::system::system_error An error occurred when creating the timer
Returns
Shared pointer containing the new instance of CIoUsecTimer.
Definition at line 18 of file io_usec_timer.cpp.
References CIoUsecTimer().
void px::asio::CIoUsecTimer::assign (CTimedUsecObject * obj)
Assign the timer to a new object.
Parameters
obj The object performing the operation. This pointer must remain valid for the lifetime of the timer (or until assign() is called again).
Definition at line 66 of file io_usec_timer.cpp.
References _mutex, and _obj.
void px::asio::CIoUsecTimer::cancel ()
Cancel the timer if currently running.
The timer can be restarted after this by calling reset() with some new timer delay.
The handle_timeout() will normally be called when this is done, but will recognize that it was canceled and not call its timeout function.
Definition at line 86 of file io_usec_timer.cpp.
References _mutex, _timer, and LIBPX_FERR.
Referenced by ~CIoUsecTimer().
void px::asio::CIoUsecTimer::reset (uint64_t usec)
Reset the timer, so that it will expire relative to the current time rather than when it was created (or previously reset)
Setting it to 0 effectively stops it (similar to cancel()).
If handle_timeout() is invoked by the action of resetting the timer, it will detect that this was due to a reset and not call
Parameters
usec The timeout value, in microseconds
Definition at line 105 of file io_usec_timer.cpp.
References _mutex, _timer, _usec, LIBPX_FERR, and wait().
uint64_t px::asio::CIoUsecTimer::get_timeout () const
Getter method for timeout value.
Returns
The recurring value that this timer is set to, in microseconds.
Definition at line 131 of file io_usec_timer.cpp.
References _usec.
uint64_t px::asio::CIoUsecTimer::get_time_remaining () const
Gets the time remaining on the running timer for this cycle.
Returns
The time remaining on this timer right now, in microseconds.
Definition at line 137 of file io_usec_timer.cpp.
References _timer.
boost::system::error_code px::asio::CIoUsecTimer::do_synchronous_wait (const CIoActor & actor, uint64_t usec) static
Static utility function to perform a synchronous wait for a monotonic delay, and return when complete.
Temporarily creates and uses its own ASIO timer. This function does not actually use or affect any members of the CIoUsecTimer class.
Parameters
actor A related I/O actor, from which we extract the underlying I/O service to register this time with
usec The timeout value, in microseconds
Returns
Returns the error code, if any, from the timer completion. In particular, you might look for a SigHandler interrupt, boost::system::errc::interrupted = EINTR
Definition at line 190 of file io_usec_timer.cpp.
References px::asio::CIoActor::get_io_service(), LIBPX_INFO, and LIBPX_WARN.
void px::asio::CIoUsecTimer::wait () private
Perform an asynchronous wait on this timer.
This must be called in order for the timer to be useful. The only reason it's not invoked automatically by the constructor is that shared_from_this() doesn't work yet at that point. Using the factory function hides this detail.
This function returns immediately; when the timer expires, handle_timeout() will be invoked.
Definition at line 148 of file io_usec_timer.cpp.
References _timer, and handle_timeout().
Referenced by reset().
void px::asio::CIoUsecTimer::handle_timeout (const boost::system::error_code & err, const std::shared_ptr< CIoUsecTimer > & ptimer) private
Callback invoked when the timer expires; will call the timeout() function of the CTimedUsecObject that was assigned to this timer class.
If the timer expires before this object has been closed/destroyed, this callback function is invoked.
Parameters
err The error code for the "wait" operation If the error indicates that the timer was canceled or reset, the CTimedUsecObject's timeout() function will not be called.
ptimer Shared pointer to 'this'
Definition at line 161 of file io_usec_timer.cpp.
References _mutex, _obj, LIBPX_FERR, and px::asio::CTimedUsecObject::timeout().
Referenced by wait().
Member Data Documentation
CTimedUsecObject* px::asio::CIoUsecTimer::_obj private
The I/O actor performing the operation for which this timer is counting down.
Definition at line 219 of file io_usec_timer.hpp.
Referenced by assign(), and handle_timeout().
boost::asio::steady_timer px::asio::CIoUsecTimer::_timer private
Timer object which is used to wait the specified amount of time.
Definition at line 224 of file io_usec_timer.hpp.
Referenced by cancel(), CIoUsecTimer(), get_time_remaining(), reset(), and wait().
boost::recursive_mutex px::asio::CIoUsecTimer::_mutex private
Mutex used to protect the timer; this is needed because the timer may be bound to a command that is trying to manipulate it (e.g.
cancel it) in a worker thread context at the same time that the main thread is invoking its callback function due to expiration.
Definition at line 232 of file io_usec_timer.hpp.
Referenced by assign(), cancel(), handle_timeout(), and reset().
uint64_t px::asio::CIoUsecTimer::_usec private
The timeout value, in microseconds.
Definition at line 237 of file io_usec_timer.hpp.
Referenced by get_timeout(), and reset().
The documentation for this class was generated from the following files:
io_usec_timer.hpp
io_usec_timer.cpp