libpx: px::CChannel Class Reference
px::CChannel Class Reference
Channel as referred to by the CDS.
#include "px/data/channel.hpp"
Public Member Functions
PUBLIC CChannel ()
Default constructor.
PUBLIC CChannel (px::id_t id, px::id_t parent)
Parameterized constructor.
PUBLIC CChannel (const px::proto::MclEntry &arg)
Construct from protobuf object.
PUBLIC CChannel (CChannel &&arg)
Move constructor.
PUBLIC CChannel (const CChannel &arg)
Copy constructor.
PUBLIC ~CChannel ()
Destructor.
template<typename Archive >
void serialize (Archive &ar)
px::id_t id () const
Retreive unique channel ID.
px::id_t parent () const
Retreive unique parent device ID.
PUBLIC CChannel & operator= (const CChannel &arg)
Assignment operator (needed for vector use)
bool operator== (const CChannel &x) const
Equality operator.
bool operator!= (const CChannel &x) const
Not Equality operator Just negates the results of the Equality operation.
bool operator< (const CChannel &x) const
Less-than comparison operator.
PUBLIC size_t hash () const
Hash function.
PUBLIC void from (const px::proto::MclEntry &arg, bool &bump_change_signature)
Update from protobuf object.
PUBLIC void from (const px::tk_proto::storage::PersistedChannel &channel)
Update from protobuf object.
PUBLIC void to (px::proto::MclEntry &arg) const
Create protobuf object.
PUBLIC void to (px::tk_proto::storage::PersistedChannel &channel) const
Create protobuf object.
PUBLIC void set_ids (px::id_t id, px::id_t parent)
Set parent and channel IDs.
PUBLIC px::string get_multistate_svalue () const
Gets the string value if this is a multi-state channel.
PUBLIC bool get_field_by_name (const px::string &field_string, px::CValue &field_value) const
Get the passed field for this device by name (string).
PUBLIC px::CBitset
< px::realtime_state > get_state () const
Return the device's state, the union of bits set by inherited_state and own_state.
PUBLIC void set_state (const px::CBitset< px::realtime_state > &st)
Set the channel's own_state.
PUBLIC void set_inherited_state (const px::CBitset< px::realtime_state > &st)
PUBLIC void copy_state (const px::CChannel &other_ch)
PUBLIC px::CBitset
< px::realtime_state > get_own_state () const
Public Attributes
std::shared_ptr
< px::CChannelSettings > channel_settings
Settings per channel as defined by Mercury.
std::unordered_set
< px::CAlarmTrigger > alarm_settings
Alarm settings associated with channel.
px::CValue value
Channel's current realtime value.
px::CWallTime timestamp
The most recent time the channel's realtime value was updated.
std::shared_ptr
< px::CTrendAccumulator > trend_accumulator
Trending accumulator Should be present only if this channel is configured to be trended.
Private Attributes
px::CBitset< px::realtime_state > own_state
This channel's state.
px::CBitset< px::realtime_state > inherited_state
State inherited from parents.
Detailed Description
Channel as referred to by the CDS.
Through composition, brings all the pieces of a channel into one object, as in the px::proto::MclEntry protobuf object.
Note that the ID that identifies the Channel is actually stored in the ChannelSettings.
Definition at line 27 of file channel.hpp.
Constructor & Destructor Documentation
px::CChannel::CChannel ()
Default constructor.
Primarily used by serialization to instantiate a dummy object, then de-serialize from shared memory to assign the actual member values. Defaults id and parent id to UINT64_MAX.
Definition at line 14 of file channel.cpp.
px::CChannel::CChannel (px::id_t id, px::id_t parent)
Parameterized constructor.
Used mainly in the CDS to create a new device with an allocated ID
Parameters
id Unique id of the channel
Definition at line 18 of file channel.cpp.
px::CChannel::CChannel (const px::proto::MclEntry & arg) explicit
Construct from protobuf object.
missing parameters are set to defaults.
Parameters
arg Object used to initialize this channel settings from.
Exceptions
generic_err Thrown if channel settings protobuf object is missing.
Definition at line 37 of file channel.cpp.
References LIBPX_NOTICE, and px::generic_err::what().
px::CChannel::CChannel (CChannel && arg)
Move constructor.
Parameters
arg Object used to initialize this channel
Definition at line 22 of file channel.cpp.
References px::timestamp.
px::CChannel::CChannel (const CChannel & arg)
Copy constructor.
Parameters
arg Object used to initialize this channel
Definition at line 29 of file channel.cpp.
References px::timestamp.
px::CChannel::~CChannel ()
Destructor.
Definition at line 51 of file channel.cpp.
Member Function Documentation
template<typename Archive > void px::CChannel::serialize (Archive & ar)
Definition at line 94 of file channel.hpp.
References alarm_settings, channel_settings, inherited_state, own_state, timestamp, and value.
px::id_t px::CChannel::id () const
Retreive unique channel ID.
Definition at line 109 of file channel.hpp.
References channel_settings.
Referenced by px::db::AddChannelToBatch(), and px::db::FetchChannels().
px::id_t px::CChannel::parent () const
Retreive unique parent device ID.
Definition at line 117 of file channel.hpp.
References channel_settings.
Referenced by px::db::FetchChannels().
px::CChannel & px::CChannel::operator= (const CChannel & arg)
Assignment operator (needed for vector use)
Definition at line 57 of file channel.cpp.
References alarm_settings, channel_settings, inherited_state, own_state, px::timestamp, timestamp, trend_accumulator, and value.
bool px::CChannel::operator== (const CChannel & x) const
Equality operator.
Parameters
x Channel to compare against
Returns
True if this channel matches channel x in all of IDs, Settings, Value, etc.
Definition at line 69 of file channel.cpp.
References alarm_settings, channel_settings, get_state(), px::timestamp, timestamp, and value.
bool px::CChannel::operator!= (const CChannel & x) const
Not Equality operator Just negates the results of the Equality operation.
Parameters
x Channel to compare against
Returns
True if this channel Does Not match channel x in any of IDs, Settings, Value, etc.
Definition at line 145 of file channel.hpp.
bool px::CChannel::operator< (const CChannel & x) const
Less-than comparison operator.
This is useful for putting channels into an ordered container.
Note
based purely on channel ID
Parameters
x Channel to compare against
Returns
True if this channels id is less than that of channel x id
Definition at line 160 of file channel.hpp.
References channel_settings.
size_t px::CChannel::hash () const
Hash function.
This call returns a hash value for the underlying channel settings
Returns
A hash value for this channel
Definition at line 270 of file channel.cpp.
void px::CChannel::from (const px::proto::MclEntry & arg, bool & bump_change_signature)
Update from protobuf object.
Missing parameters are set to defaults.
Parameters
arg Object used to initialize this channel from
Exceptions
generic_err Thrown if channel settings protobuf object is missing.
Definition at line 84 of file channel.cpp.
References px::CAlarmTrigger::from(), px::has_actual, px::has_avg, px::has_max, px::has_min, and px::trending_enabled.
void px::CChannel::from (const px::tk_proto::storage::PersistedChannel & channel)
Update from protobuf object.
Missing parameters are set to defaults.
Parameters
channel Object used to initialize this channel from
Exceptions
generic_err Thrown if channel settings protobuf object is missing.
Definition at line 175 of file channel.cpp.
void px::CChannel::to (px::proto::MclEntry & arg) const
Create protobuf object.
Parameters
arg Object filled out with channel settings
Definition at line 197 of file channel.cpp.
References px::has_actual, px::has_avg, px::has_max, px::has_min, PX_ID_UNSET, px::trending_enabled, and unlikely.
Referenced by px::db::AddChannelToBatch().
void px::CChannel::to (px::tk_proto::storage::PersistedChannel & channel) const
Create protobuf object.
Parameters
arg Object filled out with channel settings
Definition at line 259 of file channel.cpp.
void px::CChannel::set_ids (px::id_t id, px::id_t parent)
Set parent and channel IDs.
Will throw generic_err if those IDs already had valid values.
Definition at line 275 of file channel.cpp.
References PX_ID_UNSET, and unlikely.
px::string px::CChannel::get_multistate_svalue () const
Gets the string value if this is a multi-state channel.
Definition at line 286 of file channel.cpp.
References likely.
bool px::CChannel::get_field_by_name (const px::string & field_string, px::CValue & field_value) const
Get the passed field for this device by name (string).
This is only supported for public fields.
Unsupported fields (return false) alarm_settings.* state timestamp alarm_state trend_accumulator.*
Noted fields alarm_settings - without a "." accessor for a field under it, this returns false. channel_settings - without a "." accessor for a field under it, this returns false. trend_accumulator - without a "." accessor for a field under it, this returns false. channel_settings.multistate_map - Returns the label mapped value of "value" field by default. Will return another label mapped value if passed, e.g. channel_settings.multistate_map.1. channel_settings.* - see channel_settings.hpp for description
Parameters
field_string String name of field to read
field_value Value of the field read. Unchanged if return is false.
Returns
bool True if field_string is valid, supported, and not an empty string. False if not.
Definition at line 305 of file channel.cpp.
References px::CValue::as_string(), px::CProtoOPS::GetFieldValue(), px::invalid, LIBPX_NOTICE, likely, px::size, px::CUtil::split_string(), px::CValue::type(), and px::generic_err::what().
px::CBitset< px::realtime_state > px::CChannel::get_state () const
Return the device's state, the union of bits set by inherited_state and own_state.
Definition at line 385 of file channel.cpp.
References px::CBitset< T >::mask_set().
Referenced by operator==().
void px::CChannel::set_state (const px::CBitset< px::realtime_state > & st)
Set the channel's own_state.
Definition at line 401 of file channel.cpp.
Referenced by px::db::FetchChannels(), and px::db::MigrateChannelDB().
void px::CChannel::set_inherited_state (const px::CBitset< px::realtime_state > & st)
Definition at line 409 of file channel.cpp.
void px::CChannel::copy_state (const px::CChannel & other_ch)
Definition at line 417 of file channel.cpp.
References inherited_state, and own_state.
px::CBitset< px::realtime_state > px::CChannel::get_own_state () const
Definition at line 393 of file channel.cpp.
Referenced by px::db::AddChannelToBatch().
Member Data Documentation
std::shared_ptr<px::CChannelSettings> px::CChannel::channel_settings
Settings per channel as defined by Mercury.
Definition at line 290 of file channel.hpp.
Referenced by px::db::AddChannelToBatch(), BOOST_AUTO_TEST_CASE(), px::db::FetchChannels(), id(), operator<(), operator=(), operator==(), parent(), and serialize().
std::unordered_set<px::CAlarmTrigger> px::CChannel::alarm_settings
Alarm settings associated with channel.
Definition at line 295 of file channel.hpp.
Referenced by operator=(), operator==(), and serialize().
px::CValue px::CChannel::value
Channel's current realtime value.
Definition at line 300 of file channel.hpp.
Referenced by px::db::AddChannelToBatch(), px::db::FetchChannels(), operator=(), operator==(), and serialize().
px::CWallTime px::CChannel::timestamp
The most recent time the channel's realtime value was updated.
Definition at line 305 of file channel.hpp.
Referenced by px::db::AddChannelToBatch(), px::db::FetchChannels(), operator=(), operator==(), and serialize().
std::shared_ptr<px::CTrendAccumulator> px::CChannel::trend_accumulator
Trending accumulator Should be present only if this channel is configured to be trended.
Definition at line 311 of file channel.hpp.
Referenced by operator=().
px::CBitset<px::realtime_state> px::CChannel::own_state private
This channel's state.
Definition at line 321 of file channel.hpp.
Referenced by copy_state(), operator=(), and serialize().
px::CBitset<px::realtime_state> px::CChannel::inherited_state private
State inherited from parents.
This and own_state are combined as the output of get_state().
Definition at line 327 of file channel.hpp.
Referenced by copy_state(), operator=(), and serialize().
The documentation for this class was generated from the following files:
channel.hpp
channel.cpp