libpx: semantics.hpp File Reference
semantics.hpp File Reference
Classes
class stmt_vec_converter
Visitor function used to convert a statement into a statement array (non-destructively)
Typedefs
typedef std::vector< expression > arglist_t
Utility functions utilized by the parser to build an abstract syntax tree.
typedef std::unique_ptr
< statement > stmt_ptr_t
typedef std::unique_ptr
< expression > expr_ptr_t
typedef std::unique_ptr
< arglist_t > arglist_ptr_t
Functions
static statement * stmt_add_to_list (statement *list, statement *newstmt)
static statement * stmt_make_noop ()
static statement * stmt_make_expr (expression *expr)
template<typename T >
static statement * stmt_make_cond (expression *cond, statement *stmt1, statement *stmt2)
template<typename T >
static expression * expr_make_unary (expression *arg)
template<typename T >
static expression * expr_make_binary (expression *arg1, expression *arg2)
template<typename T >
static expression * expr_make_variadic (arglist_t *arglist)
static arglist_t * arg_add_to_list (arglist_t *arglist, expression *expr)
static arglist_t * create_arglist ()
Typedef Documentation
typedef std::vector<expression> arglist_t
Utility functions utilized by the parser to build an abstract syntax tree.
See the Bison source to see how this is used.
Definition at line 10 of file semantics.hpp.
typedef std::unique_ptr<statement> stmt_ptr_t
Definition at line 11 of file semantics.hpp.
typedef std::unique_ptr<expression> expr_ptr_t
Definition at line 12 of file semantics.hpp.
typedef std::unique_ptr<arglist_t> arglist_ptr_t
Definition at line 13 of file semantics.hpp.
Function Documentation
static statement* stmt_add_to_list (statement * list, statement * newstmt) static
Definition at line 44 of file semantics.hpp.
Referenced by px::eq::detail::switch().
static statement* stmt_make_noop () static
Definition at line 61 of file semantics.hpp.
Referenced by px::eq::detail::switch().
static statement* stmt_make_expr (expression * expr) static
Definition at line 67 of file semantics.hpp.
Referenced by px::eq::detail::switch().
template<typename T > static statement* stmt_make_cond (expression * cond, statement * stmt1, statement * stmt2) static
Definition at line 77 of file semantics.hpp.
template<typename T > static expression* expr_make_unary (expression * arg) static
Definition at line 91 of file semantics.hpp.
template<typename T > static expression* expr_make_binary (expression * arg1, expression * arg2) static
Definition at line 101 of file semantics.hpp.
template<typename T > static expression* expr_make_variadic (arglist_t * arglist) static
Definition at line 113 of file semantics.hpp.
static arglist_t* arg_add_to_list (arglist_t * arglist, expression * expr) static
Definition at line 122 of file semantics.hpp.
Referenced by px::eq::detail::switch().
static arglist_t* create_arglist () static
Definition at line 133 of file semantics.hpp.
Referenced by px::eq::detail::switch().