libpx: px::asio::CUdsConnection Class Reference
px::asio::CUdsConnection Class Reference
ASIO interface details and general IO functions.
Unix Domain Socket Connection class, which manages transactions on a socket of type stream_protocol::socket.
#include <uds_connection.hpp>
Public Member Functions
CUdsConnection (CIoManager &manager, const CProtocolHandler &prot)
Constructor.
~CUdsConnection ()
Destructor.
virtual PUBLIC const std::string source ()
Get text describing the source of a message (eg, dotted IP address).
void close () override
Inherited from CIoTransactor.
void read_more () override
Inherited from CIoTransactor.
PUBLIC int peer_uid ()
Public Member Functions inherited from px::asio::CIoTransactor
CIoTransactor (CIoManager &manager, const CProtocolHandler &prot)
Constructor.
virtual ~CIoTransactor ()
Destructor.
PUBLIC void start ()
Kick-start the messenger by waiting for incoming data.
PUBLIC iobuf_const_pair_t get_rbuf ()
Get the currently-read message boundaries.
PUBLIC void clear_rbuf (iobuf_const_iter_t end)
Clear (perhaps only partially) the read-buffer contents after servicing a single request.
PUBLIC bool get_parse_success ()
PUBLIC void set_parse_failed (bool val)
virtual PUBLIC uint16_t source_port ()
Get port number of the source of a message (0 if N/A).
virtual PUBLIC void write (std::shared_ptr< io_buf_t > pbuf)
Write data to the messenger's output channel's outbox.
Public Member Functions inherited from px::asio::CIoActor
CIoActor (CIoManager &manager)
Constructor.
virtual ~CIoActor ()
Destructor.
boost::asio::io_service & get_io_service () const
Get the I/O service associated with the owner of this actor.
PUBLIC CServerCore & get_server_core () const
Get the container for CDS data management.
PUBLIC CCdsHandler & get_cds_handler () const
Get the container for CDS data management.
PUBLIC bool get_quit_status ()
Get the quit status from connection IO manager.
Static Public Member Functions
static std::shared_ptr
< CUdsConnection > create (CIoManager &manager, const CProtocolHandler &prot)
Factory function to create a new CUdsConnection object.
Protected Member Functions
void write_more (const std::shared_ptr< io_buf_t > &pbuf) override
Write the data from the outbox to the service.
Protected Member Functions inherited from px::asio::CIoTransactor
void handle_read (const boost::system::error_code &err, size_t bytes_transferred)
Callback function to handle incoming data.
void handle_write (const boost::system::error_code &err, size_t bytes_transferred)
Callback function to handle a completed "write" operation.
void parse ()
Attempt to parse the currently-read data in the buffer.
void clear_outbox ()
Clear the outbox queue.
std::shared_ptr< io_buf_t > get_outbox_front_buf ()
Get the front item from the outbox if any.
Protected Member Functions inherited from px::asio::CIoActor
void remove ()
This method is called when an actor wants to remove itself from the I/O management interface.
Private Attributes
std::unique_ptr
< boost::asio::local::stream_protocol::socket > _sock
The underlying Boost.Asio Unix Domain socket object.
Additional Inherited Members
Public Attributes inherited from px::asio::CIoTransactor
bool started
True if start() has been called This can be used to distinguish e.g.
Protected Attributes inherited from px::asio::CIoTransactor
io_buf_t _rbuf
I/O buffer used for reading message data.
size_t _offset
Current offset in _rbuf, i.e.
std::shared_ptr< CProtocolHandler > _prot
Protocol-specific handler, used to parse and handle incoming requests and generate responses.
std::queue< std::shared_ptr
< io_buf_t > > _outbox
Queues the outgoing data to send.
Protected Attributes inherited from px::asio::CIoActor
CIoManager & _owner
The I/O manager object that "owns" this connection.
Detailed Description
Unix Domain Socket Connection class, which manages transactions on a socket of type stream_protocol::socket.
Note: has no current uses; may need work.
Definition at line 20 of file uds_connection.hpp.
Constructor & Destructor Documentation
px::asio::CUdsConnection::CUdsConnection (CIoManager & manager, const CProtocolHandler & prot)
Constructor.
Parameters
manager The I/O manager object to which this connection is to be bound
prot Protocol handler object which is utilized to perform protocol-specific operations on this UDS connection in an abstracted manner
Exceptions
boost::system::system_error The connection could not be initialized
Definition at line 35 of file uds_connection.cpp.
References _sock, and px::asio::CIoActor::get_io_service().
Referenced by create().
px::asio::CUdsConnection::~CUdsConnection ()
Destructor.
Definition at line 47 of file uds_connection.cpp.
References close(), and LIBPX_FDEBUG.
Member Function Documentation
std::shared_ptr< CUdsConnection > px::asio::CUdsConnection::create (CIoManager & manager, const CProtocolHandler & prot) static
Factory function to create a new CUdsConnection object.
Parameters
manager The I/O manager object to which this object is to be bound
prot Protocol handler object which is utilized to perform protocol-specific operations on this UDS connection in an abstracted manner
Exceptions
boost::system::system_error The connection could not be initialized
Returns
Shared pointer containing the new instance of CUdsConnection.
Definition at line 21 of file uds_connection.cpp.
References CUdsConnection().
Referenced by px::asio::CUdsListener::accept().
virtual PUBLIC const std::string px::asio::CUdsConnection::source () virtual
Get text describing the source of a message (eg, dotted IP address).
Returns
Description or name of the source of this message.
Implements px::asio::CIoTransactor.
Definition at line 71 of file uds_connection.hpp.
References _sock.
void px::asio::CUdsConnection::close () override virtual
Inherited from CIoTransactor.
Reimplemented from px::asio::CIoTransactor.
Definition at line 64 of file uds_connection.cpp.
References _sock, LIBPX_DEBUG, and LIBPX_ERR.
Referenced by ~CUdsConnection().
void px::asio::CUdsConnection::read_more () override virtual
Inherited from CIoTransactor.
Implements px::asio::CIoTransactor.
Definition at line 92 of file uds_connection.cpp.
References px::asio::CIoTransactor::_offset, px::asio::CIoTransactor::_rbuf, _sock, and px::asio::CIoTransactor::handle_read().
int px::asio::CUdsConnection::peer_uid ()
Returns
The Linux UID of the connected peer, -1 if not known
Definition at line 133 of file uds_connection.cpp.
References _sock.
void px::asio::CUdsConnection::write_more (const std::shared_ptr< io_buf_t > & pbuf) override protected virtual
Write the data from the outbox to the service.
Implements px::asio::CIoTransactor.
Definition at line 113 of file uds_connection.cpp.
References _sock, and px::asio::CIoTransactor::handle_write().
Member Data Documentation
std::unique_ptr<boost::asio::local::stream_protocol::socket> px::asio::CUdsConnection::_sock private
The underlying Boost.Asio Unix Domain socket object.
Definition at line 103 of file uds_connection.hpp.
Referenced by close(), CUdsConnection(), peer_uid(), read_more(), source(), and write_more().
The documentation for this class was generated from the following files:
uds_connection.hpp
uds_connection.cpp