libpx: px::asio::CCdsSyncIO Class Reference
px::asio::CCdsSyncIO Class Reference
Provides a set of common CDS utility functions.
#include <cds_sync_io.hpp>
Public Member Functions
PUBLIC CCdsSyncIO (const bool enable_data_validation=true)
Constructor.
virtual PUBLIC ~CCdsSyncIO ()
Default destructor.
PUBLIC void check_cds_result (const std::shared_ptr< px::cds::CRequestResponse > cds_resp, const char *req_name) const
Utility function to check if we got a response, and that the returned CDS Results status is Success.
PUBLIC int cds_login (const px::string &service, px::string &session_token, px::CBitset< px::permissions > &perms)
Do a CDS Client Login (no username or password) to get a session token and permissions.
PUBLIC void ping_watchdog_s ()
Watchdog Related Member Functions.
PUBLIC void register_watchdog (uint32_t timeout, bool auto_clear_on_close=true)
Utility function to register the CDS watchdog timer.
PUBLIC void clear_watchdog ()
Utility function to clear the CDS watchdog timer.
PUBLIC bool get_oob (const px::string &tag, px::proto::toolkitStruct &data)
OOB Related Member Functions.
PUBLIC std::pair< px::CValue,
bool > get_oob_field (const px::string &tag_name, const px::string &field_name) const
Convenience method for synchronous CDS request to get one OOB field value.
PUBLIC std::vector< px::string > get_oob_tags (const px::string &tag_hint)
Get the list of OOB tags, given a starting hint (which can be empty to get all).
PUBLIC void set_oob_s (const px::string &tag, const px::proto::toolkitStruct &data, bool persist=false)
Synchronous non-ASIO version of CDS Set OOB, with fire-and-forget submission to the CDS.
PUBLIC bool set_oob_wait (const px::string &tag, const px::proto::toolkitStruct &data, bool persist=false)
Synchronous non-ASIO version of CDS Set OOB, which waits for the CDS response to the set.
PUBLIC int set_oob_field (::cds::field_t &field)
Convenience method for synchronous CDS request to set one OOB field value.
PUBLIC void clear_oob (const px::string &tag)
Utility function to delete an OOB object from the CDS.
PUBLIC px::id_t create_channel (const px::id_t dev_id, const px::string &canonical_name, const bool is_custom=false)
Channel Related Member Functions.
PUBLIC int delete_channel (const px::id_t ch_id)
Utility function to delete a channel in the CDS.
PUBLIC int delete_channels (const std::vector< px::id_t > ch_ids)
Utility function to delete one or more channels in the CDS.
PUBLIC px::CChannel get_channel (const px::id_t chan_id)
Retrieve a single channel by its channel id.
PUBLIC std::vector
< px::cds::CGetSingleChannel > get_channels (const px::id_t dev_id)
Get a list of Channel(s) for a given device.
PUBLIC std::vector
< px::cds::CGetSingleChannel > get_channels_by_name (px::id_t dev_id, const std::vector< px::string > &canonical_names)
Get a list of Channel(s) for a given device, looked up by their MCL canonical name(s).
PUBLIC std::shared_ptr
< px::cds::CGetChannelSettings > get_channel_settings (const px::id_t dev_id)
Utility function to get all Channel Settings for a device in the CDS.
PUBLIC bool get_data_validation ()
Utility function to check if CDS data validation is enabled or disabled.
PUBLIC void set_data_validation (const bool validate)
Utility function to enable/disable CDS data validation in member functions that set channel values.
PUBLIC void set_channel_value_s (const px::id_t channel_id, const px::CValue &value)
Synchronous non-ASIO version of CDS Set Channel Value.
PUBLIC void set_channel_values (const std::vector< px::cds::CUpdateSingleChannelValue > &values)
Utility function to set the current Values of multiple Channels into the CDS.
PUBLIC px::CDevice create_device (const bool use_given_id, const px::CDevice &device)
Device Related Member Functions.
PUBLIC std::vector< px::CDevice > create_devices (const bool use_given_ids, const std::vector< px::CDevice > &devices)
Utility function to create single or multiple devices in the CDS.
PUBLIC void delete_device (const px::id_t delete_id)
Delete the provided device ID from the CDS.
PUBLIC void delete_devices (const std::vector< px::id_t > &delete_ids)
Delete the provided device IDs from the CDS.
PUBLIC px::CDevice get_device_s (const px::id_t dev_id)
Synchronous non-ASIO version of CDS Get Device.
PUBLIC std::map< px::id_t,
px::CDevice > get_devices (const px::id_t starting_dev_id=PX_ID_ROOT)
Utility function to retrieve a map of a device and child devices.
PUBLIC std::vector
< px::CChannelTrends > get_device_trend_row (px::id_t dev_id, unsigned int interval_minutes=5, px::CWallTime start_time=px::CWallTime(), bool recursive=false)
ToDo: setup means to always have the latest trend data at hand.
PUBLIC int set_device_guid (const px::string &name_str, px::CDevice &px_device, bool is_direct=false, bool do_forget=false)
Set Device GUID in the given CDevice instance and in the CDS.
PUBLIC int set_device_guid (const px::string &name_str, px::id_t dev_id)
Set Device GUID in the given CDevice instance and in the CDS, generating the UUID from the given seed text.
PUBLIC void set_device_state (const std::vector< px::cds::CSetSingleDeviceState > &dev_states)
State Related Member Functions.
PUBLIC void set_channel_state (const std::vector< px::cds::CSetSingleChannelState > &chan_states)
Utility function to set the channel state for one or more channels.
PUBLIC void enable_device (const px::id_t dev_id, const bool is_enabled)
Utility function to enable/disable a device.
PUBLIC void enable_device (px::CDevice &device, const bool is_enabled)
Utility function to enable/disable a device, and update the realtime state of the passed in px::CDevice object.
PUBLIC void set_device_communicating (const px::id_t dev_id, const bool is_communicating)
Utility function to set the communicating state of a device.
PUBLIC void set_device_communicating (px::CDevice &device, const bool is_communicating)
Utility function to set the communicating state of a device, and update the realtime state of the passed in px::CDevice object.
PUBLIC void set_channel_communicating (const px::id_t chan_id, const bool is_communicating)
Utility function to set the communicating state of a channel.
PUBLIC::cds::field_t get_field (const ::cds::field_t &field) const
Field Related Member Functions.
PUBLIC int set_field (::cds::field_t &field)
Convenience method for synchronous CDS request to set one field value.
PUBLIC uint64_t subscribe_by_id (uint64_t sub_id, px::sub::subscription_type sub_type, px::id_t item_id, bool is_recursive_device=false, bool is_reflexive=false, std::string library_name="")
Subscription Related Member Functions.
PUBLIC bool unsubscribe_id (uint64_t sub_id, px::sub::subscription_type sub_type, px::id_t item_id, std::string library_name="")
Unsubscribe the given Device or Channel from the given subscription (by ID and type).
PUBLIC uint64_t subscribe_oob (uint64_t sub_id, px::string oob_tag, bool is_reflexive=false, bool is_tag_partial=false)
Create or update a subscription for the OOB with the given tag (name).
PUBLIC bool unsubscribe_oob (uint64_t sub_id, px::string oob_tag, bool is_tag_partial=false)
Unsubscribe the given OOB from the given subscription (by ID).
PUBLIC std::vector< uint64_t > get_subscriber_ids (size_t count, bool reflexive=false)
Use CManageSubscriberIDs to request new subscriber ID(s) for our use.
Protected Member Functions
std::vector< px::CChannelSettings > get_channel_by_group (const std::vector< px::id_t > &get_ids, unsigned int offset, const unsigned int &limit)
The function is used to get the channel settings for a subset of the provided ids It groups the required channels and sends request to CDS.
Protected Attributes
bool _bypass_validation
If true, bypass CDS data validation when setting channel values.
Detailed Description
Provides a set of common CDS utility functions.
These functions use a synchronous interface to the CDS API.
– Note: Using this class does NOT require ASIO services –
Public member functions ending in "_s" are synchronous versions of the same function in the CCdsHandler class.
Definition at line 41 of file cds_sync_io.hpp.
Constructor & Destructor Documentation
px::asio::CCdsSyncIO::CCdsSyncIO (const bool enable_data_validation = true)
Constructor.
Parameters
enable_data_validation Enable/disable CDS data validation. Defaults to true.
Definition at line 57 of file cds_sync_io.cpp.
px::asio::CCdsSyncIO::~CCdsSyncIO () virtual
Default destructor.
A base class must have a virtual Xtor.
Definition at line 62 of file cds_sync_io.cpp.
References px::cds::CClient::disconnect(), and px::cds::CClient::get().
Member Function Documentation
void px::asio::CCdsSyncIO::check_cds_result (const std::shared_ptr< px::cds::CRequestResponse > cds_resp, const char * req_name) const
Utility function to check if we got a response, and that the returned CDS Results status is Success.
Will throw if the shared pointer is empty or the status is something else.
Parameters
cds_resp The response message pointer, upcast to the base CRequestResponse.
req_name The name of the message we are checking (for the error message). Must not be null.
Exceptions
If cds_resp is empty or status is anything other than Success, will throw px::generic_err with an informative message.
Definition at line 72 of file cds_sync_io.cpp.
References px::cds::req_name(), and px::cds::SUCCEEDED.
Referenced by cds_login(), create_channel(), create_device(), create_devices(), delete_channel(), delete_channels(), delete_device(), px::asio::CCdsHandler::do_alarm_discovery(), get_channel(), get_channel_by_group(), get_channel_settings(), px::asio::CCdsHandler::get_channel_value(), get_channels(), get_channels_by_name(), px::asio::CCdsHandler::get_device(), get_device_s(), get_device_trend_row(), get_devices(), get_field(), get_oob(), get_oob_field(), get_oob_tags(), get_subscriber_ids(), set_device_guid(), set_field(), px::asio::CCdsHandler::set_oob(), set_oob_field(), set_oob_wait(), px::asio::CCdsHandler::subscribe_alarm_callback(), subscribe_by_id(), px::asio::CCdsHandler::subscribe_device_callbacks(), subscribe_oob(), unsubscribe_id(), and unsubscribe_oob().
int px::asio::CCdsSyncIO::cds_login (const px::string & service, px::string & session_token, px::CBitset< px::permissions > & perms)
Do a CDS Client Login (no username or password) to get a session token and permissions.
This is useful for internal processes for which there is no user name or password. Will store the session token to authorize the process' CDS or Mercury requests.
Parameters
service Service to login, normally the name of the calling application
[out] session_token Session token that we are logged into the CDS with
[out] perms session_token This client's set of permissions
Returns
0 on success, -1 on failure to retrieve session token and permissions.
Exceptions
If unable to fetch from CDS, will throw px::generic_err with an informative message.
Will throw px::generic_err in the unlikely case where this login fails.
Definition at line 96 of file cds_sync_io.cpp.
References check_cds_result(), px::cds::CClient::get(), px::cds::CCdsClientLogin::hard_timeout, px::cds::CCdsClientLogin::idle_timeout, LIBPX_DEBUG, LIBPX_ERR, LIBPX_WARN, px::permission::perms_to_short_str(), px::cds::CCdsClientLogin::service, px::cds::CClient::submit_wait(), and px::generic_err::what().
void px::asio::CCdsSyncIO::ping_watchdog_s ()
Watchdog Related Member Functions.
                               Synchronous non-ASIO version of CDS Ping Watchdog
Utility function to ping the CDS watchdog timer directly. For most applications, this will be managed automatically by the ASIO CIoManager's ping_timer, but this function is provided for convenience in those times when the manager is not given the chance to run.
Definition at line 145 of file cds_sync_io.cpp.
References px::cds::CClient::get(), LIBPX_DEBUG, LIBPX_ERR, px::cds::CClient::submit(), and px::generic_err::what().
void px::asio::CCdsSyncIO::register_watchdog (uint32_t timeout, bool auto_clear_on_close = true)
Utility function to register the CDS watchdog timer.
Parameters
timeout Watchdog timeout, in seconds. Must be > 0.
auto_clear_on_close If true, and this client's connection to the CDS closes without the client having sent a px::cds::CClearWatchdog, un-register (so the CDS will not reboot the system just because no more messages are forthcoming). Weakens the watchdog protection, so this should only be used when clearly appropriate. Default = true.
Definition at line 165 of file cds_sync_io.cpp.
References px::cds::CClient::get(), LIBPX_INFO, and px::cds::CClient::submit().
void px::asio::CCdsSyncIO::clear_watchdog ()
Utility function to clear the CDS watchdog timer.
Definition at line 180 of file cds_sync_io.cpp.
References px::cds::CClient::get(), LIBPX_INFO, and px::cds::CClient::submit_wait().
bool px::asio::CCdsSyncIO::get_oob (const px::string & tag, px::proto::toolkitStruct & data)
OOB Related Member Functions.
Utility function to read a full OOB object from the CDS (synchronously).
Parameters
tag CDS OOB path/name to get. Must not be blank.
[out] data The OOB contents returned by the CDS.
Returns
True if the data is valid on return, else False if the fetch failed.
Definition at line 193 of file cds_sync_io.cpp.
References check_cds_result(), px::cds::CClient::get(), LIBPX_WARN, px::cds::CClient::submit_wait(), px::cds::CGetOOBData::tags, and px::generic_err::what().
std::pair< px::CValue, bool > px::asio::CCdsSyncIO::get_oob_field (const px::string & tag_name, const px::string & field_name) const
Convenience method for synchronous CDS request to get one OOB field value.
Parameters
tag_name Tag name for the OOB to get the field.
field_name Field name to get from OOB.
Returns
A pair containing the field value and the function call status, i.e. true on success, false on failure.
Definition at line 228 of file cds_sync_io.cpp.
References check_cds_result(), px::cds::config, px::cds::CGetFieldValue::fields, px::cds::CClient::get(), px::invalid, LIBPX_WARN, px::cds::CClient::submit_wait(), and px::generic_err::what().
std::vector< px::string > px::asio::CCdsSyncIO::get_oob_tags (const px::string & tag_hint)
Get the list of OOB tags, given a starting hint (which can be empty to get all).
Parameters
tag_hint The starting text of OOB tag(s) to be returned; if this is empty, then all existing OOB tags will be returned.
Returns
An array of OOB tags returned for the given hint.
Definition at line 267 of file cds_sync_io.cpp.
References check_cds_result(), px::cds::CGetOOBTags::filters, px::cds::CClient::get(), LIBPX_DEBUG, LIBPX_WARN, px::cds::CClient::submit_wait(), and px::generic_err::what().
void px::asio::CCdsSyncIO::set_oob_s (const px::string & tag, const px::proto::toolkitStruct & data, bool persist = false)
Synchronous non-ASIO version of CDS Set OOB, with fire-and-forget submission to the CDS.
Utility function to set a particular OOB object. Does a fire-and-forget when writing this out.
Differs from set_oob_field() in that it sets a full OOB object rather than just one field in an OOB.
Parameters
tag CDS OOB path/name to write to. Must not be blank.
data The OOB contents to write.
Exceptions
If unable to write to the CDS, will throw px::generic_err with an informative message.
Definition at line 311 of file cds_sync_io.cpp.
References px::cds::CSetOOBData::data, px::cds::do_not_save, px::cds::CClient::get(), LIBPX_ERR, LIBPX_INFO, px::cds::save_always, and px::cds::CClient::submit().
bool px::asio::CCdsSyncIO::set_oob_wait (const px::string & tag, const px::proto::toolkitStruct & data, bool persist = false)
Synchronous non-ASIO version of CDS Set OOB, which waits for the CDS response to the set.
Utility function to set a particular OOB object. Differs from CCdsHandler::set_oob() in that this one doesn't guard against being in the CdsHandler callbacks, and also doesn't throw if the set operation fails.
Parameters
tag CDS OOB path/name to write to.
data The OOB contents to write.
Returns
True on success, else False if the set operation failed. Does not throw.
Definition at line 341 of file cds_sync_io.cpp.
References check_cds_result(), px::cds::CSetOOBData::data, px::cds::do_not_save, px::cds::CClient::get(), LIBPX_ERR, LIBPX_INFO, px::cds::save_always, px::cds::CClient::submit_wait(), and px::generic_err::what().
int px::asio::CCdsSyncIO::set_oob_field (::cds::field_t & field)
Convenience method for synchronous CDS request to set one OOB field value.
Parameters
field OOB Paths/ID that names where the data should be placed in the CDS, and its new value. Field tag must not be blank.
Returns
0 on success, 1 on failure.
Exceptions
px::generic_err if unable to set to the CDS
Definition at line 372 of file cds_sync_io.cpp.
References check_cds_result(), px::cds::CSetFieldValue::fields, px::cds::CClient::get(), px::cds::CSingleField::id, px::invalid, LIBPX_ERR, px::cds::CSingleField::pv, px::cds::save_always, px::cds::CClient::submit_wait(), and px::cds::CSingleField::tag.
void px::asio::CCdsSyncIO::clear_oob (const px::string & tag)
Utility function to delete an OOB object from the CDS.
Parameters
tag Name of the OOB to remove. Must not be blank.
Definition at line 402 of file cds_sync_io.cpp.
References px::cds::CClient::get(), LIBPX_ERR, LIBPX_INFO, px::cds::CClient::submit(), px::cds::CClearOOBData::tags, and px::generic_err::what().
px::id_t px::asio::CCdsSyncIO::create_channel (const px::id_t dev_id, const px::string & canonical_name, const bool is_custom = false)
Channel Related Member Functions.
Utility function to create a channel in the CDS.
Parameters
dev_id The parent device id. Must be > 0.
canonical_name The canonical name of this channel. Must not be blank.
is_custom Set to true if this channel is NOT in the MCL.
Returns
ID of the newly created device.
Exceptions
If unable to create a channel in the CDS, will throw px::generic_err with an informative message.
Definition at line 426 of file cds_sync_io.cpp.
References check_cds_result(), px::cds::CClient::get(), LIBPX_DEBUG, px::cds::CCreateChannel::requests, and px::cds::CClient::submit_wait().
int px::asio::CCdsSyncIO::delete_channel (const px::id_t ch_id)
Utility function to delete a channel in the CDS.
Parameters
ch_id The channel id to delete. Must be > 0.
Returns
zero on success, 1 on failure.
Exceptions
If unable to delete a channel in the CDS, will throw px::generic_err with an informative message.
Definition at line 459 of file cds_sync_io.cpp.
References check_cds_result(), px::cds::CClient::get(), px::cds::CDeleteChannel::ids, LIBPX_DEBUG, and px::cds::CClient::submit_wait().
int px::asio::CCdsSyncIO::delete_channels (const std::vector< px::id_t > ch_ids)
Utility function to delete one or more channels in the CDS.
Parameters
ch_ids Vector of channel ids to delete. Must not be empty.
Returns
zero on success, 1 on failure.
Exceptions
If unable to delete the channels in the CDS, will throw px::generic_err with an informative message.
Definition at line 483 of file cds_sync_io.cpp.
References check_cds_result(), px::cds::CClient::get(), px::cds::CDeleteChannel::ids, LIBPX_DEBUG, LIBPX_ERR, px::cds::CClient::submit_wait(), and px::generic_err::what().
px::CChannel px::asio::CCdsSyncIO::get_channel (const px::id_t chan_id)
Retrieve a single channel by its channel id.
This will return the channel data from the CDS using a synchronous CDS request.
Parameters
chan_id The ID of the channel being requested. Must be > 0.
Returns
A copy of the requested CChannel object.
Exceptions
If unable to fetch from CDS, will throw px::generic_err with an informative message.
Definition at line 516 of file cds_sync_io.cpp.
References check_cds_result(), px::cds::CClient::get(), px::cds::CGetChannel::ids, LIBPX_DEBUG, and px::cds::CClient::submit_wait().
std::vector< px::cds::CGetSingleChannel > px::asio::CCdsSyncIO::get_channels (const px::id_t dev_id)
Get a list of Channel(s) for a given device.
This will return vector of CGetSingleChannel channel data from the CDS using a synchronous CDS request.
Can also be used to fetch a single channel by passing in a channel id as the dev_id parameter.
Parameters
id The CDS device (or channel) whose channel data we want to get. Must be > 0.
Returns
On success will return an array of data for each channel under the device.
Definition at line 542 of file cds_sync_io.cpp.
References check_cds_result(), px::cds::CGetChannel::device_id, px::cds::CClient::get(), LIBPX_WARN, px::none, px::cds::CClient::submit_wait(), and px::generic_err::what().
std::vector< px::cds::CGetSingleChannel > px::asio::CCdsSyncIO::get_channels_by_name (px::id_t dev_id, const std::vector< px::string > & canonical_names)
Get a list of Channel(s) for a given device, looked up by their MCL canonical name(s).
On return, each entry has the ID, Value, Settings, Timestamp, and State. Normally requires a synchronous CDS call to get this data.
Parameters
dev_id The CDS device ID whose channel data we want to get. Must be > 0.
canonical_names List of canonical (ie, MCL) names for the desired Channels. Must not be empty.
Returns
On success, will return an array of data for each channel found by its name. If no names match, this will be an empty array.
Exceptions
If unable to fetch from CDS, will throw px::generic_err with an informative message.
Definition at line 572 of file cds_sync_io.cpp.
References check_cds_result(), px::cds::CGetChannel::device_id, px::cds::CClient::get(), LIBPX_FNOTICE, px::cds::CClient::submit_wait(), and px::generic_err::what().
std::shared_ptr< px::cds::CGetChannelSettings > px::asio::CCdsSyncIO::get_channel_settings (const px::id_t dev_id)
Utility function to get all Channel Settings for a device in the CDS.
Parameters
dev_id The device id. Must be > 0.
Returns
std::shared_ptr<px::cds::CGetChannelSettings> object. shared_ptr .get() method will fail if no channel settings were found.
Exceptions
If unable to fetch from CDS, will throw px::generic_err with an informative message.
Definition at line 604 of file cds_sync_io.cpp.
References check_cds_result(), px::cds::CClient::get(), get_channel_by_group(), px::cds::CGetChannelSettings::ids, LIBPX_DEBUG, MAX_CHANNELS_PER_REQ, px::cds::CGetDevice::maxdepth, px::cds::CGetDevice::requested_ids, px::cds::RESPONSE_TOO_BIG, and px::cds::CClient::submit_wait().
Referenced by px::asio::CCdsHandler::list_channel_settings().
bool px::asio::CCdsSyncIO::get_data_validation ()
Utility function to check if CDS data validation is enabled or disabled.
Returns
If true, CDS data validation is ON. If false, CDS data validation is OFF.
Definition at line 718 of file cds_sync_io.hpp.
References _bypass_validation.
void px::asio::CCdsSyncIO::set_data_validation (const bool validate)
Utility function to enable/disable CDS data validation in member functions that set channel values.
i.e.: CCdsSyncIO::set_channel_value_s CCdsSyncIO::set_channel_values CCdsHandler::set_channel_value
Parameters
validate If true, CDS data validation is ON. If false, CDS data validation is OFF.
Definition at line 720 of file cds_sync_io.hpp.
References _bypass_validation.
void px::asio::CCdsSyncIO::set_channel_value_s (const px::id_t channel_id, const px::CValue & value)
Synchronous non-ASIO version of CDS Set Channel Value.
Utility function to set the current Value of a Channel into the CDS. Does a fire-and-forget when writing this out.
Parameters
channel_id The ID of the Channel whose Value is to be written.
value The Value to write to the CDS.
Exceptions
If unable to set value in CDS, will throw px::generic_err with an informative message.
Definition at line 688 of file cds_sync_io.cpp.
References _bypass_validation, px::CValue::as_string(), px::cds::CUpdateChannelValue::bypass_validation, px::cds::CClient::get(), LIBPX_ERR, LIBPX_INFO, px::CWallTime::now(), px::cds::CClient::submit(), px::cds::CUpdateChannelValue::updates, and px::cds::CUpdateChannelValue::when.
void px::asio::CCdsSyncIO::set_channel_values (const std::vector< px::cds::CUpdateSingleChannelValue > & values)
Utility function to set the current Values of multiple Channels into the CDS.
Does a fire-and-forget when writing this out.
Parameters
values Vector of updated channel values. Must not be empty.
Exceptions
If unable to set value in CDS, will throw px::generic_err with an informative message.
Definition at line 716 of file cds_sync_io.cpp.
References _bypass_validation, px::cds::CUpdateChannelValue::bypass_validation, px::cds::CClient::get(), LIBPX_ERR, LIBPX_INFO, px::CWallTime::now(), px::cds::CClient::submit(), px::cds::CUpdateChannelValue::updates, and px::cds::CUpdateChannelValue::when.
px::CDevice px::asio::CCdsSyncIO::create_device (const bool use_given_id, const px::CDevice & device)
Device Related Member Functions.
Utility function to create a single device in the CDS.
Parameters
use_given_id The use the ID of the px_device being passed in.
px_device The device to be created.
Returns
px::CDevice of the newly created device.
Exceptions
If unable to create device in the CDS, will throw px::generic_err with an informative message.
Definition at line 748 of file cds_sync_io.cpp.
References check_cds_result(), px::cds::CCreateDevice::devices, px::cds::CClient::get(), px::cds::CClient::submit_wait(), and px::cds::CCreateDevice::use_given_ids.
std::vector< px::CDevice > px::asio::CCdsSyncIO::create_devices (const bool use_given_ids, const std::vector< px::CDevice > & devices)
Utility function to create single or multiple devices in the CDS.
Parameters
use_given_ids The use the IDs of the px_devices being passed in.
px_devices Vector of devices to be created. Must not be empty.
Returns
Vector of newly created devices.
Exceptions
If unable to create the device(s) in the CDS, will throw px::generic_err with an informative message.
Definition at line 772 of file cds_sync_io.cpp.
References check_cds_result(), px::cds::CCreateDevice::devices, px::cds::CClient::get(), LIBPX_ERR, px::cds::CClient::submit_wait(), and px::cds::CCreateDevice::use_given_ids.
void px::asio::CCdsSyncIO::delete_device (const px::id_t delete_id)
Delete the provided device ID from the CDS.
There is no response since this CDS operation has no response.
Parameters
delete_id The device ID to delete. Must be > 0.
Exceptions
If CDS error occurrs, will throw px::generic_err with an informative message.
Definition at line 805 of file cds_sync_io.cpp.
References check_cds_result(), px::cds::CDeleteDevice::devices, px::cds::CClient::get(), LIBPX_ERR, LIBPX_INFO, and px::cds::CClient::submit_wait().
void px::asio::CCdsSyncIO::delete_devices (const std::vector< px::id_t > & delete_ids)
Delete the provided device IDs from the CDS.
There is no response since this CDS operation has no response.
Parameters
delete_ids The vector of device ID(s) to delete. Must not be empty nor id's < 0.
Exceptions
If CDS error occurrs, will throw px::generic_err with an informative message.
Definition at line 833 of file cds_sync_io.cpp.
References px::cds::CDeleteDevice::devices, px::cds::CClient::get(), LIBPX_ERR, LIBPX_INFO, and px::cds::CClient::submit().
px::CDevice px::asio::CCdsSyncIO::get_device_s (const px::id_t dev_id)
Synchronous non-ASIO version of CDS Get Device.
Utility function to retrieve a single device by its device id.
Parameters
dev_id The ID of the device being requested. Must be > 0.
Returns
A copy of the requested Device object.
Exceptions
If unable to fetch from CDS, will throw px::generic_err with an informative message.
Definition at line 866 of file cds_sync_io.cpp.
References check_cds_result(), px::cds::CClient::get(), LIBPX_DEBUG, px::cds::CGetDevice::maxdepth, px::cds::CGetDevice::requested_ids, and px::cds::CClient::submit_wait().
Referenced by set_device_guid().
std::map< px::id_t, px::CDevice > px::asio::CCdsSyncIO::get_devices (const px::id_t starting_dev_id = PX_ID_ROOT)
Utility function to retrieve a map of a device and child devices.
Parameters
starting_dev_id The Device ID of the first device for discovery; the process is recursive, so all children will be found. Must be > 0.
Returns
On success, a std::map<px::id_t, px::CDevice> of the discovered Devices. Keyed by device id. Will be an empty array if the CDS retrieval failed (eg, no such device exists).
Definition at line 892 of file cds_sync_io.cpp.
References check_cds_result(), px::cds::CClient::get(), px::CDevice::id(), LIBPX_DEBUG, LIBPX_WARN, px::cds::CGetDevice::maxdepth, px::cds::CGetDevice::requested_ids, px::cds::CClient::submit_wait(), and px::generic_err::what().
std::vector< px::CChannelTrends > px::asio::CCdsSyncIO::get_device_trend_row (px::id_t dev_id, unsigned int interval_minutes = 5, px::CWallTime start_time = px::CWallTime(), bool recursive = false)
ToDo: setup means to always have the latest trend data at hand.
Get one trend row for all channels of the given device at (or after) the specified time. Assumes 5 minute trend data. Makes a synchronous request.
Parameters
dev_id The CDS device ID whose trend data we want to get. Must be > 0.
interval_minutes Interval duration (in minutes) for which to query trends; defaults to 5 minutes; allowed values are 5, 15, 60, 1440 minutes.
start_time The time of the interval data to request. The trend row result will be for this time or the next available interval. If left at the "invalid" default, the time of the last interval (latest) will be requested.
Returns
The array of Channel Trend data for one row (one time interval) at the specified time. If there is no trend data at or after that time period, the array will be empty.
Exceptions
If unable to fetch from CDS, will throw px::generic_err with an informative message.
Definition at line 929 of file cds_sync_io.cpp.
References check_cds_result(), px::cds::CClient::get(), LIBPX_DEBUG, LIBPX_WARN, px::CTimestamp::localtime_str(), px::CWallTime::now(), px::cds::CQueryTrends::start_time, and px::cds::CClient::submit_wait().
int px::asio::CCdsSyncIO::set_device_guid (const px::string & name_str, px::CDevice & px_device, bool is_direct = false, bool do_forget = false)
Set Device GUID in the given CDevice instance and in the CDS.
May generate the UUID from a seed text.
Parameters
name_str Normally, the unique seed string value for generating GUID. Must not be empty. If is_direct is true, then instead, this is the UUID text itself (with or without dashes).
px_device CDS device object. Device id must be > 0.
is_direct If true, use the name_str directly as the UUID (must be 32 or 36 chars long). If false (the default), the name_str will be used to generate the UUID.
do_forget If true, will submit the request to the CDS as a fire-and-forget operation. If false (the default), will make a synchronous request and check the response.
Returns
0 on success, -1 on failure.
Definition at line 973 of file cds_sync_io.cpp.
References check_cds_result(), px::CUtil::create_uuid(), px::cds::CUpdateDevice::devices, px::cds::CClient::get(), px::guid_2_bytes(), px::CDevice::id(), LIBPX_DEBUG, LIBPX_ERR, px::CDevice::set_device_uuid(), px::cds::CClient::submit(), px::cds::CClient::submit_wait(), and px::generic_err::what().
Referenced by set_device_guid().
int px::asio::CCdsSyncIO::set_device_guid (const px::string & name_str, px::id_t dev_id)
Set Device GUID in the given CDevice instance and in the CDS, generating the UUID from the given seed text.
Parameters
name_str Unique seed string value for generating GUID. Must not be empty.
dev_id The CDS device ID whose GUID we want to set. Must be > 0.
Returns
0 on success, -1 on failure.
Definition at line 1053 of file cds_sync_io.cpp.
References get_device_s(), LIBPX_ERR, and set_device_guid().
void px::asio::CCdsSyncIO::set_device_state (const std::vector< px::cds::CSetSingleDeviceState > & dev_states)
State Related Member Functions.
Utility function to set the device state for one or more devicee.
Parameters
dev_states Vector of px::cds::CSetSingleDeviceState requests. Must not be empty. The process is recursive, so all children will be found.
Exceptions
If unable to set device state(s), will throw px::generic_err with an informative message.
Definition at line 1075 of file cds_sync_io.cpp.
References px::cds::CSetDeviceState::devices, px::cds::CClient::get(), LIBPX_ERR, LIBPX_INFO, and px::cds::CClient::submit().
Referenced by enable_device(), and set_device_communicating().
void px::asio::CCdsSyncIO::set_channel_state (const std::vector< px::cds::CSetSingleChannelState > & chan_states)
Utility function to set the channel state for one or more channels.
Parameters
chan_states Vector of px::cds::CSetSingleChannelState requests. Must not be empty.
Exceptions
If unable to set channel state(s), will throw px::generic_err with an informative message.
Definition at line 1107 of file cds_sync_io.cpp.
References px::cds::CSetChannelState::channels, px::cds::CClient::get(), LIBPX_ERR, LIBPX_INFO, and px::cds::CClient::submit().
Referenced by set_channel_communicating().
void px::asio::CCdsSyncIO::enable_device (const px::id_t dev_id, const bool is_enabled)
Utility function to enable/disable a device.
Parameters
dev_id The ID of the device to enable/disable. Must be > 0.
is_enabled If true, device will be enabled. If false, device will be disabled.
Exceptions
If unable to set device state, will throw px::generic_err with an informative message.
Definition at line 1137 of file cds_sync_io.cpp.
References px::disabled, px::cds::op_clear_flags, px::cds::op_set_flags, px::CBitset< T >::reset(), px::CBitset< T >::set(), and set_device_state().
Referenced by enable_device().
void px::asio::CCdsSyncIO::enable_device (px::CDevice & device, const bool is_enabled)
Utility function to enable/disable a device, and update the realtime state of the passed in px::CDevice object.
Parameters
[out] device The px::CDevice of the device enable/disable. The px::CDevice realtime disabled state will be updated as well. Device id must be > 0.
is_enabled If true, device will be enabled. If false, device will be disabled.
Exceptions
If unable to set device state, will throw px::generic_err with an informative message.
Definition at line 1160 of file cds_sync_io.cpp.
References px::disabled, enable_device(), px::CDevice::get_state(), px::CDevice::id(), px::CBitset< T >::set(), and px::CDevice::set_state().
void px::asio::CCdsSyncIO::set_device_communicating (const px::id_t dev_id, const bool is_communicating)
Utility function to set the communicating state of a device.
Parameters
dev_id The ID of the device to set communications state. Must be > 0.
is_enabled If true, device will set to communicating. If false, device will be set to NOT communicating.
Exceptions
If unable to set device state, will throw px::generic_err with an informative message.
Definition at line 1179 of file cds_sync_io.cpp.
References px::not_communicating, px::cds::op_clear_flags, px::cds::op_set_flags, px::CBitset< T >::reset(), px::CBitset< T >::set(), and set_device_state().
Referenced by set_device_communicating().
void px::asio::CCdsSyncIO::set_device_communicating (px::CDevice & device, const bool is_communicating)
Utility function to set the communicating state of a device, and update the realtime state of the passed in px::CDevice object.
Parameters
[out] device The px::CDevice of the device to set communications state. The px::CDevice realtime not_communicating state will be updated as well. Device id must be > 0.
is_enabled If true, device will set to communicating. If false, device will be set to NOT communicating.
Exceptions
If unable to set device state, will throw px::generic_err with an informative message.
Definition at line 1199 of file cds_sync_io.cpp.
References px::CDevice::get_state(), px::CDevice::id(), px::not_communicating, px::CBitset< T >::set(), set_device_communicating(), and px::CDevice::set_state().
void px::asio::CCdsSyncIO::set_channel_communicating (const px::id_t chan_id, const bool is_communicating)
Utility function to set the communicating state of a channel.
Parameters
chan_id The ID of the channel to set communications state. Must be > 0.
is_communicating If true, channel will set to communicating. If false, channel will be set to NOT communicating.
Exceptions
If unable to set channel state, will throw px::generic_err with an informative message.
Definition at line 1216 of file cds_sync_io.cpp.
References px::not_communicating, px::cds::op_clear_flags, px::cds::op_set_flags, px::CBitset< T >::reset(), px::CBitset< T >::set(), and set_channel_state().
cds::field_t px::asio::CCdsSyncIO::get_field (const ::cds::field_t & field) const
Field Related Member Functions.
Utility function for synchronous CDS request to ask for one field value.
Parameters
field
Returns
a CSingleField with value set
Exceptions
If unable to fetch from CDS, will throw px::generic_err with an informative message.
Definition at line 1238 of file cds_sync_io.cpp.
References check_cds_result(), px::cds::CGetFieldValue::fields, px::cds::CClient::get(), px::invalid, LIBPX_WARN, and px::cds::CClient::submit_wait().
int px::asio::CCdsSyncIO::set_field (::cds::field_t & field)
Convenience method for synchronous CDS request to set one field value.
Parameters
field Paths/ID that names where the data should be placed in the CDS, and its new value.
Returns
0 on success, 1 on failure.
Definition at line 1262 of file cds_sync_io.cpp.
References check_cds_result(), px::cds::CSingleField::field, px::cds::CSetFieldValue::fields, px::cds::CClient::get(), px::invalid, LIBPX_ERR, px::cds::CClient::submit_wait(), and px::generic_err::what().
uint64_t px::asio::CCdsSyncIO::subscribe_by_id (uint64_t sub_id, px::sub::subscription_type sub_type, px::id_t item_id, bool is_recursive_device = false, bool is_reflexive = false, std::string library_name = "")
Subscription Related Member Functions.
Create or update a subscription of the given type for the given Device or Channel ID. If the sub_id is non-zero, then that (existing) subscription will be updated with the new type and ID. The updates to the subscribed item(s) will be received by the handle_response() callback, where the subscription ID can be used to determine which subscription the notification is for.
Parameters
sub_id The subscription ID to update. If it is given as 0, then a new subscription ID will be taken out for this subscription; so use 0 when first subscribing.
sub_type The type of the subscription (from the set of enums).
item_id The Device or Channel ID that is being subscribed to. Must be > 0.
is_recursive_device If the item_id is a Device ID, this can be used to make the the subscription recursive for its child devices.
is_reflexive When first creating a subscription (sub_id = 0), if set to True, then even changes made by this application will generate notifications (handle_response() callbacks). Normally left at default of False.
library_name Name of the library used to validate the data.
Returns
The subscription ID that was subscribed to. If sub_id is non-zero, then this value will be simply returned UNLESS the subscription call failed; in those failure cases, will throw a px::generic_err or 0 will be returned. The calling application is responsible for storing and managing this subscription ID.
Definition at line 1300 of file cds_sync_io.cpp.
References check_cds_result(), px::cds::CClient::get(), get_subscriber_ids(), LIBPX_DEBUG, LIBPX_ERR, px::cds::CSubscribe::libraryName, px::cds::CClient::submit_wait(), and px::cds::CSubscribe::subscriptions.
bool px::asio::CCdsSyncIO::unsubscribe_id (uint64_t sub_id, px::sub::subscription_type sub_type, px::id_t item_id, std::string library_name = "")
Unsubscribe the given Device or Channel from the given subscription (by ID and type).
May throw a px::generic_err if the unsubscribe call parameters are invalid.
Parameters
sub_id The subscription ID to update by removing this item and type. Must be > 0.
sub_type The type of the subscription (from the set of enums). If this type is max_subscription_type, the whole subscription (under sub_id) will be cancelled.
item_id The Device or Channel ID that is being unsubscribed. Must be > 0.
library_name Name of the library used to validate the data.
Returns
True on successful unsubscription, else False if the unsubscription had some issue (eg, the given item or type had not been subscribed to).
Definition at line 1338 of file cds_sync_io.cpp.
References check_cds_result(), px::cds::CClient::get(), LIBPX_DEBUG, px::cds::CSubscribe::libraryName, px::cds::CClient::submit_wait(), and px::cds::CSubscribe::subscriptions.
uint64_t px::asio::CCdsSyncIO::subscribe_oob (uint64_t sub_id, px::string oob_tag, bool is_reflexive = false, bool is_tag_partial = false)
Create or update a subscription for the OOB with the given tag (name).
If the given sub_id is non-zero, then that (existing) subscription will be updated with the new tag. The updates to the subscribed OOB will be received by the handle_response() callback, where the subscription ID can be used to determine which subscription the notification is for. This includes deletion of that OOB.
Parameters
sub_id The subscription ID to update. If it is given as 0, then a new subscription ID will be taken out for this subscription; so use 0 when first subscribing.
oob_tag The name (tag) of the OOB that is being subscribed to. This is not wildcarded, but must be the precise tag to be watched. Must not be empty.
is_reflexive When first creating a subscription (sub_id = 0), if set to True, then even changes made by this application will generate notifications (handle_response() callbacks). Normally left at default of False.
is_tag_partial If true, notify on changes to any OOB tag that starts with the string given in the oob_tag parameter. With the default of false, the tags must match exactly.
Returns
The subscription ID that was subscribed to. If sub_id is non-zero, then this value will be simply returned UNLESS the subscription call failed; in those failure cases, 0 will be returned. The calling application is responsible for storing and managing this subscription ID.
Definition at line 1379 of file cds_sync_io.cpp.
References check_cds_result(), px::cds::CClient::get(), get_subscriber_ids(), px::cds::CClient::have_unsolicited_callback(), LIBPX_DEBUG, LIBPX_ERR, px::sub::oob_data, px::cds::CClient::submit_wait(), px::cds::CSubscribe::subscriptions, and px::generic_err::what().
bool px::asio::CCdsSyncIO::unsubscribe_oob (uint64_t sub_id, px::string oob_tag, bool is_tag_partial = false)
Unsubscribe the given OOB from the given subscription (by ID).
Parameters
sub_id The subscription ID to update by removing this OOB. Must be > 0.
oob_tag The name (tag) of the OOB that is being unsubscribed. Must not be empty.
Returns
True on successful unsubscription, else False if the unsubscription had some issue (eg, the given item or type had not been subscribed to).
Definition at line 1419 of file cds_sync_io.cpp.
References check_cds_result(), px::cds::CClient::get(), LIBPX_DEBUG, LIBPX_ERR, px::sub::oob_data, px::cds::CClient::submit_wait(), px::cds::CSubscribe::subscriptions, and px::generic_err::what().
std::vector< uint64_t > px::asio::CCdsSyncIO::get_subscriber_ids (size_t count, bool reflexive = false)
Use CManageSubscriberIDs to request new subscriber ID(s) for our use.
Parameters
count How many new IDs to request.
reflexive Set to True if you want notifications for changes that this application makes to the CDS data itself. (Normally the default of False is the desired setting.)
Definition at line 1363 of file cds_sync_io.cpp.
References check_cds_result(), px::cds::CClient::get(), LIBPX_DEBUG, px::cds::CManageSubscriberIDs::new_ids_requested, px::cds::CManageSubscriberIDs::reflexive, and px::cds::CClient::submit_wait().
Referenced by px::asio::CCdsHandler::init_device_map(), px::asio::CCdsHandler::subscribe_alarm_callback(), subscribe_by_id(), and subscribe_oob().
std::vector< px::CChannelSettings > px::asio::CCdsSyncIO::get_channel_by_group (const std::vector< px::id_t > & get_ids, unsigned int offset, const unsigned int & limit) protected
The function is used to get the channel settings for a subset of the provided ids It groups the required channels and sends request to CDS.
Parameters
get_ids[IN] List of all the channel ids required
offset[IN] Starting index of the vector from which the channel settings will be requested
limit[IN] Number of channels to be requested in a single CDS request
Returns
std::vector<px::CChannelSettings> Vector of channel settings data
Definition at line 664 of file cds_sync_io.cpp.
References check_cds_result(), px::cds::CClient::get(), px::cds::CGetChannelSettings::ids, and px::cds::CClient::submit_wait().
Referenced by get_channel_settings().
Member Data Documentation
bool px::asio::CCdsSyncIO::_bypass_validation protected
If true, bypass CDS data validation when setting channel values.
Definition at line 715 of file cds_sync_io.hpp.
Referenced by get_data_validation(), px::asio::CCdsHandler::set_channel_value(), set_channel_value_s(), set_channel_values(), and set_data_validation().
The documentation for this class was generated from the following files:
cds_sync_io.hpp
cds_sync_io.cpp